import {test,expect} from '@playwright/test';
import {writeFileSync} from 'node:fs';
test.use({viewport:{width:390,height:844}});test.setTimeout(150000);
test('current edition is healthy on mobile card by card with real media',async({page})=>{
 await page.goto('http://127.0.0.1:3000',{waitUntil:'domcontentloaded',timeout:20000});
 const articles=page.locator('article');await expect(articles.first()).toBeVisible({timeout:10000});const articleCount=await articles.count();const diagnosticLabels=await articles.evaluateAll(nodes=>nodes.map(node=>node.textContent?.slice(0,900)||''));writeFileSync('artifacts/mobile-composition.json',JSON.stringify({articleCount,labels:diagnosticLabels},null,2));expect(articleCount).toBe(20);
 const dimensions=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,bodyScrollWidth:document.body.scrollWidth,innerWidth:window.innerWidth}));expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth+1);expect(dimensions.bodyScrollWidth).toBeLessThanOrEqual(dimensions.innerWidth+1);
 const expectedOrder=['Papo de hoje','Desafio do casal','Curiosidade · Animais','Curiosidade · Oceano','Curiosidade · Espaço','Curiosidade · Terra','Curiosidade · Tecnologia','Gravidez','Ser Pai','Mundo','Política','Tempo e Clima','Corinthians','Viagens','Música','Sertanejo da Roça','Tecnologia','Carros até R$ 70 mil','Motos','Mecânica'];
 for(const [i,label] of expectedOrder.entries())await expect(articles.nth(i)).toContainText(label);
 const pageText=(await page.locator('body').innerText()).toLowerCase();const mediaSources=await page.locator('img, iframe').evaluateAll(nodes=>nodes.map(node=>({tag:node.tagName,src:(node as HTMLImageElement|HTMLIFrameElement).src||'',alt:(node as HTMLImageElement).alt||''})));const labels=await articles.evaluateAll(nodes=>nodes.map(node=>node.textContent?.slice(0,900)||''));writeFileSync('artifacts/mobile-diagnostics.json',JSON.stringify({articleCount,dimensions,labels,mediaCount:mediaSources.length,mediaSources},null,2));
 for(const required of ['13 set 2026','melhor compra pequena','encontrem uma foto antiga','tubarões percebem campos elétricos','fontes hidrotermais podem passar de 340','pôr do sol em marte pode parecer azul','aurora nasce quando partículas carregadas','fibra óptica guia luz','10 semanas completas','meia hora de descanso','alerta em vilnius era um bando de aves','aeroporto reabre após 38 minutos','prestação de contas parcial','grande são paulo entra no domingo sob alerta','corinthians confirma time misto','17h30','hugo souza','pedro milans','lingard','condição da estrada antes de sair','canção com duas vozes','cabocla tereza','trump minimiza temores sobre ia','liderança dos eua sobre a china','código dot','corrente e coroa','fluido de freio'])expect(pageText).toContain(required.toLowerCase());
 for(const omitted of ['12 set 2026','qual música mudou de significado','20 minutos sem tela','mais de um milhão de fios de pelo','3,8 centímetros por ano','polo norte magnético','remodelação microscópica','sem correções relativísticas','9 semanas + 6 dias','refeição inteira','vilnius fecha aeroporto após possível drone','origem do possível drone não foi confirmada','navio atingido em hormuz pega fogo','brics adota declaração conjunta','declaração de nova délhi','hyundai adia software próprio','fim de 2029','nvidia','level 2+','supervisão do motorista','comandos elétricos','retentores das bengalas','correia de acessórios','náutica','romance de hoje','conexão a dois','missão romântica','mensagem romântica artificial'])expect(pageText).not.toContain(omitted.toLowerCase());
 for(const omittedLabel of ['Brasil','Zona Leste em Foco','Games','Finanças','Security Briefing','Cyber Security','AppSec / SSDLC'])await expect(page.getByText(omittedLabel,{exact:true})).toHaveCount(0);
 expect(mediaSources.length).toBeGreaterThanOrEqual(articleCount);expect(mediaSources.filter(x=>x.tag==='IFRAME').some(x=>/youtube\.com\/embed\/kv2jknSIBGc/.test(x.src))).toBe(true);
 const forbidden=mediaSources.filter(x=>/sprite(?:-news)?\.jpg|clean-covers\.jpg|transparent\.gif|data:|\.svg(?:$|\?)/i.test(x.src)||/arte\s*9:16|arte editorial|arte abstrata|gerad[ao]\s+por\s+(?:ia|ai)|ai-generated|ilustra(?:ç|c)[aã]o/i.test(x.alt));expect(forbidden).toEqual([]);
 for(let i=0;i<articleCount;i+=1){const article=articles.nth(i);await article.scrollIntoViewIfNeeded();const visual=article.locator('img, iframe').first();await expect(visual).toBeVisible({timeout:10000});const tag=await visual.evaluate(node=>node.tagName);const src=await visual.getAttribute('src')??'';expect(src.length).toBeGreaterThan(3);expect(src).not.toMatch(/sprite(?:-news)?\.jpg|clean-covers\.jpg|transparent\.gif|data:|\.svg(?:$|\?)/i);if(tag==='IMG'){expect(src).toMatch(/^https:\/\//i);const alt=await visual.getAttribute('alt')??'';expect(alt.length).toBeGreaterThan(8);expect(alt).not.toMatch(/arte\s*9:16|arte editorial|arte abstrata|gerad[ao]\s+por\s+(?:ia|ai)|ai-generated|ilustra(?:ç|c)[aã]o/i);await expect.poll(async()=>visual.evaluate(node=>{const img=node as HTMLImageElement;return img.complete&&img.naturalWidth>0&&img.naturalHeight>0;}),{timeout:15000}).toBe(true);}else{expect(src).toMatch(/^https:\/\//i);}await article.screenshot({path:`artifacts/mobile-card-${String(i+1).padStart(2,'0')}.png`});}
 await expect(page.getByText(/Náutica|Romance de hoje|Conexão a dois|missão romântica|mensagem romântica artificial/i)).toHaveCount(0);await page.screenshot({path:'artifacts/mobile-390x844-full.png',fullPage:true});
});
