import { test, expect } from '@playwright/test';
import { writeFileSync } from 'node:fs';
test.use({ viewport: { width: 390, height: 844 } });test.setTimeout(150000);
test('30 Aug full edition is healthy on mobile card by card', async ({ page }) => {
  await page.goto('http://127.0.0.1:3000',{waitUntil:'domcontentloaded',timeout:20000});const articles=page.locator('article');await expect(articles.first()).toBeVisible({timeout:10000});await expect(articles).toHaveCount(23,{timeout:15000});
  const dimensions=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,bodyScrollWidth:document.body.scrollWidth,innerWidth:window.innerWidth}));const labels=await articles.evaluateAll(nodes=>nodes.map(node=>node.textContent?.slice(0,420)||''));const mediaSources=await page.locator('img, iframe').evaluateAll(nodes=>nodes.map(node=>({tag:node.tagName,src:(node as HTMLImageElement|HTMLIFrameElement).src||''})));writeFileSync('artifacts/mobile-diagnostics.json',JSON.stringify({articleCount:await articles.count(),dimensions,labels,mediaCount:mediaSources.length,mediaSources},null,2));expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth+1);expect(dimensions.bodyScrollWidth).toBeLessThanOrEqual(dimensions.innerWidth+1);
  const required=['30 AGO 2026','Qual hábito pequeno seu você gostaria que eu entendesse melhor?','playlist de cinco músicas para começar setembro','Em Vênus, uma rotação completa','Minúsculos cristais de carbonato','controlador do SSD','8 semanas exatas','preparar a segunda-feira','hepatite B','Facções rivais da Líbia','TSE migra serviços em nuvem','Domingo quente em São Paulo','Sarau do Binho','Corinthians recebe o Santos hoje','Paranapiacaba','Galo de Briga','Chico Mineiro','gamescom chega ao último dia','aposenta hoje o GPT oficial do DALL·E','G20 de Finanças','Metasploit recebe hoje','câmbio frio e quente','direção com “calo”','bateria fraca'];const pageText=await page.locator('body').innerText();for(const value of required)expect(pageText.toLowerCase()).toContain(value.toLowerCase());for(const stale of ['29 AGO 2026','água pode ferver em temperatura ambiente','dedos enrugam na água','satélites GPS','Quedas e queimaduras','Irã enfrenta inflação de 66%','Tristeza do Jeca','Hasbro começa a notificar','Náutica'])expect(pageText.toLowerCase()).not.toContain(stale.toLowerCase());for(const omitted of ['Security Briefing','Cyber Security'])expect(labels.some(v=>v.includes(omitted))).toBe(false);
  const expectedMedia:Record<number,RegExp>={0:/Couple%20outdoors\.jpg/i,1:/Couple%20walking%20in%20park\.jpg/i,2:/curiosity-venus-day-20260830/i,3:/curiosity-otoconia-20260830/i,4:/curiosity-ssd-wear-leveling-20260830/i,5:/pregnancy-week8-20260830/i,6:/father-support-20260830/i,7:/brasil-hepatitis-research-20260830/i,8:/world-libya-election-roadmap-20260830/i,9:/politics-tse-cloud-20260830/i,10:/weather-sp-20260830/i,11:/zona-leste-sarau-20260830/i,12:/corinthians-classic-20260830/i,13:/travel-paranapiacaba-20260830/i,14:/music-galo-20260830/i,15:/cz8i7UrvKds/i,16:/games-gamescom-sunday-20260830/i,17:/technology-dalle-retirement-20260830/i,18:/finance-g20-20260830/i,19:/appsec-langflow-20260830/i,20:/cars-transmission-20260830/i,21:/motos-steering-20260830/i,22:/mechanic-battery-20260830/i};const forbidden=/sprite(?:-news)?\.jpg|clean-covers\.jpg|transparent\.gif|data:image\/gif|US%20Treasury%20Building|USB-C/i;
  for(let i=0;i<23;i+=1){const article=articles.nth(i);await article.scrollIntoViewIfNeeded();const visual=article.locator('img, iframe').first();await expect(visual).toBeVisible({timeout:12000});const src=await visual.getAttribute('src')??'';expect(src).toMatch(expectedMedia[i]);expect(src).not.toMatch(forbidden);if(await visual.evaluate(node=>node.tagName==='IMG'))await expect.poll(async()=>visual.evaluate(node=>{const img=node as HTMLImageElement;return img.complete&&img.naturalWidth>0;}),{timeout:15000}).toBe(true);await article.screenshot({path:`artifacts/mobile-card-${String(i+1).padStart(2,'0')}.png`});}await page.screenshot({path:'artifacts/mobile-390x844-full.png',fullPage:true});
});
