import { test, expect } from '@playwright/test';
import { writeFileSync } from 'node:fs';
test.use({ viewport: { width: 390, height: 844 } });test.setTimeout(60000);
test('current edition is healthy on mobile', async ({ page }) => {
  await page.goto('http://127.0.0.1:3000',{waitUntil:'domcontentloaded',timeout:15000});const articles=page.locator('article');await expect(articles.first()).toBeVisible({timeout:10000});await expect(articles).toHaveCount(19,{timeout:10000});
  const dimensions=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,bodyScrollWidth:document.body.scrollWidth,innerWidth:window.innerWidth}));const mediaSources=await page.locator('img, iframe').evaluateAll(nodes=>nodes.map(node=>({tag:node.tagName,src:(node as HTMLImageElement|HTMLIFrameElement).src||''})));const labels=await articles.evaluateAll(nodes=>nodes.map(node=>node.textContent?.slice(0,260)||''));writeFileSync('artifacts/mobile-diagnostics.json',JSON.stringify({articleCount:await articles.count(),dimensions,labels,mediaCount:mediaSources.length,mediaSources},null,2));expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth+1);expect(dimensions.bodyScrollWidth).toBeLessThanOrEqual(dimensions.innerWidth+1);
  await expect(articles.nth(0)).toContainText('Papo de hoje');await expect(articles.nth(1)).toContainText('Desafio do casal');await expect(articles.nth(2)).toContainText('Curiosidade · Ciência');await expect(articles.nth(3)).toContainText('Curiosidade · Corpo Humano');await expect(articles.nth(4)).toContainText('Curiosidade · Tecnologia');
  const pageText=(await page.locator('body').innerText()).toLowerCase();for(const required of ['29 ago 2026','7 semanas + 6 dias','flávio bolsonaro','guerra e sanções','são paulo esquenta','corinthians ganha hugo souza','gamescom tem final','openai anuncia fim'])expect(pageText).toContain(required.toLowerCase());for(const omitted of ['service now corrige','papercut','27 ago 2026','28 ago 2026','náutica'])expect(pageText).not.toContain(omitted.toLowerCase());
  const forbidden=mediaSources.map(item=>item.src).filter(src=>/sprite(?:-news)?\.jpg|clean-covers\.jpg|transparent\.gif|data:image\/gif/i.test(src));expect(forbidden).toEqual([]);const expectedCuriosityMedia=[/moire/i,/olfactory/i,/dns/i];for(let i=0;i<5;i+=1){const article=articles.nth(i);await article.scrollIntoViewIfNeeded();const visual=article.locator('img, iframe').first();await expect(visual).toBeVisible({timeout:10000});const src=await visual.getAttribute('src')??'';if(i>=2)expect(src).toMatch(expectedCuriosityMedia[i-2]);if(await visual.evaluate(node=>node.tagName==='IMG'))await expect.poll(async()=>visual.evaluate(node=>{const img=node as HTMLImageElement;return img.complete&&img.naturalWidth>0;}),{timeout:10000}).toBe(true);await article.screenshot({path:`artifacts/mobile-card-${i+1}.png`});}
  await expect(page.getByText(/25 AGO 2026|Daily Intelligence · 25 de agosto|Náutica/i)).toHaveCount(0);await page.screenshot({path:'artifacts/mobile-390x844.png',fullPage:true});
});
