import type {RichMediaEntry} from './rich-media';
const commons=(name:string)=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(name).replace(/%2F/g,'/')}`;
export const dailyRichMedia20260829:RichMediaEntry[]=[
{label:'Curiosidades',matches:['dois padrões sobrepostos','moiré','moire'],tag:'MÍDIA REAL · CIÊNCIA',title:'Padrão moiré',caption:'Imagem específica do fenômeno de interferência visual descrito no Reel.',images:[{url:commons('Moire.png'),alt:'Padrão moiré formado pela sobreposição de conjuntos de linhas',caption:'Exemplo de padrão moiré.',credit:'Heron / Wikimedia Commons · CC BY-SA 3.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Moire.png',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['nariz pode parar de notar','olfato','cheiro'],tag:'MÍDIA REAL · CORPO HUMANO',title:'Sistema olfatório humano',caption:'Diagrama anatômico diretamente ligado ao funcionamento do olfato.',images:[{url:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Olfactory_system.svg/1280px-Olfactory_system.svg.png',alt:'Diagrama anatômico do sistema olfatório humano com epitélio e bulbo olfatório',caption:'Sistema olfatório humano.',credit:'Chabacano / Wikimedia Commons · CC BY-SA 2.5',sourceUrl:'https://commons.wikimedia.org/wiki/File:Olfactory_system.svg',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['internet pode continuar lembrando','dns','ttl'],tag:'MÍDIA REAL · TECNOLOGIA',title:'Hierarquia DNS',caption:'Diagrama específico da hierarquia do Domain Name System.',images:[{url:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/DNS_schema.svg/1280px-DNS_schema.svg.png',alt:'Diagrama da hierarquia de nomes e servidores DNS',caption:'Esquema de DNS.',credit:'TilmannR / Wikimedia Commons · CC BY-SA',sourceUrl:'https://commons.wikimedia.org/wiki/File:DNS_schema.svg',kind:'REFERENCE'}]},
{label:'Política',matches:['flávio bolsonaro diz que respeitará','e-título','e-titulo'],tag:'MÍDIA ELEITORAL · TSE',title:'Urna eletrônica brasileira',caption:'Imagem institucional neutra para o radar eleitoral.',images:[{url:commons('Brazilian DRE voting machine for 2022 elections.jpg'),alt:'Urna eletrônica brasileira em fotografia institucional',caption:'Urna eletrônica brasileira.',credit:'TSE / Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Brazilian_DRE_voting_machine_for_2022_elections.jpg',kind:'PHOTO'}]},
{label:'Mundo',matches:['guerra e sanções aprofundam','economia do irã','hormuz'],tag:'MÍDIA REAL · MAPA',title:'Estreito de Hormuz',caption:'Mapa geográfico diretamente ligado à rota marítima citada.',images:[{url:commons('Strait of Hormuz-svg-en.svg'),alt:'Mapa do Estreito de Hormuz entre Irã e Omã',caption:'Estreito de Hormuz.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Strait_of_Hormuz-svg-en.svg',kind:'REFERENCE'}]},
{label:'Tempo e Clima',matches:['são paulo esquenta','sao paulo esquenta','máxima pode superar 32'],tag:'MÍDIA REAL · SÃO PAULO',title:'São Paulo em dia quente',caption:'Fotografia real da cidade como contexto para o boletim do CGE.',images:[{url:commons('Parque da Independência - São Paulo - Brasil.jpg'),alt:'Parque da Independência em São Paulo sob céu aberto',caption:'São Paulo.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Parque_da_Independ%C3%AAncia_-_S%C3%A3o_Paulo_-_Brasil.jpg',kind:'PHOTO'}]},
{label:'Games',matches:['gamescom tem final do concurso de cosplay','final do concurso de cosplay','gamescom'],tag:'MÍDIA REAL · GAMESCOM',title:'gamescom em Colônia',caption:'Fotografia real da entrada da gamescom, diretamente ligada ao evento.',images:[{url:commons('Main Entrance View at Gamescom 2025 in Cologne, Germany.jpg'),alt:'Entrada principal da gamescom no centro de exposições de Colônia',caption:'gamescom em Colônia.',credit:'RAWdz Ivan / Wikimedia Commons · CC BY 4.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Main_Entrance_View_at_Gamescom_2025_in_Cologne,_Germany.jpg',kind:'PHOTO'}]},
{label:'Tecnologia',matches:['openai anuncia fim','fornecimento de modelos ao cursor','cursor'],tag:'MÍDIA REAL · IA',title:'OpenAI',caption:'Marca da OpenAI, empresa diretamente envolvida no anúncio.',images:[{url:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/OpenAI_Logo.svg/1024px-OpenAI_Logo.svg.png',alt:'Logotipo da OpenAI',caption:'OpenAI.',credit:'OpenAI / Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:OpenAI_Logo.svg',kind:'REFERENCE'}]},
{label:'Corinthians',matches:['corinthians ganha hugo souza','hugo souza','matheus bidu'],tag:'MÍDIA REAL · CORINTHIANS',title:'Corinthians',caption:'Imagem relacionada ao Corinthians para o clássico contra o Santos.',images:[{url:'https://s2-cbn.glbimg.com/P_wXvQ-Ks8UHdDwWGCCglRTv52A=/1200x/smart/filters:cover()/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_d975fad146a14bbfad9e763717b09688/internal_photos/bs/2024/z/7/dl7DuXRIuwuFzGi0fAaQ/corinthian.png',alt:'Símbolo do Corinthians',caption:'Corinthians.',credit:'CBN/Globo',sourceUrl:'https://ge.globo.com/futebol/times/corinthians/',kind:'PHOTO'}]}
];
