import { dailyContent, edition, todayDrops } from './daily-content';
import { politicsTracker } from './politics-2026';

const set=(slug:string,data:any)=>Object.assign(dailyContent[slug],data);
Object.assign(edition,{date:'20/08/2026',dateLabel:'20 AGO 2026',title:'Daily Intelligence · 20 de agosto'});
Object.assign(politicsTracker,{updatedAt:'20/08/2026 · 17h',notice:'Hoje é o último dia para requerer, alterar ou cancelar a habilitação para voto em trânsito e outras modalidades de transferência temporária previstas pelo TSE. Campanha, pedido de registro e situação processual de candidatura continuam sendo assuntos separados.'});

const drops=[
{slug:'brasil',label:'Brasil',emoji:'🇧🇷',title:'Fiscal: governo projeta novo esforço e corte de despesas obrigatórias em 2027',detail:'Ministro da Fazenda falou em manter o arcabouço e citou ajustes que reduzem despesas obrigatórias em cerca de R$10 bilhões em 2027.'},
{slug:'seguranca-zl',label:'Zona Leste em Foco',emoji:'🚨',title:'Itaquera hoje: tecnologia, jogo na Arena e serviços locais; segurança sem novo fato confirmado',detail:'A aba separa notícias gerais da região, pauta policial, casos, matérias, dados, ações e serviços.'},
{slug:'politica',label:'Política',emoji:'🏛️',title:'Voto em trânsito: prazo termina hoje',detail:'O TSE fixa 20 de agosto como último dia para solicitar, alterar ou cancelar a habilitação.'},
{slug:'mundo',label:'Mundo',emoji:'🌍',title:'Energia e dívida continuam puxando o risco global',detail:'Petróleo alto, dívida soberana e juros longos seguem conectando geopolítica, inflação e mercados.'},
{slug:'planeta',label:'Planeta',emoji:'🌎',title:'Correntes de retorno: por que o mar pode puxar para longe da praia',detail:'Entenda como canais estreitos de água retornam ao oceano e por que nadar lateralmente é mais seguro que lutar contra a corrente.'},
{slug:'animais',label:'Mundo Animal',emoji:'🐙',title:'Polvos “provam” o ambiente com os braços',detail:'Quimiorreceptores nos braços ajudam o polvo a explorar superfícies e alimentos sem depender apenas da visão.'},
{slug:'tempo',label:'Tempo e Clima',emoji:'🌦️',title:'Umidade baixa: por que o corpo perde água mesmo sem suor aparente',detail:'Ar seco acelera evaporação e pode ressecar vias aéreas; hidratação e ambiente importam mais do que sensação de sede isolada.'},
{slug:'curiosidades',label:'Curiosidades',emoji:'🧠',title:'Por que uma colher parece “entortar” dentro da água?',detail:'Refração muda a direção da luz ao atravessar meios diferentes e desloca a posição aparente do objeto.'},
{slug:'musica',label:'Música',emoji:'🎵',title:'Rock e viola continuam em trilhas separadas',detail:'Seleção do dia preserva contexto, história e players sem reproduzir letras protegidas.'},
{slug:'games',label:'Games',emoji:'🎮',title:'Gamescom se aproxima: o que acompanhar sem misturar anúncio e rumor',detail:'A pauta separa agenda oficial, trailers confirmados e expectativas para a próxima semana.'},
{slug:'gravidez',label:'Gravidez',emoji:'🤰',title:'6 semanas + 4 dias: enjoo, vômito e recuperação entre episódios',detail:'A aba agora mantém orientação prática fixa sobre hidratação, proteção dos dentes, alimentação gradual e sinais de alerta.'},
{slug:'pai',label:'Ser Pai',emoji:'👨‍🍼',title:'Ação de hoje: prepare a “zona segura” pós-enjoo',detail:'Água, recipiente, enxágue bucal, toalha e lanche tolerável prontos reduzem esforço quando o enjoo vier.'},
{slug:'carros',label:'Carros',emoji:'🚗',title:'Usado bom é histórico verificável, não só km baixa',detail:'Hoje o foco é como cruzar laudo cautelar, manutenção, pneus, arrefecimento e desgaste interno antes de decidir.'},
{slug:'motos',label:'Motos',emoji:'🏍️',title:'Moto usada: marcas de queda contam uma história que o anúncio não conta',detail:'Batentes, manetes, pedaleiras, guidão, rodas e bengalas ajudam a separar tombos simples de impactos estruturais.'},
{slug:'mecanica',label:'Mecânica',emoji:'🔧',title:'Teste de compressão: o que ele consegue — e o que não consegue — diagnosticar',detail:'Compressão desigual aponta perda de vedação, mas precisa ser interpretada junto com leak-down, velas e sintomas.'},
{slug:'nautica',label:'Náutica',emoji:'⚓',title:'Coletes não são todos iguais: flutuabilidade e uso mudam conforme a atividade',detail:'A escolha depende de homologação, tamanho, flutuabilidade, ambiente e tipo de navegação.'},
{slug:'viagens',label:'Viagens',emoji:'✈️',title:'Holambra no fim de agosto: flores, calor e planejamento de bate-volta',detail:'A preparação combina ingresso, horários, estacionamento, hidratação e previsão do tempo.'},
{slug:'financas',label:'Finanças',emoji:'💰',title:'Juro longo caiu, mas isso não significa crédito barato amanhã',detail:'Recompras do Tesouro dos EUA aliviaram yields; Fed segue atento à inflação. Curto e longo prazo podem divergir.'},
{slug:'tecnologia',label:'Tecnologia',emoji:'💻',title:'IA virou projeto de infraestrutura: chips são só uma parte da conta',detail:'Energia, rede, storage, refrigeração, capital e disponibilidade física começam a limitar escala tanto quanto compute.'},
{slug:'security-briefing',label:'Security Briefing',emoji:'📰',title:'Security Briefing V2: decisões e evidências continuam no centro',detail:'P0/P1, Decision Queue, exposure path, evidência e owner permanecem como estrutura principal do briefing.'},
{slug:'seguranca',label:'Cyber Security',emoji:'🛡️',title:'Vulnerabilidade explorada vale mais que CVSS isolado na fila de resposta',detail:'Exploração real, exposição, privilégio e blast radius devem orientar hunting, mitigação e patch.'},
{slug:'appsec-ssdlc',label:'AppSec / SSDLC',emoji:'🧬',title:'Finding sem reachability pode estar inflando sua fila; finding explorável não pode esperar',detail:'A priorização de AppSec precisa combinar severidade, reachability, exposição, exploit evidence e criticidade da aplicação.'}
];
todayDrops.splice(0,todayDrops.length,...drops);

set('hoje',{title:'22 missões · edição completa de 20 de agosto',summary:'Como as janelas anteriores não chegaram ao main hoje, a revisão das 17h recompõe a edição inteira: atualidades verificadas, conhecimento novo e Zona Leste em Foco atualizada sem reciclar notícia vencida.',shareSummary:'20/08: edição completa com 22 áreas, incluindo Brasil, Política, Zona Leste em Foco, gravidez, veículos, finanças, tecnologia, Cyber e AppSec.',readTime:'22 MISSÕES',badge:'17H COMPLETE RECOVERY',sections:[]});

set('brasil',{title:'Fiscal: governo fala em manter arcabouço e novo esforço de ajuste em 2027',summary:'O ministro da Fazenda, Dario Durigan, afirmou nesta quinta-feira que o governo pretende preservar o arcabouço fiscal e citou ajustes negociados com o Congresso que podem reduzir despesas obrigatórias em cerca de R$ 10 bilhões em 2027.',shareSummary:'Brasil 20/08: Fazenda fala em manter arcabouço fiscal e cita cerca de R$10 bi de redução de despesas obrigatórias em 2027. Declaração é diretriz política/econômica, não resultado fiscal já realizado.',readTime:'6 MIN READ',badge:'BRASIL · FISCAL',sections:[{title:'O que aconteceu',paragraphs:['A fala ocorre em meio à discussão sobre sustentabilidade da dívida, juros ainda altos e necessidade de espaço orçamentário. O ministro também defendeu continuidade do controle de gastos e recuperação de receitas.']},{title:'Por que importa',bullets:['Menor crescimento de despesas obrigatórias abre espaço para outras políticas dentro das regras fiscais.','Juros altos aumentam o custo da dívida e tornam o ajuste fiscal mais sensível.']},{title:'O que ainda é incerto',paragraphs:['Projeções de economia futura dependem de execução, legislação e comportamento das receitas; não são resultado garantido.']}],sources:[{label:'Reuters · Brasil · 20/08/2026',url:'https://www.reuters.com/world/americas/brazil-keep-fiscal-framework-spending-restraint-under-new-lula-term-minister-2026-08-20/'}]});

set('politica',{title:'Voto em trânsito: 20 de agosto é o último dia para pedir, alterar ou cancelar a habilitação',summary:'O TSE mantém hoje como data final para voto em trânsito e outras transferências temporárias previstas na regulamentação. O pedido pode ser feito pelo Autoatendimento Eleitoral quando os requisitos forem atendidos ou presencialmente em cartório.',shareSummary:'Política 20/08: hoje termina o prazo para voto em trânsito. É um serviço do eleitor e não altera o status jurídico de candidaturas.',readTime:'6 MIN READ',badge:'POLÍTICA · SERVIÇO ELEITORAL',sections:[{title:'Quem deve prestar atenção',paragraphs:['Quem estará fora do domicílio eleitoral no dia da eleição, mas em território nacional, deve conferir as regras hoje. Pessoas já habilitadas também têm até hoje para alterar ou cancelar a opção.']},{title:'Não confunda os prazos',bullets:['Voto em trânsito é serviço do eleitor.','Campanha eleitoral já está em andamento.','Registro e deferimento de candidatura são processos separados.']}],sources:[{label:'TSE · Voto em trânsito 2026',url:'https://www.tse.jus.br/eleicoes/eleicoes-2026-content/voto-em-transito-perguntas-e-respostas'},{label:'TSE · Calendário Eleitoral 2026',url:'https://www.tse.jus.br/eleicoes/calendario-eleitoral/'}]});

set('mundo',{title:'Energia e dívida: dois choques diferentes seguem se encontrando na inflação',summary:'Mercados globais continuam equilibrando petróleo elevado, tensões no Oriente Médio e alívio parcial nos juros longos após o Tesouro dos EUA ampliar recompras de títulos. A combinação afeta inflação esperada, moedas e custo de capital.',readTime:'7 MIN READ',badge:'MUNDO · MACRO',sections:[{title:'A conexão menos óbvia',paragraphs:['Petróleo caro pressiona inflação; juros longos altos encarecem financiamento. Mesmo quando yields cedem por questões de liquidez, isso não apaga o risco inflacionário de energia.']},{title:'Para guardar',bullets:['Preço de energia e custo do dinheiro podem se mover por motivos distintos.','Alívio no bond market não equivale automaticamente a corte do Fed.']}],sources:[{label:'Reuters · Morning Bid · 20/08/2026',url:'https://www.reuters.com/commentary/reuters-open-interest/global-markets-view-usa-2026-08-20/'}]});

set('planeta',{title:'Correntes de retorno: o perigo não é “o mar puxar para baixo”, mas a água escoar para fora',summary:'Correntes de retorno são canais estreitos e rápidos que levam água da zona de arrebentação de volta para o mar. Elas podem afastar um banhista da praia rapidamente, mas não funcionam como um ralo vertical.',readTime:'5 MIN READ',badge:'PLANETA · OCEANO',sections:[{title:'Como reconhecer',bullets:['Faixa com menos quebra de ondas.','Água mais escura ou com sedimentos seguindo para fora.','Espuma ou objetos deslocando-se para o mar.']},{title:'Aplicação prática',paragraphs:['Se for arrastado, não tente vencer a corrente nadando direto contra ela; conserve energia, flutue e nade paralelo à praia para sair do canal quando possível, seguindo orientação de guarda-vidas.']}],sources:[{label:'NOAA · Rip currents',url:'https://www.noaa.gov/jetstream/ripcurrents'}]});

set('animais',{title:'Polvos exploram o mundo com braços que também “sentem química”',summary:'Além do tato, os braços possuem receptores capazes de detectar compostos químicos em superfícies. Isso ajuda o animal a investigar alimento e esconderijos em ambientes onde a visão nem sempre basta.',readTime:'4 MIN READ',badge:'MUNDO ANIMAL · SENSORIAL',sections:[{title:'Por que é fascinante',paragraphs:['Grande parte do sistema nervoso do polvo está distribuída pelos braços. Sensação e controle local tornam a exploração do ambiente muito diferente da nossa.']},{title:'Conexão',paragraphs:['É um exemplo de como evolução não precisa concentrar toda a percepção em uma única “central” para produzir comportamento sofisticado.']}],sources:[{label:'Harvard · octopus chemotactile sensing',url:'https://news.harvard.edu/gazette/story/2020/10/how-octopus-arms-taste-and-touch/' }]});

set('tempo',{title:'Ar seco e hidratação: sede atrasada não é um bom medidor',summary:'Em umidade baixa, a evaporação aumenta e mucosas ressecam. A sensação de sede pode surgir depois de já ter ocorrido perda de água, especialmente em atividade física ou ambientes quentes.',readTime:'4 MIN READ',badge:'TEMPO · SAÚDE PRÁTICA',sections:[{title:'O que fazer',bullets:['Distribua líquidos ao longo do dia.','Observe urina muito concentrada junto com outros sinais de desidratação.','Evite exercício intenso no horário mais quente quando o ar estiver muito seco.']},{title:'Sem alarmismo',paragraphs:['Umidade baixa não significa emergência para todas as pessoas; impacto depende de exposição, atividade, saúde e hidratação.']}],sources:[{label:'OMS · Heat and health',url:'https://www.who.int/news-room/fact-sheets/detail/climate-change-heat-and-health'}]});

set('curiosidades',{title:'A colher “quebrada” dentro da água é um truque da refração',summary:'A luz muda de velocidade e direção ao passar entre água e ar. Seu cérebro prolonga os raios em linha reta e interpreta uma posição aparente diferente da posição real.',readTime:'4 MIN READ',badge:'CURIOSIDADE · FÍSICA',sections:[{title:'Teste simples',paragraphs:['Coloque uma colher num copo transparente e observe de lado. A região submersa parece deslocada no limite entre água e ar.']},{title:'Onde isso aparece',bullets:['Lentes.','Óculos.','Câmeras.','Miragens.','Profundidade aparente de piscinas.']}],sources:[{label:'Britannica · Refraction',url:'https://www.britannica.com/science/refraction'}]});

set('gravidez',{title:'6 semanas + 4 dias: o que fazer depois de vomitar importa tanto quanto tentar evitar o próximo episódio',summary:'Náuseas e vômitos são comuns no início da gestação. A recuperação deve priorizar pequenos goles de líquido, retorno gradual da alimentação e cuidado com os dentes, além de observar sinais de desidratação.',readTime:'7 MIN READ',badge:'GRAVIDEZ · 6S + 4D',sections:[{title:'Depois de cada episódio',bullets:['Enxágue a boca com água; não escove os dentes imediatamente após o ácido do vômito.','Recomece líquidos em pequenos goles frequentes quando tolerado.','Quando o líquido estiver ficando no estômago, retome pequenas porções de alimentos simples/toleráveis.','Evite longos períodos de jejum se isso piorar o enjoo.']},{title:'Quando falar com o pré-natal',paragraphs:['Incapacidade de manter líquidos, pouca urina ou urina muito escura, tontura importante, desmaio, palpitação, perda de peso, sangue no vômito, febre ou dor importante justificam avaliação.']}],sources:[{label:'ACOG · Morning sickness',url:'https://www.acog.org/womens-health/faqs/morning-sickness-nausea-and-vomiting-of-pregnancy'},{label:'RCOG · Pregnancy sickness',url:'https://www.rcog.org.uk/for-the-public/browse-our-patient-information/pregnancy-sickness-nausea-and-vomiting-of-pregnancy-and-hyperemesis-gravidarum/'}]});

set('pai',{title:'Ação prática: deixe um kit pós-enjoo pronto antes de ele ser necessário',summary:'Uma pequena preparação reduz esforço quando o enjoo vem forte: água, recipiente, toalha, enxágue bucal e um alimento simples que esteja sendo tolerado.',readTime:'3 MIN READ',badge:'SER PAI · AÇÃO DO DIA',sections:[{title:'Faça sem transformar em obrigação',bullets:['Pergunte quais líquidos e alimentos estão sendo tolerados.','Deixe tudo acessível, não escondido em armário alto.','Assuma a limpeza depois do episódio para reduzir carga física e mental.']}]});

set('carros',{title:'Usado bom: quilometragem é só uma evidência entre várias',summary:'Uma compra segura combina histórico de manutenção, laudo cautelar, desgaste coerente, arrefecimento, pneus, suspensão, fluidos e scanner. Baixa quilometragem sem documentação não vence um carro mais rodado e bem cuidado automaticamente.',readTime:'6 MIN READ',badge:'CARROS · COMPRA PRÁTICA',sections:[{title:'Cruze evidências',bullets:['Notas/revisões x km do painel.','Desgaste de volante, bancos e pedais.','Datas dos pneus e bateria.','Estado de reservatório, mangueiras e fluidos.','Laudo cautelar e scanner.']},{title:'Decisão',paragraphs:['Compre o exemplar, não o anúncio. O custo de “colocar em dia” pode apagar rapidamente uma diferença pequena de preço.']}]});

set('motos',{title:'Moto usada: sinais de queda ajudam a reconstruir o passado',summary:'Riscos em manetes, pedaleiras, tampas, escapamento e pontas do guidão podem indicar tombos; batentes de direção, rodas e bengalas ajudam a detectar impactos mais sérios.',readTime:'6 MIN READ',badge:'MOTOS · INSPEÇÃO',sections:[{title:'Checklist',bullets:['Batentes da mesa sem marcas anormais.','Guidão alinhado.','Bengalas sem vazamento ou empeno.','Rodas sem trinca/empeno.','Pneus e relação com desgaste coerente.','ABS sem luz de falha após partida.']}]});

set('mecanica',{title:'Teste de compressão não fecha diagnóstico sozinho',summary:'Pressão baixa em um cilindro pode indicar perda de vedação, mas a origem pode estar em válvula, anel, junta ou sincronismo. O teste de leak-down ajuda a localizar para onde o ar está escapando.',readTime:'5 MIN READ',badge:'MECÂNICA · DIAGNÓSTICO',sections:[{title:'Como interpretar',bullets:['Compare cilindros, não apenas um número absoluto.','Repita nas condições recomendadas pelo fabricante/procedimento.','Use leak-down para separar admissão, escape, cárter ou sistema de arrefecimento.']}]});

set('nautica',{title:'Colete salva-vidas precisa combinar com a atividade, o corpo e a homologação',summary:'Não basta “ter um colete no barco”. Tamanho, flutuabilidade, ajuste, estado e adequação à navegação determinam se ele realmente ajuda numa emergência.',readTime:'5 MIN READ',badge:'NÁUTICA · SEGURANÇA',sections:[{title:'Antes de sair',bullets:['Confirme homologação aplicável.','Ajuste no corpo antes da emergência.','Inspecione fechos, espuma e costuras.','Crianças exigem modelo e tamanho apropriados.']}]});

set('viagens',{title:'Holambra no fim de agosto: planeje o bate-volta antes de entrar no carro',summary:'Na temporada de flores, estacionamento, filas, horários e calor podem pesar mais que a distância. Planejamento simples melhora muito a experiência.',readTime:'5 MIN READ',badge:'VIAGEM · PERTO DE SP',sections:[{title:'Checklist',bullets:['Compre ingresso apenas em canal oficial quando o evento exigir.','Confira estacionamento e horário de pico.','Leve água, proteção solar e calçado confortável.','Se houver gestante no grupo, programe pausas e evite longos períodos em pé.']}]});

set('financas',{title:'Queda do juro longo não significa queda imediata do seu financiamento',summary:'O Tesouro dos EUA ampliou recompras de títulos longos e aliviou yields, mas o Fed continua preocupado com inflação. Taxas de mercado, taxa básica, spread bancário e risco do cliente são camadas diferentes.',readTime:'6 MIN READ',badge:'FINANÇAS · JUROS',sections:[{title:'Aplicação prática',paragraphs:['Ao comparar refinanciamento ou crédito, use CET e custo total contratado. Não tome uma dívida hoje supondo que um movimento de mercado vai virar juros menores para você amanhã.']},{title:'Por que isso importa',bullets:['Juro longo influencia financiamento e valuation.','Fed controla a taxa curta, mas não “manda” sozinho na curva inteira.']}],sources:[{label:'Reuters · Markets · 20/08/2026',url:'https://www.reuters.com/commentary/reuters-open-interest/global-markets-view-usa-2026-08-20/'}]});

set('tecnologia',{title:'IA em escala é infraestrutura física: energia, rede e capital podem virar o gargalo',summary:'Treinar e servir modelos exige mais do que aceleradores. Data centers dependem de conexão elétrica, refrigeração, interconexão, memória, storage, licenciamento, construção e financiamento.',readTime:'6 MIN READ',badge:'TECNOLOGIA · IA INFRA',sections:[{title:'A pilha real',bullets:['Compute: GPU/ASIC.','Memória: HBM/DRAM.','Rede: switches e óptica.','Storage: datasets, checkpoints e logs.','Energia/refrigeração: capacidade contínua.','Capital: custo de construir e operar.']},{title:'Conexão',paragraphs:['Quando o custo de capital sobe, projetos de IA precisam justificar retorno não só por performance, mas por utilização e receita.']}],sources:[{label:'Reuters · Markets / AI capex · 20/08/2026',url:'https://www.reuters.com/commentary/reuters-open-interest/global-markets-view-usa-2026-08-20/'}]});

set('seguranca',{title:'Cyber: exploração conhecida deve puxar hunting, não só patch',summary:'Uma vulnerabilidade ativamente explorada pode exigir investigar comprometimento anterior à correção. A pergunta deixa de ser apenas “qual versão corrigida?” e passa a incluir “houve exposição e evidência de abuso?”.',readTime:'7 MIN READ',badge:'CYBER · VULNERABILITY RESPONSE',sections:[{title:'Priorize com contexto',bullets:['Exploração confirmada.','Exposição à internet.','Privilégio obtido.','Criticidade do ativo.','Blast radius.','Telemetria disponível.']},{title:'Ação',paragraphs:['Para ativos expostos e exploráveis, preserve logs, procure indicadores e credenciais abusadas, aplique mitigação/patch e revalide integridade.']}],sources:[{label:'CISA · Known Exploited Vulnerabilities',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog'}]});

set('appsec-ssdlc',{title:'AppSec: severity + reachability + exposure + exploit evidence é melhor que CVSS sozinho',summary:'Uma fila de findings fica mais útil quando diferencia biblioteca presente de caminho realmente alcançável e quando adiciona contexto de internet exposure, exploração ativa e criticidade da aplicação.',readTime:'8 MIN READ',badge:'APPSEC · PRIORITIZATION',sections:[{title:'Modelo prático',bullets:['Severity: impacto potencial.','Reachability: o caminho vulnerável é executável?','Exposure: pode ser atingido externamente?','Exploit evidence: há exploração real/KEV/PoC?','Criticality: qual o impacto no negócio?']},{title:'Gate',paragraphs:['Bloqueio deve ser explicável e auditável. Um finding médio explorado e exposto pode merecer prioridade maior que um crítico inalcançável em código morto.']}],sources:[{label:'CISA · BOD 26-04 / KEV risk-based prioritization',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog'}]});

set('security-briefing',{title:'Security Briefing V2: decisões antes de volume',summary:'A estrutura permanece focada em sinais de maior valor, prioridade contextual, evidência a coletar, owner, decision gate e compartilhamento executivo/técnico.',readTime:'10 SINAIS',badge:'SECURITY BRIEFING V2'});

set('games',{title:'Gamescom 2026 se aproxima: agenda oficial vale mais que rumor',summary:'Com a Opening Night Live marcada para 25 de agosto e a feira principal na sequência, a pauta passa a separar anúncio confirmado, trailer, disponibilidade e expectativa ainda sem confirmação.',readTime:'5 MIN READ',badge:'GAMES · AGENDA'});
set('musica',{title:'Música: duas trilhas, dois contextos',summary:'Rock e sertanejo de época continuam totalmente separados, com histórico e players próprios. A curadoria do dia evita repetir artista+título e não reproduz letras protegidas.',readTime:'PLAYLISTS',badge:'MÚSICA · CURADORIA'});
