import type {RichMediaEntry} from './rich-media';
const commons=(name:string)=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(name).replace(/%2F/g,'/')}`;
export const dailyRichMedia20260829:RichMediaEntry[]=[
{label:'Curiosidades',matches:['dois padrões sobrepostos','moiré','moire'],tag:'MÍDIA REAL · CIÊNCIA',title:'Padrão moiré',caption:'Imagem específica do fenômeno de interferência visual descrito no Reel.',images:[{url:commons('Moiré pattern.svg'),alt:'Padrão moiré formado pela sobreposição de conjuntos de linhas',caption:'Exemplo de padrão moiré.',credit:'Fibonacci / Wikimedia Commons · CC BY-SA 3.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Moir%C3%A9_pattern.svg',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['nariz pode parar de notar','olfato','cheiro'],tag:'MÍDIA REAL · CORPO HUMANO',title:'Sistema olfatório humano',caption:'Diagrama anatômico diretamente ligado ao funcionamento do olfato.',images:[{url:commons('Olfactory system.svg'),alt:'Diagrama anatômico do sistema olfatório humano com epitélio e bulbo olfatório',caption:'Sistema olfatório humano.',credit:'Chabacano / Wikimedia Commons · CC BY-SA 2.5',sourceUrl:'https://commons.wikimedia.org/wiki/File:Olfactory_system.svg',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['internet pode continuar lembrando','dns','ttl'],tag:'MÍDIA REAL · TECNOLOGIA',title:'Hierarquia DNS',caption:'Diagrama específico da hierarquia do Domain Name System.',images:[{url:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/DNS_schema.svg/960px-DNS_schema.svg.png',alt:'Diagrama da hierarquia de nomes e servidores DNS',caption:'Esquema de DNS.',credit:'TilmannR / Wikimedia Commons · CC BY-SA 2.5',sourceUrl:'https://commons.wikimedia.org/wiki/File:DNS_schema.svg',kind:'REFERENCE'}]},
{label:'Política',matches:['flávio bolsonaro diz que respeitará','e-título entra em manutenção','e-titulo entra em manutencao'],tag:'MÍDIA ELEITORAL · TSE',title:'Urna eletrônica brasileira',caption:'Imagem institucional neutra para o radar eleitoral.',images:[{url:commons('Brazilian DRE voting machine for 2022 elections.jpg'),alt:'Urna eletrônica brasileira em fotografia institucional',caption:'Urna eletrônica brasileira.',credit:'TSE / Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Brazilian_DRE_voting_machine_for_2022_elections.jpg',kind:'PHOTO'}]},
{label:'Mundo',matches:['guerra e sanções aprofundam','economia do irã','hormuz'],tag:'MÍDIA REAL · MAPA',title:'Estreito de Hormuz',caption:'Mapa geográfico diretamente ligado à rota marítima citada.',images:[{url:commons('Strait of Hormuz-svg-en.svg'),alt:'Mapa do Estreito de Hormuz entre Irã e Omã',caption:'Estreito de Hormuz.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Strait_of_Hormuz-svg-en.svg',kind:'REFERENCE'}]},
{label:'Tempo e Clima',matches:['são paulo tem sábado seco e quente','sao paulo tem sabado seco e quente','33°c'],tag:'MÍDIA REAL · SÃO PAULO',title:'São Paulo em dia ensolarado',caption:'Fotografia real da cidade como contexto para o boletim do CGE.',images:[{url:commons('Parque da Independência - São Paulo - Brasil.jpg'),alt:'Parque da Independência em São Paulo sob céu aberto',caption:'São Paulo.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Parque_da_Independ%C3%AAncia_-_S%C3%A3o_Paulo_-_Brasil.jpg',kind:'PHOTO'}]},
{label:'Games',matches:['gamescom tem final do concurso de cosplay','final do concurso de cosplay','gamescom'],tag:'MÍDIA REAL · GAMESCOM',title:'gamescom em Colônia',caption:'Fotografia real da entrada da gamescom, diretamente ligada ao evento.',images:[{url:commons('Main Entrance View at Gamescom 2025 in Cologne, Germany.jpg'),alt:'Entrada principal da gamescom no centro de exposições de Colônia',caption:'gamescom em Colônia.',credit:'RAWdz Ivan / Wikimedia Commons · CC BY 4.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Main_Entrance_View_at_Gamescom_2025_in_Cologne,_Germany.jpg',kind:'PHOTO'}]}
];
