import type { RichMediaEntry } from './rich-media';
import { dailyRichMedia20260820 } from './daily-rich-media-2026-08-20';
import { appSecPostMedia } from './appsec-feed-media';

const commons = (name: string) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(name).replace(/%2F/g,'/')}`;
const base = (label: string) => dailyRichMedia20260820.find((item) => item.label === label);

type Img = RichMediaEntry['images'][number];
const image = (url:string, alt:string, caption:string, credit:string, sourceUrl:string, kind:Img['kind']='REFERENCE'): Img => ({ url, alt, caption, credit, sourceUrl, kind });

function reuse(label:string, matches:string[], title:string, caption:string, images?:Img[], relatedHref?:string): RichMediaEntry {
  const previous = base(label);
  return {
    label,
    matches,
    tag:'MÍDIA DA EDIÇÃO · 21 AGO',
    title,
    caption,
    images: images ?? previous?.images ?? [],
    relatedLabel: previous?.relatedLabel ?? 'Abrir fonte visual',
    relatedHref: relatedHref ?? previous?.relatedHref,
    youtubeId: previous?.youtubeId,
  };
}

const appsec = appSecPostMedia['agent-authorization'];

export const dailyRichMedia20260821: RichMediaEntry[] = [
  reuse('Brasil', ['fim da escala 6x1','escala 6x1','jornada semanal'], 'Congresso no centro da discussão sobre jornada de trabalho', 'Imagem do plenário do Senado como contexto institucional para a tramitação. O avanço legislativo deve ser conferido nas fontes da matéria.', [image(commons('PlenarioSenadoFederal.jpg'),'Plenário do Senado Federal em Brasília','Plenário do Senado Federal.','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:PlenarioSenadoFederal.jpg','PHOTO')]),
  reuse('Zona Leste em Foco', ['zl agora','zona leste em foco','aricanduva','ponte rasa','itaquera e serviços'], 'Itaquera nas últimas horas', 'A imagem é da partida na Neo Química Arena em 20/08, uma das pautas atuais de Itaquera; segurança, saúde, obras e serviços aparecem em cards próprios no hub.', [image('https://conteudo.imguol.com.br/c/esporte/f5/2026/08/20/memphis-comemora-gol-do-corinthians-sobre-o-rosario-central-em-jogo-da-libertadores-1787279421859_v2_450x450.jpg','Memphis comemora gol do Corinthians sobre o Rosario Central na Neo Química Arena','Corinthians x Rosario Central em Itaquera, 20 de agosto.','REUTERS / Jean Carniel · via UOL Esporte','https://www.uol.com.br/esporte/futebol/ultimas-noticias/2026/08/20/libertadores-corinthians-x-rosario-central.ghtm','PHOTO')]),
  reuse('Política', ['tse define','horário eleitoral','propaganda no rádio','propaganda na tv'], 'Justiça Eleitoral e a próxima fase da campanha', 'Imagem oficial do TSE identifica a pauta eleitoral; datas e regras do horário eleitoral ficam vinculadas às fontes oficiais.', undefined, 'https://www.tse.jus.br/comunicacao/noticias/2026/Agosto/tse-aprova-plano-de-midia-para-o-horario-eleitoral-gratuito-das-eleicoes-2026'),
  reuse('Mundo', ['kyiv sofre','ataque de grande escala','mísseis balísticos','defesa aérea'], 'Defesa antimíssil volta ao centro da guerra na Ucrânia', 'A imagem mostra um sistema Patriot, diretamente relacionado ao debate sobre interceptadores após o ataque de grande escala a Kyiv. Não representa a cena do ataque de 20/08.', [image(commons('MIM-104 Patriot surface-to-air missile system launcher.jpg'),'Sistema de defesa aérea MIM-104 Patriot','Sistema Patriot; imagem contextual, não fotografia do ataque de 20/08.','Robert Barney / U.S. Air Force · domínio público via Wikimedia Commons','https://commons.wikimedia.org/wiki/File:MIM-104_Patriot_surface-to-air_missile_system_launcher.jpg','PHOTO')]),
  reuse('Planeta', ['termoclina','fronteira invisível','água quente da superfície'], 'Termoclina visualizada em corte do oceano', 'Diagrama NOAA ajuda a enxergar a camada quente superficial e a mudança rápida de temperatura com a profundidade.', [image('https://www.pmel.noaa.gov/elnino/sites/default/files/thumbnails/image/normal-only.gif','Diagrama NOAA mostrando camada superficial quente e termoclina no Pacífico','Esquema de condições normais no Pacífico com a termoclina indicada.','NOAA / PMEL','https://www.pmel.noaa.gov/elnino/what-is-el-nino','CHART')]),
  reuse('Mundo Animal', ['canal acústico','som por enormes distâncias','sofar'], 'O canal acústico profundo do oceano', 'O diagrama da NOAA mostra como a velocidade do som varia com profundidade e pode criar o canal SOFAR usado para propagação de longa distância.', [image('https://oceanservice.noaa.gov/facts/sofar.jpg','Diagrama da NOAA sobre o canal SOFAR e velocidade do som no oceano','Canal SOFAR: som pode ficar refratado em uma faixa de profundidade.','NOAA Ocean Service','https://oceanservice.noaa.gov/facts/sofar.html','CHART')]),
  reuse('Tempo e Clima', ['são paulo esfria','sexta mais fria','vento merece atenção'], 'São Paulo entra numa sexta mais fria', 'A fotografia situa a pauta na capital; temperatura, vento e alertas devem ser lidos nos dados meteorológicos e comunicados da Defesa Civil.', undefined),
  reuse('Curiosidades', ['pôr do sol fica vermelho','céu normalmente é azul','espalhamento da luz'], 'Por que a luz muda de cor perto do horizonte', 'Diagrama educativo da NASA mostra o caminho da luz na atmosfera e ajuda a visualizar por que o céu e o pôr do sol têm cores diferentes.', [image('https://spaceplace.nasa.gov/blue-sky/en/sky3.en.png','Diagrama da NASA mostrando espalhamento da luz solar na atmosfera','A luz atravessa mais atmosfera perto do horizonte; azul é espalhado e os tons quentes dominam o feixe direto.','NASA Space Place','https://spaceplace.nasa.gov/blue-sky/en/','CHART')]),
  reuse('Música', ['fim de semana coloca rock','rock nacional dos anos 80','sertanejo histórico'], 'São Paulo recebe dois encontros de memória musical neste fim de semana', 'A arte do Histórias representa uma das trilhas do fim de semana; Rock continua separado dentro do hub.', undefined),
  reuse('Games', ['gamescom entra','dev começa dia 23','evento principal abre','opening night live'], 'gamescom 2026 entra na semana decisiva', 'Arte ligada à participação confirmada na gamescom; o hub usa agenda oficial para separar datas confirmadas de rumor.', undefined),
  reuse('Gravidez', ['6 semanas + 5 dias','pós-parto','preparação inteligente para o pós-parto'], 'Referência visual da fase gestacional', 'Imagem de referência da gestação inicial. O módulo da aba também traz material educativo de puerpério; imagem não substitui ultrassom clínico.', undefined),
  reuse('Ser Pai', ['reduza a carga mental','perceber','apoio que reduz carga'], 'Apoio materno é presença prática', 'Material do CDC Hear Her reforça escuta, apoio e busca de cuidado quando necessário.', undefined),
  reuse('Carros', ['histórico térmico','superaquecimento','arrefecimento'], 'Comparativo de usados com foto real dos modelos', 'A Home usa um dos modelos reais da seleção; cada veículo possui sua própria foto e análise dentro do comparador.', undefined),
  reuse('Motos', ['pneu velho','pneu de moto','ressecamento'], 'Moto usada precisa ser lida além da quilometragem', 'A Home usa um modelo real da seleção; o comparador mantém fotos individuais e checklist técnico.', undefined),
  reuse('Mecânica', ['fluido de freio','absorve umidade','margem térmica'], 'Reservatório de fluido de freio no veículo', 'O fluido faz parte do circuito hidráulico. A imagem mostra o reservatório; a matéria explica por que umidade e temperatura reduzem margem contra fervura.', [image(commons('Brake fluid reservoir in Škoda Fabia I.jpg'),'Reservatório de fluido de freio em automóvel','Reservatório de fluido de freio em um Škoda Fabia I; usado apenas para ilustrar o componente.','Frettie / Wikimedia Commons · CC','https://commons.wikimedia.org/wiki/File:Brake_fluid_reservoir_in_%C5%A0koda_Fabia_I.jpg','PHOTO')]),
  reuse('Náutica', ['nó e milha náutica','milha náutica','1.852'], 'Carta náutica: a linguagem em que milhas e nós fazem sentido', 'Carta náutica da NOAA ajuda a conectar distância, coordenadas e navegação; não deve ser usada como carta atual para navegar.', [image(commons('Culebra Nautical chart.png'),'Carta náutica NOAA da ilha de Culebra','Carta náutica NOAA usada como exemplo visual da linguagem de navegação.','NOAA · domínio público via Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Culebra_Nautical_chart.png','CHART')]),
  reuse('Viagens', ['paranapiacaba','bate-volta perto de sp','neblina'], 'Paranapiacaba vista do alto', 'A fotografia mostra a vila ferroviária e ajuda a visualizar o relevo e a ocupação histórica do destino.', [image(commons('Paranapiacaba SP.jpg'),'Vista de Paranapiacaba a partir da passarela','Vila Ferroviária de Paranapiacaba, em Santo André.','Belle Oliveira / Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Paranapiacaba_SP.jpg','PHOTO')]),
  reuse('Finanças', ['dólar fechou','dólar perto','petróleo subiu','geopolítica pode voltar ao seu bolso'], 'Real, câmbio e o canal financeiro do choque externo', 'Cédulas brasileiras representam a dimensão cambial da pauta; a cotação do dia e o petróleo vêm das fontes de mercado, não da fotografia.', [image(commons('Nota de 100 reais (dinheiro do Brasil).jpg'),'Cédula de cem reais brasileira','Imagem contextual do real brasileiro para a pauta de câmbio e petróleo.','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Nota_de_100_reais_(dinheiro_do_Brasil).jpg','PHOTO')]),
  reuse('Tecnologia', ['cerebras lança cs-4','cerebras cs-4','acelerar inferência'], 'Cerebras CS-4: rack-scale para inferência', 'Imagem oficial do novo sistema CS-4, apresentado em agosto de 2026.', [image('https://cdn.sanity.io/images/e4qjo92p/production/b6b320e96a3a5e615e4c1474bb1deac4ca669416-10394x8820.png?auto=format&dpr=2&fit=max&q=75&w=1600','Sistema Cerebras CS-4 em rack, com gabinete fechado e interior exposto','Cerebras CS-4, sistema rack-scale para inferência.','Cerebras · divulgação oficial','https://www.cerebras.ai/cs4','REFERENCE')]),
  reuse('Security Briefing', ['decision desk revisado','identidade, supply chain','exploração real e agentes'], 'Security Decision Desk validado na edição de hoje', 'O catálogo KEV continua sendo uma das fontes de exploração conhecida; o briefing cruza esse sinal com identidade, exposição, supply chain e blast radius.', undefined),
  reuse('Cyber Security', ['clickfix continua','clickfix','corrigir um erro'], 'A cadeia do ClickFix em um diagrama oficial', 'A Microsoft mostra a sequência típica: lure → copiar/executar comando → download de código → malware. O foco do site é prevenção e detecção.', [image('https://www.microsoft.com/en-us/security/blog/wp-content/uploads/2025/08/Fig1-Typical-ClickFix-attack-chain-1.webp','Diagrama da Microsoft sobre a cadeia típica de ataque ClickFix','Fluxo típico do ClickFix, da isca à entrega de malware.','Microsoft Threat Intelligence / Microsoft Defender Experts','https://www.microsoft.com/en-us/security/blog/2025/08/21/think-before-you-clickfix-analyzing-the-clickfix-social-engineering-technique/','CHART')]),
  reuse('AppSec / SSDLC', ['agentic ci/cd','pipeline precisa tratar prompt','tool call e token'], 'Agentic Security e autorização por ação', appsec?.caption ?? 'Material OWASP associado à segurança de sistemas agentic e autorização de ferramentas.', appsec ? [image(appsec.url,appsec.alt,appsec.caption,appsec.credit,appsec.sourceUrl,'REFERENCE')] : undefined, appsec?.sourceUrl),
];
