import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f4f0e7"/><rect x="70" y="110" width="940" height="1700" rx="84" fill="#e8eeea"/><circle cx="540" cy="610" r="285" fill="#31594d" opacity=".15"/><text x="540" y="705" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M210 1030h660" stroke="#31594d" stroke-width="14" opacity=".55"/><text x="540" y="1215" text-anchor="middle" font-size="58" font-weight="700" font-family="Arial,sans-serif" fill="#263f37">${headline}</text><text x="540" y="1340" text-anchor="middle" font-size="37" font-family="Arial,sans-serif" fill="#51675f">${sub}</text><text x="540" y="1530" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#6b7d76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 07/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 07/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260907:RichMediaEntry[]=[
img('Papo de hoje',['o que aconteceu hoje e te deixou um pouco melhor','te deixou um pouco melhor'],'🙂','O QUE MELHOROU O DIA?','CONTE O PEQUENO MOMENTO','Arte 9:16 específica para conversa sobre um pequeno acontecimento positivo do dia','https://www.gov.br/saude/pt-br'),
img('Desafio do casal',['filme ou episódio sem rolar catálogo','duas opções'],'🎬','ESCOLHAM SEM ENROLAR','2 OPÇÕES DE CADA LADO','Arte 9:16 específica com tela de cinema e duas escolhas para desafio do casal','https://www.gov.br/cultura/pt-br'),
img('Curiosidades',['beija-flores conseguem voar para trás','beija-flor'],'🐦','VOO PARA TRÁS','BEIJA-FLOR EM CONTROLE','Arte 9:16 específica com beija-flor pairando e seta de recuo','https://nationalzoo.si.edu/migratory-birds/hummingbirds'),
img('Curiosidades',['corredor para o som viajar muito longe','canal sofar'],'🌊','CANAL SOFAR','SOM GUIADO NO OCEANO','Arte 9:16 específica com ondas acústicas curvadas em uma camada oceânica','https://oceanservice.noaa.gov/facts/sofar.html'),
img('Curiosidades',['16 nasceres do sol','estação espacial internacional'],'🛰️','ISS · CERCA DE 16','AMANHECERES POR DIA','Arte 9:16 específica com estação orbital e múltiplos amanheceres','https://www.nasa.gov/international-space-station/space-station-facts-and-figures/'),
img('Curiosidades',['metal pode derreter perto da temperatura','gálio'],'🧪','GÁLIO · 29,8°C','METAL QUE FUNDE CEDO','Arte 9:16 específica com metal sólido passando ao estado líquido','https://pubchem.ncbi.nlm.nih.gov/element/Gallium'),
img('Curiosidades',['paisagem gelada do planeta também é um deserto','antártida'],'❄️','ANTÁRTIDA','DESERTO DE GELO','Arte 9:16 específica com planície antártica e baixa precipitação','https://www.bas.ac.uk/about/antarctica/weather/'),
img('Gravidez',['9 semanas + 1 dia','9s1d'],'🤰','9 SEMANAS + 1 DIA','DESENVOLVIMENTO CONTINUA','Arte 9:16 específica para 9 semanas e 1 dia de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/9-weeks/'),
img('Ser Pai',['deixe o café da manhã mais fácil','antes de ela levantar'],'🥛','MANHÃ MAIS FÁCIL','ÁGUA + OPÇÃO SIMPLES','Arte 9:16 específica com água e pequeno café da manhã preparado com antecedência','https://www.cdc.gov/hearher/'),
img('Brasil',['7 de setembro: feriado nacional','desfile cívico-militar'],'🇧🇷','7 DE SETEMBRO','204 ANOS DE INDEPENDÊNCIA','Arte 9:16 específica com bandeira brasileira e referência a desfile cívico','https://prefeitura.sp.gov.br/w/confira-as-mudan%C3%A7as-no-tr%C3%A2nsito-e-no-transporte-para-o-desfile-de-7-de-setembro'),
img('Tempo e Clima',['feriado começa frio em são paulo','muitas nuvens'],'🌥️','SÃO PAULO · FRIO','FERIADO COM MUITAS NUVENS','Arte 9:16 específica com termômetro baixo, nuvens e chuva isolada','https://portal.inmet.gov.br/'),
img('Viagens',['passeio de feriado pelo horário de retorno','horário de retorno'],'🛣️','PLANEJE A VOLTA','NÃO SÓ A IDA','Arte 9:16 específica com estrada, relógio e rota de retorno','https://www.der.sp.gov.br/'),
img('Música',['faixa pelo baixo','linha de baixo'],'🎸','SIGA SÓ O BAIXO','UMA ESCUTA DIFERENTE','Arte 9:16 específica com baixo elétrico e linha sonora destacada','https://www.gov.br/cultura/pt-br'),
img('Finanças',['b3 e agências bancárias','sem expediente presencial'],'🏦','FERIADO FINANCEIRO','B3 FECHADA · PIX ATIVO','Arte 9:16 específica com bolsa fechada e celular representando canais digitais','https://www.b3.com.br/pt_br/noticias/operacoes-8AA8D0CCA023A7E401A0684420A61A2D.htm'),
img('Carros até R$ 70 mil',['ruído que muda quando você esterça','curvas lentas'],'🚗','ATÉ R$70 MIL','OUÇA AO ESTERÇAR','Arte 9:16 específica com carro em curva e indicação de ruído na direção','https://www.gov.br/senatran/pt-br'),
img('Motos',['pneus contam a mesma história','desgaste dos pneus'],'🏍️','LEIA OS PNEUS','PADRÃO DE DESGASTE','Arte 9:16 específica com pneus de motocicleta e zonas de desgaste destacadas','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['fluido de freio velho','aparência do fluido'],'🛠️','FLUIDO DE FREIO','APARÊNCIA NÃO BASTA','Arte 9:16 específica com reservatório de fluido e instrumento de teste','https://www.gov.br/senatran/pt-br')
];
