import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'MÍDIA REAL · 14/09',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260914:RichMediaEntry[]=[
img('Papo de hoje',['se o dia de hoje virasse uma foto','o que apareceria nela'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Couple%20sits%20together%20on%20a%20couch%20with%20a%20camera.jpg','Casal sentado no sofá com uma câmera fotográfica, em registro real','Foto real · Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Couple_sits_together_on_a_couch_with_a_camera.jpg'),
img('Desafio do casal',['escolham uma comida que nenhum dos dois pede','comida que nenhum dos dois pede há muito tempo'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Couple%20enjoys%20a%20happy%20moment%20together%20in%20a%20bright%20kitchen.jpg','Casal preparando comida junto em uma cozinha clara','Foto real · Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Couple_enjoys_a_happy_moment_together_in_a_bright_kitchen.jpg'),
img('Curiosidades',['beija-flores conseguem voar para trás','pairar e também voar para trás'],'https://images.unsplash.com/photo-1636257513918-8546b4c93d1b?auto=format&fit=crop&w=1200&q=85','Beija-flor real pairando diante de uma flor','Foto real · Unsplash','https://unsplash.com/photos/a-hummingbird-flying-near-a-flower-vDWv6qkL6SY'),
img('Curiosidades',['canal sofar','sons graves viagem enormes distâncias'],'https://cdn.oceanservice.noaa.gov/oceanserviceprod/facts/sofar.jpg','Diagrama oficial da NOAA mostrando a propagação de som no canal SOFAR','Visual científico · NOAA Ocean Service','https://oceanservice.noaa.gov/facts/sofar.html'),
img('Curiosidades',['crateras perto dos polos da lua permanecem em sombra permanente','sombra permanente'],'https://static.scientificamerican.com/sciam/cache/file/5A0ADC63-7254-4D1E-B4F5BB1B76418EB6_source.jpeg','Mosaico científico real do terreno de Shackleton no polo sul da Lua','NASA/KARI/ASU · LROC + ShadowCam','https://www.nasa.gov/missions/lro/nasa-moon-camera-mosaic-sheds-light-on-lunar-south-pole/'),
img('Curiosidades',['poeira transportada desde o saara','saara e amazônia'],'https://svs.gsfc.nasa.gov/vis/a010000/a011700/a011775/G2015-021-Saharan_Dust_Travels_To_Amazon-1920-Master_youtube_hq_print.jpg','Imagem de satélite da NASA mostrando poeira do Saara atravessando o Atlântico em direção à América do Sul','Visual científico real · NASA Goddard Scientific Visualization Studio','https://svs.gsfc.nasa.gov/11775'),
img('Curiosidades',['controles remotos comuns enviam comandos usando luz infravermelha','controle remoto tradicional'],'https://siabilderarchiv.yedo.at/images/gross/00110198.jpg','Controle remoto emitindo infravermelho observado por uma câmera digital','Foto real · YEDO Bildarchiv','https://siabilderarchiv.yedo.at/'),
img('Gravidez',['10 semanas + 1 dia','10s1d'],'https://upload.wikimedia.org/wikipedia/commons/1/1b/10_Weeks_Fetus.JPG','Ultrassom real do primeiro trimestre compatível com cerca de 10 semanas de gestação','Foto real · Wikimedia Commons · CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:10_Weeks_Fetus.JPG'),
img('Ser Pai',['assuma uma refeição inteira','sem devolver decisões'],'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg','Pessoa oferecendo apoio prático a uma gestante','Foto real · CDC Hear Her','https://www.cdc.gov/hearher/support-family-friends/index.html'),
img('Política',['prazo final para substituição ordinária de candidaturas','substituição de candidaturas'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Sede_do_Tribunal_Superior_Eleitoral%2C_em_Bras%C3%ADlia.jpg/1280px-Sede_do_Tribunal_Superior_Eleitoral%2C_em_Bras%C3%ADlia.jpg','Sede do Tribunal Superior Eleitoral em Brasília','Foto real · Alexandresena/Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Sede_do_Tribunal_Superior_Eleitoral,_em_Bras%C3%ADlia.jpg'),
img('Viagens',['essencial disponível mesmo sem internet','plano offline'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Smartphone%20with%20navigation%20map%20app.jpg','Smartphone real exibindo aplicativo de navegação por mapa','Foto real · Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Smartphone_with_navigation_map_app.jpg'),
img('Música',['prestando atenção só no baixo','linha de baixo'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Electric_bass_guitar_(front_view).jpg/800px-Electric_bass_guitar_(front_view).jpg','Baixo elétrico fotografado de frente','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Electric_bass_guitar_(front_view).jpg'),
img('Carros até R$ 70 mil',['partida a frio','motor realmente frio'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Engine%20Start%20Button%20%283733678176%29.jpg','Botão real de partida do motor em painel automotivo','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Engine_Start_Button_(3733678176).jpg'),
img('Motos',['examine discos e resposta dos freios','discos e resposta dos freios'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Brembo%20motorcycle%20brake.jpg','Conjunto real de disco e pinça de freio em uma motocicleta','Foto real · Wikimedia Commons · CC0','https://commons.wikimedia.org/wiki/File:Brembo_motorcycle_brake.jpg'),
img('Mecânica',['vibração excessiva pode apontar para coxins','coxins'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Engine%20mount%20static%20test.jpg','Coxim de motor em teste mecânico estático','Foto real · Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Engine_mount_static_test.jpg')
];
