import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f4f1e8"/><rect x="70" y="110" width="940" height="1700" rx="84" fill="#e8ece7"/><circle cx="540" cy="610" r="285" fill="#314f47" opacity=".14"/><text x="540" y="705" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M210 1030h660" stroke="#314f47" stroke-width="14" opacity=".55"/><text x="540" y="1215" text-anchor="middle" font-size="53" font-weight="700" font-family="Arial,sans-serif" fill="#263b35">${headline}</text><text x="540" y="1340" text-anchor="middle" font-size="35" font-family="Arial,sans-serif" fill="#53655f">${sub}</text><text x="540" y="1530" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#6d7b76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 10/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 10/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260910:RichMediaEntry[]=[
img('Papo de hoje',['hábito pequeno de vocês','rotina ficar mais corrida'],'🔁','UM HÁBITO QUE FICA','QUANDO A ROTINA APERTA','Arte 9:16 específica com ciclo simples representando um hábito do casal que permanece mesmo em rotina corrida','https://www.cdc.gov/healthyschools/features/connectedness.htm'),
img('Desafio do casal',['coisa simples para fazer juntos','até domingo'],'🎯','UMA COISA ATÉ DOMINGO','SIMPLES E JUNTOS','Arte 9:16 específica com alvo e calendário curto para escolher uma atividade simples até domingo','https://www.gov.br/turismo/pt-br'),
img('Curiosidades',['polvos têm três corações','três corações e sangue azul'],'🐙','3 CORAÇÕES','E SANGUE AZUL','Arte 9:16 específica com polvo e três símbolos de coração para explicar a circulação dos cefalópodes','https://ocean.si.edu/ocean-life/invertebrates/octopuses-squids-and-relatives'),
img('Curiosidades',['dia em vênus','mais longo que o ano'],'♀️','VÊNUS: DIA > ANO','243 × 225 DIAS','Arte 9:16 específica com Vênus, relógio e órbita comparando rotação e translação','https://science.nasa.gov/venus/venus-facts/'),
img('Curiosidades',['placas tectônicas','unhas crescem'],'🌎','PLACAS EM MOVIMENTO','RITMO DE UNHAS','Arte 9:16 específica com placas tectônicas e régua de centímetros por ano','https://www.usgs.gov/faqs/how-fast-do-tectonic-plates-move'),
img('Curiosidades',['olfato participa','sabor da comida'],'👃','CHEIRO + SABOR','DOIS CAMINHOS','Arte 9:16 específica mostrando nariz e boca conectados na percepção de aroma e sabor','https://www.nidcd.nih.gov/health/smell-disorders'),
img('Curiosidades',['micro-ondas usa radiação não ionizante','micro-ondas são não ionizantes'],'📡','MICRO-ONDAS','RADIAÇÃO NÃO IONIZANTE','Arte 9:16 específica com forno de micro-ondas, ondas eletromagnéticas e escudo metálico estilizado','https://www.fda.gov/radiation-emitting-products/resources-you-radiation-emitting-products/microwave-ovens'),
img('Gravidez',['9 semanas + 4 dias','9s4d'],'🤰','9 SEMANAS + 4 DIAS','DESENVOLVIMENTO ACELERADO','Arte 9:16 específica para 9 semanas e 4 dias de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/9-weeks/'),
img('Ser Pai',['tarefa logística inteira','assuma uma tarefa'],'📋','DO COMEÇO AO FIM','UMA TAREFA INTEIRA','Arte 9:16 específica com checklist concluído para representar apoio prático sem transferir coordenação','https://www.cdc.gov/hearher/support-family-friends/index.html'),
img('Política',['tse tem sessão marcada','13 processos na pauta'],'🏛️','TSE · 10H','13 PROCESSOS NA PAUTA','Arte 9:16 específica com plenário eleitoral estilizado, relógio e pauta numerada','https://www.tse.jus.br/comunicacao/noticias/2026/Setembro/confira-a-pauta-de-julgamentos-do-tse-desta-quinta-feira-10'),
img('Tempo e Clima',['são paulo entra nesta quinta','sob alerta de chuva forte'],'⛈️','ALERTA AINDA VALE','QUINTA · 10/09','Arte 9:16 específica com tempestade e calendário destacando a vigência do alerta em 10 de setembro','https://www.defesacivil.sp.gov.br/'),
img('Viagens',['destino utilizável mesmo se o sinal cair','plano offline'],'📍','PLANO OFFLINE','ENDEREÇO + ROTA','Arte 9:16 específica com mapa, pino de destino e símbolo de conexão indisponível','https://support.google.com/maps/answer/6291838'),
img('Música',['mesma faixa no estúdio e ao vivo','estúdio e ao vivo'],'🎙️','ESTÚDIO × AO VIVO','OUÇA O QUE MUDA','Arte 9:16 específica dividida entre estúdio e palco para comparar versões da mesma música','https://www.gov.br/cultura/pt-br'),
img('Games',['xbox lista uma leva de lançamentos','lançamentos prevista para esta quinta-feira'],'🎮','LANÇAMENTOS · 10/09','AGENDA XBOX','Arte 9:16 específica com controle e calendário de lançamentos previstos para 10 de setembro','https://news.xbox.com/en-us/2026/09/04/next-week-on-xbox-new-games-for-september-7-to-11/'),
img('Tecnologia',['visa, mastercard e ant criam iniciativa','verificar agentes de ia'],'🤖','AGENTES DE IA','IDENTIDADE + CONFIANÇA','Arte 9:16 específica com agente de IA, cartão e selo de verificação para padrões de pagamentos','https://www.reuters.com/technology/payment-firms-visa-mastercard-ant-international-team-up-ai-agent-trust-framework-2026-09-10/'),
img('Finanças',['brent segue acima de us$ 100','início desta quinta-feira'],'🛢️','BRENT > US$100','COTAÇÃO INTRADIA','Arte 9:16 específica com barril e gráfico intradiário acima da linha de US$100','https://www.reuters.com/business/energy/brent-holds-above-100-tanker-attacks-deepen-supply-fear-2026-09-10/'),
img('Carros até R$ 70 mil',['primeira partida com o motor frio','motor frio'],'🚗','ATÉ R$70 MIL','PARTIDA A FRIO','Arte 9:16 específica com carro usado, termômetro frio e chave de ignição para avaliação pré-compra','https://www.gov.br/senatran/pt-br'),
img('Motos',['corrente em mais de um ponto','folga da corrente'],'⛓️','CORRENTE DA MOTO','CONFIRA A VOLTA TODA','Arte 9:16 específica com transmissão de motocicleta e marcadores em diferentes trechos da corrente','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['luz da injeção acesa','peça culpada'],'🧰','LUZ DA INJEÇÃO','PISTA ≠ DIAGNÓSTICO','Arte 9:16 específica com painel, scanner e fluxo de diagnóstico automotivo sem indicar troca automática de peça','https://www.gov.br/senatran/pt-br')
];
