import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'MÍDIA REAL · 16/09',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260916:RichMediaEntry[]=[
img('Papo de hoje',['qual coisa boba sempre consegue fazer você rir'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Laughing_woman.jpg','Pessoa rindo espontaneamente','Foto real · Basile Morin/Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Laughing_woman.jpg'),
img('Desafio do casal',['cada um indica um vídeo de até 10 minutos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Youtube_App_Startup.JPG','Celular com aplicativo de vídeo aberto','Foto real · SCBY/Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Youtube_App_Startup.JPG'),
img('Curiosidades',['polvos têm três corações','três corações','sangue azulado'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Octopus2.jpg','Polvo em ambiente marinho','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Octopus2.jpg'),
img('Gravidez',['10 semanas + 3 dias','10s3d'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Embryo_at_10_weeks.JPG','Ultrassom real de embrião humano em torno de 10 semanas','Imagem médica real · X.Compagnion/Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Embryo_at_10_weeks.JPG'),
img('Ser Pai',['refeição simples encaminhada','antecipe uma refeição'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Meal_preparation.jpg','Preparação doméstica de refeição','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Mundo',['china alerta que armas dos eua no espaço','corrida armamentista'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/International_Space_Station_after_undocking_of_STS-132.jpg','Estrutura orbital fotografada no espaço','Imagem real · NASA/Wikimedia Commons · domínio público','https://commons.wikimedia.org/'),
img('Corinthians',['dia de decisão','estudiantes às 21h30'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Arena_Corinthians_fev_2014.jpg','Neo Química Arena, palco da partida desta noite','Foto real · Vitor123vitin/Wikimedia Commons · CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Arena_Corinthians_fev_2014.jpg'),
img('Viagens',['salve offline o endereço','mapa da hospedagem'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Google_Maps_on_smartphone.jpg','Mapa digital aberto em smartphone','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Música',['versão de estúdio','apresentação ao vivo'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Concert_stage.jpg','Palco de apresentação musical ao vivo','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Tecnologia',['união europeia chama laboratórios de ia','laboratórios de ia de fronteira'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Berlaymont_building.jpg','Edifício Berlaymont, sede da Comissão Europeia em Bruxelas','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Carros até R$ 70 mil',['luzes do painel','autoteste das luzes'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Car_dashboard.jpg','Painel de instrumentos de automóvel','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Motos',['óleo nas bengalas','vazamento antes do test-ride'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Motorcycle_front_fork.jpg','Suspensão dianteira de motocicleta','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Mecânica',['vibração ao frear','vibração no pedal'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Disc_brake_dsc03680.jpg','Disco e pinça de freio automotivo','Foto real · Wikimedia Commons','https://commons.wikimedia.org/')
];