import type {RichMediaEntry} from './rich-media';
const commons=(name:string)=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(name).replace(/%2F/g,'/')}`;
export const dailyRichMedia20260829:RichMediaEntry[]=[
{label:'Curiosidades',matches:['água pode ferver','temperatura ambiente','pressão cair'],tag:'ARTE ESPECÍFICA · CIÊNCIA',title:'Ebulição em baixa pressão',caption:'Visual específico de água entrando em ebulição sob baixa pressão.',images:[{url:'/generated/curiosity-vacuum-boil-20260829.svg',alt:'Recipiente com água formando bolhas em ambiente de baixa pressão',caption:'Ebulição em baixa pressão.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.nasa.gov/wp-content/uploads/2023/05/dressing-for-altitude-nov-2017.pdf',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['dedos enrugam','sistema nervoso','dedos enrugados'],tag:'ARTE ESPECÍFICA · CORPO HUMANO',title:'Dedos enrugados na água',caption:'Visual específico da resposta fisiológica dos dedos à imersão.',images:[{url:'/generated/curiosity-finger-wrinkle-20260829.svg',alt:'Mão com linhas enrugadas nos dedos e gotas de água',caption:'Dedos enrugados após imersão.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3639753/',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['satélites gps','gps','relativísticas','relatividade'],tag:'ARTE ESPECÍFICA · TECNOLOGIA',title:'GPS e relatividade',caption:'Visual específico de satélite, Terra e sincronização temporal.',images:[{url:'/generated/curiosity-gps-relativity-20260829.svg',alt:'Satélite GPS sobre a Terra com referência visual a relógio e sinal',caption:'GPS depende de correções relativísticas.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.nist.gov/blogs/taking-measure/putting-einstein-test-worlds-most-accurate-clocks',kind:'REFERENCE'}]},
{label:'Gravidez',matches:['7 semanas + 6 dias','energia poupada','hidratação'],tag:'MÍDIA REAL · GESTAÇÃO',title:'Gestação inicial',caption:'Imagem de referência de gestação inicial.',images:[{url:commons('Embryo at 6 weeks.JPG'),alt:'Ultrassom de referência de gestação inicial',caption:'Gestação inicial.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Embryo_at_6_weeks.JPG',kind:'PHOTO'}]},
{label:'Ser Pai',matches:['assumir uma tarefa inteira','carga mental'],tag:'MÍDIA REAL · APOIO',title:'Apoio na rotina',caption:'Imagem de apoio familiar e divisão de cuidado.',images:[{url:'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg',alt:'Família oferecendo apoio durante o período materno',caption:'Apoio prático e presença.',credit:'CDC Hear Her',sourceUrl:'https://www.cdc.gov/hearher/support-her/',kind:'PHOTO'}]},
{label:'Brasil',matches:['quedas e queimaduras','internações por acidentes','crianças no brasil'],tag:'ARTE ESPECÍFICA · SEGURANÇA INFANTIL',title:'Prevenção de acidentes infantis',caption:'Visual específico de segurança infantil, quedas e queimaduras.',images:[{url:'/generated/brasil-child-safety-20260829.svg',alt:'Ilustração de criança com símbolos de prevenção de quedas e queimaduras',caption:'Segurança e prevenção de acidentes infantis.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://agenciabrasil.ebc.com.br/saude/noticia/2026-08/quedas-e-queimaduras-sao-maior-causa-de-internacao-de-criancas',kind:'REFERENCE'}]},
{label:'Mundo',matches:['inflação de 66%','economia do irã','hormuz'],tag:'MÍDIA REAL · MAPA',title:'Estreito de Hormuz',caption:'Mapa geográfico da rota marítima no centro da crise.',images:[{url:commons('Strait of Hormuz-svg-en.svg'),alt:'Mapa do Estreito de Hormuz entre Irã e Omã',caption:'Estreito de Hormuz.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Strait_of_Hormuz-svg-en.svg',kind:'REFERENCE'}]},
{label:'Política',matches:['agenda presidencial','agenda informada','presidenciáveis'],tag:'MÍDIA ELEITORAL · NEUTRA',title:'Agenda eleitoral',caption:'Imagem neutra relacionada ao processo eleitoral brasileiro.',images:[{url:commons('Brazilian DRE voting machine for 2022 elections.jpg'),alt:'Urna eletrônica brasileira em fotografia institucional',caption:'Processo eleitoral brasileiro.',credit:'TSE / Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Brazilian_DRE_voting_machine_for_2022_elections.jpg',kind:'PHOTO'}]},
{label:'Tempo e Clima',matches:['meio-dia ensolarada','29°C','33°C'],tag:'MÍDIA REAL · SÃO PAULO',title:'São Paulo sob sol',caption:'Fotografia real da cidade em condição de tempo aberto.',images:[{url:commons('Bairro dos jardins em são paulo.jpg'),alt:'Vista urbana de São Paulo sob céu aberto',caption:'São Paulo.',credit:'Wikimedia Commons',sourceUrl:'https://www.cgesp.org/v3/noticias.jsp?data=2026-08-29',kind:'PHOTO'}]},
{label:'Corinthians',matches:['prepara clássico','hugo souza','matheus bidu'],tag:'MÍDIA REAL · CORINTHIANS',title:'Corinthians',caption:'Imagem relacionada ao Corinthians para o clássico contra o Santos.',images:[{url:'https://s2-cbn.glbimg.com/P_wXvQ-Ks8UHdDwWGCCglRTv52A=/1200x/smart/filters:cover()/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_d975fad146a14bbfad9e763717b09688/internal_photos/bs/2024/z/7/dl7DuXRIuwuFzGi0fAaQ/corinthian.png',alt:'Símbolo do Corinthians',caption:'Corinthians.',credit:'CBN/Globo',sourceUrl:'https://ge.globo.com/futebol/times/corinthians/',kind:'PHOTO'}]},
{label:'Viagens',matches:['museu do pontal','festival gratuito','50 anos'],tag:'MÍDIA REAL · RIO DE JANEIRO',title:'Museu do Pontal',caption:'Fachada real da nova sede do Museu do Pontal.',images:[{url:'https://odia.ig.com.br/_midias/jpg/2023/02/14/1200x750/1_museu_do_pontal_indicacao_premiacao-28083598.jpg',alt:'Fachada da nova sede do Museu do Pontal no Rio de Janeiro',caption:'Museu do Pontal.',credit:'Museu do Pontal / divulgação via O Dia',sourceUrl:'https://museudopontal.org.br/geral/festival-50-anos-no-museu-do-pontal-29-e-30-de-agosto/',kind:'PHOTO'}]},
{label:'Música',matches:['maçambique de osório','rainha ginga','tradição centenária'],tag:'ARTE ESPECÍFICA · CULTURA POPULAR',title:'Maçambique de Osório',caption:'Visual específico inspirado em tambor, canto e tradição comunitária.',images:[{url:'/generated/music-macambique-20260829.svg',alt:'Ilustração de musicista com tambor representando tradição do Maçambique',caption:'Música e tradição do Maçambique de Osório.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://agenciabrasil.ebc.com.br/cultura/noticia/2026-08/mestres-da-cultura-popular-evocam-tradicao-e-encanto-novos-publicos',kind:'REFERENCE'}]},
{label:'Games',matches:['gamescom entra na reta final','cosplay','gamescom'],tag:'MÍDIA REAL · GAMESCOM',title:'gamescom em Colônia',caption:'Fotografia real da entrada da gamescom.',images:[{url:commons('Main Entrance View at Gamescom 2025 in Cologne, Germany.jpg'),alt:'Entrada principal da gamescom no centro de exposições de Colônia',caption:'gamescom em Colônia.',credit:'RAWdz Ivan / Wikimedia Commons · CC BY 4.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Main_Entrance_View_at_Gamescom_2025_in_Cologne,_Germany.jpg',kind:'PHOTO'}]},
{label:'Tecnologia',matches:['deixará de fornecer modelos ao cursor','openai','cursor'],tag:'ARTE ESPECÍFICA · IA',title:'Mudança no fornecimento de modelos',caption:'Visual específico de uma conexão entre plataformas sendo encerrada.',images:[{url:'/generated/technology-model-supply-20260829.svg',alt:'Dois sistemas conectados por fluxo de modelos com sinal de interrupção',caption:'Mudança de fornecimento entre plataformas.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.reuters.com/business/media-telecom/openai-end-partnership-with-spacexs-cursor-2026-08-29/',kind:'REFERENCE'}]},
{label:'Finanças',matches:['novo desenrola brasil termina','desconto de até 90','renegociação'],tag:'ARTE ESPECÍFICA · RENEGOCIAÇÃO',title:'Renegociação de dívidas',caption:'Visual específico de renegociação financeira em reais.',images:[{url:'/generated/finance-debt-renegotiation-20260829.svg',alt:'Símbolo de dinheiro e seta circular representando renegociação de dívida',caption:'Renegociação financeira.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://agenciabrasil.ebc.com.br/economia/noticia/2026-08/programa-de-renegociacao-de-dividas-termina-nesta-segunda-feira',kind:'REFERENCE'}]},
{label:'Cyber Security',matches:['hasbro começa a notificar','dados pessoais','hasbro'],tag:'ARTE ESPECÍFICA · PRIVACIDADE',title:'Notificação de incidente de dados',caption:'Visual específico de documento protegido e alerta de privacidade.',images:[{url:'/generated/cyber-privacy-notice-20260829.svg',alt:'Escudo com documento e sinal de alerta de privacidade',caption:'Notificação de incidente envolvendo dados pessoais.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.securityweek.com/hasbro-data-breach-exposed-employee-personal-information/',kind:'REFERENCE'}]},
{label:'Carros até R$ 70 mil',matches:['histórico de manutenção','acessório bonito','até r$ 70 mil'],tag:'ARTE ESPECÍFICA · USADO',title:'Inspeção de carro usado',caption:'Visual específico para inspeção e histórico de manutenção.',images:[{url:'/generated/car-used-inspection-20260829.svg',alt:'Carro usado com símbolo de relógio e inspeção',caption:'Inspeção de automóvel usado.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.gov.br/senatran/',kind:'REFERENCE'}]},
{label:'Motos',matches:['corrente revela','corrente','coroa e pinhão'],tag:'ARTE ESPECÍFICA · MOTO',title:'Inspeção da transmissão',caption:'Visual específico de corrente e transmissão de motocicleta.',images:[{url:'/generated/motorcycle-chain-check-20260829.svg',alt:'Motocicleta com destaque visual para corrente e transmissão',caption:'Inspeção de corrente, coroa e pinhão.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria',kind:'REFERENCE'}]},
{label:'Mecânica',matches:['tampa do reservatório','arrefecimento','motor quente'],tag:'ARTE ESPECÍFICA · MECÂNICA',title:'Sistema de arrefecimento pressurizado',caption:'Visual específico de reservatório quente e risco de pressão.',images:[{url:'/generated/mechanic-coolant-safety-20260829.svg',alt:'Reservatório de arrefecimento com vapor e alerta de alta temperatura',caption:'Sistema de arrefecimento quente e pressurizado.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.nhtsa.gov/vehicle-safety',kind:'REFERENCE'}]}
];
