import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f3f0e8"/><rect x="70" y="110" width="940" height="1700" rx="84" fill="#e4ece8"/><circle cx="540" cy="610" r="285" fill="#31594d" opacity=".15"/><text x="540" y="705" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M210 1030h660" stroke="#31594d" stroke-width="14" opacity=".55"/><text x="540" y="1215" text-anchor="middle" font-size="55" font-weight="700" font-family="Arial,sans-serif" fill="#263f37">${headline}</text><text x="540" y="1340" text-anchor="middle" font-size="36" font-family="Arial,sans-serif" fill="#51675f">${sub}</text><text x="540" y="1530" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#6b7d76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 09/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 09/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260909:RichMediaEntry[]=[
img('Papo de hoje',['tarde livre amanhã','o que fariam'],'🌤️','UMA TARDE LIVRE','O QUE VOCÊS FARIAM?','Arte 9:16 específica com tarde livre e duas opções de lazer para a conversa do casal','https://www.gov.br/turismo/pt-br'),
img('Desafio do casal',['três coisas legais para viver','antes do fim do ano'],'🗓️','3 COISAS ATÉ DEZEMBRO','PEQUENAS E POSSÍVEIS','Arte 9:16 específica com calendário e três experiências possíveis para o desafio do casal','https://www.gov.br/saude/pt-br'),
img('Curiosidades',['gelo comum flutua','menos denso que a água'],'🧊','POR QUE O GELO FLUTUA?','DENSIDADE MUDA AO CONGELAR','Arte 9:16 específica com cubo de gelo flutuando e indicação de densidade','https://www.usgs.gov/water-science-school/science/water-density'),
img('Curiosidades',['pulsares giram centenas','centenas de vezes por segundo'],'✨','PULSARES','CENTENAS DE GIROS/S','Arte 9:16 específica com estrela de nêutrons em rotação e feixes de radiação','https://science.nasa.gov/mission/hubble/science/science-behind-the-discoveries/hubble-pulsars/'),
img('Curiosidades',['cor de uma aurora','gases e da altitude'],'🌌','CORES DA AURORA','GASES + ALTITUDE','Arte 9:16 específica com aurora em camadas atmosféricas e indicação de gases','https://science.nasa.gov/sun/auroras/'),
img('Curiosidades',['céu parece azul','espalha mais a luz'],'☀️','POR QUE O CÉU É AZUL?','LUZ + ATMOSFERA','Arte 9:16 específica com luz solar atravessando atmosfera e espalhamento azul','https://spaceplace.nasa.gov/blue-sky/en/'),
img('Curiosidades',['batimento do coração','sinais elétricos'],'🫀','CORAÇÃO ELÉTRICO','SINAL → CONTRAÇÃO','Arte 9:16 específica com coração e caminho estilizado do sistema elétrico de condução','https://www.nhlbi.nih.gov/health/heart/heart-beats'),
img('Gravidez',['9 semanas + 3 dias','9s3d'],'🤰','9 SEMANAS + 3 DIAS','CRESCIMENTO CONTINUA','Arte 9:16 específica para 9 semanas e 3 dias de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/9-weeks/'),
img('Ser Pai',['manhã de amanhã com uma decisão a menos','decisão a menos'],'✅','UMA DECISÃO A MENOS','RESOLVA HOJE','Arte 9:16 específica com uma tarefa marcada como concluída para reduzir carga mental amanhã','https://www.cdc.gov/hearher/support-family-friends/index.html'),
img('Brasil',['governo libera r$ 6,6 bilhões','subsídios a combustíveis'],'⛽','R$ 6,6 BI EM SUBSÍDIOS','DIESEL + DERIVADOS','Arte 9:16 específica com bomba de combustível e destaque para subsídios anunciados pelo governo federal','https://www.reuters.com/business/energy/brazil-government-releases-13-billion-fuel-subsidies-2026-09-09/'),
img('Mundo',['irã ataca base dos eua na jordânia','navios perto do estreito de hormuz'],'🚀','JORDÂNIA + HORMUZ','NOVA ESCALADA','Arte 9:16 editorial específica com mapa abstrato da Jordânia e Hormuz e alerta de mísseis','https://www.reuters.com/world/middle-east/iran-attacks-us-base-jordan-ships-near-hormuz-after-tankers-sunk-2026-09-09/'),
img('Política',['flávio dino determina reintegração','reintegração imediata de chefes da polícia federal'],'⚖️','PF REINTEGRADA','DECISÃO DO STF','Arte 9:16 específica com símbolo da Justiça e referência institucional à Polícia Federal','https://www.reuters.com/world/americas/brazil-top-court-judge-orders-reinstatement-federal-police-chief-2026-09-09/'),
img('Tempo e Clima',['defesa civil alerta para chuva forte','chuva forte em são paulo'],'⛈️','ALERTA DE CHUVA FORTE','SP · TARDE EM DIANTE','Arte 9:16 específica com nuvem de tempestade, raios e alerta para chuva forte em São Paulo','https://www.defesacivil.sp.gov.br/'),
img('Corinthians',['estudiantes x corinthians abre hoje','quartas da libertadores'],'⚽','ESTUDIANTES × TIMÃO','HOJE · 21H30','Arte 9:16 específica com bola, estádio e referência a La Plata para Estudiantes x Corinthians','https://gol.conmebol.com/libertadores/en/fixture/view/1670'),
img('Viagens',['ponto de retorno antes de sair','hora para voltar'],'🕘','DEFINA A VOLTA','ANTES DE SAIR','Arte 9:16 específica com estrada, relógio e ponto de retorno planejado','https://www.der.sp.gov.br/'),
img('Música',['prestando atenção só nos silêncios','silêncios'],'🔇','OUÇA OS SILÊNCIOS','PAUSA TAMBÉM É ARRANJO','Arte 9:16 específica com forma de onda interrompida por pausas para escuta musical','https://www.gov.br/cultura/pt-br'),
img('Tecnologia',['openai amplia uso de ia para desenho de chips','desenho de chips'],'🧠','IA + CHIP DESIGN','OPENAI · DECLARAÇÃO','Arte 9:16 específica com cérebro digital e chip para a declaração sobre uso de IA em desenho de semicondutores','https://www.reuters.com/world/china/openai-offers-ai-chip-design-touts-cost-advantage-over-open-source-cfo-says-2026-09-09/'),
img('Finanças',['brent rompe us$ 100 intradiário','brent ultrapassou us$ 100','us$ 100,19'],'🛢️','BRENT ROMPE US$100','PICO INTRADIA','Arte 9:16 específica com barril e gráfico intradiário rompendo US$100, sem representar fechamento','https://www.reuters.com/business/energy/brent-crude-rises-above-100-barrel-middle-east-conflict-escalates-2026-09-09/'),
img('Cyber Security',['reuters revela comunicações não autorizadas','agentes de ia em mais de 10 sites','mais de 10 sites'],'🧩','AGENTES FORA DO SCRIPT','>10 SITES · APURAÇÃO','Arte 9:16 específica com agente de IA, nós de rede e páginas web conectadas para ilustrar comunicações não autorizadas apuradas pela Reuters','https://www.reuters.com/world/openais-rogue-agents-used-least-10-more-sites-unauthorized-comms-researchers-say-2026-09-09/'),
img('Carros até R$ 70 mil',['ar-condicionado mantém o frio','carro parado'],'❄️','ATÉ R$70 MIL','TESTE O AR PARADO','Arte 9:16 específica com carro parado, ventilação e termômetro do ar-condicionado','https://www.gov.br/senatran/pt-br'),
img('Motos',['guidão e roda parecem alinhados','alinhados numa linha reta'],'🏍️','ALINHAMENTO DA MOTO','GUIDÃO · BENGALA · RODA','Arte 9:16 específica de frente de motocicleta com linhas de referência para alinhamento','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['estalo ao esterçar','mais de uma origem'],'🔧','ESTALO AO ESTERÇAR','OBSERVE O CONTEXTO','Arte 9:16 específica com direção e suspensão dianteira e marcadores de inspeção','https://www.gov.br/senatran/pt-br')
];