import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl=url):RichMediaEntry=>({label,matches,tag:'MÍDIA · 02/10',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl:sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20261002:RichMediaEntry[]=[
img('Papo de hoje',['ensinar ao bebê pelo exemplo'],'https://static.wixstatic.com/media/fd3013_955c0112d102477eba4f0fce7aa2cbe1~mv2.jpeg/v1/fill/w_980%2Ch_642%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/AdobeStock_313849799%20partner%20support.jpeg','Casal durante a gestação em momento de apoio e conversa','Sankofa Birth Experience','https://www.sankofabirth.co.uk/birth-coaching'),
img('Desafio do casal',['troquem uma pequena tarefa'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Couple_enjoys_coffee_together_at_home.jpg','Casal compartilhando um momento da rotina em casa','Wikimedia Commons'),
img('Curiosidades',['polvos têm três corações'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Octopus-vulgaris.jpg','Polvo comum em aquário','MartinThoma / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Octopus-vulgaris.jpg'),
img('Curiosidades',['sistema elétrico próprio'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Human_heart_model.jpg','Modelo anatômico de coração humano','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Human_heart_model.jpg'),
img('Curiosidades',['dia em vênus dura mais'],'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Venus_from_Mariner_10.jpg/960px-Venus_from_Mariner_10.jpg','Vênus fotografado pela sonda Mariner 10','NASA / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Venus_from_Mariner_10.jpg'),
img('Gravidez',['12 semanas + 5 dias'],'https://static.wixstatic.com/media/fd3013_955c0112d102477eba4f0fce7aa2cbe1~mv2.jpeg/v1/fill/w_980%2Ch_642%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/AdobeStock_313849799%20partner%20support.jpeg','Gestante acompanhada pelo parceiro em casa','Sankofa Birth Experience','https://www.sankofabirth.co.uk/birth-coaching'),
img('Ser Pai',['deixaria a manhã de amanhã mais fácil'],'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg','Parceiro oferecendo apoio durante a gestação','CDC Hear Her','https://www.cdc.gov/hearher/about/support-family-friends.html'),
img('Brasil',['indústria brasileira: ibge'],'https://www.parana.pr.gov.br/sites/default/arquivos_restritos/files/styles/share/public/imagem/2025-06/heineken_foto_rdziura-.jpg?itok=Od3rIqGW','Complexo industrial brasileiro visto do alto','Governo do Paraná · imagem de contexto industrial','https://www.parana.pr.gov.br/aen/Noticia/Com-369-de-participacao-Parana-lidera-volume-industrial-no-Sul-do-Brasil'),
img('Mundo',['mercados globais entram na sexta'],'https://m1.aboluowang.com/uploadfile/2023/0820/20230820111632624.jpg','Pregão asiático com terminais e painéis de mercado','Imagem de contexto de mercado asiático','https://www.aboluowang.com/2023/0820/1943342.html'),
img('Política',['eleições 2026: termina hoje'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg','Urnas eletrônicas brasileiras em imagem institucional do TSE','Abdias Pinheiro / SECOM / TSE · Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg'),
img('Tempo e Clima',['são paulo: sexta começa'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chuva_em_S%C3%A3o_Paulo.jpg','Chuva na cidade de São Paulo','Jonathan dos Santos / Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Chuva_em_S%C3%A3o_Paulo.jpg'),
img('Viagens',['regras de cancelamento e alteração'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Airplane_On_Boarding_Passes_%2844325226790%29.jpg','Cartões de embarque com avião ao fundo','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Airplane_On_Boarding_Passes_%2844325226790%29.jpg'),
img('Música',['compare a versão de estúdio'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Vinyl_Record.png','Disco de vinil usado como referência para audição musical','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Vinyl_Record.png'),
img('Finanças',['dólar chega a máxima de 17 meses'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Stock-exchange-trading-floor.jpg','Pregão de bolsa com operadores e terminais de mercado','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Stock-exchange-trading-floor.jpg'),
img('Carros',['confira chassi, versão e recalls'],'https://editorial.pxcrush.net/carsales/general/editorial/ppsr-recalls-1-uebn.jpg?height=682&width=1024','Pátio de veículos usados à venda','Carsales · imagem de contexto de usados','https://www.carsales.com.au/editorial/details/safety-recalls-added-to-governments-ppsr-security-registry-140080/'),
img('Motos',['teste manete, pedal e resposta dos freios'],'https://xprousa.com/cdn/shop/files/220-905003.jpg?v=1712557817','Conjunto de freio dianteiro de motocicleta com manete, mangueira e pinça','XProUSA · referência visual do sistema de freio','https://xprousa.com/products/220-905003'),
img('Mecânica',['nível do líquido de arrefecimento'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Engine_coolant.jpg','Líquido de arrefecimento sendo adicionado ao sistema de um veículo','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Engine_coolant.jpg')
];
