import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f2f0e9"/><rect x="76" y="116" width="928" height="1688" rx="84" fill="#dfe8e3"/><circle cx="540" cy="620" r="280" fill="#31584c" opacity=".14"/><text x="540" y="735" text-anchor="middle" font-size="250" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M220 1060h640" stroke="#31584c" stroke-width="18" opacity=".65"/><text x="540" y="1270" text-anchor="middle" font-size="72" font-weight="700" font-family="Arial,sans-serif" fill="#243f37">${headline}</text><text x="540" y="1370" text-anchor="middle" font-size="42" font-family="Arial,sans-serif" fill="#4c665d">${sub}</text><text x="540" y="1550" text-anchor="middle" font-size="34" font-family="Arial,sans-serif" fill="#657a72">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 02/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 02/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260902:RichMediaEntry[]=[
img('Papo de hoje',['música mudou de significado','depois que vocês ficaram juntos'],'🎼','MÚSICA + MEMÓRIA','UMA FAIXA, UMA HISTÓRIA','Arte editorial com nota musical e memória compartilhada do casal','https://www.gov.br/cultura/pt-br'),
img('Desafio do casal',['20 minutos sem tela','depois do jantar'],'📵','20 MIN SEM TELA','PRESENÇA > NOTIFICAÇÃO','Arte editorial com celular em modo sem notificações e mesa de jantar','https://www.gov.br/saude/pt-br'),
img('Curiosidades',['som viaja','água do que no ar'],'🌊','SOM NA ÁGUA','MAIS RÁPIDO QUE NO AR','Arte educativa com ondas sonoras atravessando água','https://oceanservice.noaa.gov/facts/sound.html'),
img('Curiosidades',['arrepio','piloereção'],'🪶','ARREPIO','PILOEREÇÃO','Arte educativa mostrando pelos eretos e músculo piloeretor','https://www.ncbi.nlm.nih.gov/books/NBK470464/'),
img('Curiosidades',['qr code','correção de erros'],'▦','QR CODE','CORREÇÃO DE ERROS','Arte educativa com QR estilizado e blocos restaurados','https://www.qrcode.com/en/about/error_correction.html'),
img('Gravidez',['8 semanas + 3 dias','8s3d'],'🤰','8S3D','DESENVOLVIMENTO','Ilustração educativa abstrata referente a 8 semanas e 3 dias de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/8-weeks/'),
img('Ser Pai',['três notas objetivas','sintomas e dúvidas'],'📝','3 NOTAS','OBSERVAR · ANOTAR · PERGUNTAR','Arte editorial com três notas organizadas para o pré-natal','https://www.cdc.gov/hearher/'),
img('Mundo',['eua concluem nova onda','ataques ao irã'],'🌍','EUA × IRÃ','NOVA ESCALADA','Arte editorial neutra com mapa e setas representando troca de ataques entre EUA e Irã','https://www.reuters.com/world/middle-east/us-military-says-it-completed-latest-wave-strikes-iran-2026-09-02/'),
img('Política',['taxa das blusinhas','cadernos de votação'],'🏛️','MP 10H · TSE','AGENDA + CALENDÁRIO','Arte editorial com plenário, relógio e caderno eleitoral','https://legis.senado.leg.br/atividade/comissoes/comissao/2856/reuniao/14963'),
img('Tempo e Clima',['menos chuva','queda de temperatura'],'🌥️','SP · 02/09','MENOS NUVENS · MAIS FRIO','Arte meteorológica com nuvens se afastando e termômetro em queda sobre São Paulo','https://portal.inmet.gov.br/noticias/previs%C3%A3o-para-quarta-feira-02-e-quinta-feira-03'),
img('Corinthians',['venda geral','15h'],'⚽','VENDA GERAL 15H','CORINTHIANS × CHAPE','Arte editorial de ingresso e bola representando abertura da venda geral para Corinthians x Chapecoense','https://www.neoquimicaarena.com.br/noticias/ingressos-corinthians-x-chapecoense-06-09-brasileirao-2026-arena'),
img('Viagens',['raio de 90 minutos','bate-volta'],'🧭','90 MIN','BATE-VOLTA SIMPLES','Arte editorial com bússola e raio de deslocamento para bate-volta','https://www.gov.br/turismo/pt-br'),
img('Música',['versão de estúdio','apresentação ao vivo'],'🎙️','ESTÚDIO × AO VIVO','COMPARE O ARRANJO','Arte editorial com microfone e formas de onda comparando estúdio e show','https://www.gov.br/cultura/pt-br'),
img('Tecnologia',['us$ 20 bilhões','taiwan'],'▦','US$ 20 BI','TAIWAN → EUA','Arte editorial com chip e seta de investimento entre Taiwan e Estados Unidos','https://www.reuters.com/world/china/taiwan-says-its-companies-plan-invest-another-20-billion-us-2026-09-02/'),
img('Finanças',['petróleo e juros longos','dólar mantém força'],'📈','BRENT · YIELDS · USD','RISCO GLOBAL','Arte editorial com barril, curva de juros e dólar representando mercados globais','https://www.reuters.com/world/china/dollar-holds-firm-middle-east-hostilities-lift-oil-2026-09-02/'),
img('Carros até R$ 70 mil',['desgaste do volante','quilometragem'],'🚗','ATÉ R$70 MIL','DESGASTE × KM','Arte editorial de interior de carro usado com volante, pedal e banco destacados','https://www.gov.br/senatran/pt-br'),
img('Motos',['manete, pedal','queda antiga'],'🏍️','SINAIS DE QUEDA','COMPARE OS LADOS','Arte editorial de motocicleta com pontos de contato de queda destacados','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['tec-tec','rotação, carga'],'🔧','TEC-TEC','OUÇA O CONTEXTO','Arte editorial com motor e ondas sonoras ligadas a rotação, carga e temperatura','https://www.nhtsa.gov/vehicle-safety')
];
