import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f4f0e7"/><rect x="70" y="110" width="940" height="1700" rx="84" fill="#e8eeea"/><circle cx="540" cy="610" r="285" fill="#31594d" opacity=".15"/><text x="540" y="705" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M210 1030h660" stroke="#31594d" stroke-width="14" opacity=".55"/><text x="540" y="1215" text-anchor="middle" font-size="58" font-weight="700" font-family="Arial,sans-serif" fill="#263f37">${headline}</text><text x="540" y="1340" text-anchor="middle" font-size="37" font-family="Arial,sans-serif" fill="#51675f">${sub}</text><text x="540" y="1530" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#6b7d76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 06/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 06/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260906:RichMediaEntry[]=[
img('Papo de hoje',['coisa boba sempre consegue fazer você rir','coisa boba sempre consegue fazer'],'😂','O QUE SEMPRE FAZ RIR?','CONTE A HISTÓRIA INTEIRA','Arte 9:16 específica com expressão de riso para conversa sobre pequenas coisas engraçadas','https://www.gov.br/saude/pt-br'),
img('Desafio do casal',['vídeo de até 10 minutos','indica um vídeo'],'📱','UM VÍDEO PARA O OUTRO','ATÉ 10 MINUTOS','Arte 9:16 específica com celular e play para troca de vídeos curtos entre o casal','https://www.gov.br/saude/pt-br'),
img('Curiosidades',['rã pode congelar parte do corpo','rã-da-madeira'],'🐸','RÃ + GELO','CONGELA E SOBREVIVE','Arte 9:16 específica com rã e cristais de gelo para adaptação ao congelamento','https://www.nps.gov/articles/000/wood-frog.htm'),
img('Curiosidades',['som pode viajar cerca de quatro vezes','som viaja muito mais rápido'],'🌊','SOM NO OCEANO','CERCA DE 4× MAIS RÁPIDO','Arte 9:16 específica com ondas acústicas atravessando água','https://oceanservice.noaa.gov/facts/sound.html'),
img('Curiosidades',['mercúrio leva 176 dias','dia solar em mercúrio'],'☿️','MERCÚRIO · 176 DIAS','UM DIA SOLAR','Arte 9:16 específica com Mercúrio e trajetória solar longa','https://science.nasa.gov/mercury/facts/'),
img('Curiosidades',['água comum boa condutora','sais dissolvidos'],'⚗️','ÁGUA + ÍONS','CONDUTIVIDADE','Arte 9:16 específica com moléculas e íons para explicar condução elétrica na água','https://www.usgs.gov/special-topics/water-science-school/science/conductivity-electrical-conductance-and-water'),
img('Curiosidades',['poeira africana ajuda','poeira do saara'],'🌍','SAARA → AMAZÔNIA','FÓSFORO PELO ATLÂNTICO','Arte 9:16 específica com fluxo de poeira entre África e Amazônia','https://earthobservatory.nasa.gov/images/85535/saharan-dust-feeds-amazon-s-rainforests'),
img('Gravidez',['9 semanas:','9 semanas completas'],'🤰','9 SEMANAS','NOVA SEMANA GESTACIONAL','Arte 9:16 abstrata específica para 9 semanas de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/9-weeks/'),
img('Ser Pai',['prepare um ponto de apoio','dias de enjoo'],'🧃','PONTO DE APOIO','PARA O ENJOO','Arte 9:16 específica com água e lanche para apoio prático durante náusea','https://www.cdc.gov/hearher/'),
img('Mundo',['israel diz atacar o sul do líbano','hezbollah lançar dois drones'],'🛩️','SUL DO LÍBANO','DRONES E RETALIAÇÃO','Arte 9:16 editorial específica com drones e mapa abstrato para a escalada Israel-Hezbollah','https://www.reuters.com/world/middle-east/israeli-military-says-it-strikes-southern-lebanon-after-hezbollah-launched-2026-09-06/'),
img('Tempo e Clima',['alertas do inmet','tempestade e queda de temperatura'],'🌧️','SÃO PAULO · ALERTAS','TEMPESTADE + FRIO','Arte 9:16 específica com chuva, vento e termômetro para alertas meteorológicos de 06/09','https://alertas2.inmet.gov.br/'),
img('Zona Leste em Foco',['abertura oficial dos festejos','466 anos neste domingo'],'🎉','SÃO MIGUEL · 466 ANOS','ABERTURA HOJE','Arte 9:16 específica com celebração comunitária para a agenda de São Miguel Paulista','https://semanadobrincar.prefeitura.sp.gov.br/web/sao_miguel_paulista/w/reuni%C3%A3o-de-festejos-do-anivers%C3%A1rio-de-s%C3%A3o-miguel-paulista-%C3%A9-realizada-na-subprefeitura'),
img('Corinthians',['recebe a chapecoense','19h30'],'⚽','CORINTHIANS × CHAPE','19H30 · NEO QUÍMICA ARENA','Arte 9:16 específica de futebol para a agenda Corinthians x Chapecoense','https://www.cbf.com.br/futebol-brasileiro/jogos/campeonato-brasileiro/serie-a/2026/corinthians-x-chapecoense/832143'),
img('Viagens',['tempo de porta a porta','destino pelo tempo'],'🧭','PORTA A PORTA','TEMPO REAL DE VIAGEM','Arte 9:16 específica com bússola e relógio para comparar deslocamentos reais','https://www.gov.br/turismo/pt-br'),
img('Música',['primeiro instrumento','primeira camada'],'🎶','OUÇA O COMEÇO','QUAL SOM ENTRA PRIMEIRO?','Arte 9:16 específica com instrumentos e ondas sonoras para escuta ativa','https://www.gov.br/cultura/pt-br'),
img('Carros até R$ 70 mil',['custo do seguro','até r$70 mil'],'🚗','ATÉ R$70 MIL','COTE O SEGURO ANTES','Arte 9:16 específica com carro, escudo e orçamento para custo de seguro','https://www.gov.br/susep/pt-br'),
img('Motos',['manete e pedal','história de uma queda'],'🏍️','MARCAS DE QUEDA','MANETE · PEDAL · TAMPA','Arte 9:16 específica com motocicleta e pontos de inspeção após possíveis quedas','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['bateria fraca nem sempre','sistema de carga'],'🔋','BATERIA OU CARGA?','MEÇA ANTES DE TROCAR','Arte 9:16 específica com bateria, multímetro e alternador para diagnóstico elétrico','https://www.gov.br/senatran/pt-br')
];
