import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'MÍDIA REAL · 17/09',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260917:RichMediaEntry[]=[
img('Papo de hoje',['o que aconteceu hoje e te deixou um pouco melhor'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Couple_enjoys_coffee_together_at_home.jpg','Casal conversando em casa','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Desafio do casal',['escolham juntos um filme ou episódio'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Watching_TV.jpg','Pessoas assistindo televisão juntas','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Curiosidades',['abelhas enxergam padrões ultravioleta'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bee_on_flower.jpg','Abelha visitando uma flor','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Curiosidades',['fígado tem uma capacidade incomum de regeneração'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Human_liver.jpg','Fígado humano em referência anatômica','Imagem médica · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Curiosidades',['quando você olha para o sol'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg','Sol observado por instrumento científico','Imagem real · NASA/Wikimedia Commons','https://commons.wikimedia.org/'),
img('Curiosidades',['maior deserto da terra é gelado'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Antarctica_6400px_from_Blue_Marble.jpg','Antártida vista do espaço','Imagem real · NASA/Wikimedia Commons','https://commons.wikimedia.org/'),
img('Curiosidades',['sem correções relativísticas, o gps'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/GPS_Satellite_NASA_art-iif.jpg','Satélite GPS em órbita','Imagem técnica · NASA/Wikimedia Commons','https://commons.wikimedia.org/'),
img('Gravidez',['10 semanas + 4 dias','10s4d'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Embryo_at_10_weeks.JPG','Ultrassom real de embrião humano em torno de 10 semanas','Imagem médica real · Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Embryo_at_10_weeks.JPG'),
img('Ser Pai',['prepare a manhã antes de dormir'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Glass_of_water.jpg','Copo de água preparado sobre uma mesa','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Brasil',['petrobras anuncia alta de r$ 1 no diesel'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Petrobras_headquarters.jpg','Sede da Petrobras','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Corinthians',['cai na libertadores'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Arena_Corinthians_fev_2014.jpg','Neo Química Arena, palco da partida','Foto real · Wikimedia Commons · CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Arena_Corinthians_fev_2014.jpg'),
img('Viagens',['plano b de transporte'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sao_Paulo_Metro_train.jpg','Transporte público em São Paulo','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Música',['faixa só pelo baixo'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Electric_bass_guitar.jpg','Baixo elétrico','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Games',['fortnite recebe atualização v42.20'],'https://cdn2.unrealengine.com/fortnite-og-social-1920x1080-a5adda66fab9.jpg','Arte oficial relacionada a Fortnite','Mídia oficial · Epic Games','https://www.fortnite.com/'),
img('Carros até R$ 70 mil',['teste ar-condicionado'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Car_air_conditioning_controls.jpg','Controles de ar-condicionado automotivo','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Motos',['manetes, pedais e sinais de queda'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Motorcycle_handlebar.jpg','Guidão e manete de motocicleta','Foto real · Wikimedia Commons','https://commons.wikimedia.org/'),
img('Mecânica',['carro puxando para um lado'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Wheel_alignment.jpg','Alinhamento de roda automotiva','Foto real · Wikimedia Commons','https://commons.wikimedia.org/')
];