import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f5f1e8"/><rect x="70" y="110" width="940" height="1700" rx="84" fill="#e6ece8"/><circle cx="540" cy="600" r="285" fill="#355d50" opacity=".14"/><text x="540" y="700" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M210 1030h660" stroke="#355d50" stroke-width="14" opacity=".55"/><text x="540" y="1220" text-anchor="middle" font-size="60" font-weight="700" font-family="Arial,sans-serif" fill="#263f37">${headline}</text><text x="540" y="1340" text-anchor="middle" font-size="38" font-family="Arial,sans-serif" fill="#51675f">${sub}</text><text x="540" y="1530" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#6b7d76">${label}</text></svg>`)}`;
const img=(matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label:'Curiosidades',matches,tag:'ARTE ESPECÍFICA · 04/09',title:headline,caption:sub,images:[{url:art('Curiosidades',glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 04/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia202609042358:RichMediaEntry[]=[
img(['wombats conseguem produzir','cocô em formato de cubo'],'🐾','WOMBAT · CUBOS','O INTESTINO MOLDA','Arte 9:16 específica com wombat e referência visual a formas cúbicas produzidas no intestino','https://pubs.rsc.org/en/content/articlehtml/2021/sm/d1sm00142f'),
img(['bilhões de animais sobem','maior migração da terra'],'🌊','MAIOR MIGRAÇÃO','ACONTECE TODA NOITE NO MAR','Arte 9:16 específica com oceano e organismos migrando verticalmente na coluna d’água','https://oceanexplorer.noaa.gov/ocean-fact/vertical-migration/'),
img(['banheira impossível','saturno flutuaria'],'🪐','SATURNO FLUTUARIA','DENSIDADE MENOR QUE A ÁGUA','Arte 9:16 específica com Saturno e comparação conceitual de densidade com água','https://science.nasa.gov/saturn/facts/'),
img(['ar ao redor de um raio','50.000 °f'],'⚡','RAIO · 50.000 °F','O AR AQUECE EM UM INSTANTE','Arte 9:16 específica com descarga elétrica e indicação de aquecimento extremo do ar','https://www.weather.gov/safety/lightning-temperature'),
img(['cadeia de montanhas mais longa','65 mil km'],'🌍','65.000 KM','A MAIOR CORDILHEIRA É SUBMERSA','Arte 9:16 específica com globo, oceano e dorsal meso-oceânica contornando o planeta','https://oceanservice.noaa.gov/facts/midoceanridge.html'),
img(['romance de hoje','agradeça uma coisa'],'❤️','HOJE · REPARE NELA','AGRADEÇA UM DETALHE REAL','Arte 9:16 romântica limpa com coração e destaque para atenção aos pequenos gestos no relacionamento','https://pubmed.ncbi.nlm.nih.gov/37745832/')
];
