import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl=url):RichMediaEntry=>({label,matches,tag:'MÍDIA · 02/10',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20261002:RichMediaEntry[]=[
img('Papo de hoje',['ensinar ao bebê pelo exemplo'],'https://static.wixstatic.com/media/fd3013_955c0112d102477eba4f0fce7aa2cbe1~mv2.jpeg/v1/fill/w_980%2Ch_642%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/AdobeStock_313849799%20partner%20support.jpeg','Casal durante a gestação em momento de apoio e conversa','Sankofa Birth Experience','https://www.sankofabirth.co.uk/birth-coaching'),
img('Desafio do casal',['troquem uma pequena tarefa'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Couple_enjoys_coffee_together_at_home.jpg','Casal compartilhando um momento da rotina em casa','Wikimedia Commons'),
img('Curiosidades',['polvos têm três corações'],'https://cdn.coloradoparent.com/2018/04/IMG_0704-1.jpg','Polvo em aquário, com braços e ventosas visíveis','Colorado Parent / Butterfly Pavilion','https://coloradoparent.com/try-your-tentacle-at-naming-the-butterfly-pavilions-newest-octopus/'),
img('Curiosidades',['sistema elétrico próprio'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Human_heart_model.jpg','Modelo anatômico de coração humano','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Human_heart_model.jpg'),
img('Curiosidades',['dia em vênus dura mais'],'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Venus_from_Mariner_10.jpg/960px-Venus_from_Mariner_10.jpg','Vênus fotografado pela sonda Mariner 10','NASA / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Venus_from_Mariner_10.jpg'),
img('Gravidez',['12 semanas + 5 dias'],'https://static.wixstatic.com/media/fd3013_955c0112d102477eba4f0fce7aa2cbe1~mv2.jpeg/v1/fill/w_980%2Ch_642%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/AdobeStock_313849799%20partner%20support.jpeg','Gestante acompanhada pelo parceiro em casa','Sankofa Birth Experience','https://www.sankofabirth.co.uk/birth-coaching'),
img('Ser Pai',['deixaria a manhã de amanhã mais fácil'],'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg','Parceiro oferecendo apoio durante a gestação','CDC Hear Her','https://www.cdc.gov/hearher/about/support-family-friends.html'),
img('Brasil',['indústria brasileira: ibge'],'https://www.parana.pr.gov.br/sites/default/arquivos_restritos/files/styles/share/public/imagem/2025-06/heineken_foto_rdziura-.jpg?itok=Od3rIqGW','Complexo industrial brasileiro visto do alto','Governo do Paraná · imagem de contexto industrial','https://www.parana.pr.gov.br/aen/Noticia/Com-369-de-participacao-Parana-lidera-volume-industrial-no-Sul-do-Brasil'),
img('Mundo',['mercados globais entram na sexta'],'https://m1.aboluowang.com/uploadfile/2023/0820/20230820111632624.jpg','Pregão asiático com terminais e painéis de mercado','Imagem de contexto de mercado asiático','https://www.aboluowang.com/2023/0820/1943342.html'),
img('Política',['eleições 2026: termina hoje'],'https://www.tse.jus.br/imagens/fotos/foto-alejandro-zambrana-secom-tse-modelos-de-urna-eletronica-ue-2022/%40%40images/image-1140-213cb849c8885ca599423fc4dd5549e6.jpeg','Urna eletrônica UE2022 usada nas Eleições Gerais de 2026','Alejandro Zambrana / Secom / TSE','https://www.tse.jus.br/comunicacao/noticias/2026/Agosto/veja-os-modelos-de-urna-que-serao-utilizados-nas-eleicoes-gerais-2026'),
img('Tempo e Clima',['são paulo: sexta começa'],'https://jpimg.com.br/uploads/2025/02/tn220250206057-700x450.jpg','Chuva em via urbana na cidade de São Paulo','Jovem Pan · imagem de contexto meteorológico','https://jovempan.com.br/noticias/brasil/chuva-faz-sp-entrar-em-estado-de-atencao-para-alagamentos-defesa-civil-emite-alerta-severo.html'),
img('Viagens',['regras de cancelamento e alteração'],'https://fotografias.antena3.com/clipping/cmsimages01/2022/06/08/55395F1F-07B8-4DEC-8D3B-332504A239D1/tarjeta-embarque_98.jpg?crop=1920%2C1080%2Cx0%2Cy78&format=webply&height=1069&optimize=low&width=1900','Passageiro com passaporte e cartão de embarque em aeroporto','Antena 3 · imagem de contexto de viagem','https://www.antena3.com/noticias/sociedad/que-hacer-pierdo-vuelo-reclamaciones-alternativas-colapso-aeropuertos_2022060862a069acd7b96e000100de44.html'),
img('Música',['compare a versão de estúdio'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Vinyl_Record.png','Disco de vinil usado como referência para audição musical','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Vinyl_Record.png'),
img('Finanças',['dólar chega a máxima de 17 meses'],'https://bnr-external-prod.imgix.net/613820-613830.jpeg','Operador acompanha cotações em múltiplos terminais de mercado','BNR · imagem de contexto financeiro','https://www.bnr.nl/nieuws/economie/10575456/grote-beleggers-trekken-zich-terug-uit-amerikaanse-markten'),
img('Carros',['confira chassi, versão e recalls'],'https://editorial.pxcrush.net/carsales/general/editorial/ppsr-recalls-1-uebn.jpg?height=682&width=1024','Pátio de veículos usados à venda','Carsales · imagem de contexto de usados','https://www.carsales.com.au/editorial/details/safety-recalls-added-to-governments-ppsr-security-registry-140080/'),
img('Motos',['teste manete, pedal e resposta dos freios'],'https://xprousa.com/cdn/shop/files/220-905003.jpg?v=1712557817','Conjunto de freio dianteiro de motocicleta com manete, mangueira e pinça','XProUSA · referência visual do sistema de freio','https://xprousa.com/products/220-905003'),
img('Mecânica',['nível do líquido de arrefecimento'],'https://cld.partsimg.com/image/upload/c_pad%2Cf_auto%2Cq_auto%2Cdpr_auto/carparts/blog/tier-zero/car-fluids-to-check-infographic/engine-coolant','Reservatório do líquido de arrefecimento no cofre do motor','CarParts.com · referência visual do reservatório','https://www.carparts.com/blog/car-fluids-to-check-infographic/')
];
