import type { RichMediaEntry } from './rich-media';

const commons=(name:string)=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(name).replace(/%2F/g,'/')}`;

export const dailyRichMedia20260827_0835: RichMediaEntry[] = [
  { label:'Brasil', matches:['escala 6x1: relator prepara parecer','pec 221/2019'], tag:'MÍDIA REAL · SENADO', title:'Plenário do Senado Federal', caption:'Fotografia real do Senado para a tramitação da PEC 221/2019.', images:[{url:commons('PlenarioSenadoFederal.jpg'),alt:'Plenário do Senado Federal em Brasília',caption:'Plenário do Senado Federal.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:PlenarioSenadoFederal.jpg',kind:'PHOTO'}] },
  { label:'Política', matches:['eleições 2026: lula terá 5m31s','tempo de tv'], tag:'MÍDIA ELEITORAL · TSE', title:'Urna eletrônica brasileira', caption:'Imagem neutra da Justiça Eleitoral para comparar os candidatos.', images:[{url:commons('Brazilian DRE voting machine for 2022 elections.jpg'),alt:'Urna eletrônica brasileira em fotografia institucional',caption:'Urna eletrônica brasileira.',credit:'Tribunal Superior Eleitoral / Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Brazilian_DRE_voting_machine_for_2022_elections.jpg',kind:'PHOTO'}] },
  { label:'Tempo e Clima', matches:['são paulo amanhece com 16°c','maxima prevista chega a 28'], tag:'MÍDIA REAL · SÃO PAULO', title:'São Paulo', caption:'Fotografia urbana relacionada à previsão da capital.', images:[{url:commons('Bairro dos jardins em são paulo.jpg'),alt:'Vista urbana de São Paulo sob céu parcialmente nublado',caption:'São Paulo.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Bairro_dos_jardins_em_s%C3%A3o_paulo.jpg',kind:'PHOTO'}] },
  { label:'Corinthians', matches:['andré pode ser vendido ao nottingham forest','andre pode ser vendido'], tag:'MÍDIA REAL · CORINTHIANS', title:'André em ação pelo Corinthians', caption:'Imagem do jogador André em ação pelo Corinthians.', images:[{url:'https://s2-cbn.glbimg.com/P_wXvQ-Ks8UHdDwWGCCglRTv52A=/1200x/smart/filters:cover()/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_d975fad146a14bbfad9e763717b09688/internal_photos/bs/2024/z/7/dl7DuXRIuwuFzGi0fAaQ/corinthian.png',alt:'Imagem relacionada ao Corinthians',caption:'Corinthians.',credit:'Globo/CBN',sourceUrl:'https://ge.globo.com/futebol/times/corinthians/',kind:'REFERENCE'}] },
  { label:'Security Briefing', matches:['cisa publica revisão de vulnerabilidades','cisa publica revisao'], tag:'MÍDIA OFICIAL · CISA', title:'CISA', caption:'Identidade visual da agência que publicou a revisão.', images:[{url:commons('Cybersecurity and Infrastructure Security Agency logo.svg'),alt:'Logo da CISA',caption:'Cybersecurity and Infrastructure Security Agency.',credit:'CISA / Wikimedia Commons',sourceUrl:'https://www.cisa.gov/',kind:'REFERENCE'}] },
  { label:'Cyber Security', matches:['cisa confirma exploração ativa','citrix netscaler','cve-2026-8452'], tag:'IMAGEM DA MATÉRIA · 27/08', title:'Citrix NetScaler sob exploração ativa', caption:'Imagem da matéria publicada em 27/08 sobre a CVE-2026-8452.', images:[{url:'https://www.bleepstatic.com/content/hl-images/2026/08/27/Citrix.jpg',alt:'Imagem Citrix usada na matéria sobre exploração ativa do NetScaler',caption:'Citrix NetScaler.',credit:'BleepingComputer',sourceUrl:'https://www.bleepingcomputer.com/news/security/cisa-hackers-now-exploiting-citrix-netscaler-rce-flaw-in-attacks/',kind:'REFERENCE'}] },
  { label:'AppSec / SSDLC', matches:['avada wordpress','cve-2026-18431','rce zero-click'], tag:'IMAGEM DA MATÉRIA · WORDPRESS', title:'WordPress / Avada', caption:'Imagem relacionada à matéria sobre a cadeia RCE no Avada.', images:[{url:'https://www.bleepstatic.com/content/hl-images/2026/05/14/wordpress.jpg',alt:'Imagem WordPress usada em matéria de segurança',caption:'WordPress.',credit:'BleepingComputer',sourceUrl:'https://www.bleepingcomputer.com/news/security/critical-avada-wordpress-theme-flaw-enables-zero-click-rce/',kind:'REFERENCE'}] }
];
