import { dailyContent, edition, todayDrops } from './daily-content';
import { politicsTracker } from './politics-2026';
import { localSecurityTodayStatus, localSecuritySignals } from './local-security-content';
import { securityBriefingStories } from './security-briefing-content';
import { appSecFeedPosts } from './appsec-feed-content';

const set=(slug:string,data:any)=>Object.assign(dailyContent[slug],data);
Object.assign(edition,{date:'20/08/2026',dateLabel:'20 AGO 2026',title:'Daily Intelligence · 20 de agosto · 19h'});
Object.assign(politicsTracker,{updatedAt:'20/08/2026 · 19h05',notice:'Edição revalidada às 19h05. O prazo de voto em trânsito termina hoje; fatos de campanha, protestos, propostas e situação jurídica de candidaturas permanecem separados.'});
Object.assign(localSecurityTodayStatus,{date:'20 AGO 2026',status:'VARREDURA ATUALIZADA · 19H05',note:'A revisão encontrou fatos novos/úteis na Zona Leste: agenda eleitoral com protestos em São Miguel e Vila Formosa; decisão de Libertadores em Itaquera; vacinação em Corinthians-Itaquera nesta sexta; homicídio em Aricanduva ocorrido no dia 19 e publicado hoje; e desmanche clandestino localizado pela Polícia Civil na Zona Leste no dia 19. Cada item preserva data, fonte e status próprio, sem transformar ocorrência isolada em tendência.',nextCheck:'próxima checagem: 05h, ou antes se houver mudança relevante confirmada'});

if(!localSecuritySignals.some((item:any)=>item.id==='aricanduva-homicidio-20ago')) localSecuritySignals.unshift({
  id:'aricanduva-homicidio-20ago',type:'ALERTA',area:'Aricanduva · Zona Leste',date:'FATO 19 AGO · PUBLICADO 20 AGO 2026',freshness:'RECENTE',ageLabel:'HOJE',
  title:'Briga entre vizinhos terminou em homicídio em Aricanduva; suspeito fugiu',
  summary:'Uma discussão entre vizinhos ocorrida na tarde de 19 de agosto terminou com a morte de um homem de 57 anos em Aricanduva. Segundo a cobertura publicada hoje, a Polícia Civil registrou o caso e o suspeito não havia sido localizado no momento da publicação.',
  whyItMatters:'É um fato recente confirmado e deve ser acompanhado como ocorrência/investigação específica. O site não extrapola o episódio para uma avaliação geral de risco do bairro.',
  source:{label:'UOL Cotidiano · 20/08/2026',url:'https://noticias.uol.com.br/cotidiano/ultimas-noticias/2026/08/20/briga-entre-vizinhos-deixa-um-morto-na-zona-leste-de-sao-paulo.ghtm'}
} as any);
if(!localSecuritySignals.some((item:any)=>item.id==='desmanche-zl-19ago')) localSecuritySignals.unshift({
  id:'desmanche-zl-19ago',type:'ALERTA',area:'Zona Leste · localização operacional não destacada',date:'19 AGO 2026',freshness:'RECENTE',ageLabel:'1D',
  title:'Polícia Civil localizou desmanche clandestino e prendeu quatro suspeitos em flagrante',
  summary:'A 1ª Divecar localizou uma estrutura usada para desmontar veículos roubados e furtados. Segundo a Band, quatro suspeitos foram presos e havia recursos destinados a dificultar rastreamento dos veículos.',
  whyItMatters:'O caso ajuda a entender a cadeia de receptação/desmanche por trás de parte dos roubos e furtos de veículos. Detalhes operacionais que possam facilitar evasão não são reproduzidos.',
  source:{label:'Band · Brasil Urgente · 19/08/2026',url:'https://www.band.com.br/noticias/brasil-urgente/ultimas/policia-descobre-desmanche-clandestino-na-zona-leste-de-sp-202608191653'}
} as any);

const drops=[
{slug:'brasil',label:'Brasil',emoji:'🇧🇷',title:'Fiscal: governo fala em preservar arcabouço e reduzir despesas obrigatórias em 2027',detail:'A fala é diretriz e projeção, não economia já realizada; execução depende de medidas, receitas e Congresso.'},
{slug:'seguranca-zl',label:'Zona Leste em Foco',emoji:'🚨',title:'Zona Leste hoje: campanha em São Miguel/Vila Formosa, Arena em Itaquera e novas ocorrências confirmadas',detail:'A edição de 19h separa notícias gerais, segurança, serviços e casos com fonte/data explícitas.'},
{slug:'politica',label:'Política',emoji:'🏛️',title:'Voto em trânsito: prazo termina hoje; campanha segue em outra trilha',detail:'20 de agosto é o último dia para pedir, alterar ou cancelar a habilitação, conforme o TSE.'},
{slug:'mundo',label:'Mundo',emoji:'🌍',title:'Petróleo e juros longos voltam a pressionar mercados globais',detail:'Brent subiu e Treasuries voltaram a vender, juntando inflação de energia, dívida e custo de capital.'},
{slug:'planeta',label:'Planeta',emoji:'🌎',title:'Correntes de retorno: entender o fluxo é mais útil do que “lutar contra o mar”',detail:'A água escoa da arrebentação para fora em canais; reconhecer o padrão e conservar energia salva decisões.'},
{slug:'animais',label:'Mundo Animal',emoji:'🐙',title:'Polvos combinam tato e detecção química nos braços',detail:'Receptores quimiotáteis ajudam a explorar superfícies e alimento mesmo em baixa visibilidade.'},
{slug:'tempo',label:'Tempo e Clima',emoji:'🌬️',title:'São Paulo vira o tempo: calor e baixa umidade hoje, vento e queda de temperatura a partir de sexta',detail:'O INMET mantém alerta de baixa umidade hoje; a frente fria deve derrubar as máximas e trazer rajadas amanhã.'},
{slug:'curiosidades',label:'Curiosidades',emoji:'🧠',title:'Por que uma colher parece quebrar dentro da água?',detail:'Refração muda o caminho da luz e desloca a posição aparente do objeto.'},
{slug:'musica',label:'Música',emoji:'🎵',title:'Fim de semana tem encontro de gerações do sertanejo; Rock segue em trilha própria',detail:'Festival Histórias reúne seis nomes importantes em São Paulo no sábado; o hub mantém Top 10 Rock separado.'},
{slug:'games',label:'Games',emoji:'🎮',title:'gamescom entra na semana decisiva: dev começa dia 23 e feira principal dia 26',detail:'Agenda oficial já permite separar data confirmada, evento de desenvolvedores, Opening Night Live e rumor.'},
{slug:'gravidez',label:'Gravidez',emoji:'🤰',title:'6 semanas + 4 dias: desenvolvimento, enjoo, recuperação após vômito e preparação para o puerpério',detail:'A leitura da fase atual agora se conecta também ao pós-parto e ao plano de apoio do parceiro.'},
{slug:'pai',label:'Ser Pai',emoji:'👨‍🍼',title:'Ser pai agora é reduzir carga: apoio no enjoo hoje e preparo para assumir tarefas no puerpério',detail:'Presença útil é prática: antecipar necessidades, dividir trabalho mental e observar sinais importantes.'},
{slug:'carros',label:'Carros',emoji:'🚗',title:'Comparativo de usados até R$70 mil: preço não substitui histórico, laudo e manutenção',detail:'Modelos e imagens reais permanecem; a decisão combina custo de compra, risco mecânico e exemplar.'},
{slug:'motos',label:'Motos',emoji:'🏍️',title:'Moto usada: ciclística e marcas de queda contam mais do que brilho de anúncio',detail:'Guidão, batentes, rodas, bengalas, relação, pneus, freios e histórico entram no checklist.'},
{slug:'mecanica',label:'Mecânica',emoji:'🔧',title:'Compressão x leak-down: dois testes que respondem perguntas diferentes',detail:'Pressão baixa aponta problema; o segundo teste ajuda a localizar por onde a vedação está escapando.'},
{slug:'nautica',label:'Náutica',emoji:'⚓',title:'Colete salva-vidas: tamanho, ajuste e homologação importam tanto quanto “ter um a bordo”',detail:'Equipamento errado pode não cumprir a função quando realmente necessário.'},
{slug:'viagens',label:'Viagens',emoji:'🌷',title:'Expoflora 2026 começa em 28 de agosto: já dá para montar o bate-volta com informação oficial',detail:'Evento vai até 27 de setembro, de sexta a domingo e no feriado de 7/9, das 9h às 19h.'},
{slug:'financas',label:'Finanças',emoji:'💰',title:'Alívio nos Treasuries durou pouco: juros longos voltaram a subir nesta quinta',detail:'Yield de 10 e 30 anos voltou a pressionar ativos enquanto petróleo subiu; crédito não muda de um dia para outro.'},
{slug:'tecnologia',label:'Tecnologia',emoji:'💻',title:'Data center de IA virou compromisso de décadas — e a conta inclui energia, rede, terrenos e garantias',detail:'A escala do novo ciclo de IA aparece em projetos bilionários e contratos de infraestrutura de longo prazo.'},
{slug:'security-briefing',label:'Security Briefing',emoji:'📰',title:'Security Briefing revalidado: supply chain, IAM/cloud e exploração acelerada por IA seguem no topo',detail:'As prioridades foram rechecadas contra Mandiant/GTIG, Microsoft e CISA; P0 depende de exposição real e blast radius.'},
{slug:'seguranca',label:'Cyber Security',emoji:'🛡️',title:'Exploração antes do patch virou cenário real: vulnerability management precisa assumir que “zero-day” pode já ter acontecido',detail:'GTIG e M-Trends mostram pressão crescente sobre exposure management, hunting e resposta.'},
{slug:'appsec-ssdlc',label:'AppSec / SSDLC',emoji:'🧬',title:'Supply chain e agentes de IA mudam o gate: dependência, pipeline, identidade e provenance entram na mesma decisão',detail:'A revisão do dia conecta GTIG, NIST SSDF, SLSA, SBOM e least privilege no CI/CD.'}
];
todayDrops.splice(0,todayDrops.length,...drops);

set('hoje',{title:'22 áreas · todas revalidadas às 19h05',summary:'Antes desta publicação, cada área foi classificada como atualizada ou validada. Notícias e eventos foram rechecados; conteúdos educativos permaneceram somente quando ainda estavam corretos e não repetiam a edição anterior.',shareSummary:'20/08 · 19h05: 22 áreas revalidadas, com Zona Leste renovada, tempo atualizado, gamescom, Expoflora, mercados, tecnologia, Cyber/AppSec e puerpério na gravidez.',readTime:'22 MISSÕES',badge:'19H05 · ALL TABS VERIFIED',sections:[]});

set('brasil',{title:'Fiscal: governo fala em preservar arcabouço e reduzir despesas obrigatórias em 2027',summary:'O ministro da Fazenda, Dario Durigan, disse nesta quinta que a intenção é manter o arcabouço fiscal e citou medidas capazes de reduzir despesas obrigatórias em cerca de R$10 bilhões em 2027. A informação é uma projeção de política fiscal, não uma economia já realizada.',shareSummary:'Brasil 20/08: Fazenda fala em manter arcabouço e reduzir despesas obrigatórias em 2027; efeito depende de medidas, Congresso, receitas e execução.',readTime:'7 MIN READ',badge:'ATUALIZADO 19H05 · BRASIL',sections:[{title:'O que aconteceu hoje',paragraphs:['A fala veio num momento de pressão sobre dívida, juros e espaço orçamentário. O governo sinaliza continuidade da regra fiscal combinada com tentativa de conter despesas que crescem automaticamente.']},{title:'O que precisa acontecer para virar resultado',bullets:['Medidas precisam existir em texto legal ou regulatório.','Congresso pode alterar desenho e impacto.','A execução de 2027 depende também de receitas e crescimento.','Resultado primário e dívida/PIB devem ser acompanhados, não apenas anúncios.']},{title:'Impacto prático',paragraphs:['Uma trajetória fiscal mais previsível pode reduzir prêmio de risco ao longo do tempo, mas não derruba juros ao consumidor de forma automática. Crédito depende também de Selic, risco bancário, spread e inadimplência.']},{title:'O que acompanhar',bullets:['LDO/LOA de 2027.','Medidas efetivamente aprovadas.','Relatórios bimestrais e trajetória da dívida.']}],sources:[{label:'Reuters · 20/08/2026',url:'https://www.reuters.com/world/americas/brazil-keep-fiscal-framework-spending-restraint-under-new-lula-term-minister-2026-08-20/'}]});

set('seguranca-zl',{title:'Zona Leste em Foco: notícia local, segurança, serviço e contexto no mesmo lugar — sem misturar as camadas',summary:'A varredura de 19h05 encontrou assuntos atuais em São Miguel, Vila Formosa, Itaquera e Aricanduva, além de fato policial publicado no dia 19. A aba dedicada abre por Região e separa Segurança, Casos, Matérias, Dados, Ações e Serviços.',shareSummary:'ZL 20/08: agenda eleitoral com protestos em São Miguel/Vila Formosa, Libertadores em Itaquera, vacinação amanhã em Corinthians-Itaquera e ocorrências recentes em Aricanduva/ZL.',readTime:'12 MIN READ',badge:'ATUALIZADO 19H05 · ZONA LESTE',sections:[{title:'Hoje / próximas horas',bullets:['São Miguel e Vila Formosa receberam agendas de campanha com protestos registrados pelo UOL.','Corinthians recebe Rosario Central em Itaquera às 21h30 pela Libertadores.','Corinthians-Itaquera tem vacinação contra sarampo programada para sexta, 21/08, das 10h às 20h.']},{title:'Segurança recente',bullets:['UOL publicou hoje homicídio em Aricanduva ocorrido no dia 19; suspeito estava foragido na publicação.','Band publicou em 19/08 a localização de desmanche clandestino na Zona Leste com quatro prisões em flagrante.']},{title:'Como a aba deve ser lida',paragraphs:['Notícia local não vira indicador criminal; ocorrência não vira tendência; status jurídico precisa de fonte e data. Redes sociais podem servir de radar, mas fatos sensíveis exigem confirmação independente.']}],sources:[{label:'UOL · campanha na Zona Leste · 20/08',url:'https://noticias.uol.com.br/eleicoes/2026/08/20/protesto-flavio-bolsonaro-zona-leste-de-sao-paulo.ghtm'},{label:'UOL · Aricanduva · 20/08',url:'https://noticias.uol.com.br/cotidiano/ultimas-noticias/2026/08/20/briga-entre-vizinhos-deixa-um-morto-na-zona-leste-de-sao-paulo.ghtm'},{label:'Band · desmanche · 19/08',url:'https://www.band.com.br/noticias/brasil-urgente/ultimas/policia-descobre-desmanche-clandestino-na-zona-leste-de-sp-202608191653'}]});

set('politica',{title:'Voto em trânsito: prazo termina hoje; campanha e candidaturas seguem em trilhas separadas',summary:'O TSE mantém 20 de agosto como último dia para pedir, alterar ou cancelar a habilitação para voto em trânsito e outras transferências temporárias. Isso é serviço eleitoral do eleitor, não decisão sobre candidatura.',shareSummary:'Política 20/08: prazo de voto em trânsito termina hoje. Campanha, protestos, propostas e situação de registro de candidatura devem ser analisados separadamente.',readTime:'7 MIN READ',badge:'ATUALIZADO 19H05 · POLÍTICA',sections:[{title:'O serviço que vence hoje',paragraphs:['Eleitores elegíveis que estarão fora do domicílio eleitoral podem usar voto em trânsito conforme regras do TSE. Quem já fez a opção também tem hoje para alteração ou cancelamento.']},{title:'O que não misturar',bullets:['Prazo do eleitor ≠ prazo de registro de candidatura.','Agenda de campanha ≠ pesquisa eleitoral.','Proposta ≠ política aprovada.','Investigação/ação judicial ≠ condenação definitiva.']},{title:'Na Zona Leste hoje',paragraphs:['O UOL registrou protestos durante agendas de Flávio Bolsonaro em São Miguel e Vila Formosa. O fato é relevante como ocorrência de campanha, mas não mede intenção de voto.']}],sources:[{label:'TSE · voto em trânsito 2026',url:'https://www.tse.jus.br/eleicoes/eleicoes-2026-content/voto-em-transito-perguntas-e-respostas'},{label:'TSE · calendário eleitoral',url:'https://www.tse.jus.br/eleicoes/calendario-eleitoral/'},{label:'UOL · campanha na Zona Leste · 20/08',url:'https://noticias.uol.com.br/eleicoes/2026/08/20/protesto-flavio-bolsonaro-zona-leste-de-sao-paulo.ghtm'}]});

set('mundo',{title:'Petróleo e juros longos voltam a pressionar mercados globais',summary:'Nesta quinta, Treasuries voltaram a vender depois do alívio inicial provocado pelas recompras do Tesouro americano. O Brent também avançou com as disrupções em Hormuz, mantendo energia, inflação e custo de capital no mesmo radar.',shareSummary:'Mundo 20/08: juros longos voltaram a subir e Brent avançou; energia cara e dívida continuam pressionando inflação e ativos.',readTime:'8 MIN READ',badge:'ATUALIZADO 19H05 · MUNDO',sections:[{title:'O que mudou no dia',bullets:['Yield do Treasury de 10 anos voltou para perto de 4,7%.','O Treasury de 30 anos voltou a superar 5,2%.','Brent avançou com risco e disrupção em Hormuz.']},{title:'Por que isso importa fora de Wall Street',paragraphs:['Juros longos são referência para custo de capital e valuation. Petróleo entra em combustível, transporte, petroquímica e expectativa de inflação. Quando os dois apertam juntos, empresas e consumidores sentem por canais diferentes.']},{title:'Limite da leitura',paragraphs:['Uma sessão não define tendência. Recompra de título pode melhorar liquidez sem resolver déficit, inflação ou dívida estrutural.']}],sources:[{label:'Reuters · Global Markets · 20/08/2026',url:'https://www.reuters.com/world/china/global-markets-global-markets-2026-08-20/'}]});

set('planeta',{title:'Correntes de retorno: o risco é o fluxo para fora, não um “ralo” puxando para baixo',summary:'Canais de retorno transportam água da zona de arrebentação de volta ao oceano. Podem afastar rapidamente um banhista da praia e exigem leitura do mar, conservação de energia e orientação de guarda-vidas.',readTime:'6 MIN READ',badge:'VALIDADO 19H05 · PLANETA',sections:[{title:'Como se formam',paragraphs:['Ondas empurram água para a praia; essa água precisa retornar ao mar. Bancos de areia e relevo concentram o escoamento em canais.']},{title:'Sinais visuais',bullets:['Faixa com menos ondas quebrando.','Água mais escura ou turva seguindo para fora.','Espuma e objetos deslocando-se em direção ao mar.']},{title:'O que fazer',paragraphs:['A orientação de segurança depende do local e do guarda-vidas. Em geral, não gastar toda a energia tentando nadar diretamente contra o fluxo é mais seguro do que “brigar” com a corrente.']}],sources:[{label:'NOAA · Rip Currents',url:'https://www.noaa.gov/jetstream/ripcurrents'}]});

set('animais',{title:'Polvos combinam tato e detecção química nos braços',summary:'Os braços de polvos têm receptores capazes de detectar compostos químicos em superfícies. Isso ajuda o animal a investigar alimento, fendas e objetos sem depender apenas da visão.',readTime:'5 MIN READ',badge:'VALIDADO 19H05 · MUNDO ANIMAL',sections:[{title:'Um sistema nervoso diferente do nosso',paragraphs:['Uma parcela enorme dos neurônios do polvo está distribuída pelos braços. Isso permite processamento local de informação sensorial e controle motor muito sofisticado.']},{title:'“Provar com o braço” é metáfora',paragraphs:['O mecanismo não é paladar humano. É detecção química combinada com tato, útil para explicar a forma incomum como o polvo explora o ambiente.']},{title:'Por que interessa à ciência',bullets:['Neurobiologia distribuída.','Sensores para robótica macia.','Evolução independente de comportamentos complexos.']}],sources:[{label:'OIST · pesquisa sobre quimiotato em polvos · 2026',url:'https://www.oist.jp/news-center/news/2026/4/3'},{label:'Harvard · octopus arms taste and touch',url:'https://news.harvard.edu/gazette/story/2020/10/how-octopus-arms-taste-and-touch/'}]});

set('tempo',{title:'São Paulo vira o tempo: baixa umidade hoje, vento e queda de temperatura a partir de sexta',summary:'A capital teve tarde quente nesta quinta e o INMET manteve alerta de baixa umidade. A partir de sexta, frente fria e ciclone no Sul mudam a circulação, com vento e queda importante de temperatura em São Paulo.',shareSummary:'Tempo 20/08: calor e ar seco hoje; sexta fica mais fresca e ventosa, e o fim de semana esfria. A mudança é gradual e não significa temporal forte na capital.',readTime:'6 MIN READ',badge:'ATUALIZADO 19H05 · TEMPO',sections:[{title:'Hoje',bullets:['Máxima na casa de 31°C na capital em previsões consultadas.','INMET indicou baixa umidade em parte de São Paulo.','Hidratação e redução de esforço no período mais seco continuam relevantes.']},{title:'A virada',paragraphs:['A frente fria associada ao ciclone extratropical deve aumentar o vento e derrubar temperaturas a partir de sexta. O efeito mais forte de chuva não está concentrado na capital, mas a sensação térmica muda.']},{title:'Fim de semana',paragraphs:['As previsões apontam máximas mais baixas e manhãs frias, com sábado e domingo já bem diferentes da quinta quente.']}],sources:[{label:'Folha · ciclone e queda de temperatura · 20/08',url:'https://www1.folha.uol.com.br/cotidiano/2026/08/ciclone-extratropical-deve-derrubar-as-temperaturas-em-sao-paulo-a-partir-de-sexta-21.shtml'},{label:'Band/INMET · alerta de vendaval e baixa umidade',url:'https://www.band.com.br/noticias/inmet-emite-alerta-amarelo-para-vendaval-em-sp-rj-e-es-veja-previsao-202608192206'}]});

set('curiosidades',{title:'Por que uma colher parece “quebrar” dentro da água?',summary:'Ao atravessar água e ar, a luz muda de velocidade e direção. O cérebro reconstrói o caminho como se fosse reto e cria uma posição aparente deslocada.',readTime:'5 MIN READ',badge:'VALIDADO 19H05 · CURIOSIDADES',sections:[{title:'O mecanismo',paragraphs:['A mudança de direção é a refração. Quanto maior a diferença de índice de refração e o ângulo de incidência, mais evidente pode ficar o desvio.']},{title:'Onde isso aparece na vida real',bullets:['Óculos e lentes.','Câmeras e microscópios.','Piscinas que parecem mais rasas.','Fibra óptica e instrumentos científicos.']},{title:'Experimento simples',paragraphs:['Coloque lápis ou colher em um copo transparente e mude o ângulo de observação. O objeto não dobrou; a trajetória da luz até seus olhos é que mudou.']}],sources:[{label:'OpenStax · Geometric Optics',url:'https://openstax.org/books/physics/pages/16-2-refraction'}]});

set('musica',{title:'Fim de semana junta gerações do sertanejo em São Paulo; Rock segue com curadoria própria',summary:'O Festival Histórias acontece sábado, 22 de agosto, em São Paulo, reunindo Chitãozinho & Xororó, Zezé Di Camargo & Luciano, Daniel, César Menotti & Fabiano, Victor & Leo e Matogrosso & Mathias. O hub mantém Rock e sertanejo de época em trilhas separadas.',readTime:'7 MIN READ',badge:'ATUALIZADO 19H05 · MÚSICA',sections:[{title:'O que torna o evento interessante',paragraphs:['O line-up atravessa modão, romantismo sertanejo e fases diferentes do gênero. Para a aba, isso vira contexto histórico e não só agenda de show.']},{title:'Na curadoria',bullets:['Top 10 Rock continua separado.','Sertanejo de época privilegia repertório histórico e viola.','Charts atuais entram como contexto, não substituem a trilha de clássicos.']},{title:'O que acompanhar',paragraphs:['Programação de sábado e novos lançamentos da semana em fontes musicais; sem reproduzir letras protegidas.']}],sources:[{label:'Billboard Brasil · Festival Histórias · 12/08/2026',url:'https://billboard.com.br/festival-historias-em-sp-detalhes/'},{label:'Billboard Brasil · Sertanejo',url:'https://billboard.com.br/generos/sertanejo/'}]});

set('games',{title:'gamescom entra na semana decisiva: dev começa dia 23 e feira principal dia 26',summary:'A gamescom dev tem atividades de 23 a 25 de agosto; a gamescom principal acontece de 26 a 30, com Opening Night Live no dia 25. A edição separa agenda confirmada de rumor e expectativa.',readTime:'7 MIN READ',badge:'ATUALIZADO 19H05 · GAMES',sections:[{title:'Datas confirmadas',bullets:['gamescom dev: 23–25/08.','Conferência principal do dev: 24 e 25/08.','Opening Night Live: 25/08.','gamescom: 26–30/08.']},{title:'O que vale acompanhar',bullets:['Trailers e anúncios oficiais.','Indies selecionados e gamescom dev awards.','Atualizações de PlayStation, Xbox, Nintendo e publishers somente quando confirmadas.']},{title:'Regra anti-hype',paragraphs:['Wishlist, rumor, leak e expectativa ficam rotulados como tal. “Aparecerá na gamescom” só entra como confirmado quando organizador ou publisher disser isso.']}],sources:[{label:'gamescom dev · agenda oficial 2026',url:'https://dev.gamescom.global/conference/'},{label:'gamescom congress · programação 2026',url:'https://congress.gamescom.global/en/program/'}]});

set('gravidez',{title:'6 semanas + 4 dias: desenvolvimento, enjoo e uma visão completa do cuidado que vem depois do parto',summary:'A gestação está no começo da organogênese, fase em que estruturas embrionárias mudam rapidamente. A aba mantém cuidado com enjoo/vômito e agora inclui um módulo de puerpério para preparar apoio físico, emocional e doméstico à mãe.',readTime:'12 MIN READ',badge:'ATUALIZADO 19H05 · GRAVIDEZ',sections:[{title:'Fase atual',paragraphs:['Com 6 semanas + 4 dias pela DUM de 05/07, o embrião atravessa mudanças rápidas no sistema nervoso, coração e brotos dos membros. Datas e medidas variam e ultrassom clínico é mais preciso para avaliação individual.']},{title:'Enjoo e vômito',bullets:['Pequenos goles e retorno gradual de líquidos.','Não forçar comida imediatamente.','Enxaguar a boca e evitar escovação imediata após o ácido do vômito.','Observar capacidade de manter líquidos e frequência dos episódios.']},{title:'Puerpério também faz parte do planejamento',paragraphs:['O módulo dedicado cobre primeiras 24–72 horas, dias 3–14, semanas 2–6, recuperação, descanso, visitas, divisão de tarefas, autonomia, sinais maternos de alerta e formas concretas de transmitir segurança.']},{title:'Papel do parceiro',bullets:['Assumir tarefas sem esperar que ela delegue tudo.','Proteger sono e pausas.','Levar sintomas a sério.','Não pressionar corpo, sexo, exercício ou forma de alimentar o bebê.','Acompanhar consultas e organizar rede de apoio.']}],sources:[{label:'CDC · Hear Her',url:'https://www.cdc.gov/hearher/support/index.html'},{label:'WHO · Postnatal care',url:'https://www.who.int/publications/i/item/9789240045989'},{label:'ACOG · Morning Sickness',url:'https://www.acog.org/womens-health/faqs/morning-sickness-nausea-and-vomiting-of-pregnancy'}]});

set('pai',{title:'Ser pai agora é reduzir carga — durante o enjoo e no preparo para o puerpério',summary:'Apoio não é esperar instrução para “ajudar”. É assumir parte real da logística, observar necessidades, respeitar autonomia e criar previsibilidade para que a mãe não precise gerenciar também o parceiro.',readTime:'8 MIN READ',badge:'ATUALIZADO 19H05 · SER PAI',sections:[{title:'Hoje',bullets:['Deixe água, recipiente, toalha e opção de alimento tolerável acessíveis.','Cuide da limpeza e reposição sem transformar isso em tarefa dela.','Pergunte o que está ajudando; preferências podem mudar de um dia para outro.']},{title:'Para o puerpério',bullets:['Planeje refeições simples e apoio doméstico.','Combine filtro de visitas.','Separe contatos e documentos do pré-natal.','Aprenda rotina básica do bebê junto, não depois.','Reserve espaço para ela descansar sem precisar justificar.']},{title:'Como transmitir segurança',paragraphs:['Previsibilidade, escuta e coerência ajudam mais que frases prontas. Dizer o que você vai assumir e cumprir reduz carga mental.']}],sources:[{label:'CDC · Supporting Pregnant and Postpartum People',url:'https://www.cdc.gov/hearher/support/index.html'},{label:'WHO · Positive postnatal experience',url:'https://www.who.int/publications/i/item/9789240045989'}]});

set('carros',{title:'Comparativo de usados até R$70 mil: o exemplar vale mais do que a fama do modelo',summary:'A seleção mantém motores acima de 1.0 e combina preço de mercado, geração, manutenção, problemas conhecidos e inspeção. Foto do modelo/geração faz parte do card e da análise detalhada.',readTime:'10 MIN READ',badge:'VALIDADO 19H05 · CARROS',sections:[{title:'O filtro antes do anúncio',bullets:['Motor acima de 1.0.','Faixa até R$70 mil.','Peças e manutenção compatíveis com uso real.','Histórico verificável e laudo cautelar.']},{title:'O que revisar no carro',bullets:['Arrefecimento e vazamentos.','Câmbio e embreagem.','Pneus e alinhamento.','Suspensão e ruídos.','Scanner, luzes de falha e documentação.']},{title:'Regra de decisão',paragraphs:['Um modelo “confiável” mal cuidado pode ser compra pior que um modelo mais complexo com histórico impecável.']}],sources:[{label:'FIPE · consulta de referência',url:'https://veiculos.fipe.org.br/'}]});

set('motos',{title:'Moto usada: ciclística, sinais de queda e manutenção contam a história real',summary:'A comparação considera preço, perfil de uso, quilometragem, ciclística, suspensão, pneus, relação, freios/ABS, manutenção e sinais de impacto. Fotos reais do modelo ajudam a comparar geração e proposta.',readTime:'9 MIN READ',badge:'VALIDADO 19H05 · MOTOS',sections:[{title:'Sinais de queda',bullets:['Batentes de direção marcados.','Guidão/manetes desalinhados.','Pedaleiras e escapamento ralados.','Bengalas, rodas e mesa fora de alinhamento.']},{title:'Desgaste que custa dinheiro',bullets:['Kit relação.','Pneus.','Pastilhas/discos.','Retentores de bengala.','Bateria e sistema de carga.']},{title:'Teste de uso',paragraphs:['A moto precisa seguir reta, frear sem vibração anormal e não apresentar folga excessiva na direção/suspensão.']}],sources:[{label:'FIPE · consulta de referência',url:'https://veiculos.fipe.org.br/'}]});

set('mecanica',{title:'Compressão x leak-down: dois testes que respondem perguntas diferentes',summary:'Compressão mostra quanta pressão o cilindro desenvolve no giro do motor; leak-down pressuriza o cilindro parado para ajudar a descobrir por onde a vedação está escapando.',readTime:'6 MIN READ',badge:'VALIDADO 19H05 · MECÂNICA',sections:[{title:'Compressão',paragraphs:['É ótima para comparar cilindros, mas o número depende de procedimento, bateria, temperatura, borboleta e especificação do motor.']},{title:'Leak-down',bullets:['Ar na admissão sugere investigar válvula de admissão.','No escape, válvula de escape.','No cárter, anéis/cilindro.','Bolhas no arrefecimento pedem investigação de comunicação indevida.']},{title:'Erro comum',paragraphs:['Trocar peça baseado apenas em “compressão baixa” sem localizar a perda é diagnóstico incompleto.']}],sources:[{label:'Auto Service Praxis · teste de compressão',url:'https://www.autoservicepraxis.de/nachrichten/kfz-werkstatt/der-ist-doch-nicht-ganz-dicht-3679344'}]});

set('nautica',{title:'Colete salva-vidas: tamanho, ajuste e homologação importam tanto quanto ter o equipamento',summary:'Equipamentos de flutuação têm usos diferentes. Um colete mal dimensionado ou degradado pode subir no corpo, limitar movimentos ou não cumprir o desempenho esperado.',readTime:'6 MIN READ',badge:'VALIDADO 19H05 · NÁUTICA',sections:[{title:'Antes de sair',bullets:['Confirme quantidade e tamanhos para todos a bordo.','Teste ajuste de crianças.','Revise costuras, fechos e material flutuante.','Verifique requisitos aplicáveis à embarcação e navegação.']},{title:'Durante a navegação',paragraphs:['Condições de mar, velocidade, atividade e experiência da tripulação mudam o nível de risco. Equipamento guardado e inacessível não ajuda numa emergência rápida.']}],sources:[{label:'Marinha do Brasil · Segurança da Navegação',url:'https://www.marinha.mil.br/dpc/seguranca-da-navegacao'},{label:'U.S. Coast Guard · Life Jacket Safety',url:'https://www.dvidshub.net/image/9055262/coast-guard-promotes-life-jacket-safety-during-national-safe-boating-week'}]});

set('viagens',{title:'Expoflora 2026 começa em 28 de agosto: planeje o bate-volta com o calendário oficial',summary:'A 43ª Expoflora acontece de 28 de agosto a 27 de setembro, às sextas, sábados, domingos e no feriado de 7/9, das 9h às 19h, no Parque da Expoflora em Holambra.',readTime:'7 MIN READ',badge:'ATUALIZADO 19H05 · VIAGENS',sections:[{title:'O ingresso inclui',bullets:['Exposição de arranjos florais.','Mostra de paisagismo.','Parada/Chuva de Pétalas e atrações do parque conforme programação.','Museu, danças e apresentações culturais.']},{title:'O que pode ser cobrado à parte',bullets:['Campo de girassóis.','Parque de diversões.','Alimentação.','Estacionamento e compras.']},{title:'Planejamento realista',paragraphs:['Chegar cedo reduz pressão de fila e estacionamento. Confirme ingresso, clima, tempo de estrada e atividades extras no canal oficial antes de sair.']}],sources:[{label:'Expoflora · informações oficiais 2026',url:'https://www.expoflora.com.br/saladeimprensa/noticia/11-expoflora-informacoes-essenciais-sobre-o-evento'},{label:'Expoflora · site oficial',url:'https://expoflora.com.br/home'}]});

set('financas',{title:'Alívio nos Treasuries durou pouco: juros longos voltaram a subir nesta quinta',summary:'Depois da reação à expansão das recompras pelo Tesouro americano, yields voltaram a avançar. O movimento reforça que liquidez pode aliviar mercado sem resolver inflação, déficit e oferta de dívida.',readTime:'8 MIN READ',badge:'ATUALIZADO 19H05 · FINANÇAS',sections:[{title:'O que aconteceu',bullets:['10 anos perto de 4,7%.','30 anos voltou para perto/acima de 5,2%.','Petróleo alto adicionou pressão inflacionária.']},{title:'Por que não vira seu financiamento amanhã',paragraphs:['Taxas ao consumidor incluem curva de juros, spread bancário, risco, prazo, impostos e competição. A direção de Treasury ajuda a entender custo global de capital, mas não determina sozinho o CET brasileiro.']},{title:'O que acompanhar',bullets:['Fed e inflação.','Oferta de dívida americana.','Petróleo e dólar.','Curva de juros brasileira.']}],sources:[{label:'Reuters · Global Markets · 20/08/2026',url:'https://www.reuters.com/world/china/global-markets-global-markets-2026-08-20/'}]});

set('tecnologia',{title:'IA virou infraestrutura de décadas: um data center agora envolve energia, garantias, rede e capital em escala inédita',summary:'A Reuters informou que a Nvidia ofereceu garantias de até US$105 bilhões ligadas a um data center para OpenAI em Ohio. O número mostra como a corrida de IA saiu do “comprar GPUs” e entrou em energia, imóveis, contratos e financiamento de longo prazo.',readTime:'8 MIN READ',badge:'ATUALIZADO 19H05 · TECNOLOGIA',sections:[{title:'Escala física',bullets:['Projeto prevê até 8 GW de capacidade.','Primeira parcela de 800 MW é esperada para 2028.','O desenho financeiro mistura equity, dívida e garantias.']},{title:'O que isso ensina sobre IA',paragraphs:['Compute sem energia, rede e resfriamento não entrega capacidade. A vantagem competitiva passa a incluir acesso a infraestrutura física e financiamento, não apenas modelo e chip.']},{title:'Risco / incerteza',paragraphs:['Garantia não é receita realizada. Projetos dessa escala carregam risco de execução, demanda, energia, financiamento e utilização.']}],sources:[{label:'Reuters · Nvidia/OpenAI data center · 17/08/2026',url:'https://www.reuters.com/business/media-telecom/nvidia-invest-15-billion-sb-energy-under-openai-data-center-deal-2026-08-17/'}]});

set('security-briefing',{title:'Security Briefing revalidado: IAM/cloud, supply chain e exploração acelerada por IA continuam exigindo decisão',summary:'A revisão de 19h05 não trocou sinais fortes só para parecer “nova”. Em vez disso, revalidou impacto, fonte, exposição e ação: identidade privilegiada, supply chain de pacotes/CI, SD-WAN e AI-assisted vulnerability management continuam materialmente relevantes.',readTime:'18 MIN READ',badge:'REVALIDADO 19H05 · SECURITY BRIEFING',sections:[{title:'O que foi revalidado',bullets:['Microsoft: comprometimento de identidade pode cruzar M365, Azure e Key Vault.','Mandiant: exploração zero-day em Cisco SD-WAN Manager mostrou cadeia admin→root.','Microsoft/GTIG: supply chain alcança package registry, developer workstation e CI/CD.','Mandiant: IA pode acelerar vuln management, mas agentes privilegiados criam nova superfície.']},{title:'Regra de prioridade',paragraphs:['P0/P1 não vem de CVSS sozinho. O briefing considera exploração observada, internet exposure, privilégio, control plane, blast radius, criticidade e controles existentes.']}],sources:[{label:'Google Threat Intelligence · Threat Intelligence feed',url:'https://cloud.google.com/blog/topics/threat-intelligence/'},{label:'CISA · KEV',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog'}]});

set('seguranca',{title:'Exploração antes do patch virou cenário real: defesa precisa combinar exposure management, hunting e resposta',summary:'M-Trends 2026 reporta tempo médio de exploração estimado em -7 dias — isto é, em parte dos casos a exploração começa antes de existir correção. O GTIG também documenta uso de IA para acelerar descoberta e weaponization.',readTime:'9 MIN READ',badge:'ATUALIZADO 19H05 · CYBER',sections:[{title:'O que muda operacionalmente',bullets:['Inventário internet-facing precisa ser confiável.','Sinal de exploração conhecida sobe prioridade.','Hunting pode ser necessário mesmo depois do patch.','Logs e evidência precisam existir antes do incidente.']},{title:'IA no lado adversário',paragraphs:['O GTIG observou atores usando modelos para pesquisa de vulnerabilidade, desenvolvimento de exploit e automação. Isso comprime o tempo disponível para defesa, mas não elimina a necessidade de validação técnica do exploit.']},{title:'Plano mínimo',bullets:['Exposição + ativo + privilégio + evidência de exploração.','Mitigação/patch.','Hunting retroativo.','Rotação de credenciais se houver risco de comprometimento.','Teste de recuperação para ativos críticos.']}],sources:[{label:'Mandiant · M-Trends 2026',url:'https://cloud.google.com/blog/topics/threat-intelligence/m-trends-2026'},{label:'GTIG · AI Threat Tracker · 11/05/2026',url:'https://cloud.google.com/blog/topics/threat-intelligence/ai-vulnerability-exploitation-initial-access/'}]});

set('appsec-ssdlc',{title:'Supply chain e agentes de IA mudam o gate: dependência, pipeline, identidade e provenance entram na mesma decisão',summary:'O GTIG descreveu compromissos de pacotes e repositórios/GitHub Actions com roubo de AWS keys e GitHub tokens de ambientes de build. A lição é estrutural: CI/CD e integrações de IA são superfícies privilegiadas e precisam de trust boundaries explícitas.',readTime:'12 MIN READ',badge:'ATUALIZADO 19H05 · APPSEC',sections:[{title:'O caminho de ataque',bullets:['Pacote/PyPI ou PR malicioso.','Compromisso de repositório/Action.','Execução em runner.','Roubo de secrets/tokens.','Pivot para cloud ou downstream artifact.']},{title:'Gate que faz sentido',bullets:['Pinning e origem confiável.','Runner isolado e efêmero quando possível.','Token curto e mínimo por job.','SBOM + provenance/attestation.','Detecção de alteração de workflow e publicação.','Revalidação quando ferramenta/agente ganha nova permissão.']},{title:'AI/Agentic',paragraphs:['Skills, connectors e tools são dependências executáveis. O modelo não deve ser a camada de autorização; cada ação de alto impacto precisa continuar protegida por política determinística e identidade.']}],sources:[{label:'GTIG · AI Threat Tracker 2026',url:'https://cloud.google.com/blog/topics/threat-intelligence/ai-vulnerability-exploitation-initial-access/'},{label:'GTIG · Supply Chain Mitigation Guidance · 30/07/2026',url:'https://cloud.google.com/blog/topics/threat-intelligence/mitigation-guidance-for-supply-chain-compromise'},{label:'NIST SSDF',url:'https://csrc.nist.gov/pubs/sp/800/218/final'}]});

// Atualiza conteúdo de topo dos hubs dedicados sem apagar a curadoria rica já existente.
if (securityBriefingStories[0]) securityBriefingStories[0].freshness = 'REVALIDADO 20 AGO · 19H05';
if (securityBriefingStories[1]) securityBriefingStories[1].freshness = 'REVALIDADO 20 AGO · 19H05';
if (securityBriefingStories[2]) securityBriefingStories[2].freshness = 'REVALIDADO 20 AGO · 19H05';
if (appSecFeedPosts[0]) appSecFeedPosts[0].tag = 'AI PENTEST / SSDLC · VALIDADO 20 AGO';
if (appSecFeedPosts[1]) appSecFeedPosts[1].tag = 'PENTEST COM IA · VALIDADO 20 AGO';
