import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f3f0e7"/><rect x="70" y="110" width="940" height="1700" rx="84" fill="#e6ece9"/><circle cx="540" cy="610" r="285" fill="#2d5048" opacity=".14"/><text x="540" y="705" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M210 1030h660" stroke="#2d5048" stroke-width="14" opacity=".55"/><text x="540" y="1215" text-anchor="middle" font-size="53" font-weight="700" font-family="Arial,sans-serif" fill="#263b35">${headline}</text><text x="540" y="1340" text-anchor="middle" font-size="35" font-family="Arial,sans-serif" fill="#53655f">${sub}</text><text x="540" y="1530" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#6d7b76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 12/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 12/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260912:RichMediaEntry[]=[
img('Papo de hoje',['música mudou de significado','depois que vocês ficaram juntos'],'🎵','MÚSICA + MEMÓRIA','O QUE MUDOU DE SENTIDO?','Arte 9:16 específica com notas musicais e duas memórias conectadas para o papo de 12/09','https://www.gov.br/cultura/pt-br'),
img('Desafio do casal',['20 minutos sem tela','depois do jantar'],'📵','20 MIN SEM TELA','SÓ VOCÊS DOIS','Arte 9:16 específica com celular pausado e mesa para conversa sem telas','https://www.gov.br/saude/pt-br'),
img('Curiosidades',['três corações trabalhando','cefalópodes têm três corações'],'🐙','3 CORAÇÕES','CEFALÓPODES','Arte 9:16 específica com polvo e três símbolos de coração','https://ocean.si.edu/ocean-life/invertebrates/octopuses-squids-and-relatives'),
img('Curiosidades',['lua se afasta da terra','3,8 centímetros por ano'],'🌕','LUA EM MOVIMENTO','≈ 3,8 CM/ANO','Arte 9:16 específica com Terra, Lua e seta de afastamento orbital','https://science.nasa.gov/solar-system/moon/10-things-what-we-learn-about-earth-by-studying-the-moon/'),
img('Curiosidades',['polo norte magnético','muda de posição'],'🧭','NORTE MAGNÉTICO','ELE SE MOVE','Arte 9:16 específica com bússola e trajetória do polo norte magnético','https://www.ncei.noaa.gov/products/wandering-geomagnetic-poles'),
img('Curiosidades',['remodelação microscópica','osteoclastos removem'],'🦴','OSSO VIVO','REMOVE + RECONSTRÓI','Arte 9:16 específica com osso e ciclo de remodelação','https://pmc.ncbi.nlm.nih.gov/articles/PMC6172306/'),
img('Curiosidades',['gps precisa corrigir','38 microssegundos por dia'],'🛰️','GPS + EINSTEIN','38 µs/DIA','Arte 9:16 específica com satélite GPS, relógio atômico e correção relativística','https://www.nist.gov/atomic-clocks/a-powerful-tool-for-science/putting-einstein-test'),
img('Gravidez',['9 semanas + 6 dias','9s6d'],'🤰','9 SEMANAS + 6 DIAS','AMANHÃ: 10 SEMANAS','Arte 9:16 específica para 9 semanas e 6 dias de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/9-weeks/'),
img('Ser Pai',['refeição inteira','cozinha resolvida'],'🍽️','REFEIÇÃO COMPLETA','DECISÃO → COZINHA RESOLVIDA','Arte 9:16 específica com refeição pronta e cozinha organizada para missão de pai','https://www.cdc.gov/hearher/support-family-friends/index.html'),
img('Mundo',['arábia saudita fecha oleoduto','oleoduto leste-oeste'],'🛢️','OLEODUTO FECHADO','ARÁBIA SAUDITA · 12/09','Arte 9:16 específica com mapa saudita, oleoduto e interrupção após ataque com drone','https://www.reuters.com/business/energy/saudis-shut-down-oil-pipeline-houthis-tighten-grip-red-sea-shipping-2026-09-12/'),
img('Tempo e Clima',['chuva e queda de temperatura','ciclone extratropical'],'🌧️','SP · 12/09','CHUVA + AR MAIS FRIO','Arte 9:16 específica com São Paulo, chuva e entrada de ar frio','https://portal.inmet.gov.br/noticias/previs%C3%A3o-para-s%C3%A1bado-12-domingo-13-e-segunda-feira-14'),
img('Viagens',['plano b','chuva, trânsito ou lotação'],'🗺️','PLANO B','SEM IMPROVISO','Arte 9:16 específica com rota principal e alternativa para viagem curta','https://www.gov.br/turismo/pt-br'),
img('Música',['versão de estúdio','apresentação ao vivo'],'🎙️','ESTÚDIO x AO VIVO','COMPARE O ARRANJO','Arte 9:16 específica com estúdio e palco ao vivo lado a lado','https://www.gov.br/cultura/pt-br'),
img('Carros até R$ 70 mil',['comandos elétricos','vidro, trava, retrovisor'],'🚗','ATÉ R$70 MIL','TESTE OS ELÉTRICOS','Arte 9:16 específica com painel de carro e comandos elétricos em checklist','https://www.gov.br/senatran/pt-br'),
img('Motos',['retentores das bengalas','suspensão dianteira'],'🏍️','SUSPENSÃO DIANTEIRA','OLHE OS RETENTORES','Arte 9:16 específica com bengala e retentor da suspensão dianteira de moto','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['correia de acessórios','tensionador e polias'],'⚙️','CORREIA DE ACESSÓRIOS','TRINCAS + RUÍDO + ALINHAMENTO','Arte 9:16 específica com correia, tensionador e polias em inspeção','https://www.gov.br/senatran/pt-br')
];
