import type { RichMediaEntry } from './rich-media';

const commons=(name:string)=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(name).replace(/%2F/g,'/')}`;

export const dailyRichMedia20260828: RichMediaEntry[] = [
  { label:'Curiosidades', matches:['duas pessoas lado a lado não veem exatamente o mesmo arco-íris','arco-íris'], tag:'MÍDIA REAL · CIÊNCIA', title:'Arco-íris real', caption:'Fotografia real diretamente ligada à geometria do arco-íris.', images:[{url:commons('Rainbow image.jpg'),alt:'Arco-íris real no céu após chuva',caption:'Arco-íris observado no céu.',credit:'DavidConstantinescu / Wikimedia Commons · CC BY-SA 4.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Rainbow_image.jpg',kind:'PHOTO'}] },
  { label:'Curiosidades', matches:['existe um ponto cego real em cada olho','ponto cego real'], tag:'MÍDIA REAL · CORPO HUMANO', title:'Ponto cego da retina', caption:'Diagrama do ponto cego produzido pela saída do nervo óptico.', images:[{url:commons('Eye blind spot.svg'),alt:'Diagrama da retina mostrando o ponto cego na saída do nervo óptico',caption:'Ponto cego fisiológico do olho.',credit:'Wikimedia Commons · CC BY-SA',sourceUrl:'https://commons.wikimedia.org/wiki/File:Eye_blind_spot.svg',kind:'REFERENCE'}] },
  { label:'Curiosidades', matches:['o usb-c é reversível','usb-c é reversível','usb-c'], tag:'MÍDIA REAL · TECNOLOGIA', title:'Conector USB-C', caption:'Fotografia real de conector e receptáculo USB-C.', images:[{url:commons('USB-C connector and receptacle.webp'),alt:'Conector USB-C e receptáculo em fotografia aproximada',caption:'Conector e porta USB-C.',credit:'Wikideas1 / Wikimedia Commons · CC0',sourceUrl:'https://commons.wikimedia.org/wiki/File:USB-C_connector_and_receptacle.webp',kind:'PHOTO'}] },
  { label:'Zona Leste em Foco', matches:['vacinação contra sarampo segue hoje','shopping metrô itaquera'], tag:'MÍDIA REAL · ITAQUERA', title:'Shopping Metrô Itaquera', caption:'Fotografia real do local da ação de vacinação.', images:[{url:commons('Shopping Metrô Itaquera - 1.jpg'),alt:'Interior do Shopping Metrô Itaquera em São Paulo',caption:'Shopping Metrô Itaquera.',credit:'Ajmcbarreto / Wikimedia Commons · CC BY-SA 4.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Shopping_Metr%C3%B4_Itaquera_-_1.jpg',kind:'PHOTO'}] },
  { label:'Política', matches:['horário eleitoral gratuito começa hoje','tse reforça regras'], tag:'MÍDIA ELEITORAL · TSE', title:'Urna eletrônica brasileira', caption:'Imagem neutra da Justiça Eleitoral para a pauta do horário eleitoral.', images:[{url:commons('Brazilian DRE voting machine for 2022 elections.jpg'),alt:'Urna eletrônica brasileira em fotografia institucional',caption:'Urna eletrônica brasileira.',credit:'Tribunal Superior Eleitoral / Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Brazilian_DRE_voting_machine_for_2022_elections.jpg',kind:'PHOTO'}] },
  { label:'Mundo', matches:['negociações se concentram em reabrir hormuz','hormuz'], tag:'MÍDIA REAL · MAPA', title:'Estreito de Hormuz', caption:'Mapa geográfico da rota marítima citada na pauta.', images:[{url:commons('Strait of Hormuz-svg-en.svg'),alt:'Mapa do Estreito de Hormuz entre Irã e Omã',caption:'Estreito de Hormuz.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Strait_of_Hormuz-svg-en.svg',kind:'REFERENCE'}] },
  { label:'Tempo e Clima', matches:['onda de calor começa hoje em são paulo','34°c'], tag:'MÍDIA REAL · SÃO PAULO', title:'São Paulo em dia quente', caption:'Fotografia real da cidade para contextualizar a onda de calor.', images:[{url:commons('Parque da Independência - São Paulo - Brasil.jpg'),alt:'Área externa do Parque da Independência em São Paulo sob sol',caption:'São Paulo em ambiente aberto.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Parque_da_Independ%C3%AAncia_-_S%C3%A3o_Paulo_-_Brasil.jpg',kind:'PHOTO'}] },
  { label:'Games', matches:['gamescom continua hoje','última chance para votar no cosplay','gamescom'], tag:'MÍDIA REAL · GAMESCOM', title:'gamescom em Colônia', caption:'Fotografia real da entrada da gamescom.', images:[{url:commons('Main Entrance View at Gamescom 2025 in Cologne, Germany.jpg'),alt:'Entrada principal da gamescom em Colônia',caption:'gamescom em Colônia.',credit:'RAWdz Ivan / Wikimedia Commons · CC BY 4.0',sourceUrl:'https://commons.wikimedia.org/wiki/File:Main_Entrance_View_at_Gamescom_2025_in_Cologne,_Germany.jpg',kind:'PHOTO'}] },
  { label:'Finanças', matches:['mercados aguardam discurso do fed','petróleo opera perto da estabilidade'], tag:'MÍDIA REAL · FED', title:'Federal Reserve', caption:'Fotografia real do edifício do Federal Reserve para a pauta de juros.', images:[{url:commons('Federal Reserve Board building.jpg'),alt:'Edifício do Federal Reserve em Washington',caption:'Federal Reserve.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Federal_Reserve_Board_building.jpg',kind:'PHOTO'}] },
  { label:'Tecnologia', matches:['marvell cai após resultado forte','acordo de ia com google'], tag:'MÍDIA REAL · CHIPS', title:'Semicondutor', caption:'Fotografia macro de hardware de processamento ligada à pauta de chips de IA.', images:[{url:commons('Integrated circuit on microchip.jpg'),alt:'Circuito integrado em microchip visto de perto',caption:'Semicondutor.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/wiki/File:Integrated_circuit_on_microchip.jpg',kind:'PHOTO'}] },
  { label:'Security Briefing', matches:['papercut libera patch emergencial','zero-day explorado'], tag:'MÍDIA DA PAUTA · PAPERCUT', title:'PaperCut zero-day', caption:'Imagem editorial específica da pauta de exploração do PaperCut.', images:[{url:'https://www.securityweek.com/wp-content/uploads/2026/08/PaperCut-print-management.jpeg',alt:'Imagem relacionada ao PaperCut NG/MF e ao zero-day explorado',caption:'PaperCut NG/MF.',credit:'SecurityWeek',sourceUrl:'https://www.securityweek.com/papercut-releases-emergency-patch-for-exploited-zero-day/',kind:'REFERENCE'}] },
  { label:'Cyber Security', matches:['servicenow corrige três falhas críticas','servicenow'], tag:'MÍDIA DA PAUTA · SERVICENOW', title:'ServiceNow', caption:'Imagem editorial específica da pauta ServiceNow publicada em 28/08.', images:[{url:'https://www.bleepstatic.com/content/hl-images/2026/07/20/servicenow-headpic.jpg',alt:'Imagem relacionada à plataforma ServiceNow',caption:'ServiceNow AI Platform.',credit:'BleepingComputer',sourceUrl:'https://www.bleepingcomputer.com/news/security/servicenow-warns-of-three-max-severity-security-vulnerabilities/',kind:'REFERENCE'}] }
];
