import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'MÍDIA REAL · 15/09',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260915:RichMediaEntry[]=[
img('Papo de hoje',['que comida vocês gostariam de aprender','aprender a fazer juntos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cooking_at_home.jpg','Duas pessoas preparando comida juntas em uma cozinha','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:People_cooking'),
img('Desafio do casal',['mini passeio de 30 minutos','caminhar pelo bairro'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Couple_walking_in_a_park.jpg','Casal caminhando junto ao ar livre','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Couples_walking'),
img('Curiosidades',['corvos conseguem reconhecer','lembrar rostos humanos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/American_Crow.jpg','Corvo-americano fotografado em ambiente aberto','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Corvus_brachyrhynchos'),
img('Curiosidades',['bioluminescência é extremamente comum','90% dos animais','produzir luz'],'https://oceanexplorer.noaa.gov/multimedia/edu-themes-bioluminescence-media-multimedia-atolla/media/atolla-hires.jpg','Água-viva Atolla exibindo bioluminescência no oceano profundo','Imagem científica real · NOAA Ocean Exploration','https://oceanexplorer.noaa.gov/multimedia/edu-themes-bioluminescence-media-multimedia-atolla/'),
img('Curiosidades',['corrente de jato em saturno forma um hexágono','hexágono gigantesco'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Saturn_hexagon_Cassini.jpg','Hexágono no polo norte de Saturno observado pela sonda Cassini','Imagem real de missão · NASA/JPL-Caltech/SSI','https://science.nasa.gov/resource/saturns-hexagon-as-summer-solstice-approaches/'),
img('Curiosidades',['maior deserto da terra é coberto de gelo','antártida é o maior deserto'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Antarctica_6400px_from_Blue_Marble.jpg','Continente antártico coberto por gelo visto por satélite','Imagem real de satélite · NASA/Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Antarctica_6400px_from_Blue_Marble.jpg'),
img('Curiosidades',['acelerômetro e giroscópio','celular a entender como você o move'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Smartphone_gyroscope.jpg','Smartphone representando sensores internos de movimento e orientação','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Smartphones'),
img('Gravidez',['10 semanas + 2 dias','10s2d'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Embryo_at_10_weeks.JPG','Ultrassom real de embrião humano em torno de 10 semanas','Imagem médica real · X.Compagnion/Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Embryo_at_10_weeks.JPG'),
img('Ser Pai',['tarefa invisível','sem esperar pedido'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Man_washing_dishes.jpg','Homem lavando louça e assumindo uma tarefa doméstica','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Washing_dishes'),
img('Mundo',['china coloca em vigor novas restrições','segurança tecnológica'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Beijing_CBD_skyline_2022.jpg','Vista real do distrito financeiro de Pequim, China','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Beijing_CBD'),
img('Corinthians',['venda de ingressos para corinthians x fluminense','estudiantes nesta quarta'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Arena_Corinthians_2014.jpg','Neo Química Arena, estádio do Corinthians em São Paulo','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Arena_Corinthians'),
img('Viagens',['fotografe o estado do carro alugado','carro alugado antes de sair'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rental_cars.jpg','Veículos estacionados em área de locadora de automóveis','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Car_rental'),
img('Música',['prestando atenção só na bateria','bateria ou percussão'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Drum_set.jpg','Bateria acústica montada para execução musical','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Drum_kits'),
img('Tecnologia',['mediatek lança dimensity 9600 pro','primeiro chip móvel de 2 nm'],'https://www.mediatek.com/hubfs/MediaTek%20Assets/Images/dimensity-chipset.jpg','Chip real da família MediaTek Dimensity usado para representar o lançamento do Dimensity 9600 Pro','Imagem de produto · MediaTek','https://www.mediatek.com/technology/5g/dora'),
img('Finanças',['bolsas globais caem e treasury','maior rendimento desde 2007','brent acima de us$ 107'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/New_York_Stock_Exchange_Trading_Floor.jpg','Pregão da Bolsa de Nova York durante sessão de mercado','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:New_York_Stock_Exchange'),
img('Carros até R$ 70 mil',['pneus contam a mesma história','compare desgaste e idade'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Car_tire.jpg','Pneu automotivo real visto de perto para inspeção de desgaste','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Automobile_tires'),
img('Motos',['folga da corrente','corrente antes do test-ride'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Motorcycle_chain.jpg','Corrente e coroa de transmissão de uma motocicleta','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Motorcycle_chains'),
img('Mecânica',['barulho ao esterçar parado','ruído ao esterçar'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Car_steering_rack.jpg','Conjunto real de caixa de direção automotiva em manutenção','Foto real · Wikimedia Commons','https://commons.wikimedia.org/wiki/Category:Steering_systems')
];
