import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f1efe9"/><rect x="76" y="116" width="928" height="1688" rx="84" fill="#e2e7e3"/><circle cx="540" cy="620" r="278" fill="#33584d" opacity=".13"/><text x="540" y="730" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M220 1050h640" stroke="#33584d" stroke-width="16" opacity=".58"/><text x="540" y="1245" text-anchor="middle" font-size="62" font-weight="700" font-family="Arial,sans-serif" fill="#243f37">${headline}</text><text x="540" y="1365" text-anchor="middle" font-size="39" font-family="Arial,sans-serif" fill="#50675f">${sub}</text><text x="540" y="1545" text-anchor="middle" font-size="32" font-family="Arial,sans-serif" fill="#6a7d76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 04/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 04/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260904:RichMediaEntry[]=[
img('Papo de hoje',['se o dia de hoje virasse uma foto','virasse uma foto'],'📷','O DIA EM UMA FOTO','QUAL CENA FICARIA?','Arte editorial específica com câmera e moldura de fotografia para a pergunta do dia','https://www.gov.br/cultura/pt-br'),
img('Desafio do casal',['comida que nenhum dos dois pede','nenhum dos dois pede há muito tempo'],'🍽️','SAIAM DO AUTOMÁTICO','UMA COMIDA ESQUECIDA','Arte editorial específica com dois pratos e talheres para o desafio do casal','https://www.gov.br/saude/pt-br'),
img('Curiosidades',['grandes altitudes','ferver abaixo de 100'],'⛰️','ALTITUDE × EBULIÇÃO','PRESSÃO MUDA A TEMPERATURA','Arte educativa com montanha, panela e termômetro representando ebulição em altitude','https://www.usgs.gov/water-science-school/science/boiling-point-water-and-altitude'),
img('Curiosidades',['ponto cego natural','nervo óptico sai da retina'],'👁️','PONTO CEGO','RETINA + NERVO ÓPTICO','Arte educativa com olho e marcação do disco óptico','https://www.ncbi.nlm.nih.gov/books/NBK545310/'),
img('Curiosidades',['https pode criptografar','site em si não é confiável'],'🔒','HTTPS ≠ CONFIANÇA','CONEXÃO PROTEGIDA','Arte educativa com cadeado, navegador e aviso de confiança do site','https://developer.mozilla.org/en-US/docs/Glossary/HTTPS'),
img('Gravidez',['8 semanas + 5 dias','8s5d'],'🤰','8S5D','DESENVOLVIMENTO ACELERADO','Ilustração editorial abstrata referente a 8 semanas e 5 dias de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/8-weeks/'),
img('Ser Pai',['microdecisão logística','carga mental'],'✅','ASSUMA E RESOLVA','MENOS CARGA MENTAL','Arte editorial com checklist concluído e itens de rotina organizados','https://www.cdc.gov/hearher/'),
img('Brasil',['vale suspende por prazo indefinido','ipo da unidade de minerais críticos'],'⛏️','VALE BASE METALS','IPO SUSPENSO · REPORTAGEM','Arte editorial específica com mineração e documento de mercado representando a reportagem sobre a Vale Base Metals','https://www.reuters.com/world/americas/brazils-vale-drops-ipo-plans-critical-minerals-unit-globe-mail-reports-2026-09-04/'),
img('Mundo',['coreia do sul diz avaliar','navegação no estreito de hormuz'],'🚢','HORMUZ','SEUL AVALIA OPÇÕES','Arte editorial neutra com navio e estreito marítimo representando a declaração sul-coreana','https://www.reuters.com/world/asia-pacific/south-korea-reviewing-options-support-hormuz-navigation-official-says-2026-09-04/'),
img('Política',['tse prevê concluir hoje','lacração dos sistemas'],'🗳️','TSE · LACRAÇÃO','AGENDA · 04/09','Arte editorial específica com urna, assinatura digital e lacre para a agenda do TSE','https://www.tse.jus.br/comunicacao/noticias/2026/Agosto/comeca-hoje-31-cerimonia-de-compilacao-assinatura-digital-e-lacracao-dos-sistemas-das-eleicoes-2026'),
img('Tempo e Clima',['possibilidade de chuva isolada','alerta de tempestade'],'⛈️','SP · 04/09','CHUVA ISOLADA + ALERTA','Arte meteorológica específica com nuvens, chuva e símbolo de alerta para São Paulo','https://portal.inmet.gov.br/noticias/previs%C3%A3o-para-sexta-feira-04-e-s%C3%A1bado-05'),
img('Viagens',['passeio por bairro','três coisas próximas'],'🗺️','UM BAIRRO','TRÊS PARADAS PRÓXIMAS','Arte editorial com mapa compacto e três marcadores próximos','https://www.gov.br/turismo/pt-br'),
img('Música',['linha do baixo','acompanhe só a linha do baixo'],'🎸','SIGA O BAIXO','UMA CAMADA POR VEZ','Arte editorial com baixo elétrico e ondas sonoras em camadas','https://www.gov.br/cultura/pt-br'),
img('Finanças',['iene caminha para melhor semana','2,5% frente ao dólar'],'💴','IENE · SEMANA FORTE','~2,5% CONTRA O DÓLAR','Arte editorial específica com iene, dólar e gráfico semanal','https://www.reuters.com/world/asia-pacific/yen-headed-strongest-week-month-dollar-flat-ahead-payroll-data-2026-09-04/'),
img('Carros até R$ 70 mil',['piso irregular','trecho reto','carro até r$70 mil'],'🚗','ATÉ R$70 MIL','TESTE EM PISOS DIFERENTES','Arte editorial de carro usado em trecho reto e piso irregular para test-drive','https://www.gov.br/senatran/pt-br'),
img('Motos',['corrente, coroa e pinhão','relação gasta'],'🏍️','RELAÇÃO DA MOTO','CORRENTE + COROA + PINHÃO','Arte editorial de motocicleta com destaque para conjunto de transmissão final','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['viscosidade do óleo','especificação inteira'],'🛢️','ÓLEO DO MOTOR','VISCOSIDADE + HOMOLOGAÇÃO','Arte editorial com frasco de óleo e manual técnico destacando especificações','https://www.api.org/products-and-services/engine-oil')
];
