import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'MÍDIA REAL · 13/09',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260913:RichMediaEntry[]=[
img('Papo de hoje',['melhor compra pequena','custaram pouco'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Woman%20shops%20online%20with%20a%20small%20shopping%20cart%20and%20cash%20in%20a%20modern%20office%20setting%20during%20the%20afternoon.jpg','Pessoa fazendo uma pequena compra, com dinheiro e um carrinho de compras em miniatura ao lado do computador','Foto real · Shixart1985/Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Woman_shops_online_with_a_small_shopping_cart_and_cash_in_a_modern_office_setting_during_the_afternoon.jpg'),
img('Desafio do casal',['encontrem uma foto antiga','foto antiga que vocês gostam'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Facilities%20old%20vintage%20photo%20album.jpg','Álbum fotográfico antigo aberto com fotografias reais impressas','Foto real · U.S. Fish and Wildlife Service/Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Facilities_old_vintage_photo_album.jpg'),
img('Curiosidades',['tubarões percebem campos elétricos','ampolas de lorenzini'],'https://cf-images.us-east-1.prod.boltdns.net/v1/static/659677166001/dd188186-7589-4c0b-8d9a-95cd7d628fe2/94828f1c-51ec-4990-8865-4ea0abf8537b/1280x720/match/image.jpg','Tubarão nadando diante de equipamento de pesquisa subaquática da NOAA','Foto real · NOAA Fisheries','https://videos.fisheries.noaa.gov/detail/video/5637096261001/underwater-camera-research---northwestern-hawaiian-islands-sharks_clipped'),
img('Curiosidades',['fontes hidrotermais podem passar de 340','não ferve'],'https://www.pmel.noaa.gov/eoi/sites/default/files/styles/home_block_images/public/thumbnails/image/FK171110-Lau-blacksmoker.jpg?itok=hj2N09S4','Fonte hidrotermal black smoker no fundo do oceano','Foto real · NOAA/PMEL','https://www.pmel.noaa.gov/eoi/news-story/underwater-fire-exploring-tongas-submarine-volcanoes'),
img('Curiosidades',['pôr do sol em marte pode parecer azul','pôr do sol marciano'],'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia19/pia19400/PIA19400.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1080&w=1344','Pôr do sol azulado fotografado pelo rover Curiosity em Marte','Foto real · NASA/JPL-Caltech/MSSS/Texas A&M','https://science.nasa.gov/photojournal/sunset-in-mars-gale-crater/'),
img('Curiosidades',['aurora nasce quando partículas carregadas','gases da atmosfera brilham'],'https://svs.gsfc.nasa.gov/vis/a030000/a030100/a030179/frames/4256x2832_3x2_30p/ISS029-E-5890.jpg','Aurora verde e vermelha fotografada da Estação Espacial Internacional','Foto real · NASA Scientific Visualization Studio','https://science.nasa.gov/sun/the-atmosphere-after-dark/'),
img('Curiosidades',['fibra óptica guia luz','reflexão interna total'],'https://www.batiactu.com/images/auto/620-465-c/20240603_174826_rouleau-fibre-optique-istock-richard-villalon.jpg','Bobina real de cabo de fibra óptica','Foto real · Batiactu','https://www.batiactu.com/edito/sabotages-sur-fibre-un-appel-a-repenser-resilience-69166.php'),
img('Gravidez',['10 semanas completas','10s0d'],'https://upload.wikimedia.org/wikipedia/commons/1/1b/10_Weeks_Fetus.JPG','Ultrassom real do primeiro trimestre compatível com 10 semanas de gestação','Foto real · Wikimedia Commons · CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:10_Weeks_Fetus.JPG'),
img('Ser Pai',['30 minutos de descanso','proteja meia hora'],'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg','Pessoa oferecendo apoio prático a uma gestante','Foto real · CDC Hear Her','https://www.cdc.gov/hearher/support-family-friends/index.html'),
img('Mundo',['alerta em vilnius era um bando de aves','bando de aves','aeroporto reabre após 38 minutos','otan aciona caça','šiauliai'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Romanian%20F-16%20at%20%C5%A0iauliai%20Air%20Base%2C%20Lithuania.jpg','Caça F-16 decolando da Base Aérea de Šiauliai, na Lituânia, durante missão de policiamento aéreo da OTAN','Foto real · NATO Allied Air Command/Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Romanian_F-16_at_%C5%A0iauliai_Air_Base%2C_Lithuania.jpg'),
img('Política',['prestação de contas parcial','prazo termina neste domingo'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Sede_do_Tribunal_Superior_Eleitoral%2C_em_Bras%C3%ADlia.jpg/1280px-Sede_do_Tribunal_Superior_Eleitoral%2C_em_Bras%C3%ADlia.jpg','Sede do Tribunal Superior Eleitoral em Brasília','Foto real · Alexandresena/Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Sede_do_Tribunal_Superior_Eleitoral,_em_Bras%C3%ADlia.jpg'),
img('Tempo e Clima',['domingo segue com chuva','grande são paulo entra no domingo sob alerta','alerta para tempestades','temperatura mais baixa'],'https://f.i.uol.com.br/fotografia/2026/09/12/17892626576aa5fb41c09b1_1789262657_3x2_md.jpg','Rio Tietê cheio após as chuvas que antecederam o alerta de tempestades mantido para este domingo em São Paulo','Foto real · Allison Sales/Folhapress · publicada na matéria de 13/09/2026','https://www1.folha.uol.com.br/cotidiano/2026/09/sao-paulo-segue-em-alerta-de-perigo-para-tempestades-neste-domingo-13.shtml'),
img('Corinthians',['corinthians confirma time misto','escalação confirmada','flamengo no maracanã','hugo souza','pedro milans'],'https://conteudo.imguol.com.br/c/esporte/7e/2026/04/09/plata-voltou-a-ser-titular-na-vitoria-do-flamengo-por-2-a-0-sobre-o-cusco-1775766195842_v2_450x600.jpg','Gonzalo Plata, titular do Flamengo no confronto deste domingo contra o Corinthians no Maracanã','Foto real · Gilvan de Souza/Flamengo · usada pela reportagem de escalações publicada em 13/09/2026','https://www.uol.com.br/esporte/futebol/ultimas-noticias/2026/09/13/flamengo-corinthians-escalacoes-brasileiro.ghtm'),
img('Viagens',['condição da estrada antes de sair','rodovia antes de sair'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/RodBandeirantes.jpg/960px-RodBandeirantes.jpg','Trecho real da Rodovia dos Bandeirantes em São Paulo','Foto real · Ana Paula Hirama/Wikimedia Commons · CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:RodBandeirantes.jpg'),
img('Música',['canção com duas vozes','duas vozes','participação de dois artistas'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Musicians_perform_on_stage_during_live_concert.jpg/960px-Musicians_perform_on_stage_during_live_concert.jpg','Três músicos tocando juntos em uma apresentação ao vivo','Foto real · Shixart1985/Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Musicians_perform_on_stage_during_live_concert.jpg'),
img('Tecnologia',['trump minimiza temores sobre ia','liderança dos eua sobre a china','salvaguardas podem existir'],'https://dims.apnews.com/dims4/default/e1ead2d/2147483647/strip/true/crop/3682x2454%2B0%2B0/resize/599x399%21/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2F57%2F21%2Fc5e283a68f946efe13317f5883df%2F271278e8438a4e5f8e7bff66ffda8323','Donald Trump durante o Irish Open em Doonbeg, Irlanda, neste domingo, 13 de setembro de 2026','Foto real · AP/Julia Demaree Nikhinson · 13/09/2026','https://apnews.com/article/russia-ukraine-war-drones-odesa-refinery-border-crossing-17bb6a0401abc3eaa7d4586150a41d7d'),
img('Carros até R$ 70 mil',['código dot','idade real dos pneus'],'https://static.delti.com/static/rduk/media/tyre_DOT_number.jpg','Close real do código DOT gravado na lateral de um pneu','Foto real · ReifenDirekt','https://www.reifendirekt.de/blog/reifen-dot-code-bedeutung.html'),
img('Motos',['corrente e coroa','folga da corrente'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Motorcycle_chain.jpg/330px-Motorcycle_chain.jpg','Corrente metálica de motocicleta em close','Foto real · sutulo/Wikimedia Commons · CC0','https://commons.wikimedia.org/wiki/File:Motorcycle_chain.jpg'),
img('Mecânica',['fluido de freio','reservatório do fluido'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Brake_fluid_reservoir_in_%C5%A0koda_Fabia_I.jpg/960px-Brake_fluid_reservoir_in_%C5%A0koda_Fabia_I.jpg','Reservatório real de fluido de freio no cofre do motor','Foto real · Frettie/Wikimedia Commons · CC BY 3.0','https://commons.wikimedia.org/wiki/File:Brake_fluid_reservoir_in_%C5%A0koda_Fabia_I.jpg')
];
