import type {RichMediaEntry} from './rich-media';
export const dailyRichMedia20260830:RichMediaEntry[]=[
{label:'Curiosidades',matches:['céu fica azul','moléculas do ar espalham'],tag:'ILUSTRAÇÃO CIENTÍFICA',title:'Espalhamento da luz',caption:'Luz solar atravessando a atmosfera.',images:[{url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rayleigh_scattering.svg',alt:'Diagrama educativo de espalhamento Rayleigh da luz',caption:'Espalhamento Rayleigh.',credit:'Wikimedia Commons',sourceUrl:'https://spaceplace.nasa.gov/blue-sky/en/',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['ponto cego real','nervo óptico'],tag:'ILUSTRAÇÃO CIENTÍFICA',title:'Ponto cego do olho',caption:'Diagrama do ponto cego.',images:[{url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Eye%20blind%20spot.svg',alt:'Diagrama educativo do ponto cego do olho humano',caption:'Ponto cego.',credit:'Wikimedia Commons',sourceUrl:'https://www.nei.nih.gov/learn-about-eye-health/healthy-vision/how-eyes-work',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['qr code pode continuar','reed–solomon','reed-solomon'],tag:'ILUSTRAÇÃO TECNOLÓGICA',title:'QR Code e correção de erros',caption:'QR Code ilustrativo.',images:[{url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/QR_Code_Structure_Example_3.svg',alt:'Diagrama educativo da estrutura de um QR Code',caption:'Estrutura de QR Code.',credit:'Wikimedia Commons',sourceUrl:'https://www.qrcode.com/en/about/error_correction.html',kind:'REFERENCE'}]},
{label:'Mundo',matches:['bancos centrais europeus','turbulência na relação financeira'],tag:'ARTE ESPECÍFICA · FINANÇAS GLOBAIS',title:'Relações financeiras transatlânticas',caption:'Arte editorial específica sobre Europa, EUA, liquidez e previsibilidade.',images:[{url:'/generated/finance-transatlantic-20260830.svg',alt:'Arte editorial com Europa e Estados Unidos conectados por fluxos financeiros',caption:'Relações financeiras transatlânticas.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.reuters.com/business/finance/europes-central-bankers-fear-more-turbulence-testy-us-relations-2026-08-30/',kind:'REFERENCE'}]},
{label:'Finanças',matches:['previsibilidade dos eua','europa coloca previsibilidade'],tag:'ARTE ESPECÍFICA · MERCADOS',title:'Mercados globais e previsibilidade',caption:'Arte editorial específica sobre euro, dólar e confiança institucional.',images:[{url:'/generated/finance-transatlantic-20260830.svg',alt:'Arte editorial com euro e dólar em contexto de relações financeiras transatlânticas',caption:'Mercados globais.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.reuters.com/business/finance/europes-central-bankers-fear-more-turbulence-testy-us-relations-2026-08-30/',kind:'REFERENCE'}]},
{label:'Tempo e Clima',matches:['são paulo tem domingo quente','domingo quente e seco'],tag:'FOTO RELACIONADA',title:'São Paulo quente e seco',caption:'Vista urbana de São Paulo.',images:[{url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bairro%20dos%20jardins%20em%20s%C3%A3o%20paulo.jpg',alt:'Vista urbana da cidade de São Paulo',caption:'São Paulo.',credit:'Wikimedia Commons',sourceUrl:'https://www1.folha.uol.com.br/cotidiano/2026/08/tempo-em-sp-continua-abafado-com-sol-entre-nuvens-neste-domingo-30.shtml',kind:'REFERENCE'}]},
{label:'Corinthians',matches:['corinthians recebe o santos','corinthians x santos'],tag:'FOTO RELACIONADA',title:'Corinthians x Santos',caption:'Neo Química Arena.',images:[{url:'https://s2-cbn.glbimg.com/P_wXvQ-Ks8UHdDwWGCCglRTv52A=/1200x/smart/filters:cover()/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_d975fad146a14bbfad9e763717b09688/internal_photos/bs/2024/z/7/dl7DuXRIuwuFzGi0fAaQ/corinthian.png',alt:'Neo Química Arena do Corinthians',caption:'Neo Química Arena.',credit:'CBN/Globo',sourceUrl:'https://ge.globo.com/sp/futebol/brasileirao-serie-a/noticia/2026/08/30/corinthians-x-santos-onde-assistir-ao-vivo-horario-e-escalacoes.ghtml',kind:'REFERENCE'}]},
{label:'Games',matches:['gamescom 2026 chega ao último dia'],tag:'FOTO RELACIONADA',title:'gamescom 2026',caption:'gamescom em Colônia.',images:[{url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Gamescom_logo.svg',alt:'Logotipo da gamescom',caption:'gamescom.',credit:'Wikimedia Commons',sourceUrl:'https://www.gamescom.global/en',kind:'REFERENCE'}]},
{label:'Gravidez',matches:['8 semanas hoje'],tag:'ILUSTRAÇÃO EDUCATIVA',title:'8 semanas',caption:'Ilustração educativa do desenvolvimento embrionário.',images:[{url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Embryo%20at%206%20weeks.JPG',alt:'Ilustração educativa de embrião em fase inicial',caption:'Ilustração educativa.',credit:'Wikimedia Commons',sourceUrl:'https://www.nhs.uk/pregnancy/week-by-week/1-to-12/8-weeks/',kind:'REFERENCE'}]},
{label:'Ser Pai',matches:['missão de hoje'],tag:'FOTO RELACIONADA',title:'Apoio na gestação',caption:'Apoio familiar.',images:[{url:'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg',alt:'Casal em momento de apoio',caption:'Apoio durante a gestação.',credit:'CDC',sourceUrl:'https://www.cdc.gov/hearher/',kind:'REFERENCE'}]},
{label:'Viagens',matches:['domingo de passeio'],tag:'FOTO RELACIONADA',title:'Passeio de domingo',caption:'Passeio tranquilo.',images:[{url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Holambra%20windmill.jpg',alt:'Paisagem de passeio ao ar livre',caption:'Passeio ao ar livre.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/',kind:'REFERENCE'}]},
{label:'Música',matches:['domingo musical'],tag:'FOTO RELACIONADA',title:'Ouvir um álbum inteiro',caption:'Experiência musical.',images:[{url:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Headphones_1.jpg',alt:'Fones de ouvido para escutar música',caption:'Música.',credit:'Wikimedia Commons',sourceUrl:'https://commons.wikimedia.org/',kind:'REFERENCE'}]}
];
