import { dailyContent, edition, todayDrops } from './daily-content';
import { wordOfDay, upcomingWords } from './word-of-day';
import { regionalWords } from './regional-vocabulary';
import { rockTracks, caipiraTracks } from './music-content';
import { politicsTracker, presidentialProfiles, spGovernorProfiles, spSenateProfiles } from './politics-2026';

Object.assign(edition, { date:'18/08/2026', dateLabel:'18 AGO 2026', title:'Daily Intelligence · 18 de agosto' });

const set=(slug:string,data:any)=>Object.assign(dailyContent[slug],data);
const moveTrackToFront=(tracks:any[], artist:string, title:string)=>{ const index=tracks.findIndex((track)=>track.artist===artist&&track.title===title); if(index>0){ const [track]=tracks.splice(index,1); tracks.unshift(track); } };

moveTrackToFront(rockTracks,'Audioslave','Like a Stone');
moveTrackToFront(caipiraTracks,'Tonico & Tinoco','Tristeza do Jeca');

Object.assign(wordOfDay,{ word:'Escorreito', pronunciation:'es-cor-REI-to', meaning:'Correto, bem formulado, sem falhas evidentes ou desvios.', naturalUse:'“O relatório ficou escorreito: objetivo, consistente e sem contradições.”', synonyms:['correto','apurado','irrepreensível'], tone:'Mais formal e menos comum, útil para elogiar texto, conduta ou execução bem feita.', note:'Não significa “sofisticado”; a ideia central é correção e ausência de defeitos relevantes.' });
upcomingWords.splice(0,upcomingWords.length,{word:'Díspar',hint:'Muito diferente ou desigual em relação a outro.'},{word:'Sopesar',hint:'Avaliar pesos, consequências ou argumentos antes de decidir.'},{word:'Perenne',hint:'Duradouro, contínuo, que permanece.'},{word:'Contingente',hint:'Que pode ou não ocorrer; dependente de circunstâncias.'});
const mineiro=regionalWords.find((item)=>item.id==='mineiro');
if(mineiro) Object.assign(mineiro,{word:'Pelejar',pronunciation:'pe-le-JAR',meaning:'Insistir, batalhar ou se esforçar bastante para resolver alguma coisa.',naturalUse:'“Pelejei com aquele parafuso até ele soltar.”',equivalent:'batalhar · insistir · se esforçar',nuance:'É comum no interior e em Minas, mas também aparece em outras regiões; funciona muito bem para esforço teimoso ou prolongado.',note:'Pode ser literal ou figurado: pelejar com uma tarefa, um problema ou uma situação.',upcoming:['Cismado','Custoso','Arredar','Uai','Sô','Tiquim']});
const portugal=regionalWords.find((item)=>item.id==='portugal');
if(portugal) Object.assign(portugal,{word:'Peúgas',pronunciation:'PEU-gas',meaning:'Meias, especialmente as usadas nos pés dentro de sapatos.',naturalUse:'“Leva umas peúgas mais quentes porque à noite vai arrefecer.”',equivalent:'meias',nuance:'É uma palavra perfeitamente cotidiana em Portugal e pode soar curiosa para brasileiros por quase não ser usada com esse sentido no Brasil.',note:'Em português europeu, “meias” também existe; “peúgas” é uma alternativa comum para socks.',upcoming:['Autocarro','Telemóvel','Pequeno-almoço','Esplanada','Fato','Fixe']});

Object.assign(politicsTracker,{updatedAt:'18/08/2026 · 05h',notice:'Hoje é a data do calendário eleitoral usada para levantar o total nacional de candidaturas constantes dos RRC e RRCI para aferir percentuais mínimos de repasse do FEFC na prestação de contas, incluindo pedidos recebidos e aceitos até 23h59. Isso é uma fotografia estatística/financeira e não significa deferimento coletivo de candidaturas. A situação jurídica individual continua no DivulgaCandContas.'});
[...presidentialProfiles,...spGovernorProfiles,...spSenateProfiles].forEach((profile)=>{ profile.status='Pós-registro: situação jurídica individual deve ser conferida no DivulgaCandContas; a fotografia nacional de 18/08 para cálculo de percentuais do FEFC não equivale a deferimento.'; profile.sourceLabel='TSE · DivulgaCandContas'; profile.sourceUrl='https://divulgacandcontas.tse.jus.br/divulga/#/'; });

todayDrops.splice(0,todayDrops.length,
 {slug:'brasil',label:'Brasil',emoji:'🇧🇷',title:'BC PROTEGE+: uma trava contra abertura fraudulenta de conta em seu nome',detail:'O serviço do Banco Central permite sinalizar que você não quer novas contas ou inclusão como titular/representante e pode ser ativado no Meu BC.'},
 {slug:'politica',label:'Política',emoji:'🏛️',title:'18 de agosto: fotografia das candidaturas entra no cálculo do FEFC',detail:'O TSE usa o total de pedidos recebidos e aceitos até 23h59 para aferir percentuais mínimos de repasse; isso não equivale a deferimento coletivo.'},
 {slug:'mundo',label:'Mundo',emoji:'🌍',title:'Brent volta a US$ 91,76 com paz EUA–Irã mais distante e Hormuz sob risco',detail:'Petróleo sobe pelo terceiro pregão; diplomacia enfraquece e o tráfego no estreito segue severamente limitado.'},
 {slug:'planeta',label:'Planeta',emoji:'🧭',title:'A bússola quase nunca aponta exatamente para o norte geográfico',detail:'Declinação magnética muda com lugar e tempo porque o campo terrestre não é um dipolo perfeito alinhado ao eixo de rotação.'},
 {slug:'animais',label:'Mundo Animal',emoji:'🕊️',title:'Pombos, céu nublado e um “compasso” magnético em um lugar inesperado',detail:'Estudo de 2026 encontrou macrófagos superparamagnéticos no fígado associados à orientação quando o Sol não está visível; o mecanismo ainda pede confirmação adicional.'},
 {slug:'tempo',label:'Tempo e Clima',emoji:'☀️',title:'São Paulo entra em terça de calor crescente e ar seco',detail:'A capital está numa sequência de aquecimento que pode levar a máxima semanal perto de 34°C; hidratação e baixa umidade seguem no radar.'},
 {slug:'curiosidades',label:'Curiosidades',emoji:'🪞',title:'O espelho não troca esquerda e direita: ele inverte frente e trás',detail:'A sensação de “lado trocado” nasce da forma como imaginamos girar o próprio corpo para ocupar a posição da imagem.'},
 {slug:'musica',label:'Música',emoji:'🎵',title:'Audioslave no rock; Tristeza do Jeca na memória caipira',detail:'Like a Stone abre o arquivo Rock; Tonico & Tinoco conduzem a trilha raiz. Players e catálogos continuam totalmente separados.'},
 {slug:'games',label:'Games',emoji:'🎮',title:'PS5 Radar: Marvel’s Wolverine chega em 15 de setembro',detail:'Insomniac confirmou data, trailer de história, The Hand, Deathstrike, Jean Grey, compositor e pré-venda; qualidade final ainda depende do jogo entregue.'},
 {slug:'gravidez',label:'Gravidez',emoji:'🤰',title:'6 semanas + 2 dias: fadiga e idas frequentes ao banheiro podem ganhar força',detail:'Hormônios e mudanças circulatórias já podem mexer bastante com energia e rotina; sintomas variam muito entre gestantes.'},
 {slug:'pai',label:'Ser Pai',emoji:'👨‍🍼',title:'Missão de hoje: assuma uma tarefa fixa e retire uma decisão da rotina dela',detail:'Escolha uma responsabilidade diária — louça, jantar, gatos, compras ou organização — e cuide dela sem precisar ser lembrado.'},
 {slug:'carros',label:'Carros',emoji:'🚗',title:'Radar >1.0 até R$ 70 mil: Cruze, Sentra, 2008 e Fiesta',detail:'Quatro usados de propostas diferentes, todos com FIPE e média nacional de agosto/2026 dentro do teto da curadoria.'},
 {slug:'motos',label:'Motos',emoji:'🏍️',title:'Radar novo: Twister, Himalayan, G 310 R e NC 750X',detail:'Street, trail, naked premium e touring com FIPE, média nacional, faixa observada e checklist específico.'},
 {slug:'mecanica',label:'Mecânica',emoji:'🔉',title:'Rolamento de roda ou pneu? O ruído muda quando a carga lateral muda',detail:'Um ronco que cresce com velocidade e muda em curvas pode apontar rolamento, mas desgaste serrilhado do pneu consegue imitar o sintoma.'},
 {slug:'nautica',label:'Náutica',emoji:'⚙️',title:'Ânodo de sacrifício: a peça que “aceita corroer” para proteger metais do barco',detail:'Zinco, alumínio ou magnésio precisam ser escolhidos conforme ambiente e sistema; pintar o ânodo destrói sua função.'},
 {slug:'viagens',label:'Viagens',emoji:'🌷',title:'Expoflora 2026: Holambra entra na reta final de planejamento',detail:'Evento começa em 28/08; lote atual vai até 19/08, com preços oficiais, estacionamento e extras já publicados.'},
 {slug:'financas',label:'Finanças',emoji:'💰',title:'Juro longo dos EUA em 5,327%: por que petróleo e dívida podem pesar mesmo sem alta imediata do Fed',detail:'O Treasury de 30 anos atingiu o maior nível desde 2007 enquanto energia e risco fiscal mantêm prêmio de prazo elevado.'},
 {slug:'tecnologia',label:'Tecnologia',emoji:'🧠',title:'NPU e TOPS: por que “40 trilhões de operações” não conta a história inteira de um AI PC',detail:'Copilot+ PCs usam NPUs de 40+ TOPS, mas desempenho real também depende de modelo, memória, runtime, precisão e software.'},
 {slug:'seguranca',label:'Cyber',emoji:'🛡️',title:'The Gentlemen: ransomware que tenta se propagar pela rede em paralelo',detail:'A Microsoft descreve um RaaS em Go com múltiplas técnicas simultâneas de movimento lateral, criptografia e dupla extorsão.'},
 {slug:'appsec-ssdlc',label:'AppSec',emoji:'🧬',title:'API4: recurso sem limite também é vulnerabilidade — e pode virar uma conta enorme',detail:'Rate limit sozinho não basta: tamanho de payload, paginação, batching, timeout, memória e gastos com terceiros também precisam de teto.'}
);

set('hoje',{title:'20 missões novas para terça-feira, 18 de agosto',summary:'A edição-base de hoje troca todos os assuntos: proteção financeira, calendário eleitoral, petróleo e juros longos, magnetismo, ciência animal, PS5, gestação 6s+2d, novos radares de veículos, viagem, tecnologia e segurança.',shareSummary:'Bom dia: a edição de 18/08 traz 20 missões novas, incluindo BC PROTEGE+, petróleo acima de US$ 91, PS5 Radar com Wolverine, novos carros/motos e leituras novas de Cyber e AppSec.',readTime:'20 MISSÕES',badge:'05H BASE EDITION',sections:[]});

set('brasil',{title:'BC PROTEGE+: uma trava simples contra conta aberta por fraude de identidade',summary:'O Banco Central permite ativar no Meu BC uma proteção que sinaliza às instituições que você não quer abertura de nova conta nem inclusão como titular ou representante. A ativação exige conta gov.br prata ou ouro com verificação em duas etapas e pode ser revertida quando você realmente quiser abrir uma conta.',shareSummary:'Brasil: BC PROTEGE+ funciona como uma trava preventiva contra abertura indevida de conta em seu CPF. Ative no Meu BC; quando precisar abrir uma conta de verdade, você pode desativar e reativar.',readTime:'7 MIN READ',badge:'BRASIL / ANTIFRAUDE',stats:[{label:'CUSTO',value:'GRÁTIS'},{label:'ACESSO',value:'MEU BC'},{label:'GOV.BR',value:'PRATA/OURO + 2FA'}],sections:[{title:'O que ele impede',paragraphs:['Com a proteção ativa, instituições participantes devem consultar o sinal antes de abrir nova conta ou incluir você como titular/representante. É uma camada preventiva contra fraude de identidade, não uma garantia absoluta contra todo tipo de golpe.']},{title:'Como usar sem travar sua própria vida',bullets:['Ative a proteção quando não estiver abrindo conta.','Se for abrir uma conta legítima, desative no Meu BC durante a jornada e reative depois.','Guarde o histórico de ativações como evidência.']},{title:'Se algo passar mesmo assim',paragraphs:['O próprio BC orienta procurar primeiro a Ouvidoria da instituição e pedir encerramento imediato. Se persistir, registre reclamação no Banco Central e em órgãos de defesa do consumidor, anexando o histórico de ativações.']}],sources:[{label:'Banco Central · ativar BC PROTEGE+',url:'https://www.bcb.gov.br/meubc/faqs/p/como-ativo-a-protecao-para-o-meu-cpf-pessoa-fisica'},{label:'Banco Central · conta aberta apesar da proteção',url:'https://www.bcb.gov.br/meubc/faqs/p/o-que-fazer-se-uma-conta-bancaria-foi-aberta-mesmo-com-o-bc-protege-ativado'}]});

set('politica',{title:'18 de agosto: a fotografia nacional de candidaturas entra na matemática do financiamento eleitoral',summary:'O calendário do TSE define hoje como a data para levantar o total de candidaturas constantes dos pedidos coletivos e individuais no país, incluindo pedidos recebidos e aceitos até 23h59. Esse número serve para aferir percentuais mínimos de repasse do FEFC na prestação de contas — não para declarar todas as candidaturas deferidas.',shareSummary:'Política: 18/08 é uma data técnica do calendário eleitoral. O total de pedidos recebidos e aceitos até 23h59 entra na aferição dos percentuais mínimos do FEFC. Isso não significa deferimento automático; status jurídico continua no DivulgaCandContas.',readTime:'9 MIN READ',badge:'POLÍTICA / FEFC',stats:[{label:'DATA-BASE',value:'18/08'},{label:'CORTE',value:'23H59'},{label:'EFEITO',value:'PERCENTUAIS FEFC'}],sections:[{title:'O que acontece hoje',paragraphs:['O TSE usa o total nacional de candidaturas constantes dos RRC/RRCI, incluindo pedidos recebidos e aceitos até 23h59, como base estatística para aferir percentuais mínimos de repasse de recursos do Fundo Especial de Financiamento de Campanha na prestação de contas.']},{title:'Impacto na vida real',paragraphs:['Para o cidadão e contribuinte, a importância está na transparência do uso de dinheiro público de campanha: o número de candidaturas ajuda a definir critérios mínimos de distribuição. Isso não muda seu salário ou imposto hoje, mas influencia como recursos eleitorais públicos são repartidos e depois fiscalizados.'],bullets:['Eleitor: não confunda fotografia estatística com candidatura deferida.','Contribuinte: acompanhe receitas e despesas no DivulgaCandContas.','Cidadão: compare promessa, status jurídico e financiamento em fontes diferentes.']},{title:'Próximo checkpoint',paragraphs:['Em 20 de agosto termina o prazo para alguns pedidos ligados a voto em seção distinta da origem, incluindo voto em trânsito. O calendário oficial deve ser a referência para prazos.']}],sources:[{label:'TSE · Calendário Eleitoral 2026',url:'https://www.tse.jus.br/eleicoes/calendario-eleitoral/calendario-eleitoral'},{label:'TSE · Resolução 23.760/2026',url:'https://www.tse.jus.br/legislacao/compilada/res/2026/resolucao-no-23-760-de-2-de-marco-de-2026'},{label:'TSE · DivulgaCandContas',url:'https://divulgacandcontas.tse.jus.br/divulga/#/'}]});

set('mundo',{title:'Petróleo sobe pelo terceiro dia e Brent chega a US$ 91,76 com diplomacia EUA–Irã enfraquecida',summary:'O Brent avançava a US$ 91,76 por barril nesta manhã, maior nível desde 30 de julho, enquanto o WTI chegava a US$ 85,55. O movimento acompanha o enfraquecimento das perspectivas de acordo entre EUA e Irã e o tráfego de petroleiros ainda severamente limitado no Estreito de Hormuz.',shareSummary:'Mundo: Brent chega a US$ 91,76 com paz EUA–Irã mais distante e Hormuz ainda restrito. É um choque de risco de oferta: o preço pode mudar rápido se diplomacia ou fluxo marítimo mudarem.',readTime:'8 MIN READ',badge:'GLOBAL / ENERGY',stats:[{label:'BRENT',value:'US$ 91,76'},{label:'WTI',value:'US$ 85,55'},{label:'SESSÃO',value:'3ª ALTA'}],sections:[{title:'O que mudou',paragraphs:['As esperanças de um acordo de paz de curto prazo perderam força e o mercado voltou a precificar risco de interrupção de oferta. O Estreito de Hormuz permanece como ponto crítico porque o tráfego de petroleiros continua muito abaixo do normal.']},{title:'O que chega à vida real',bullets:['Petróleo mais caro pode pressionar combustíveis e frete, mas o repasse não é automático nem imediato.','Energia cara pode complicar inflação e juros em vários países.','Uma melhora diplomática pode derrubar o prêmio de risco rapidamente; por isso, preço de hoje não é previsão de preço futuro.']}],sources:[{label:'Reuters · petróleo e EUA–Irã · 18/08/2026',url:'https://www.reuters.com/business/energy/oil-climbs-fading-us-iran-peace-hopes-raise-supply-risks-2026-08-18/'}]});

set('planeta',{title:'Norte magnético não é norte geográfico: a diferença que a bússola precisa corrigir',summary:'A agulha da bússola se alinha ao campo magnético local, não diretamente ao eixo de rotação da Terra. Como o campo não é perfeitamente dipolar nem alinhado, surge a declinação magnética — um ângulo que muda com localização e tempo.',shareSummary:'Planeta: bússola não aponta necessariamente para o norte verdadeiro. A diferença é a declinação magnética, que varia conforme lugar e tempo porque o campo terrestre é complexo e dinâmico.',readTime:'7 MIN READ',badge:'PLANETA / GEOMAGNETISMO',stats:[{label:'CAMPO SUPERFICIAL',value:'30–60 μT'},{label:'EIXO MAGNÉTICO',value:'~10°'},{label:'CORREÇÃO',value:'DECLINAÇÃO'}],sections:[{title:'De onde vem o campo',paragraphs:['Movimentos do material condutor no núcleo externo sustentam o geodínamo. Na superfície, o campo é aproximadamente dipolar, mas contém componentes não dipolares importantes.']},{title:'Por que isso importa na navegação',paragraphs:['Mapa e GPS normalmente usam norte verdadeiro; a bússola entrega norte magnético. Para navegação precisa, a declinação local precisa ser conhecida e atualizada.']},{title:'Conexão inesperada',paragraphs:['A mesma estrutura física que obriga navegadores a corrigir a bússola é uma das pistas usadas por animais que conseguem orientação magnética.']}],sources:[{label:'USGS · Introduction to Geomagnetism',url:'https://www.usgs.gov/programs/geomagnetism/introduction-geomagnetism'},{label:'USGS · What is declination?',url:'https://www.usgs.gov/faqs/what-declination?page=1'}]});

set('animais',{title:'Pombos-correio podem recorrer a células magnéticas no fígado quando o céu fecha',summary:'Um estudo publicado na Science em 2026 identificou macrófagos superparamagnéticos no fígado de pombos. Quando essas células foram temporariamente reduzidas, a orientação piorou em condições nubladas, mas não quando o Sol estava visível. Os autores propõem participação na orientação magnética, embora a magnetorrecepção continue sendo uma área com mecanismos em investigação.',shareSummary:'Mundo Animal: estudo de 2026 encontrou células ricas em propriedades magnéticas no fígado de pombos associadas à orientação sob céu nublado. É uma pista forte, não uma explicação final para toda magnetorrecepção animal.',readTime:'8 MIN READ',badge:'WILDLIFE / NAVIGATION',sections:[{title:'O experimento',paragraphs:['Os pesquisadores procuraram propriedades magnéticas em diferentes tecidos e encontraram resposta superparamagnética relevante em fígado e baço. Depois testaram orientação em voo com e sem os macrófagos-alvo.']},{title:'A pista mais interessante',paragraphs:['Sob céu nublado, aves com macrófagos reduzidos perderam a orientação usual; com Sol visível, o desempenho permaneceu. Isso sugere redundância de pistas — solar quando disponível e magnética em condições difíceis.']},{title:'O que ainda não sabemos',paragraphs:['O estudo propõe um mecanismo físico, mas a transmissão exata do sinal ao sistema nervoso e a relação com outras hipóteses de magnetorrecepção ainda precisam de investigação.']}],sources:[{label:'Science · homing pigeon navigation · 28/05/2026',url:'https://doi.org/10.1126/science.ady2486'},{label:'PubMed · registro do estudo',url:'https://pubmed.ncbi.nlm.nih.gov/42207892/'}]});

set('tempo',{title:'São Paulo aquece durante a semana: calor e baixa umidade continuam no centro da previsão',summary:'A capital entra na terça-feira dentro de uma sequência de aquecimento e tempo seco. A previsão divulgada na segunda aponta elevação gradual das máximas ao longo da semana, podendo chegar perto de 34°C na quinta-feira, com baixa umidade e ausência de chuva como principais pontos de atenção.',shareSummary:'Tempo SP: semana segue aquecendo e a capital pode chegar perto de 34°C na quinta. Até lá, calor, baixa umidade e ausência de chuva pedem hidratação e cuidado no período mais quente.',readTime:'5 MIN READ',badge:'TEMPO / SP',stats:[{label:'TENDÊNCIA',value:'AQUECIMENTO'},{label:'PICO SEMANAL',value:'~34°C'},{label:'RISCO',value:'AR SECO'}],sections:[{title:'O padrão atmosférico',paragraphs:['Uma área de alta pressão favorece subsidência do ar, pouca nebulosidade e bloqueio à entrada de sistemas mais frios, elevando temperaturas e reduzindo umidade.']},{title:'Aplicação prática',bullets:['Hidrate-se ao longo do dia, não apenas quando sentir sede.','Evite exercício intenso no pico de calor e umidade baixa.','Atenção extra com crianças, idosos, pessoas com alergias/doenças respiratórias e animais.','Não use fogo para limpeza de terreno ou vegetação seca.']}],sources:[{label:'Folha / Inmet · calor e tempo seco em SP · 17/08/2026',url:'https://www1.folha.uol.com.br/cotidiano/2026/08/cidade-de-sao-paulo-deve-ter-calor-de-ate-34c-e-tempo-seco-ao-longo-da-semana.shtml'}]});

set('curiosidades',{title:'Espelho não troca esquerda por direita — nós é que imaginamos a rotação errada',summary:'Um espelho plano inverte o eixo perpendicular à sua superfície: o que estava à frente aparece “atrás” do plano. A sensação de esquerda/direita trocadas surge porque mentalmente comparamos a imagem com uma pessoa que teria girado 180° para ficar de frente para nós.',shareSummary:'Curiosidade: espelho não inverte esquerda e direita; ele inverte frente e trás. O cérebro cria a sensação lateral quando imagina uma rotação para comparar você com o reflexo.',readTime:'5 MIN READ',badge:'CURIOSIDADE / ÓPTICA',sections:[{title:'Teste simples',paragraphs:['Levante a mão direita: a imagem levanta a mão que está do mesmo lado do espelho que sua mão direita. O que muda é a coordenada para frente/para trás em relação ao plano refletor.']},{title:'Por que letras parecem “invertidas”',paragraphs:['Uma palavra escrita na camiseta está orientada para fora do seu corpo. No reflexo, essa direção frente/trás muda, e a leitura fica espelhada.']},{title:'A pegadinha mental',paragraphs:['Quando imaginamos outra pessoa de frente para nós, pressupomos que ela girou. A rotação troca os lados relativos — o espelho não realizou essa rotação.']}],sources:[]});

set('musica',{title:'Like a Stone + Tristeza do Jeca: peso moderno e saudade rural em dois arquivos separados',summary:'O Rock abre com Audioslave e a construção paciente de Like a Stone. No arquivo caipira, Tonico & Tinoco entram com Tristeza do Jeca, uma canção em que saudade, lugar e identidade rural caminham juntos. O Top 5 histórico permanece intacto.',shareSummary:'Música: Audioslave — Like a Stone no Rock; Tonico & Tinoco — Tristeza do Jeca no arquivo raiz. Catálogos e players seguem independentes, sem misturar estilos.',readTime:'2 FAIXAS + ARQUIVOS',badge:'MUSIC DROP',sections:[{title:'Rock: escute o espaço',paragraphs:['Like a Stone mostra como uma base relativamente econômica pode crescer por dinâmica, timbre e interpretação vocal sem precisar preencher cada segundo.']},{title:'Caipira: saudade é também geografia',paragraphs:['Tristeza do Jeca é útil para perceber como a música caipira antiga trata saudade não apenas como romance, mas como relação com território, memória e modo de vida.']}],sources:[]});

set('games',{title:'PS5 Radar: Marvel’s Wolverine já tem data — 15 de setembro — mas trailer não é review',summary:'A Insomniac confirmou Marvel’s Wolverine para 15 de setembro de 2026 no PlayStation 5. O trailer de história mostrou Jean Grey, The Hand e Deathstrike; David Fleming assina a trilha e a pré-venda já está aberta. Tudo isso é fato de produto. Qualidade de combate, performance, duração e consistência da campanha só poderão ser julgadas com o jogo final.',shareSummary:'Games / PS5: Marvel’s Wolverine chega em 15/09/2026. Insomniac mostrou novo trailer, Jean Grey, The Hand e Deathstrike e abriu pré-venda. Vale acompanhar — mas trailer e marketing não substituem análise do jogo final.',readTime:'9 MIN READ',badge:'GAMES / PS5 RADAR',stats:[{label:'PLATAFORMA',value:'PS5'},{label:'LANÇAMENTO',value:'15/09/2026'},{label:'STATUS',value:'PRÉ-VENDA'}],sections:[{title:'O que está confirmado',bullets:['Lançamento em 15 de setembro de 2026 para PS5.','Jean Grey aparece na história; The Hand é uma das facções inimigas e Deathstrike está entre as ameaças destacadas.','David Fleming compôs a trilha.','Há edição Standard e Digital Deluxe em pré-venda.']},{title:'O que o trailer não prova',paragraphs:['Trailer confirma direção artística, personagens e pedaços da proposta; não prova estabilidade técnica, frame rate final, duração, variedade de missões ou qualidade da campanha inteira. Pré-venda é decisão comercial, não selo de qualidade.']},{title:'Por que merece o radar',paragraphs:['É um dos grandes single-player first-party do calendário PS5 de 2026 e vem de um estúdio com experiência em ação narrativa. A pergunta que fica para setembro é como a Insomniac diferencia o combate de Wolverine de seus jogos de Spider-Man sem transformar o personagem apenas em uma variação mais violenta da mesma fórmula.']}],sources:[{label:'PlayStation Blog · Story Trailer · 23/07/2026',url:'https://blog.playstation.com/2026/07/23/marvels-wolverine-story-trailer-new-art-composer-details-and-more/comment-page-2/'},{label:'PlayStation Blog BR · Marvel’s Wolverine',url:'https://blog.br.playstation.com/2026/07/23/marvels-wolverine-trailer-da-historia-arte-nova-detalhes-sobre-a-composicao-musical-e-mais/'}]});

set('gravidez',{title:'6 semanas + 2 dias: o corpo pode pedir mais descanso e mais idas ao banheiro',summary:'Nesta fase, fadiga, náusea, sensibilidade mamária, alterações de cheiro e vontade de urinar com mais frequência podem aparecer ou se intensificar. A intensidade varia muito e ausência de um sintoma específico não é, por si só, sinal de problema.',shareSummary:'Gravidez: 6s+2d. Fadiga e vontade de urinar mais podem ganhar força junto com náusea e sensibilidade a cheiros. Sintomas variam muito; sinais importantes devem ser discutidos no pré-natal.',readTime:'8 MIN READ',badge:'GESTAÇÃO / 6S2D',stats:[{label:'IDADE',value:'6S + 2D'},{label:'DPP',value:'11/04/2027'},{label:'TRIMESTRE',value:'1º'}],sections:[{title:'Por que o cansaço pode pesar',paragraphs:['Hormônios, adaptação circulatória e o próprio gasto metabólico da gestação podem aumentar sonolência e fadiga. Descanso não é “preguiça”; é uma necessidade que pode variar dia a dia.']},{title:'Vontade de urinar',paragraphs:['Mudanças hormonais e aumento do fluxo sanguíneo renal podem fazer a frequência urinária subir cedo na gestação. Dor, ardor, febre ou urina com sangue não entram na categoria de “sintoma normal”: precisam de avaliação.']},{title:'Cuidados simples',bullets:['Água fracionada ao longo do dia.','Descanso quando o corpo pedir.','Não reduzir água apenas para urinar menos.','Anotar sintomas diferentes para conversar no pré-natal.']}],sources:[{label:'NHS · Pregnancy week 6',url:'https://www.nhs.uk/start-for-life/pregnancy/week-by-week-guide-to-pregnancy/1st-trimester/week-6/'}],disclaimer:'Informação educativa; não substitui pré-natal ou avaliação médica.'});

set('pai',{title:'Missão de hoje: escolha uma responsabilidade fixa e tire uma decisão do caminho',summary:'Apoio prático funciona melhor quando não depende de delegação diária. Escolha uma tarefa recorrente — jantar, louça, compras, caixa dos gatos, organização de documentos ou outra — e torne-se responsável por perceber, planejar e executar.',shareSummary:'Ser Pai: hoje escolha uma tarefa fixa e assuma do começo ao fim, sem esperar ser lembrado. Apoiar também é reduzir a quantidade de decisões que a outra pessoa precisa carregar.',readTime:'5 MIN READ',badge:'SER PAI / OWNERSHIP',sections:[{title:'A diferença entre ajudar e assumir',paragraphs:['“Me fala o que eu faço” ainda exige que outra pessoa perceba, priorize e delegue. Ownership é observar a necessidade, organizar recursos e concluir a tarefa.']},{title:'Faça hoje',bullets:['Escolha uma tarefa diária ou semanal.','Defina o padrão: quando, como e o que precisa repor.','Execute sem lembrete.','Se algo mudar por causa de enjoo ou cansaço, adapte sem transformar isso em cobrança.']}],sources:[]});

set('carros',{title:'Radar >1.0 até R$ 70 mil: quatro usados sem repetir o conjunto de ontem',summary:'Cruze LT 1.8 automático 2014, Sentra SV 2.0 CVT 2015, Peugeot 2008 Allure 1.6 automático 2018 e Fiesta SE 1.6 manual 2018 formam o radar de hoje. Todos têm FIPE e média Webmotors de agosto/2026 abaixo de R$ 70 mil.',shareSummary:'Carros: Cruze 1.8 AT, Sentra 2.0 CVT, 2008 1.6 AT e Fiesta 1.6 manual. Todos >1.0 e com FIPE/média nacional de ago/26 abaixo de R$ 70 mil; compare histórico antes de km.',readTime:'4 OPÇÕES · 15 MIN',badge:'GARAGE RADAR / >1.0 / ≤70K',stats:[{label:'OPÇÕES',value:'4'},{label:'MOTOR',value:'>1.0'},{label:'TETO',value:'R$ 70 MIL'}],sections:[{title:'Como ler o radar',paragraphs:['Preço é filtro, não diagnóstico. Em usados dessa faixa, histórico de manutenção, transmissão, arrefecimento, estrutura, pneus e custo da revisão inicial podem mudar completamente a decisão.']},{title:'Destaque do dia',paragraphs:['O Sentra SV 2015 aparece com FIPE de R$ 51.344 e média Webmotors de R$ 52.898,82 em agosto/2026. O conforto é atraente, mas o histórico do CVT deve ser tratado como critério eliminatório.']}],sources:[{label:'Webmotors · Cruze LT 2014',url:'https://www.webmotors.com.br/tabela-fipe/carros/chevrolet/cruze/2014/18-lt-16v-flex-4p-automatico'},{label:'Webmotors · Sentra SV 2015',url:'https://www.webmotors.com.br/tabela-fipe/carros/nissan/sentra/2015/20-sv-16v-flex-4p-automatico'},{label:'Webmotors · 2008 Allure 2018',url:'https://www.webmotors.com.br/tabela-fipe/carros/peugeot/2008/2018/16-16v-flex-allure-4p-automatico'},{label:'Webmotors · Fiesta SE 2018',url:'https://www.webmotors.com.br/tabela-fipe/carros/ford/fiesta/2018/16-ti-vct-flex-se-manual'}]});

set('motos',{title:'Radar de motos: quatro propostas novas de R$ 19 mil a R$ 39 mil',summary:'CB Twister ABS 2020, Himalayan 411 2021, BMW G 310 R 2018 e Honda NC 750X 2016 trazem quatro usos distintos: cidade, trail, naked premium e viagem.',shareSummary:'Motos: Twister ABS, Himalayan, BMW G 310 R e NC 750X. Quatro propostas e custos bem diferentes — compare uso real, seguro, consumíveis, ciclística e histórico.',readTime:'4 OPÇÕES · 15 MIN',badge:'MOTO RADAR / 4 PICKS',stats:[{label:'OPÇÕES',value:'4'},{label:'FAIXA FIPE',value:'R$ 18–36 MIL'},{label:'FOCO',value:'USO + ESTADO'}],sections:[{title:'Destaque racional',paragraphs:['A CB Twister ABS 2020 entra com FIPE de R$ 19.049 e média nacional perto de R$ 20,5 mil, oferecendo ABS, boa rede de peças e uso urbano simples.']},{title:'Não compare só cilindrada',bullets:['Himalayan: ergonomia e piso ruim.','G 310 R: naked leve com custo premium de propriedade.','NC 750X: viagem e torque, mas consumíveis/seguro sobem.']}],sources:[{label:'Webmotors · CB Twister ABS 2020',url:'https://www.webmotors.com.br/tabela-fipe/motos/honda/cb-250f-twister-abs/2020'},{label:'Webmotors · Himalayan 2021',url:'https://www.webmotors.com.br/tabela-fipe/motos/royal-enfield/himalayan/2021'},{label:'Webmotors · BMW G 310 R 2018',url:'https://www.webmotors.com.br/tabela-fipe/motos/bmw/g-310-r/2018'},{label:'Webmotors · NC 750X 2016',url:'https://www.webmotors.com.br/tabela-fipe/motos/honda/nc-750x/2016'}]});

set('mecanica',{title:'Rolamento de roda ou pneu serrilhado? Use velocidade, curva e inspeção para separar os ruídos',summary:'Rolamento defeituoso costuma produzir ronco que acompanha a velocidade e pode mudar quando a carga lateral muda numa curva. Pneus com desgaste em “escamas” também roncam e conseguem enganar. Diagnóstico bom cruza teste de rodagem com inspeção física.',shareSummary:'Mecânica: ronco que aumenta com velocidade não condena automaticamente rolamento. Pneu serrilhado imita o sintoma; curva, piso, toque na banda e inspeção do conjunto ajudam a separar as causas.',readTime:'7 MIN READ',badge:'MECÂNICA / RUÍDO',sections:[{title:'Pista 1: carga lateral',paragraphs:['Em curva leve e segura, a carga muda entre lados do carro. Se o ruído muda de forma consistente, o rolamento ganha força como hipótese — mas a relação entre lado da curva e lado defeituoso não deve ser usada isoladamente.']},{title:'Pista 2: o pneu fala com a mão',paragraphs:['Passe a mão na banda de rodagem: desgaste serrilhado ou em escamas pode gerar ronco semelhante a rolamento e costuma apontar também para alinhamento, amortecimento ou geometria.']},{title:'Não faça',bullets:['Não levantar o carro de forma insegura para “ouvir roda”.','Não trocar cubo/rolamento só pelo som sem checar pneus.','Não ignorar folga, aquecimento anormal ou vibração crescente.']}],sources:[]});

set('nautica',{title:'Ânodo de sacrifício: corrosão controlada para preservar rabeta, eixo e outras peças metálicas',summary:'Quando metais diferentes ficam eletricamente conectados em água, cria-se uma célula galvânica. O ânodo é escolhido para corroer preferencialmente e proteger componentes mais nobres — por isso material, contato elétrico e inspeção importam.',shareSummary:'Náutica: ânodo de sacrifício funciona justamente porque corrói no lugar de outras peças. Não pinte, mantenha bom contato elétrico e escolha material compatível com o ambiente e orientação do fabricante.',readTime:'7 MIN READ',badge:'NÁUTICA / CORROSÃO',sections:[{title:'O princípio',paragraphs:['A corrosão galvânica ocorre quando metais diferentes, conectados eletricamente, estão imersos em eletrólito. O ânodo menos nobre entrega material primeiro e protege o restante do sistema.']},{title:'Erros comuns',bullets:['Pintar o ânodo e isolá-lo da água.','Montar sobre superfície sem contato elétrico adequado.','Escolher material “pelo costume” sem considerar água doce/salgada e recomendação do fabricante.','Esperar desaparecer completamente antes de trocar.']},{title:'Inspeção',paragraphs:['Compare perda de material com o padrão do fabricante e procure corrosão anormal em outras peças. Ânodo consumindo rápido demais também pode ser sinal de problema elétrico ou configuração inadequada.']}],sources:[]});

set('viagens',{title:'Expoflora 2026 começa em 28 de agosto: planejar agora ainda muda bastante o custo do passeio',summary:'A 43ª Expoflora acontece em Holambra de 28 de agosto a 27 de setembro, sextas, sábados, domingos e 7 de setembro, das 9h às 19h. O lote “Última Chance” está anunciado até 19/08, com inteira a partir de R$ 117,80, solidário a partir de R$ 60,90 e meia a partir de R$ 58,90; preços variam por data.',shareSummary:'Viagens: Expoflora começa 28/08 em Holambra. Lote atual vai até 19/08: inteira a partir de R$117,80, solidário a partir de R$60,90 e meia a partir de R$58,90. Estacionamento antecipado está em R$57,90.',readTime:'8 MIN READ',badge:'VIAGEM / HOLAMBRA',stats:[{label:'INÍCIO',value:'28/08'},{label:'FIM',value:'27/09'},{label:'HORÁRIO',value:'9H–19H'}],sections:[{title:'Custo oficial antes de sair',bullets:['Inteira antecipada: a partir de R$ 117,80 no lote atual.','Solidário: a partir de R$ 60,90.','Meia: a partir de R$ 58,90, mediante regras aplicáveis.','Estacionamento antecipado para carro: R$ 57,90.','Passeio ao campo de girassóis: R$ 59,90.']},{title:'Como aproveitar melhor',paragraphs:['O ingresso inclui atrações como mostra de paisagismo, exposição de arranjos, danças típicas, Parada das Flores e Chuva de Pétalas; alimentação, campo de girassóis e parque de diversões são extras. Chegar cedo ajuda a diluir o custo por hora e evitar fazer tudo correndo.']},{title:'Cuidado com preço congelado em print',paragraphs:['A organização informa que valores mudam conforme lote. Confira novamente no site oficial antes de comprar ou viajar.']}],sources:[{label:'Expoflora · ingressos 2026',url:'https://expoflora.com.br/ingressos'},{label:'Expoflora · informações oficiais',url:'https://www.expoflora.com.br/informacoes'}]});

set('financas',{title:'Treasury de 30 anos em 5,327%: juro longo pode subir mesmo quando o curto prazo parece menos agressivo',summary:'O rendimento do Treasury americano de 30 anos atingiu 5,327%, maior nível desde 2007. Energia acima de US$ 90, preocupação fiscal, emissão de dívida e prêmio de prazo ajudam a explicar por que a ponta longa pode ficar pressionada mesmo sem uma decisão imediata do Fed.',shareSummary:'Finanças: juro de 30 anos dos EUA chegou a 5,327%, maior desde 2007. Curto e longo prazo respondem a forças diferentes; petróleo, déficit, emissão de dívida e prêmio de prazo podem manter financiamentos longos caros.',readTime:'8 MIN READ',badge:'FINANÇAS / JUROS LONGOS',stats:[{label:'30Y UST',value:'5,327%'},{label:'MARCO',value:'MAIOR DESDE 2007'},{label:'PETRÓLEO',value:'> US$ 90'}],sections:[{title:'Curto ≠ longo',paragraphs:['A taxa curta reage fortemente à política monetária esperada. A longa incorpora inflação futura, crescimento, risco fiscal, oferta de títulos e prêmio exigido por prender dinheiro por décadas.']},{title:'Aplicação prática',bullets:['Financiamento longo deve ser comparado por CET e custo total, não apenas taxa anunciada.','Não conte com queda futura de juros para justificar uma parcela apertada hoje.','Prazo menor reduz juros totais, mas aumenta parcela: decisão precisa caber no orçamento real.']},{title:'O choque de energia',paragraphs:['Petróleo acima de US$ 90 reabre preocupação inflacionária. Isso não garante inflação maior em cada país, mas aumenta um dos riscos que investidores colocam no preço dos títulos.']}],sources:[{label:'Reuters · Treasury de 30 anos · 18/08/2026',url:'https://www.reuters.com/business/us-30-year-yields-hit-highest-level-since-2007-war-oil-worries-fester-2026-08-18/'},{label:'Reuters · petróleo · 18/08/2026',url:'https://www.reuters.com/business/energy/oil-climbs-fading-us-iran-peace-hopes-raise-supply-risks-2026-08-18/'}],disclaimer:'Conteúdo educacional; não é recomendação individual de investimento.'});

set('tecnologia',{title:'NPU, TOPS e AI PC: por que um número grande não garante o aplicativo mais rápido',summary:'A Microsoft define Copilot+ PC com NPU de 40+ TOPS, entre outros requisitos. TOPS mede capacidade teórica de operações, mas desempenho real de IA local depende do modelo, precisão numérica, memória, largura de banda, runtime, drivers e de quanto do workload realmente roda na NPU.',shareSummary:'Tecnologia: 40+ TOPS virou referência para Copilot+ PCs, mas TOPS sozinho não mede experiência real. Modelo, memória, runtime, drivers e suporte de software decidem quanto daquela capacidade vira desempenho útil.',readTime:'7 MIN READ',badge:'TECH / ON-DEVICE AI',stats:[{label:'COPILOT+ NPU',value:'40+ TOPS'},{label:'RAM',value:'16 GB+'},{label:'IDEIA',value:'IA LOCAL'}],sections:[{title:'O que é NPU',paragraphs:['É um acelerador dedicado a operações comuns em redes neurais. A vantagem potencial é executar tarefas de IA com eficiência energética melhor que CPU/GPU em workloads compatíveis.']},{title:'O que TOPS não conta',bullets:['Precisão usada no benchmark.','Tamanho e arquitetura do modelo.','Memória disponível e movimentação de dados.','Qualidade do runtime e dos drivers.','Se o aplicativo realmente usa a NPU ou cai para CPU/GPU.']},{title:'Como comparar melhor',paragraphs:['Para uma compra real, procure benchmark do aplicativo que você usa, consumo energético, memória e qualidade do software. TOPS é uma especificação útil, não um placar universal.']}],sources:[{label:'Microsoft Learn · Copilot+ PC / NPU',url:'https://learn.microsoft.com/pt-br/windows/ai/npu-devices/'},{label:'Microsoft Learn · comparação de soluções Windows AI',url:'https://learn.microsoft.com/pt-br/windows/ai/windows-ai-comparison'}]});

set('seguranca',{title:'The Gentlemen: quando ransomware vira também um mecanismo de propagação lateral',summary:'A Microsoft detalhou um ransomware-as-a-service em Go associado ao Storm-2697 que combina criptografia, dupla extorsão e um módulo de auto-propagação. Quando ativado, o malware tenta múltiplas técnicas de execução remota em paralelo para alcançar outros hosts.',shareSummary:'Cyber: The Gentlemen mostra por que ransomware não é só “arquivo criptografado”. O módulo de propagação tenta várias rotas laterais; segmentação, privilégio mínimo, hardening de ferramentas remotas e contenção rápida viram controles de impacto.',readTime:'9 MIN READ',badge:'CYBER / RANSOMWARE',stats:[{label:'MODELO',value:'RAAS'},{label:'LINGUAGEM',value:'GO'},{label:'ATOR',value:'STORM-2697'}],sections:[{title:'Por que é diferente',paragraphs:['O encryptor pode tentar transformar um host comprometido em ponto de distribuição e disparar várias técnicas de movimento lateral por alvo. Redundância ofensiva aumenta a chance de uma única rota escapar do hardening.']},{title:'Defesa que reduz blast radius',bullets:['Privilégio administrativo separado e bem controlado.','Segmentação e limitação de SMB/execução remota entre estações.','Proteção contra tampering e regras de redução de superfície de ataque.','Backups isolados e teste de restauração.','Detecção de PsExec/WMI/scheduled tasks fora do padrão.']},{title:'Resposta',paragraphs:['Se houver sinal de propagação, não trate o incidente como “um endpoint infectado”. Contenção de identidade, rede e credenciais deve acompanhar a investigação de endpoints.']}],sources:[{label:'Microsoft Threat Intelligence · The Gentlemen · 28/05/2026',url:'https://www.microsoft.com/en-us/security/blog/2026/05/28/the-gentlemen-ransomware-dissecting-a-self-propagating-go-encryptor/'}]});

set('appsec-ssdlc',{title:'API4: Unrestricted Resource Consumption — segurança também precisa colocar teto no custo de cada requisição',summary:'Uma API pode estar autenticada, autorizada e sem injection e ainda assim permitir que um cliente consuma CPU, memória, banda, storage ou serviços pagos sem limite. OWASP API4 cobre justamente esse risco, que pode produzir DoS e aumento de custo.',shareSummary:'AppSec: API4 não é só rate limit. Gate deve validar payload, upload, paginação, batching, timeout, concorrência e custos de terceiros. Uma requisição “válida” pode ser abusiva se o orçamento de recursos for ilimitado.',readTime:'9 MIN READ',badge:'APPSEC / API4',sections:[{title:'Os limites que costumam faltar',bullets:['Tamanho máximo de upload/payload.','Registros máximos por página.','Quantidade de operações em batch/GraphQL.','Timeout e concorrência.','Memória/CPU por execução.','Limite de chamadas e gasto em SMS, e-mail, biometria e APIs pagas.']},{title:'Como virar teste de pipeline',paragraphs:['Crie testes negativos que tentem exceder cada limite e esperem rejeição previsível. Para APIs críticas, combine testes funcionais com carga controlada e policies de gateway/infra.']},{title:'Gate pragmático',bullets:['Bloquear endpoint novo sem limite de paginação quando retorna coleção grande.','Bloquear upload sem max size server-side.','Exigir rate limit em fluxos caros/sensíveis.','Exigir budget/alerta para integrações pagas por chamada.','Registrar exceção formal quando o limite não puder ser aplicado.']}],sources:[{label:'OWASP API Security · API4:2023',url:'https://owasp.org/API-Security/editions/2023/en/0xa4-unrestricted-resource-consumption/'},{label:'OWASP API Security Testing Framework',url:'https://owasp.org/www-project-api-security-testing-framework/'}]});
