import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f2f0e9"/><rect x="76" y="116" width="928" height="1688" rx="84" fill="#dfe8e3"/><circle cx="540" cy="620" r="280" fill="#31584c" opacity=".14"/><text x="540" y="735" text-anchor="middle" font-size="230" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M220 1060h640" stroke="#31584c" stroke-width="18" opacity=".65"/><text x="540" y="1260" text-anchor="middle" font-size="68" font-weight="700" font-family="Arial,sans-serif" fill="#243f37">${headline}</text><text x="540" y="1370" text-anchor="middle" font-size="40" font-family="Arial,sans-serif" fill="#4c665d">${sub}</text><text x="540" y="1550" text-anchor="middle" font-size="34" font-family="Arial,sans-serif" fill="#657a72">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 03/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 03/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260903:RichMediaEntry[]=[
img('Papo de hoje',['melhor compra pequena','último ano'],'🛍️','PEQUENA COMPRA','GRANDE DIFERENÇA','Arte editorial com pequena sacola e objeto cotidiano representando uma compra útil','https://www.gov.br/mj/pt-br/assuntos/seus-direitos/consumidor'),
img('Desafio do casal',['foto antiga','gostam'],'🖼️','UMA FOTO ANTIGA','CONTE A HISTÓRIA','Arte editorial com fotografia impressa e balões de conversa','https://www.gov.br/cultura/pt-br'),
img('Curiosidades',['metal pode parecer mais frio','mesma temperatura'],'🧊','METAL × MADEIRA','MESMA TEMP. · OUTRO TOQUE','Arte educativa comparando metal e madeira na mesma temperatura','https://www.britannica.com/science/thermal-conductivity'),
img('Curiosidades',['mais alto ao acordar','fim do dia'],'📏','ALTURA MUDA','DISCOS DA COLUNA','Arte educativa com coluna vertebral e régua indicando pequena variação de altura','https://www.ncbi.nlm.nih.gov/books/NBK448134/'),
img('Curiosidades',['gps precisa corrigir','relatividade'],'🛰️','GPS + EINSTEIN','38 µs / DIA','Arte educativa com satélite, relógio atômico e Terra representando correções relativísticas','https://www.nist.gov/atomic-clocks/a-powerful-tool-for-science/putting-einstein-test'),
img('Gravidez',['8 semanas + 4 dias','8s4d'],'🤰','8S4D','DESENVOLVIMENTO','Ilustração educativa abstrata referente a 8 semanas e 4 dias de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/8-weeks/'),
img('Ser Pai',['tarefa da manhã','noite anterior'],'✅','UMA TAREFA ANTES','MENOS CORRERIA AMANHÃ','Arte editorial com checklist noturno e itens preparados para a manhã','https://www.cdc.gov/hearher/'),
img('Brasil',['nestlé anuncia r$ 2 bilhões','fórmula infantil'],'🏭','R$ 2 BI NO BRASIL','NOVA FÁBRICA EM MG','Arte editorial específica com fábrica e marcador de Minas Gerais sobre investimento anunciado','https://www.reuters.com/business/healthcare-pharmaceuticals/nestle-build-infant-formula-plant-brazil-part-393-million-investment-2026-09-03/'),
img('Mundo',['vítimas civis','eua–irã','eua-irã'],'🌍','EUA × IRÃ','IMPACTO CIVIL','Arte editorial neutra com mapa e símbolo humanitário representando atualização sobre vítimas civis','https://www.reuters.com/world/middle-east/iran-war-escalation-raises-concern-over-civilian-death-toll-2026-09-03/'),
img('Política',['tse tem sessão','oito processos'],'🏛️','TSE · 10H','8 PROCESSOS','Arte editorial com plenário eleitoral, relógio e oito marcadores de pauta','https://www.tse.jus.br/comunicacao/noticias/2026/Setembro/confira-a-pauta-de-julgamentos-do-tse-desta-quinta-feira-3'),
img('Tempo e Clima',['amanhecer frio','névoa úmida'],'🌫️','SP · 03/09','9°C → 25°C','Arte meteorológica com névoa matinal e termômetro para São Paulo','https://portal.inmet.gov.br/noticias/previs%C3%A3o-para-quarta-feira-02-e-quinta-feira-03'),
img('Viagens',['plano a','plano b'],'🧭','PLANO A / B','UM PASSEIO · DUAS ROTAS','Arte editorial com mapa bifurcado entre passeio externo e opção coberta','https://www.gov.br/turismo/pt-br'),
img('Música',['identificar os instrumentos','créditos'],'🎧','OUÇA EM CAMADAS','INSTRUMENTOS PRIMEIRO','Arte editorial com fones e camadas de instrumentos musicais','https://www.gov.br/cultura/pt-br'),
img('Games',['state of play','10h no brasil'],'🎮','STATE OF PLAY','HOJE · 10H','Arte editorial específica com controle e relógio para agenda do State of Play','https://blog.playstation.com/2026/08/31/state-of-play-state-of-play-japan-return-on-september-3/'),
img('Finanças',['petróleo recua','us$ 95,04'],'🛢️','BRENT · US$ 95,04','MADRUGADA · INTRADIA','Arte editorial específica com barril e gráfico de leve queda do petróleo','https://www.reuters.com/business/energy/oil-edges-down-investors-weigh-uncertainty-over-us-iran-strikes-2026-09-03/'),
img('Carros até R$ 70 mil',['laudo cautelar','sinal'],'🚗','ATÉ R$70 MIL','LAUDO ANTES DO SINAL','Arte editorial de carro usado com documento de inspeção cautelar','https://www.gov.br/senatran/pt-br'),
img('Motos',['partida','motor realmente frio'],'🏍️','PARTIDA A FRIO','OUÇA ANTES DE AQUECER','Arte editorial de motocicleta com motor frio e chave de partida','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['fluido de arrefecimento','cor não define'],'🧪','ARREFECIMENTO','ESPECIFICAÇÃO > COR','Arte editorial com frascos de fluido e manual técnico destacando especificação','https://www.nhtsa.gov/vehicle-safety')
];
