import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f5f1e8"/><rect x="70" y="110" width="940" height="1700" rx="84" fill="#e6ece8"/><circle cx="540" cy="600" r="285" fill="#355d50" opacity=".14"/><text x="540" y="700" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M210 1030h660" stroke="#355d50" stroke-width="14" opacity=".55"/><text x="540" y="1220" text-anchor="middle" font-size="58" font-weight="700" font-family="Arial,sans-serif" fill="#263f37">${headline}</text><text x="540" y="1340" text-anchor="middle" font-size="37" font-family="Arial,sans-serif" fill="#51675f">${sub}</text><text x="540" y="1530" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#6b7d76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 05/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 05/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260905:RichMediaEntry[]=[
img('Papo de hoje',['comida vocês gostariam de aprender','aprender a fazer juntos'],'🍳','COZINHAR JUNTOS','QUAL RECEITA SERIA?','Arte 9:16 específica com panela e utensílios para conversa sobre receita a aprender juntos','https://www.gov.br/saude/pt-br'),
img('Desafio do casal',['mini passeio de 30 minutos','passeio de 30 minutos'],'🚶','30 MINUTOS JUNTOS','UM PASSEIO SEM COMPLICAÇÃO','Arte 9:16 específica com casal caminhando simbolicamente em passeio curto','https://www.gov.br/saude/pt-br'),
img('Curiosidades',['wombats conseguem produzir','cocô em formato de cubo'],'🐾','WOMBAT · CUBOS','O INTESTINO MOLDA','Arte 9:16 específica com wombat e formas cúbicas representando o fenômeno intestinal','https://pubs.rsc.org/en/content/articlehtml/2021/sm/d1sm00142f'),
img('Curiosidades',['bilhões de animais sobem','maior migração da terra'],'🌊','MAIOR MIGRAÇÃO','ACONTECE TODA NOITE NO MAR','Arte 9:16 específica com oceano e organismos migrando verticalmente','https://oceanexplorer.noaa.gov/ocean-fact/vertical-migration/'),
img('Curiosidades',['banheira impossível','saturno flutuaria'],'🪐','SATURNO FLUTUARIA','DENSIDADE MENOR QUE A ÁGUA','Arte 9:16 específica com Saturno e comparação conceitual de densidade com água','https://science.nasa.gov/saturn/facts/'),
img('Curiosidades',['ar ao redor de um raio','50.000 °f'],'⚡','RAIO · 50.000 °F','O AR AQUECE EM UM INSTANTE','Arte 9:16 específica com descarga elétrica e aquecimento extremo do ar','https://www.weather.gov/safety/lightning-temperature'),
img('Curiosidades',['cadeia de montanhas mais longa','65 mil km'],'🌍','65.000 KM','A MAIOR CORDILHEIRA É SUBMERSA','Arte 9:16 específica com globo e dorsal meso-oceânica','https://oceanservice.noaa.gov/facts/midoceanridge.html'),
img('Gravidez',['8 semanas + 6 dias','8s6d'],'🤰','8S6D','DESENVOLVIMENTO EM RITMO RÁPIDO','Arte 9:16 abstrata específica para 8 semanas e 6 dias de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/8-weeks/'),
img('Ser Pai',['tarefa mais pesa','assuma uma parte concreta'],'🤝','ASSUMA UMA PARTE','APOIO PRÁTICO HOJE','Arte 9:16 com gesto de apoio e tarefa resolvida para missão de pai','https://www.cdc.gov/hearher/'),
img('Mundo',['eua atingem três petroleiros iranianos','três navios que transportavam petróleo iraniano'],'🛢️','EUA × IRÃ','3 PETROLEIROS ATINGIDOS','Arte 9:16 editorial específica com petroleiro e referência ao Golfo para escalada militar entre EUA e Irã','https://www.reuters.com/world/middle-east/us-military-strikes-three-iranian-crude-oil-carriers-central-command-says-2026-09-05/'),
img('Zona Leste em Foco',['são miguel paulista inicia programação','xiv mostra de teatro'],'🎭','SÃO MIGUEL · 466 ANOS','MOSTRA DE TEATRO HOJE','Arte 9:16 específica com máscaras de teatro e referência a São Miguel Paulista para a programação de 466 anos','https://prefeitura.sp.gov.br/web/sao_miguel_paulista/w/s%C3%A3o-miguel-paulista-celebra-466-anos-com-programa%C3%A7%C3%A3o-que-re%C3%BAne-cultura-f%C3%A9-esporte-e-tradi%C3%A7%C3%A3o'),
img('Viagens',['três destinos curtos','bate-volta'],'🗺️','3 DESTINOS','UM FUTURO BATE-VOLTA','Arte 9:16 com mapa e três marcadores para shortlist de bate-volta','https://www.gov.br/turismo/pt-br'),
img('Música',['faixa que marcou sua adolescência','música da adolescência'],'🎧','MÚSICA DA ADOLESCÊNCIA','UMA FAIXA, UMA HISTÓRIA','Arte 9:16 com fones e notas para troca de memórias musicais','https://www.gov.br/cultura/pt-br'),
img('Carros até R$ 70 mil',['histórico e laudo','até r$70 mil'],'🚗','ATÉ R$70 MIL','HISTÓRICO + LAUDO','Arte 9:16 de carro usado com documento e inspeção independente','https://www.gov.br/senatran/pt-br'),
img('Motos',['pneu bom não é só','pneus envelhecidos'],'🏍️','PNEUS DA MOTO','SULCO + TRINCAS + IDADE','Arte 9:16 de motocicleta com foco visual nos pneus e sinais de envelhecimento','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['fluido de arrefecimento','cor sozinha não define'],'🌡️','ARREFECIMENTO','USE A ESPECIFICAÇÃO CERTA','Arte 9:16 com reservatório, termômetro e manual representando especificação do fluido','https://www.gov.br/senatran/pt-br')
];
