import type {RichMediaEntry} from './rich-media';
const art=(label:string,shape:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#121b2b"/><circle cx="540" cy="650" r="270" fill="#304a6b"/><path d="M250 1120 Q540 870 830 1120 Q540 1370 250 1120Z" fill="#e5e7eb"/><text x="540" y="1540" text-anchor="middle" font-size="58" font-family="Arial,sans-serif" fill="white">${shape}</text><text x="540" y="1640" text-anchor="middle" font-size="32" font-family="Arial,sans-serif" fill="#cbd5e1">${label}</text></svg>`)}`;
const img=(label:string,shape:string,alt:string,sourceUrl:string)=>({url:art(label,shape),alt,caption:label,credit:'Father Giulian News · arte editorial específica',sourceUrl,kind:'REFERENCE' as const});
export const dailyRichMedia20260901:RichMediaEntry[]=[
{label:'Papo de hoje',matches:['lugar perto de casa','exploraram direito'],tag:'ARTE ESPECÍFICA · PAPO',title:'Explorar perto',caption:'Mapa de bairro e conversa.',images:[img('Papo de hoje','MAPA + CAFÉ','Arte editorial com mapa e ponto de encontro para conversa sobre um lugar próximo','https://www.gov.br/turismo/')]},
{label:'Desafio do casal',matches:['escolhe uma música para o outro','ouçam as duas'],tag:'ARTE ESPECÍFICA · DESAFIO',title:'Troca musical',caption:'Duas escolhas, duas escutas.',images:[img('Desafio do casal','2 MÚSICAS','Arte editorial com dois discos e setas de troca entre o casal','https://www.youtube.com/')]},
{label:'Curiosidades',matches:['relâmpago pode aquecer','50 mil'],tag:'ARTE ESPECÍFICA · CIÊNCIA',title:'Calor do relâmpago',caption:'Ar aquecido pela descarga.',images:[img('Ciência','RELÂMPAGO','Arte educativa de descarga elétrica aquecendo uma coluna de ar','https://www.weather.gov/safety/lightning-temperature')]},
{label:'Curiosidades',matches:['muco e bicarbonato','estômago'],tag:'ARTE ESPECÍFICA · CORPO HUMANO',title:'Barreira gástrica',caption:'Muco e bicarbonato.',images:[img('Corpo Humano','MUCO + HCO₃','Arte educativa do estômago com camada protetora de muco e bicarbonato','https://pubmed.ncbi.nlm.nih.gov/15591243/')]},
{label:'Curiosidades',matches:['usb power delivery negocia','240 w'],tag:'ARTE ESPECÍFICA · TECNOLOGIA',title:'Negociação USB PD',caption:'Fonte, cabo e dispositivo.',images:[img('Tecnologia','USB PD','Arte educativa com carregador USB-C negociando energia com dispositivo','https://www.usb.org/usb-charger-pd')]},
{label:'Gravidez',matches:['8 semanas + 2 dias','8s2d'],tag:'ILUSTRAÇÃO EDUCATIVA',title:'8 semanas + 2 dias',caption:'Desenvolvimento inicial.',images:[img('Gravidez','8S2D','Ilustração educativa abstrata de desenvolvimento embrionário com 8 semanas e 2 dias','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/8-weeks/')]},
{label:'Ser Pai',matches:['estação de apoio','manhã começar'],tag:'ARTE ESPECÍFICA · APOIO',title:'Estação de apoio',caption:'Água e itens práticos.',images:[img('Ser Pai','APOIO','Arte editorial com água, lanche e itens de apoio organizados','https://www.cdc.gov/hearher/')]},
{label:'Mundo',matches:['petróleo sobe','hormuz'],tag:'ARTE ESPECÍFICA · MUNDO',title:'Petróleo e Hormuz',caption:'Energia e tensão no Golfo.',images:[img('Mundo','HORMUZ','Arte editorial com estreito, navio-tanque e gráfico de petróleo','https://www.reuters.com/business/energy/oil-prices-rise-latest-fighting-resurrects-middle-east-supply-disruption-risks-2026-09-01/')]},
{label:'Política',matches:['comissão mista','10h'],tag:'ARTE ESPECÍFICA · AGENDA',title:'Comissão mista às 10h',caption:'Agenda parlamentar, sem presumir resultado.',images:[img('Política','AGENDA 10H','Arte editorial neutra com plenário e relógio marcando dez horas','https://www.camara.leg.br/noticias/1301428-comissao-mista-adia-para-esta-terca-feira-votacao-do-fim-da-taxa-das-blusinhas')]},
{label:'Tempo',matches:['alerta amarelo','tempestade'],tag:'ARTE ESPECÍFICA · TEMPO',title:'Alerta de tempestade',caption:'Chuva, vento e granizo possíveis.',images:[img('Tempo','TEMPESTADE','Arte meteorológica com nuvem, raio, chuva e vento sobre São Paulo','https://portal.inmet.gov.br/')]},
{label:'Viagens',matches:['plano b de chuva','opção coberta'],tag:'ARTE ESPECÍFICA · VIAGEM',title:'Plano B de chuva',caption:'Passeio flexível.',images:[img('Viagens','PLANO B','Arte editorial de rota com abrigo coberto e retorno fácil','https://www.gov.br/turismo/')]},
{label:'Música',matches:['bateria e na percussão','escuta ativa'],tag:'ARTE ESPECÍFICA · MÚSICA',title:'Ouça a bateria',caption:'Escuta focada no ritmo.',images:[img('Música','BATERIA','Arte editorial com bateria, pratos e onda rítmica','https://www.gov.br/cultura/')]},
{label:'Carros até R$ 70 mil',matches:['ar-condicionado','até r$70 mil'],tag:'ARTE ESPECÍFICA · CARROS',title:'Ar-condicionado em usado',caption:'Checklist até R$70 mil.',images:[img('Carros até R$70 mil','A/C','Arte editorial de carro usado com fluxo do ar-condicionado em destaque','https://www.gov.br/senatran/')]},
{label:'Motos',matches:['pneus contam idade','rachaduras'],tag:'ARTE ESPECÍFICA · MOTOS',title:'Pneus da moto',caption:'Idade e desgaste.',images:[img('Motos','PNEUS','Arte editorial de pneu de motocicleta com sulcos e lateral destacados','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria')]},
{label:'Mecânica',matches:['alternador','sistema de carga'],tag:'ARTE ESPECÍFICA · MECÂNICA',title:'Sistema de carga',caption:'Bateria e alternador.',images:[img('Mecânica','ALTERNADOR','Arte editorial do circuito entre alternador e bateria automotiva','https://www.nhtsa.gov/vehicle-safety')]}
];
