import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl=url):RichMediaEntry=>({label,matches,tag:'MÍDIA · 06/10',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl:sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20261006:RichMediaEntry[]=[
img('Papo de hoje',['que parte da rotina','rotina vocês querem deixar mais leve'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pregnancy.jpg','Casal durante a gestação','Soul Flora / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pregnancy.jpg'),
img('Desafio do casal',['15 minutos','pequena pendência da casa'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Family_routine.jpg','Família realizando tarefas da rotina doméstica','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Family_routine.jpg'),
img('Curiosidades',['Wombats conseguem','formato de cubo'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Common_Wombat_1.jpg','Wombat comum fotografado em zoológico','Xavier Lahey / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Common_Wombat_1.jpg'),
img('Curiosidades',['O revestimento do intestino','cinco dias'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Small_intestine.jpg','Preparação anatômica do intestino delgado humano','Anatomist90 / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Small_intestine.jpg'),
img('Curiosidades',['A Lua se afasta','3,8 centímetros'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Earth_from_Apollo_10.jpg','Terra fotografada pela missão Apollo 10 durante a viagem lunar','NASA / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Earth_from_Apollo_10.jpg'),
img('Gravidez',['13 semanas + 2 dias','ossos endurecem'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pregnancy.jpg','Gestação em imagem real de contexto','Soul Flora / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pregnancy.jpg'),
img('Ser Pai',['tire uma tarefa inteira','tarefa inteira da cabeça'],'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg','Parceiro oferecendo apoio durante a gestação','CDC Hear Her','https://www.cdc.gov/hearher/about/support-family-friends.html'),
img('Brasil',['Resultados do 1º turno','consulta e auditoria'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg','Urnas eletrônicas brasileiras','Abdias Pinheiro / SECOM / TSE','https://commons.wikimedia.org/wiki/File:Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg'),
img('Mundo',['Europa eleva alerta','ataques híbridos russos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Friedrich_Merz_in_2026.jpg','Chanceler alemão Friedrich Merz em 2026','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Friedrich_Merz_in_2026.jpg'),
img('Política',['Segundo turno será','25 de outubro'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg','Urnas eletrônicas brasileiras','Abdias Pinheiro / SECOM / TSE','https://commons.wikimedia.org/wiki/File:Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg'),
img('Tempo e Clima',['São Paulo terá terça chuvosa','alagamentos e queda de árvores'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rain_on_window.jpg','Chuva observada através de uma janela','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Rain_on_window.jpg'),
img('Zona Leste em Foco',['Itaquera ganha nova ligação','Cristóvão de Salamanca'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Corinthians-Itaquera_station_(Linha_3-Vermelha%2C_Linha_11-Coral)%2C_SP%2C_2026-03-01_(25).jpg','Estação Corinthians-Itaquera na Zona Leste de São Paulo','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Corinthians-Itaquera_station_(Linha_3-Vermelha,_Linha_11-Coral),_SP,_2026-03-01_(25).jpg'),
img('Corinthians',['Bidu volta ao treino','confronto com o Internacional'],'https://agemt.pucsp.br/sites/default/files/inline-images/539970296534d0f05c147o.jpg','Corinthians em campo em partida oficial','Agemt / PUC-SP','https://agemt.pucsp.br/noticias/corinthians-supera-sao-paulo-no-morumbis'),
img('Viagens',['12 de outubro cai','fim de semana'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Boarding_Pass_Confirmation_Card%2C_Baiyun_Airport.jpg','Cartão de embarque em contexto de viagem','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Boarding_Pass_Confirmation_Card,_Baiyun_Airport.jpg'),
img('Música',['Playlist de hoje','Alok + NAYEON'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Live_rock_concert_performance_featuring_musicians_playing_guitar_on_stage_at_night_with_vibrant_lighting_effects.jpg','Músicos tocando em apresentação ao vivo','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Live_rock_concert_performance_featuring_musicians_playing_guitar_on_stage_at_night_with_vibrant_lighting_effects.jpg'),
img('Games',['Gears of War: E-Day','STAR WARS: Galactic Racer'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/PSX-Console-wController.jpg','Console PlayStation e controle como referência de videogames','Evan-Amos / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:PSX-Console-wController.jpg'),
img('Tecnologia',['Direitos autorais de IA','Austrália'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Data_Center.jpg','Infraestrutura de data center associada a computação e IA','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Data_Center.jpg'),
img('Finanças',['Ibovespa dispara','recorde após o primeiro turno'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Stock-exchange-trading-floor.jpg','Pregão de bolsa com operadores e terminais de mercado','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Stock-exchange-trading-floor.jpg'),
img('Security Briefing',['FBI remove contratada','PeopleSoft'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Server_Rack_(54126210834).jpg','Rack de servidores em ambiente de infraestrutura digital','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Server_Rack_(54126210834).jpg'),
img('Cyber Security',['Coreia do Sul diz','ataques recentes a bancos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/CSIRO_ScienceImage_2042_A_row_of_computer_servers_in_a_server_rack.jpg','Servidores em rack usados como contexto de segurança de sistemas','CSIRO / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_2042_A_row_of_computer_servers_in_a_server_rack.jpg'),
img('AppSec / SSDLC',['AppSec urgente','CVE-2026-21589'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Programming_code.jpg','Código de software exibido em tela','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Programming_code.jpg'),
img('Carros até R$ 70 mil',['Carros até R$70 mil','teto como filtro'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Used_Car_Lot_(6806377146).jpg','Pátio de automóveis usados à venda','John Fowler / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Used_Car_Lot_(6806377146).jpg'),
img('Motos',['chuva forte em São Paulo','pilotagem suave'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/HONDA%20CBX%20250%20TWISTER.jpg','Motocicleta Honda CBX 250 Twister em imagem real','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:HONDA_CBX_250_TWISTER.jpg'),
img('Mecânica',['antes da chuva de hoje','palhetas, pneus'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rainy_Windshield_Wipers.jpg','Para-brisa com chuva e limpadores em funcionamento','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Rainy_Windshield_Wipers.jpg')
];
