import type {RichMediaEntry} from './rich-media';

export const dailyRichMedia202609061917:RichMediaEntry[]=[
{
 label:'Curiosidades',matches:['rã pode congelar parte do corpo','rã pode congelar'],tag:'FOTO REAL · ANIMAL',title:'Wood frog congelada',caption:'Foto real de wood frog congelada, diretamente relacionada à adaptação descrita no card.',images:[{url:'https://www.fws.gov/sites/default/files/styles/large_square/public/images/2025-03/frozen-wood-frog-janet-storey.jpg?h=4521fff0&itok=ySQW9GiZ',alt:'Wood frog parcialmente congelada sobre folhas e gelo',caption:'Wood frog durante congelamento sazonal.',credit:'U.S. Fish & Wildlife Service',sourceUrl:'https://www.fws.gov/species/wood-frog-rana-sylvatica',kind:'PHOTO'}],relatedLabel:'U.S. Fish & Wildlife Service · Wood Frog',relatedHref:'https://www.fws.gov/species/wood-frog-rana-sylvatica'
},
{
 label:'Curiosidades',matches:['poeira africana ajuda','poeira africana','amazônia'],tag:'IMAGEM SATELITAL · NASA',title:'Poeira do Saara atravessa o Atlântico',caption:'Visualização da pluma de poeira cruzando o Atlântico em direção à América do Sul, ligada diretamente à curiosidade sobre nutrientes da Amazônia.',images:[{url:'https://assets-jpcust.jwpsrv.com/thumbnails/y0tt3fk3-720.jpg',alt:'Imagem de satélite mostrando poeira do Saara atravessando o Atlântico em direção à Amazônia',caption:'Transporte transatlântico de poeira saariana observado por satélite.',credit:'NASA/CALIPSO · visualização publicada pela TIME',sourceUrl:'https://www.nasa.gov/centers-and-facilities/goddard/nasa-satellite-reveals-how-much-saharan-dust-feeds-amazons-plants/',kind:'REFERENCE'}],relatedLabel:'NASA · Saharan dust feeds Amazon',relatedHref:'https://www.nasa.gov/centers-and-facilities/goddard/nasa-satellite-reveals-how-much-saharan-dust-feeds-amazons-plants/'
},
{
 label:'Brasil',matches:['justiça suspende licenças','sigma lithium','grota do cirilo'],tag:'FOTO REAL · REUTERS',title:'Grota do Cirilo',caption:'Foto real da operação da Sigma Lithium na mina Grota do Cirilo, em Itinga (MG).',images:[{url:'https://www.reuters.com/resizer/v2/NITFZMVO3VLN5OHDOGQ73ZSCMY.jpg?auth=131f667a784bed0d3b09e72ceb917f481f519e25c246557de37abe49bc53fb80&quality=80&width=1920',alt:'Operação da Sigma Lithium na mina Grota do Cirilo em Itinga, Minas Gerais',caption:'Produção da Sigma Lithium em Grota do Cirilo.',credit:'Reuters · Washington Alves',sourceUrl:'https://www.reuters.com/world/americas/brazilian-court-suspends-licenses-sigma-lithium-mine-2026-09-06/',kind:'PHOTO'}],relatedLabel:'Reuters · decisão sobre Grota do Cirilo',relatedHref:'https://www.reuters.com/world/americas/brazilian-court-suspends-licenses-sigma-lithium-mine-2026-09-06/'
},
{
 label:'Mundo',matches:['primeira rodada em kyiv termina','conversas substantivas','cerca de três horas'],tag:'FOTO REAL · REUTERS',title:'Zelenskiy recebe enviados dos EUA em Kyiv',caption:'Foto real do encontro em Kyiv em 6 de setembro, diretamente ligada ao card.',images:[{url:'https://www.reuters.com/resizer/v2/CVYH7FAYWBMEZL2TFT7JJQPXZ4.jpg?auth=e3188229888dde6ad3738ebc4927687960d63dad9bc09fb5128818b1e49d6f61&quality=80&width=1080',alt:'Volodymyr Zelenskiy recebe Jared Kushner e Steve Witkoff em Kyiv em 6 de setembro de 2026',caption:'Zelenskiy recebe os enviados americanos em Kyiv.',credit:'Reuters · Valentyn Ogirenko',sourceUrl:'https://www.reuters.com/business/aerospace-defense/us-envoys-make-first-kyiv-visit-amid-ukraine-war-peace-push-2026-09-06/',kind:'PHOTO'}],relatedLabel:'Reuters · negociações em Kyiv',relatedHref:'https://www.reuters.com/business/aerospace-defense/us-envoys-make-first-kyiv-visit-amid-ukraine-war-peace-push-2026-09-06/'
},
{
 label:'Zona Leste em Foco',matches:['abertura oficial dos festejos','são miguel paulista','466 anos'],tag:'CARTAZ OFICIAL · PREFEITURA',title:'Festejos de São Miguel Paulista · 466 anos',caption:'Cartaz oficial vertical da programação de 5 a 29 de setembro de 2026.',images:[{url:'https://prefeitura.sp.gov.br/documents/9401903/23466551/WhatsApp%2BImage%2B2026-09-01%2Bat%2B06.19.03.jpeg/7ac5b8f2-c9b7-f1f0-38f9-efffe5b45456?t=1788295728311',alt:'Cartaz oficial dos festejos de 466 anos de São Miguel Paulista em setembro de 2026',caption:'Programação oficial dos 466 anos de São Miguel Paulista.',credit:'Prefeitura de São Paulo · Subprefeitura São Miguel Paulista',sourceUrl:'https://prefeitura.sp.gov.br/web/sao_miguel_paulista/w/s%C3%A3o-miguel-paulista-celebra-466-anos-com-programa%C3%A7%C3%A3o-que-re%C3%BAne-cultura-f%C3%A9-esporte-e-tradi%C3%A7%C3%A3o',kind:'REFERENCE'}],relatedLabel:'Prefeitura · programação oficial',relatedHref:'https://prefeitura.sp.gov.br/web/sao_miguel_paulista/w/s%C3%A3o-miguel-paulista-celebra-466-anos-com-programa%C3%A7%C3%A3o-que-re%C3%BAne-cultura-f%C3%A9-esporte-e-tradi%C3%A7%C3%A3o'
},
{
 label:'Corinthians',matches:['memphis começa como titular','oito desfalques','chapecoense'],tag:'ARTE 9:16 · FALLBACK LOCAL',title:'Memphis titular contra a Chapecoense',caption:'Arte vertical específica hospedada no próprio Father Giulian News, usada após falha de carregamento da foto externa no Chromium mobile.',images:[{url:'/media/2026-09-06-corinthians-memphis-titular.svg',alt:'Arte vertical específica do Corinthians com camisa 10, bola e indicação de Memphis titular contra a Chapecoense',caption:'Memphis titular em Corinthians x Chapecoense.',credit:'Father Giulian News · arte temática',sourceUrl:'https://www.uol.com.br/esporte/futebol/ultimas-noticias/2026/09/06/escalacoes-corinthians-chapecoense-brasileirao-26.ghtm',kind:'REFERENCE'}],relatedLabel:'UOL · escalações de Corinthians x Chapecoense',relatedHref:'https://www.uol.com.br/esporte/futebol/ultimas-noticias/2026/09/06/escalacoes-corinthians-chapecoense-brasileirao-26.ghtm'
},
{
 label:'Finanças',matches:['opep+ mantém política de produção','inalterada para outubro','opep+'],tag:'FOTO REAL · OPEP',title:'Sede da OPEP em Viena',caption:'Foto da sede da OPEP em Viena, diretamente relacionada à decisão de produção do grupo.',images:[{url:'https://cloudfront-us-east-2.images.arcpublishing.com/reuters/SPCLQRDIPRNRDHRYMZJRRQRIWU.jpg',alt:'Sede da OPEP em Viena com o logotipo da organização na fachada',caption:'Sede da OPEP em Viena.',credit:'Reuters',sourceUrl:'https://www.opec.org/pr-detail/613-6-september-2026.html',kind:'PHOTO'}],relatedLabel:'OPEC · decisão oficial de 06/09',relatedHref:'https://www.opec.org/pr-detail/613-6-september-2026.html'
}
];
