import type {RichMediaEntry} from './rich-media';
export const dailyRichMedia20260831:RichMediaEntry[]=[
{label:'Curiosidades',matches:['lua se afasta','lasers conseguem medir'],tag:'ARTE ESPECÍFICA · CIÊNCIA',title:'Laser lunar',caption:'Medição da distância Terra–Lua.',images:[{url:'/generated/curiosity-lunar-laser-20260831.svg',alt:'Arte educativa com feixe laser entre observatório terrestre e refletor na Lua',caption:'Lunar Laser Ranging.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://science.nasa.gov/moon/exploration/lunar-laser-ranging/',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['córnea é transparente','não possui vasos'],tag:'ARTE ESPECÍFICA · CORPO HUMANO',title:'Córnea transparente',caption:'Estrutura frontal do olho.',images:[{url:'/generated/curiosity-cornea-20260831.svg',alt:'Arte educativa do olho com destaque para a córnea transparente',caption:'Córnea e entrada de luz.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.nei.nih.gov/learn-about-eye-health/healthy-vision/how-eyes-work',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['ssds usam wear leveling','memória flash'],tag:'ARTE ESPECÍFICA · TECNOLOGIA',title:'Wear leveling',caption:'Distribuição de gravações em memória flash.',images:[{url:'/generated/curiosity-ssd-wear-20260831.svg',alt:'Arte educativa de blocos de memória flash com gravações distribuídas',caption:'Wear leveling em SSD.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://csrc.nist.gov/pubs/sp/800/88/r1/final',kind:'REFERENCE'}]},
{label:'Gravidez',matches:['8 semanas + 1 dia','8s1d'],tag:'ILUSTRAÇÃO EDUCATIVA',title:'8 semanas + 1 dia',caption:'Desenvolvimento inicial.',images:[{url:'/generated/pregnancy-8w1d-20260831.svg',alt:'Ilustração educativa e não fotorrealista de desenvolvimento embrionário no início da nona semana gestacional',caption:'Ilustração educativa.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.nhs.uk/pregnancy/week-by-week/1-to-12/8-weeks/',kind:'REFERENCE'}]},
{label:'Ser Pai',matches:['cuidar de uma parte da manhã','responsabilidade concreta'],tag:'ARTE ESPECÍFICA · APOIO',title:'Apoio prático',caption:'Divisão real da rotina.',images:[{url:'/generated/parenthood-routine-20260831.svg',alt:'Arte editorial de duas pessoas dividindo tarefas de casa e cuidado',caption:'Apoio prático na rotina.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.cdc.gov/hearher/',kind:'REFERENCE'}]},
{label:'Política',matches:['tse inicia hoje julgamento','julgamento virtual dos registros'],tag:'ARTE ESPECÍFICA · ELEIÇÕES',title:'Julgamento no TSE',caption:'Sessão virtual sobre registros de candidaturas.',images:[{url:'/generated/politics-tse-register-20260831.svg',alt:'Arte editorial neutra com urna e tela de julgamento virtual do TSE',caption:'Julgamento virtual no TSE.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://agenciabrasil.ebc.com.br/politica/noticia/2026-08/tse-marca-julgamento-de-registros-dos-candidatos-presidencia',kind:'REFERENCE'}]},
{label:'Mundo',matches:['eua e irã retomam ataques','kharg segue sem confirmação'],tag:'ARTE ESPECÍFICA · MUNDO',title:'Escalada EUA–Irã',caption:'Kharg, Larak e Hormuz no radar.',images:[{url:'/generated/world-kharg-20260831.svg',alt:'Arte editorial com mapa simplificado do Golfo Pérsico destacando Kharg, Larak e Hormuz',caption:'Escalada no Golfo.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.reuters.com/world/middle-east/us-iran-exchange-fire-flare-up-bessent-signals-more-sanctions-2026-08-31/',kind:'REFERENCE'}]},
{label:'Corinthians',matches:['cruzeiro x corinthians abre hoje','brasileiro feminino'],tag:'ARTE ESPECÍFICA · CORINTHIANS',title:'Cruzeiro x Corinthians Feminino',caption:'Quartas do Brasileiro Feminino.',images:[{url:'/generated/corinthians-cruzeiro-women-20260831.svg',alt:'Arte esportiva editorial para Cruzeiro x Corinthians feminino nas quartas do Brasileiro',caption:'Cruzeiro x Corinthians.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://ge.globo.com/mg/zona-da-mata-centro-oeste/futebol/futebol-feminino/brasileiro-feminino/noticia/2026/08/31/cruzeiro-x-corinthians-onde-assistir-ao-vivo-horario-e-arbitragem.ghtml',kind:'REFERENCE'}]},
{label:'Viagens',matches:['salve um passeio curto','dia mais fresco'],tag:'ARTE ESPECÍFICA · PASSEIO',title:'Passeio flexível',caption:'Planejamento de passeio curto.',images:[{url:'/generated/travel-short-plan-20260831.svg',alt:'Arte editorial de mapa simples com destino próximo, água e área sombreada',caption:'Passeio curto e flexível.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.gov.br/turismo/',kind:'REFERENCE'}]},
{label:'Música',matches:['gravação ao vivo','canção que já conhecem'],tag:'ARTE ESPECÍFICA · MÚSICA',title:'Versão ao vivo',caption:'Comparando estúdio e palco.',images:[{url:'/generated/music-live-version-20260831.svg',alt:'Arte editorial com microfone, palco e onda sonora de apresentação ao vivo',caption:'Música ao vivo.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://cultura.uol.com.br/',kind:'REFERENCE'}]},
{label:'Finanças',matches:['último dia do novo desenrola','formalizar acordo termina hoje'],tag:'ARTE ESPECÍFICA · FINANÇAS',title:'Prazo final do Desenrola',caption:'Último dia para formalização.',images:[{url:'/generated/finance-desenrola-deadline-20260831.svg',alt:'Arte editorial com calendário em 31 de agosto e símbolo de renegociação financeira',caption:'Prazo final do Novo Desenrola.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://agenciabrasil.ebc.com.br/economia/noticia/2026-08/programa-de-renegociacao-de-dividas-termina-nesta-segunda-feira',kind:'REFERENCE'}]},
{label:'Carros até R$ 70 mil',matches:['arrefecimento antes da compra','até r$70 mil'],tag:'ARTE ESPECÍFICA · CARROS',title:'Arrefecimento em usado',caption:'Checklist até R$70 mil.',images:[{url:'/generated/car-cooling-check-20260831.svg',alt:'Arte editorial de automóvel usado com reservatório de arrefecimento em destaque',caption:'Inspeção do arrefecimento.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.gov.br/senatran/',kind:'REFERENCE'}]},
{label:'Motos',matches:['manete, pedal','história de quedas'],tag:'ARTE ESPECÍFICA · MOTOS',title:'Sinais de queda',caption:'Pontos de inspeção em moto usada.',images:[{url:'/generated/moto-fall-check-20260831.svg',alt:'Arte editorial de motocicleta com manete, pedal e guidão destacados',caption:'Inspeção de sinais de queda.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria',kind:'REFERENCE'}]},
{label:'Mecânica',matches:['bateria fraca','motor de partida'],tag:'ARTE ESPECÍFICA · MECÂNICA',title:'Diagnóstico de partida',caption:'Bateria, cabos e motor de partida.',images:[{url:'/generated/mechanic-starting-check-20260831.svg',alt:'Arte editorial de bateria automotiva conectada ao sistema de partida',caption:'Diagnóstico do sistema de partida.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.nhtsa.gov/vehicle-safety',kind:'REFERENCE'}]}
];
