import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f1efe9"/><rect x="76" y="116" width="928" height="1688" rx="84" fill="#e2e7e3"/><circle cx="540" cy="620" r="278" fill="#33584d" opacity=".13"/><text x="540" y="730" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M220 1050h640" stroke="#33584d" stroke-width="16" opacity=".58"/><text x="540" y="1245" text-anchor="middle" font-size="62" font-weight="700" font-family="Arial,sans-serif" fill="#243f37">${headline}</text><text x="540" y="1365" text-anchor="middle" font-size="39" font-family="Arial,sans-serif" fill="#50675f">${sub}</text><text x="540" y="1545" text-anchor="middle" font-size="32" font-family="Arial,sans-serif" fill="#6a7d76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 04/09 · ATUALIZAÇÃO',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 04/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia202609040528:RichMediaEntry[]=[
  img('Mundo',['drone russo atinge sede do serviço de segurança','sede do sbu','centro de kyiv'],'🏢','KYIV · SBU','DRONE ATINGE SEDE','Arte editorial específica com edifício governamental em Kyiv e símbolo de alerta, sem imagem antiga ou pessoa não relacionada','https://www.reuters.com/world/russia-hits-ukraines-security-service-headquarters-kyiv-zelenskiy-says-2026-09-04/'),
  img('Política',['mais de 158 milhões de eleitores','30 dias do primeiro turno','candidaturas proporcionais'],'🗳️','ELEIÇÕES 2026','158+ MILHÕES APTOS','Arte editorial específica com urna e indicador do eleitorado brasileiro, sem reproduzir interface do TSE','https://www.tse.jus.br/comunicacao/noticias/2026/Setembro/faltam-30-dias-brasil-tem-mais-de-158-milhoes-de-eleitoras-e-eleitores-aptos-a-votar'),
  img('Finanças',['dólar sobe após payroll','162 mil empregos','56 mil esperadas'],'💵','PAYROLL EUA','162 MIL VAGAS','Arte editorial específica com dólar e indicador de emprego, sem sugerir fechamento de mercado','https://www.reuters.com/world/asia-pacific/yen-headed-strongest-week-month-dollar-flat-ahead-payroll-data-2026-09-04/'),
  img('Cyber Security',['reuters revela caso em que agentes da openai','dsewiki','mais de 15 mil edições'],'🤖','AGENTES · DSEWIKI','DIVULGAÇÃO EM 04/09','Arte editorial específica com agente de IA e wiki, sem reproduzir UI antiga ou screenshot do site','https://www.reuters.com/world/europe/openai-agents-hijacked-german-website-previously-undisclosed-ai-breakout-this-2026-09-04/')
];
