import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'MÍDIA REAL · 13/09',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260913:RichMediaEntry[]=[
img('Papo de hoje',['melhor compra pequena','custaram pouco'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Woman%20shops%20online%20with%20a%20small%20shopping%20cart%20and%20cash%20in%20a%20modern%20office%20setting%20during%20the%20afternoon.jpg','Pessoa fazendo uma pequena compra, com dinheiro e um carrinho de compras em miniatura ao lado do computador','Foto real · Shixart1985/Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Woman_shops_online_with_a_small_shopping_cart_and_cash_in_a_modern_office_setting_during_the_afternoon.jpg'),
img('Desafio do casal',['encontrem uma foto antiga','foto antiga que vocês gostam'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Facilities%20old%20vintage%20photo%20album.jpg','Álbum fotográfico antigo aberto com fotografias reais impressas','Foto real · U.S. Fish and Wildlife Service/Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Facilities_old_vintage_photo_album.jpg'),
img('Curiosidades',['tubarões percebem campos elétricos','ampolas de lorenzini'],'https://cf-images.us-east-1.prod.boltdns.net/v1/static/659677166001/dd188186-7589-4c0b-8d9a-95cd7d628fe2/94828f1c-51ec-4990-8865-4ea0abf8537b/1280x720/match/image.jpg','Tubarão nadando diante de equipamento de pesquisa subaquática da NOAA','Foto real · NOAA Fisheries','https://videos.fisheries.noaa.gov/detail/video/5637096261001/underwater-camera-research---northwestern-hawaiian-islands-sharks_clipped'),
img('Curiosidades',['fontes hidrotermais podem passar de 340','não ferve'],'https://www.pmel.noaa.gov/eoi/sites/default/files/styles/home_block_images/public/thumbnails/image/FK171110-Lau-blacksmoker.jpg?itok=hj2N09S4','Fonte hidrotermal black smoker no fundo do oceano','Foto real · NOAA/PMEL','https://www.pmel.noaa.gov/eoi/news-story/underwater-fire-exploring-tongas-submarine-volcanoes'),
img('Curiosidades',['pôr do sol em marte pode parecer azul','pôr do sol marciano'],'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia19/pia19400/PIA19400.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1080&w=1344','Pôr do sol azulado fotografado pelo rover Curiosity em Marte','Foto real · NASA/JPL-Caltech/MSSS/Texas A&M','https://science.nasa.gov/photojournal/sunset-in-mars-gale-crater/'),
img('Curiosidades',['aurora nasce quando partículas carregadas','gases da atmosfera brilham'],'https://svs.gsfc.nasa.gov/vis/a030000/a030100/a030179/frames/4256x2832_3x2_30p/ISS029-E-5890.jpg','Aurora verde e vermelha fotografada da Estação Espacial Internacional','Foto real · NASA Scientific Visualization Studio','https://science.nasa.gov/sun/the-atmosphere-after-dark/'),
img('Curiosidades',['fibra óptica guia luz','reflexão interna total'],'https://www.batiactu.com/images/auto/620-465-c/20240603_174826_rouleau-fibre-optique-istock-richard-villalon.jpg','Bobina real de cabo de fibra óptica','Foto real · Batiactu','https://www.batiactu.com/edito/sabotages-sur-fibre-un-appel-a-repenser-resilience-69166.php'),
img('Gravidez',['10 semanas completas','10s0d'],'https://upload.wikimedia.org/wikipedia/commons/1/1b/10_Weeks_Fetus.JPG','Ultrassom real do primeiro trimestre compatível com 10 semanas de gestação','Foto real · Wikimedia Commons · CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:10_Weeks_Fetus.JPG'),
img('Ser Pai',['30 minutos de descanso','proteja meia hora'],'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg','Pessoa oferecendo apoio prático a uma gestante','Foto real · CDC Hear Her','https://www.cdc.gov/hearher/support-family-friends/index.html'),
img('Mundo',['projétil atinge navio no estreito de hormuz','estreito de hormuz'],'https://premium.vgc.no/v2/images/a0668b90-e312-4c2d-8d6c-62518c9d23e6?fit=crop&format=auto&h=1056&s=9ff6ac13b3ded4f8cc3dc3a5ba956de1b4932eba&w=1578','Navio petroleiro navegando próximo ao Estreito de Hormuz','Foto real · arquivo jornalístico','https://www.aftenposten.no/norge/i/q6Pobw/norges-inntekter-skyter-i-vaeret-som-foelge-av-krigen'),
img('Política',['prestação de contas parcial','prazo termina neste domingo'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Sede_do_Tribunal_Superior_Eleitoral%2C_em_Bras%C3%ADlia.jpg/1280px-Sede_do_Tribunal_Superior_Eleitoral%2C_em_Bras%C3%ADlia.jpg','Sede do Tribunal Superior Eleitoral em Brasília','Foto real · Alexandresena/Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Sede_do_Tribunal_Superior_Eleitoral,_em_Bras%C3%ADlia.jpg'),
img('Tempo e Clima',['domingo segue com chuva','temperatura mais baixa'],'https://portal.inmet.gov.br/uploads/fig1prev-12-13-14_2026-09-11-182159_xrmn.png','Mapa oficial do INMET mostrando o sistema meteorológico que reduz a temperatura e mantém instabilidades no Sudeste','Mapa oficial · INMET · previsão 12–14/09/2026','https://portal.inmet.gov.br/noticias/previs%C3%A3o-para-s%C3%A1bado-12-domingo-13-e-segunda-feira-14'),
img('Viagens',['condição da estrada antes de sair','rodovia antes de sair'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/RodBandeirantes.jpg/960px-RodBandeirantes.jpg','Trecho real da Rodovia dos Bandeirantes em São Paulo','Foto real · Ana Paula Hirama/Wikimedia Commons · CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:RodBandeirantes.jpg'),
img('Música',['canção com duas vozes','duas vozes','participação de dois artistas'],'https://www.concertarchives.org/image_uploads/photo/image/604126/large_image.jpg','Banda se apresentando ao vivo diante de público','Foto real · Concert Archives','https://www.concertarchives.org/'),
img('Carros até R$ 70 mil',['código dot','idade real dos pneus'],'https://static.delti.com/static/rduk/media/tyre_DOT_number.jpg','Close real do código DOT gravado na lateral de um pneu','Foto real · ReifenDirekt','https://www.reifendirekt.de/blog/reifen-dot-code-bedeutung.html'),
img('Motos',['corrente e coroa','folga da corrente'],'https://www.suzukicdn.com/uploads/news/121332611_s.jpg','Corrente e coroa reais da transmissão final de uma motocicleta','Foto real · Suzuki','https://www.suzuki.co.id/tips-trik/mari-mengenal-apa-itu-gir-motor-dan-fungsinya'),
img('Mecânica',['fluido de freio','reservatório do fluido'],'https://dekiteru.media/open/13275/img/13275_100_r48_free01_01_7_0_img.jpg.webp','Reservatório real de fluido de freio no cofre do motor','Foto real · Toukou Moto','https://www.toukou-moto.com/syuri_48.html')
];
