import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'MÍDIA REAL · 15/09',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260915:RichMediaEntry[]=[
img('Papo de hoje',['que comida vocês gostariam de aprender','aprender a fazer juntos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Quando_voc%C3%AA_mora_numa_cidade_com_milhares_de_pizzarias_(22132311531).jpg','Pizza margherita fotografada no Eataly de São Paulo, referência visual para a conversa sobre aprender uma receita juntos','Foto real · Shoichi Iwashita/Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Quando_voc%C3%AA_mora_numa_cidade_com_milhares_de_pizzarias_(22132311531).jpg'),
img('Desafio do casal',['mini passeio de 30 minutos','caminhar pelo bairro'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Couple_walking_in_a_park.jpg','Casal caminhando junto ao ar livre','Foto real · Bill Branson/NCI · domínio público','https://commons.wikimedia.org/wiki/File:Couple_walking_in_a_park.jpg'),
img('Curiosidades',['corvos conseguem reconhecer','lembrar rostos humanos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/American_Crow.jpg','Corvo-americano fotografado em ambiente aberto','Foto real · Linda Tanner/Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:American_Crow.jpg'),
img('Curiosidades',['bioluminescência é extremamente comum','90% dos animais','produzir luz'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Crystal_jelly.jpg','Água-viva Aequorea victoria, espécie bioluminescente, fotografada em aquário','Foto real · Julia Sumangil/Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Crystal_jelly.jpg'),
img('Curiosidades',['corrente de jato em saturno forma um hexágono','hexágono gigantesco'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Saturnhexagon.jpg','Hexágono no polo norte de Saturno observado pela sonda Cassini','Imagem real de missão · NASA · domínio público','https://commons.wikimedia.org/wiki/File:Saturnhexagon.jpg'),
img('Curiosidades',['maior deserto da terra é coberto de gelo','antártida é o maior deserto'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Antarctica_6400px_from_Blue_Marble.jpg','Continente antártico coberto por gelo visto por satélite','Imagem real de satélite · NASA/Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Antarctica_6400px_from_Blue_Marble.jpg'),
img('Curiosidades',['acelerômetro e giroscópio','celular a entender como você o move'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sparkfun_5DOF_Accelerometer_Gyroscope.jpg','Módulo real que combina acelerômetro e giroscópio, os tipos de sensores usados para medir movimento','Foto real · Cmcarreras/Wikimedia Commons · CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Sparkfun_5DOF_Accelerometer_Gyroscope.jpg'),
img('Gravidez',['10 semanas + 2 dias','10s2d'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Embryo_at_10_weeks.JPG','Ultrassom real de embrião humano em torno de 10 semanas','Imagem médica real · X.Compagnion/Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Embryo_at_10_weeks.JPG'),
img('Ser Pai',['tarefa invisível','sem esperar pedido'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Man_washing_dishes.jpg','Homem lavando louça e assumindo uma tarefa doméstica','Foto real · Matt Kingston/Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Man_washing_dishes.jpg'),
img('Mundo',['china coloca em vigor novas restrições','segurança tecnológica'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Beijing_skyline_(cropped).jpg','Vista real do distrito financeiro de Pequim, China','Foto real · Picrazy2/Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Beijing_skyline_(cropped).jpg'),
img('Corinthians',['venda de ingressos para corinthians x fluminense','estudiantes nesta quarta'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Arena_Corinthians_fev_2014.jpg','Neo Química Arena, estádio do Corinthians em São Paulo','Foto real · Vitor123vitin/Wikimedia Commons · CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Arena_Corinthians_fev_2014.jpg'),
img('Viagens',['fotografe o estado do carro alugado','carro alugado antes de sair'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rental_Car.jpg','Veículo real de locadora usado como referência para inspeção de retirada','Foto real · AbdAllah Khankan/Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Rental_Car.jpg'),
img('Música',['prestando atenção só na bateria','bateria ou percussão'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Drum_Set.jpg','Bateria acústica montada para execução musical','Foto real · Visitor7/Wikimedia Commons · CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Drum_Set.jpg'),
img('Tecnologia',['mediatek lança dimensity 9600 pro','primeiro chip móvel de 2 nm'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/MTK_chip.png','Chip real MediaTek Dimensity, referência visual da família de processadores móveis do lançamento','Imagem de produto · MediaTek/Wikimedia Commons','https://commons.wikimedia.org/wiki/File:MTK_chip.png'),
img('Finanças',['bolsas globais caem e treasury','maior rendimento desde 2007','brent acima de us$ 107'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/NYSE_Advanced_Trading_Floor.jpg','Pregão real da Bolsa de Nova York','Foto real · Eduard Hueber/Wikimedia Commons · CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:NYSE_Advanced_Trading_Floor.jpg'),
img('Carros até R$ 70 mil',['pneus contam a mesma história','compare desgaste e idade'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Car_Tire.jpg','Pneu automotivo real visto de perto para inspeção de desgaste','Foto real · Janeset/Wikimedia Commons · CC0','https://commons.wikimedia.org/wiki/File:Car_Tire.jpg'),
img('Motos',['folga da corrente','corrente antes do test-ride'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Motorcycle_chain.jpg','Corrente e coroa de transmissão de uma motocicleta','Foto real · sutulo/Wikimedia Commons · CC0','https://commons.wikimedia.org/wiki/File:Motorcycle_chain.jpg'),
img('Mecânica',['barulho ao esterçar parado','ruído ao esterçar'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Power_steering_rack.jpg','Caixa de direção hidráulica real com terminais internos','Foto real · l0lnix/Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Power_steering_rack.jpg')
];
