import type {RichMediaEntry} from './rich-media';
export const dailyRichMedia20260830:RichMediaEntry[]=[
{label:'Curiosidades',matches:['vênus','rotação completa','243 dias'],tag:'ARTE ESPECÍFICA · CIÊNCIA',title:'Vênus: dia maior que o ano',caption:'Visual específico de rotação lenta e órbita de Vênus.',images:[{url:'/generated/curiosity-venus-day-20260830.svg',alt:'Planeta Vênus com indicação visual de rotação e órbita',caption:'Rotação e órbita de Vênus.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://science.nasa.gov/venus/venus-facts/',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['cristais de carbonato','otocônias','gravidade e aceleração'],tag:'ARTE ESPECÍFICA · CORPO HUMANO',title:'Otocônias e equilíbrio',caption:'Visual específico do ouvido interno e otocônias.',images:[{url:'/generated/curiosity-otoconia-20260830.svg',alt:'Ouvido interno com pequenos cristais representando otocônias',caption:'Otocônias ajudam a perceber gravidade e aceleração.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.nidcd.nih.gov/health/balance-disorders',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['controlador do ssd','wear leveling','células envelheçam'],tag:'ARTE ESPECÍFICA · TECNOLOGIA',title:'Wear leveling em SSD',caption:'Visual específico de blocos NAND e distribuição de gravações.',images:[{url:'/generated/curiosity-ssd-wear-leveling-20260830.svg',alt:'Blocos de memória NAND com fluxo de distribuição de gravações',caption:'Wear leveling distribui gravações na NAND.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.kingston.com/br/ssd/ssd-faq',kind:'REFERENCE'}]},
{label:'Gravidez',matches:['8 semanas exatas','placenta ganhando estrutura','crescimento acelerado'],tag:'ARTE ESPECÍFICA · GESTAÇÃO',title:'Semana 8',caption:'Ilustração educativa de gestação inicial na semana 8.',images:[{url:'/generated/pregnancy-week8-20260830.svg',alt:'Ilustração educativa e não fotorrealista de gestação na semana 8',caption:'Semana 8 de desenvolvimento.',credit:'Father Giulian News · ilustração educativa',sourceUrl:'https://www.nhs.uk/best-start-in-life/pregnancy/week-by-week-guide-to-pregnancy/1st-trimester/week-8/',kind:'REFERENCE'}]},
{label:'Ser Pai',matches:['preparar a segunda-feira','duas coisas','carga mental'],tag:'ARTE ESPECÍFICA · APOIO',title:'Apoio prático',caption:'Visual de parceria e tarefa concluída.',images:[{url:'/generated/father-support-20260830.svg',alt:'Duas pessoas com símbolo visual de tarefa concluída e apoio',caption:'Apoio prático e divisão de carga mental.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.nhs.uk/pregnancy/your-pregnancy-care/your-antenatal-care-and-appointments/',kind:'REFERENCE'}]},
{label:'Brasil',matches:['hepatite b','estudo internacional','hucam-ufes'],tag:'ARTE ESPECÍFICA · PESQUISA',title:'Pesquisa brasileira em hepatite B',caption:'Visual específico de pesquisa biomédica no Brasil.',images:[{url:'/generated/brasil-hepatitis-research-20260830.svg',alt:'Símbolo do Brasil combinado a elementos de pesquisa biomédica',caption:'Pesquisa internacional com participação brasileira.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://agenciabrasil.ebc.com.br/saude/noticia/2026-08/brasil-participa-de-pesquisa-inedita-que-busca-cura-da-hepatite-b',kind:'REFERENCE'}]},
{label:'Mundo',matches:['facções rivais da líbia','roteiro da onu','eleições nacionais'],tag:'ARTE ESPECÍFICA · DIPLOMACIA',title:'Roteiro eleitoral na Líbia',caption:'Visual específico de caminho político e acordo.',images:[{url:'/generated/world-libya-election-roadmap-20260830.svg',alt:'Caminho pontilhado ligando dois pontos com símbolo de acordo',caption:'Roteiro político para eleições.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.reuters.com/world/africa/libya-rivals-agree-roadmap-elections-within-24-months-un-led-talks-2026-08-30/',kind:'REFERENCE'}]},
{label:'Política',matches:['tse migra serviços','nuvem hoje','auditoria dos sistemas'],tag:'ARTE ESPECÍFICA · TSE',title:'Infraestrutura eleitoral',caption:'Visual neutro de instituição e computação em nuvem.',images:[{url:'/generated/politics-tse-cloud-20260830.svg',alt:'Edifício institucional com nuvem de computação',caption:'Migração de serviços e calendário técnico eleitoral.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.tse.jus.br/comunicacao/noticias/2026/Agosto/tse-inicia-migracao-de-servicos-em-nuvem-neste-domingo-30',kind:'REFERENCE'}]},
{label:'Tempo e Clima',matches:['domingo quente','32°c','sem chuva prevista'],tag:'ARTE ESPECÍFICA · SÃO PAULO',title:'Domingo quente em São Paulo',caption:'Visual de sol e skyline urbano.',images:[{url:'/generated/weather-sp-20260830.svg',alt:'Sol sobre silhueta urbana de São Paulo',caption:'Domingo quente e seco em São Paulo.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.cgesp.org/v3/noticias.jsp?data=2026-08-30',kind:'REFERENCE'}]},
{label:'Zona Leste em Foco',matches:['sarau do binho','tatuapé','20 anos'],tag:'ARTE ESPECÍFICA · ZONA LESTE',title:'Sarau do Binho no Tatuapé',caption:'Visual específico de livro e microfone.',images:[{url:'/generated/zona-leste-sarau-20260830.svg',alt:'Livro aberto e microfone representando um sarau',caption:'Sarau do Binho no Tatuapé.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://spmaiscultura.prefeitura.sp.gov.br/todos-eventos',kind:'REFERENCE'}]},
{label:'Corinthians',matches:['recebe o santos hoje','memphis deve começar','clássico'],tag:'ARTE ESPECÍFICA · CORINTHIANS',title:'Clássico de hoje',caption:'Visual específico de futebol e clássico.',images:[{url:'/generated/corinthians-classic-20260830.svg',alt:'Bola estilizada e elementos em preto e branco representando o clássico',caption:'Corinthians x Santos neste domingo.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://ge.globo.com/sp/futebol/brasileirao-serie-a/noticia/2026/08/30/corinthians-x-santos-onde-assistir-ao-vivo-horario-e-escalacoes.ghtml',kind:'REFERENCE'}]},
{label:'Viagens',matches:['paranapiacaba','bate-volta do domingo','ferrovia'],tag:'ARTE ESPECÍFICA · DESTINO',title:'Paranapiacaba',caption:'Visual específico da vila ferroviária e Mata Atlântica.',images:[{url:'/generated/travel-paranapiacaba-20260830.svg',alt:'Vila histórica com montanhas e relógio ferroviário estilizado',caption:'Paranapiacaba como bate-volta.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www3.santoandre.sp.gov.br/turismosantoandre/vila-ferroviaria-paranapiacaba/',kind:'REFERENCE'}]},
{label:'Música',matches:['galo de briga','galo fest show','vila silva teles'],tag:'ARTE ESPECÍFICA · ROCK',title:'Galo Fest Show',caption:'Visual específico de guitarra e palco de rock.',images:[{url:'/generated/music-galo-20260830.svg',alt:'Guitarra e elementos de palco representando show de rock',caption:'Galo Fest Show neste domingo.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://spmaiscultura.prefeitura.sp.gov.br/todos-eventos',kind:'REFERENCE'}]},
{label:'Games',matches:['último dia','programação oficial de domingo','gamescom'],tag:'ARTE ESPECÍFICA · GAMESCOM',title:'Último dia da gamescom',caption:'Visual específico de controle e evento de games.',images:[{url:'/generated/games-gamescom-sunday-20260830.svg',alt:'Controle de videogame estilizado representando o último dia da gamescom',caption:'gamescom em seu último dia.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.gamescom.global/en/program',kind:'REFERENCE'}]},
{label:'Tecnologia',matches:['aposenta hoje','gpt oficial do dall·e','dall·e'],tag:'ARTE ESPECÍFICA · IA',title:'Transição do DALL·E GPT',caption:'Visual de imagem digital com sinal de encerramento.',images:[{url:'/generated/technology-dalle-retirement-20260830.svg',alt:'Quadro de imagem digital atravessado por traço de encerramento',caption:'Retirada do GPT oficial do DALL·E.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://help.openai.com/en/articles/6825453-chatgpt-release-notes',kind:'REFERENCE'}]},
{label:'Finanças',matches:['g20 de finanças','g20 financeiro','tarifas'],tag:'ARTE ESPECÍFICA · G20',title:'G20 financeiro',caption:'Visual global com gráfico de mercado.',images:[{url:'/generated/finance-g20-20260830.svg',alt:'Globo estilizado com linha de mercado financeiro',caption:'Encontro financeiro do G20.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.reuters.com/world/china/us-treasurys-bessent-faces-g20-diplomacy-test-amid-tariffs-iran-war-bond-turmoil-2026-08-30/',kind:'REFERENCE'}]},
{label:'AppSec / SSDLC',matches:['metasploit recebe hoje','langflow','cve-2026-18729'],tag:'ARTE ESPECÍFICA · APPSEC',title:'Langflow e tooling de exploit',caption:'Visual específico de shield, código e alerta.',images:[{url:'/generated/appsec-langflow-20260830.svg',alt:'Escudo com conexões de código e sinal de alerta',caption:'Sinal novo de tooling para Langflow.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://github.com/rapid7/metasploit-framework/issues/21847',kind:'REFERENCE'}]},
{label:'Carros até R$ 70 mil',matches:['câmbio frio e quente','test-drive','até r$ 70 mil'],tag:'ARTE ESPECÍFICA · USADO',title:'Teste de câmbio em usado',caption:'Visual específico de carro e transmissão.',images:[{url:'/generated/cars-transmission-20260830.svg',alt:'Carro estilizado com engrenagem representando transmissão',caption:'Teste de câmbio em carro usado.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.gov.br/transportes/pt-br/assuntos/transito/senatran',kind:'REFERENCE'}]},
{label:'Motos',matches:['calo','rolamento de caixa','direção'],tag:'ARTE ESPECÍFICA · MOTO',title:'Inspeção de direção',caption:'Visual específico de motocicleta e guidão.',images:[{url:'/generated/motos-steering-20260830.svg',alt:'Motocicleta estilizada com destaque na direção',caption:'Inspeção de caixa de direção em moto usada.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria',kind:'REFERENCE'}]},
{label:'Mecânica',matches:['bateria fraca','defeitos eletrônicos','sistema de carga'],tag:'ARTE ESPECÍFICA · ELÉTRICA',title:'Bateria e sistema de carga',caption:'Visual específico de bateria automotiva e medição elétrica.',images:[{url:'/generated/mechanic-battery-20260830.svg',alt:'Bateria automotiva estilizada com símbolo de medição',caption:'Diagnóstico de bateria e sistema de carga.',credit:'Father Giulian News · arte editorial',sourceUrl:'https://www.nhtsa.gov/vehicle-safety',kind:'REFERENCE'}]}
];
