import type {RichMediaEntry} from './rich-media';
const ICON:Record<string,string>={'Papo de hoje':'🗺️','Desafio do casal':'🎧','Ciência':'⚡','Corpo Humano':'🫃','Tecnologia':'🔌','Gravidez':'🤰','Ser Pai':'🧰','Mundo':'🛢️','Política':'🏛️','Tempo e Clima':'⛈️','Viagens':'☂️','Música':'🥁','Carros até R$70 mil':'❄️','Motos':'🛞','Mecânica':'⚙️'};
const PALETTE:Record<string,[string,string]>={'Papo de hoje':['#1f5d50','#d7f3ea'],'Desafio do casal':['#713c6f','#f5d7f1'],'Ciência':['#775b11','#fff0a6'],'Corpo Humano':['#8d4660','#f8d9e4'],'Tecnologia':['#0f5f73','#c9f0f8'],'Gravidez':['#8b5369','#f8dde8'],'Ser Pai':['#375f42','#d9efdc'],'Mundo':['#445a77','#dae5f5'],'Política':['#60533f','#eee4d2'],'Tempo e Clima':['#355f83','#d7ebfa'],'Viagens':['#3f6d6a','#d9f1ee'],'Música':['#754a35','#f1ddd2'],'Carros até R$70 mil':['#365d73','#d8eaf4'],'Motos':['#555b67','#e4e6eb'],'Mecânica':['#625746','#ece4d8']};
const art=(label:string,shape:string)=>{const [base,light]=PALETTE[label]??['#455d78','#dce7f5'];const icon=ICON[label]??'●';return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${base}"/><stop offset="1" stop-color="#25364a"/></linearGradient></defs><rect width="1080" height="1920" fill="url(#g)"/><circle cx="540" cy="690" r="300" fill="${light}" opacity=".2"/><circle cx="540" cy="690" r="235" fill="${light}" opacity=".16"/><text x="540" y="790" text-anchor="middle" font-size="260" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${icon}</text><path d="M210 1210 H870" stroke="${light}" stroke-width="8" opacity=".75"/><text x="540" y="1360" text-anchor="middle" font-size="70" font-weight="700" font-family="Arial,sans-serif" fill="white">${shape}</text><text x="540" y="1460" text-anchor="middle" font-size="34" font-family="Arial,sans-serif" fill="${light}">${label}</text></svg>`)}`};
export const dailyRichMedia20260901:RichMediaEntry[]=[
{label:'Papo de hoje',matches:['lugar perto de casa','exploraram direito'],tag:'ARTE ESPECÍFICA · PAPO',title:'Explorar perto',caption:'Mapa de bairro e conversa.',images:[{url:art('Papo de hoje','MAPA + CAFÉ'),alt:'Arte editorial com mapa e ponto de encontro para conversa sobre um lugar próximo',caption:'Mapa e conversa.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.gov.br/turismo/',kind:'REFERENCE'}]},
{label:'Desafio do casal',matches:['escolhe uma música para o outro','ouçam as duas'],tag:'ARTE ESPECÍFICA · DESAFIO',title:'Troca musical',caption:'Duas escolhas, duas escutas.',images:[{url:art('Desafio do casal','2 MÚSICAS'),alt:'Arte editorial com dois discos e setas de troca entre o casal',caption:'Troca musical.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.youtube.com/',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['relâmpago pode aquecer','50 mil'],tag:'ARTE ESPECÍFICA · CIÊNCIA',title:'Calor do relâmpago',caption:'Ar aquecido pela descarga.',images:[{url:art('Ciência','RELÂMPAGO'),alt:'Arte educativa de descarga elétrica aquecendo uma coluna de ar',caption:'Relâmpago.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.weather.gov/safety/lightning-temperature',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['muco e bicarbonato','estômago'],tag:'ARTE ESPECÍFICA · CORPO HUMANO',title:'Barreira gástrica',caption:'Muco e bicarbonato.',images:[{url:art('Corpo Humano','MUCO + HCO₃'),alt:'Arte educativa do estômago com camada protetora de muco e bicarbonato',caption:'Barreira gástrica.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://pubmed.ncbi.nlm.nih.gov/15591243/',kind:'REFERENCE'}]},
{label:'Curiosidades',matches:['usb power delivery negocia','240 w'],tag:'ARTE ESPECÍFICA · TECNOLOGIA',title:'Negociação USB PD',caption:'Fonte, cabo e dispositivo.',images:[{url:art('Tecnologia','USB PD'),alt:'Arte educativa com carregador USB-C negociando energia com dispositivo',caption:'USB PD.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.usb.org/usb-charger-pd',kind:'REFERENCE'}]},
{label:'Gravidez',matches:['8 semanas + 2 dias','8s2d'],tag:'ILUSTRAÇÃO EDUCATIVA',title:'8 semanas + 2 dias',caption:'Desenvolvimento inicial.',images:[{url:art('Gravidez','8S2D'),alt:'Ilustração educativa abstrata de desenvolvimento embrionário com 8 semanas e 2 dias',caption:'8S2D.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.nhs.uk/pregnancy/week-by-week/1-to-12/8-weeks/',kind:'REFERENCE'}]},
{label:'Ser Pai',matches:['estação de apoio','manhã começar'],tag:'ARTE ESPECÍFICA · APOIO',title:'Estação de apoio',caption:'Água e itens práticos.',images:[{url:art('Ser Pai','APOIO'),alt:'Arte editorial com água, lanche e itens de apoio organizados',caption:'Apoio prático.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.cdc.gov/hearher/',kind:'REFERENCE'}]},
{label:'Mundo',matches:['petróleo sobe','hormuz'],tag:'ARTE ESPECÍFICA · MUNDO',title:'Petróleo e Hormuz',caption:'Energia e tensão no Golfo.',images:[{url:art('Mundo','HORMUZ'),alt:'Arte editorial com estreito, navio-tanque e gráfico de petróleo',caption:'Hormuz.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.reuters.com/business/energy/oil-prices-rise-latest-fighting-resurrects-middle-east-supply-disruption-risks-2026-09-01/',kind:'REFERENCE'}]},
{label:'Política',matches:['comissão mista','10h'],tag:'ARTE ESPECÍFICA · AGENDA',title:'Comissão mista às 10h',caption:'Agenda parlamentar, sem presumir resultado.',images:[{url:art('Política','AGENDA 10H'),alt:'Arte editorial neutra com plenário e relógio marcando dez horas',caption:'Agenda 10h.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.camara.leg.br/noticias/1301428-comissao-mista-adia-para-esta-terca-feira-votacao-do-fim-da-taxa-das-blusinhas',kind:'REFERENCE'}]},
{label:'Tempo e Clima',matches:['alerta amarelo','tempestade'],tag:'ARTE ESPECÍFICA · TEMPO',title:'Alerta de tempestade',caption:'Chuva, vento e granizo possíveis.',images:[{url:art('Tempo e Clima','TEMPESTADE'),alt:'Arte meteorológica com nuvem, raio, chuva e vento sobre São Paulo',caption:'Alerta de tempestade.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://portal.inmet.gov.br/',kind:'REFERENCE'}]},
{label:'Viagens',matches:['plano b de chuva','opção coberta'],tag:'ARTE ESPECÍFICA · VIAGEM',title:'Plano B de chuva',caption:'Passeio flexível.',images:[{url:art('Viagens','PLANO B'),alt:'Arte editorial de rota com abrigo coberto e retorno fácil',caption:'Plano B.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.gov.br/turismo/',kind:'REFERENCE'}]},
{label:'Música',matches:['bateria e na percussão','escuta ativa'],tag:'ARTE ESPECÍFICA · MÚSICA',title:'Ouça a bateria',caption:'Escuta focada no ritmo.',images:[{url:art('Música','BATERIA'),alt:'Arte editorial com bateria, pratos e onda rítmica',caption:'Escuta ativa.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.gov.br/cultura/',kind:'REFERENCE'}]},
{label:'Carros até R$ 70 mil',matches:['ar-condicionado','até r$70 mil'],tag:'ARTE ESPECÍFICA · CARROS',title:'Ar-condicionado em usado',caption:'Checklist até R$70 mil.',images:[{url:art('Carros até R$70 mil','A/C'),alt:'Arte editorial de carro usado com fluxo do ar-condicionado em destaque',caption:'Ar-condicionado.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.gov.br/senatran/',kind:'REFERENCE'}]},
{label:'Motos',matches:['pneus contam idade','rachaduras'],tag:'ARTE ESPECÍFICA · MOTOS',title:'Pneus da moto',caption:'Idade e desgaste.',images:[{url:art('Motos','PNEUS'),alt:'Arte editorial de pneu de motocicleta com sulcos e lateral destacados',caption:'Pneus.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria',kind:'REFERENCE'}]},
{label:'Mecânica',matches:['alternador','sistema de carga'],tag:'ARTE ESPECÍFICA · MECÂNICA',title:'Sistema de carga',caption:'Bateria e alternador.',images:[{url:art('Mecânica','ALTERNADOR'),alt:'Arte editorial do circuito entre alternador e bateria automotiva',caption:'Alternador.',credit:'Father Giulian News · arte editorial específica',sourceUrl:'https://www.nhtsa.gov/vehicle-safety',kind:'REFERENCE'}]}
];
