import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'MÍDIA REAL · 14/09',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260914:RichMediaEntry[]=[
img('Papo de hoje',['dia de hoje virasse uma foto','o que apareceria nela'],'https://www.dynamicsgex.com.au/hubfs/alexander-wang-KjyrxSHwqTg-unsplash.jpg','Câmera DSLR real montada em tripé pronta para fotografar','Foto real · Alexander Wang/Unsplash','https://www.dynamicsgex.com.au/learning_hub/best-slr-camera-for-core-tray-photography-for-small-med-big-budgets'),
img('Desafio do casal',['comida que nenhum dos dois pede','nenhum dos dois pede há muito tempo'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Table%20set%20for%20dinner%20in%20a%20restaurant.jpg','Mesa de restaurante preparada para uma refeição compartilhada','Foto real · Shixart1985/Wikimedia Commons · CC BY 2.0 · 2026','https://commons.wikimedia.org/wiki/File:Table_set_for_dinner_in_a_restaurant.jpg'),
img('Curiosidades',['beija-flores conseguem voar para trás','pairar e também voar para trás'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hummingbird%20Hovering%20and%20Red%20Flowers.jpg','Beija-flor real pairando diante de flores vermelhas','Foto real · Amaury Laporte/Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Hummingbird_Hovering_and_Red_Flowers.jpg'),
img('Curiosidades',['som viaja mais de quatro vezes','1.500 m/s','hidrofones'],'https://sanctuaries.noaa.gov/media/img/2024-fknms-hydrophone-400.jpg','Hidrofone instalado no fundo do mar nos Florida Keys','Foto real · NOAA National Marine Sanctuaries','https://sanctuaries.noaa.gov/notes/2024/hydrophones.html'),
img('Curiosidades',['crateras perto dos polos da lua permanecem em sombra permanente','sombra permanente'],'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia13/pia13720/PIA13720.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1214&w=1214','Mapa real de iluminação do polo sul lunar, com Shackleton e regiões permanentemente sombreadas','NASA/GSFC/Arizona State University · Lunar Reconnaissance Orbiter','https://science.nasa.gov/photojournal/south-pole-illumination-map/'),
img('Curiosidades',['poeira transportada desde o saara','saara e amazônia'],'https://svs.gsfc.nasa.gov/vis/a010000/a011700/a011775/G2015-021-Saharan_Dust_Travels_To_Amazon-1920-Master_youtube_hq_print.jpg','Imagem de satélite da NASA mostrando poeira do Saara atravessando o Atlântico em direção à América do Sul','Visual científico real · NASA Goddard Scientific Visualization Studio','https://svs.gsfc.nasa.gov/11775'),
img('Curiosidades',['controles remotos comuns enviam comandos usando luz infravermelha','controle remoto tradicional'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Remote-Control-Infrared.jpg','Controle remoto real emitindo infravermelho observado por uma câmera digital','Foto real · Michael Malak/Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Remote-Control-Infrared.jpg'),
img('Gravidez',['10 semanas + 1 dia','10s1d'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Embryo%20at%2010%20weeks.JPG','Ultrassom real de embrião humano em torno de 10 semanas','Imagem médica real · X.Compagnion/Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Embryo_at_10_weeks.JPG'),
img('Ser Pai',['deixe a próxima manhã mais fácil','prepare hoje o básico'],'https://cdn.shopify.com/s/files/1/0869/4382/files/Blog-Header-Childbirth-ClassesArtboard_1_copy.jpg?v=1695834315','Parceiro oferecendo apoio físico e prático durante a gestação','Foto real · Kindred Bravely','https://www.kindredbravely.com/blogs/bravely/what-are-childbirth-classes'),
img('Política',['14 de setembro concentra prazos','sistemas eleitorais','substituição de candidaturas'],'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Sede_do_Tribunal_Superior_Eleitoral%2C_em_Bras%C3%ADlia.jpg/1280px-Sede_do_Tribunal_Superior_Eleitoral%2C_em_Bras%C3%ADlia.jpg','Sede do Tribunal Superior Eleitoral em Brasília','Foto real · Alexandresena/Wikimedia Commons · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Sede_do_Tribunal_Superior_Eleitoral,_em_Bras%C3%ADlia.jpg'),
img('Tempo e Clima',['segunda começa chuvosa','máxima perto de 19','chuvosa e fria'],'https://f.i.uol.com.br/fotografia/2026/09/13/17893367256aa71c9525e8a_1789336725_1x1_md.jpg','Rua residencial inundada no Jardim Pantanal durante as chuvas que antecedem a segunda-feira','Foto real · Clarice Bittencourt/Divulgação · 13/09/2026','https://www1.folha.uol.com.br/cotidiano/2026/09/rio-tiete-transborda-em-quatro-pontos-na-grande-sao-paulo.shtml'),
img('Viagens',['salve o essencial','funcionar sem internet','mapa offline'],'https://1.bp.blogspot.com/-Z7jRl1JGwoo/To3hdtSaORI/AAAAAAAAAnI/JGoTMJ3uYvU/s1600/Passport.jpg','Passaporte e cartão de embarque representando documentos essenciais de viagem','Foto real · referência de viagem','https://commons.wikimedia.org/wiki/Category:Boarding_passes'),
img('Música',['intensidade cresce','crescendo','arranjo constrói'],'https://cso.org/media/w0gj5m5w/cso20211111_058.jpg?mode=max&quality=80&upscale=false&width=1024','Orquestra sinfônica em apresentação com regente conduzindo a dinâmica musical','Foto real · Chicago Symphony Orchestra','https://cso.org/experience/audio/13572/hrusa-conducts-dvorak-6'),
img('Tecnologia',['ações ligadas à ia despencam','softbank chegou a cair 13,2','kioxia 9,8'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Inside%20Tokyo%20Stock%20Exchange%20(98952).jpg','Interior real da Bolsa de Valores de Tóquio, mercado onde ações ligadas à IA abriram em forte queda','Foto real · Syced/Wikimedia Commons · CC0 · 2025','https://commons.wikimedia.org/wiki/File:Inside_Tokyo_Stock_Exchange_(98952).jpg'),
img('Finanças',['ouro recua','ouro à vista caiu 0,3','us$ 4.334,31'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Gold%20bullion%20bars.jpg','Barras reais de ouro representando o mercado internacional do metal','Foto real · Stevebidmead/Wikimedia Commons · CC0','https://commons.wikimedia.org/wiki/File:Gold_bullion_bars.jpg'),
img('Security Briefing',['palantir, nvidia e booz allen restringem','zero retenção','tarefas menos sensíveis'],'https://fotografias-2.larazon.es/clipping/cmsimages01/2026/04/20/2869DE46-4631-4CB9-BA70-60EA409C07BC/palantir_58.jpg?crop=1709%2C969%2Cx0%2Cy85&format=webply&height=567&optimize=high&width=1000','Entrada real de escritório da Palantir, uma das empresas citadas na reportagem sobre restrições ao uso de modelos de IA','Foto real · Palantir / arquivo jornalístico','https://www.reuters.com/business/palantir-nvidia-curb-ai-model-use-over-data-fears-information-reports-2026-09-14/'),
img('Carros até R$ 70 mil',['teste o ar-condicionado','parado e em movimento','ar realmente esfria'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ventilation_system_in_a_modern_vehicle_interior_showcasing_adjustable_air_vents_and_sleek_design_elements.jpg','Saídas de ventilação e controles reais no interior de um automóvel','Foto real · Shixart1985/Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Ventilation_system_in_a_modern_vehicle_interior_showcasing_adjustable_air_vents_and_sleek_design_elements.jpg'),
img('Motos',['primeira partida do dia','partida realmente a frio','motor frio'],'https://images.caradisiac.com/images/8/2/3/9/138239/S1-essai-mash-seventy-five-125-cm3-les-details-465484.jpg','Mão acionando o afogador no carburador de uma motocicleta durante procedimento de partida','Foto real · Caradisiac','https://www.caradisiac.com/essai-mash-seventy-five-125-cm3-les-details-138242.htm'),
img('Mecânica',['medir o óleo','vareta','nível do óleo'],'https://d34w7g4gy10iej.cloudfront.net/photos/2505/9061210.jpg','Militar verificando o nível do óleo do motor com a vareta durante manutenção preventiva','Foto real · U.S. Army/DVIDS · domínio público','https://commons.wikimedia.org/wiki/File:OIL_DIPSTICK_(9061210).jpg')
];
