import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'MÍDIA REAL · 14/09',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260914:RichMediaEntry[]=[
img('Papo de hoje',['dia de hoje virasse uma foto','o que apareceria nela'],'https://www.dynamicsgex.com.au/hubfs/alexander-wang-KjyrxSHwqTg-unsplash.jpg','Câmera DSLR real montada em tripé pronta para fotografar','Foto real · Alexander Wang/Unsplash','https://www.dynamicsgex.com.au/learning_hub/best-slr-camera-for-core-tray-photography-for-small-med-big-budgets'),
img('Desafio do casal',['comida que nenhum dos dois pede','nenhum dos dois pede há muito tempo'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Table%20set%20for%20dinner%20in%20a%20restaurant.jpg','Mesa de restaurante preparada para uma refeição compartilhada','Foto real · Shixart1985/Wikimedia Commons · CC BY 2.0 · 2026','https://commons.wikimedia.org/wiki/File:Table_set_for_dinner_in_a_restaurant.jpg'),
img('Curiosidades',['polvos têm três corações','sangue realmente azulado','hemocianina'],'https://oceanservice.noaa.gov/news/july17/pramp3.jpg','Polvo real fotografado pela NOAA em um recife do Pacífico','Foto real · NOAA Ocean Service','https://oceanservice.noaa.gov/news/july17/pacific-mission.html'),
img('Curiosidades',['som viaja mais de quatro vezes','1.500 m/s','hidrofones'],'https://sanctuaries.noaa.gov/media/img/2024-fknms-hydrophone-400.jpg','Hidrofone instalado no fundo do mar nos Florida Keys','Foto real · NOAA National Marine Sanctuaries','https://sanctuaries.noaa.gov/notes/2024/hydrophones.html'),
img('Curiosidades',['dia em vênus dura mais','243 dias','225 dias'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Venus-real_color.jpg','Vênus em imagem planetária real processada a partir de dados científicos','Imagem planetária · Wikimedia Commons','https://science.nasa.gov/venus/venus-facts/'),
img('Curiosidades',['raio pode aquecer o ar','50 mil','cinco vezes mais quente'],'https://cdn.mos.cms.futurecdn.net/KjbjqXYom2ZoxVutF97dAd.jpg','Descargas de raios fotografadas durante uma tempestade noturna','Foto real · NOAA Photo Library','https://www.weather.gov/safety/lightning-temperature'),
img('Curiosidades',['qr codes conseguem recuperar','reed-solomon','danificada'],'https://upload.wikimedia.org/wikipedia/commons/a/ae/QRpedia_plaque_for_Shire_Hall%2C_Monmouth.jpg','Placa física com QR Code instalada em edifício histórico','Foto real · Wikimedia Commons','https://www.qrcode.com/en/about/error_correction.html'),
img('Gravidez',['10 semanas + 1 dia','10s1d'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Embryo%20at%2010%20weeks.JPG','Ultrassom real de embrião humano em torno de 10 semanas','Imagem médica real · X.Compagnion/Wikimedia Commons · domínio público','https://commons.wikimedia.org/wiki/File:Embryo_at_10_weeks.JPG'),
img('Ser Pai',['deixe a próxima manhã mais fácil','prepare hoje o básico'],'https://cdn.shopify.com/s/files/1/0869/4382/files/Blog-Header-Childbirth-ClassesArtboard_1_copy.jpg?v=1695834315','Parceiro oferecendo apoio físico e prático durante a gestação','Foto real · Kindred Bravely','https://www.kindredbravely.com/blogs/bravely/what-are-childbirth-classes'),
img('Política',['14 de setembro concentra prazos','sistemas eleitorais','substituição de candidaturas'],'https://www.tse.jus.br/imagens/fotos/fachada-do-tse-2025-24/@@images/image-1140-8465a3c20218825c3dabc5dcac7c65b9.jpeg','Edifício-sede do Tribunal Superior Eleitoral em Brasília','Foto oficial · Luiz Roberto/Secom/TSE','https://www.tse.jus.br/comunicacao/noticias/2026/Marco/eleicoes-2026-confira-as-principais-datas-do-calendario-eleitoral'),
img('Tempo e Clima',['segunda começa chuvosa','máxima perto de 19','chuvosa e fria'],'https://f.i.uol.com.br/fotografia/2026/09/13/17893367256aa71c9525e8a_1789336725_1x1_md.jpg','Rua residencial inundada no Jardim Pantanal durante as chuvas que antecedem a segunda-feira','Foto real · Clarice Bittencourt/Divulgação · 13/09/2026','https://www1.folha.uol.com.br/cotidiano/2026/09/rio-tiete-transborda-em-quatro-pontos-na-grande-sao-paulo.shtml'),
img('Viagens',['salve o essencial','funcionar sem internet','mapa offline'],'https://1.bp.blogspot.com/-Z7jRl1JGwoo/To3hdtSaORI/AAAAAAAAAnI/JGoTMJ3uYvU/s1600/Passport.jpg','Passaporte e cartão de embarque representando documentos essenciais de viagem','Foto real · referência de viagem','https://commons.wikimedia.org/wiki/Category:Boarding_passes'),
img('Música',['intensidade cresce','crescendo','arranjo constrói'],'https://cso.org/media/w0gj5m5w/cso20211111_058.jpg?mode=max&quality=80&upscale=false&width=1024','Orquestra sinfônica em apresentação com regente conduzindo a dinâmica musical','Foto real · Chicago Symphony Orchestra','https://cso.org/experience/audio/13572/hrusa-conducts-dvorak-6'),
img('Carros até R$ 70 mil',['teste o ar-condicionado','parado e em movimento','ar realmente esfria'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ventilation_system_in_a_modern_vehicle_interior_showcasing_adjustable_air_vents_and_sleek_design_elements.jpg','Saídas de ventilação e controles reais no interior de um automóvel','Foto real · Shixart1985/Wikimedia Commons · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Ventilation_system_in_a_modern_vehicle_interior_showcasing_adjustable_air_vents_and_sleek_design_elements.jpg'),
img('Motos',['primeira partida do dia','partida realmente a frio','motor frio'],'https://images.caradisiac.com/images/8/2/3/9/138239/S1-essai-mash-seventy-five-125-cm3-les-details-465484.jpg','Mão acionando o afogador no carburador de uma motocicleta durante procedimento de partida','Foto real · Caradisiac','https://www.caradisiac.com/essai-mash-seventy-five-125-cm3-les-details-138242.htm'),
img('Mecânica',['medir o óleo','vareta','nível do óleo'],'https://d34w7g4gy10iej.cloudfront.net/photos/2505/9061210.jpg','Militar verificando o nível do óleo do motor com a vareta durante manutenção preventiva','Foto real · U.S. Army/DVIDS · domínio público','https://commons.wikimedia.org/wiki/File:OIL_DIPSTICK_(9061210).jpg')
];
