import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl=url):RichMediaEntry=>({label,matches,tag:'MÍDIA · 04/10',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl:sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20261004:RichMediaEntry[]=[
img('Papo de hoje',['que valor','aprenda vendo vocês'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pregnancy.jpg','Casal durante a gestação','Soul Flora / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pregnancy.jpg'),
img('Desafio do casal',['três músicas','microplaylist'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Headphones_1.jpg','Fones de ouvido para escuta musical','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Headphones_1.jpg'),
img('Curiosidades',['Golfinhos','assobios-assinatura'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Tursiops_truncatus_01.jpg','Golfinho-nariz-de-garrafa','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Tursiops_truncatus_01.jpg'),
img('Curiosidades',['O tecido ósseo','continuamente remodelado'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Human_skeleton_front_en.svg.png','Esqueleto humano em referência anatômica','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Human_skeleton_front_en.svg'),
img('Curiosidades',['Saturno','densidade média'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Saturn_during_Equinox.jpg','Saturno fotografado pela missão Cassini','NASA / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Saturn_during_Equinox.jpg'),
img('Gravidez',['13 semanas','13 SEMANAS'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pregnancy.jpg','Gestação em imagem real de contexto','Soul Flora / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pregnancy.jpg'),
img('Ser Pai',['proteja o ritmo','presença prática'],'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg','Parceiro oferecendo apoio durante a gestação','CDC Hear Her','https://www.cdc.gov/hearher/about/support-family-friends.html'),
img('Brasil',['Brasil vota hoje','primeiro turno'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg','Urnas eletrônicas brasileiras','Abdias Pinheiro / SECOM / TSE','https://commons.wikimedia.org/wiki/File:Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg'),
img('Mundo',['Merz chega a Kyiv','acordo de drones'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Friedrich_Merz_in_2026.jpg','Chanceler alemão Friedrich Merz','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Friedrich_Merz_in_2026.jpg'),
img('Política',['Primeiro turno','apuração oficial'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg','Urnas eletrônicas brasileiras','Abdias Pinheiro / SECOM / TSE','https://commons.wikimedia.org/wiki/File:Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg'),
img('Tempo e Clima',['pancadas de chuva','domingo de eleição'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rain_on_window.jpg','Chuva observada através de uma janela','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Rain_on_window.jpg'),
img('Zona Leste em Foco',['transporte gratuito','operação reforçada'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Corinthians-Itaquera_station_(Linha_3-Vermelha%2C_Linha_11-Coral)%2C_SP%2C_2026-03-01_(25).jpg','Estação Corinthians-Itaquera na Zona Leste de São Paulo','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Corinthians-Itaquera_station_(Linha_3-Vermelha,_Linha_11-Coral),_SP,_2026-03-01_(25).jpg'),
img('Corinthians',['Corinthians fecha final feminina','vira a chave'],'https://agemt.pucsp.br/sites/default/files/inline-images/539970296534d0f05c147o.jpg','São Paulo e Corinthians em confronto pelo futebol feminino','Agemt / PUC-SP','https://agemt.pucsp.br/noticias/corinthians-supera-sao-paulo-no-morumbis'),
img('Viagens',['justificativa','domicílio eleitoral'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Boarding_Pass_Confirmation_Card%2C_Baiyun_Airport.jpg','Cartão de embarque em contexto de viagem','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Boarding_Pass_Confirmation_Card,_Baiyun_Airport.jpg'),
img('Música',['lançamentos que movimentaram','seleção dos lançamentos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Live_rock_concert_performance_featuring_musicians_playing_guitar_on_stage_at_night_with_vibrant_lighting_effects.jpg','Músicos tocando guitarra em apresentação ao vivo','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Live_rock_concert_performance_featuring_musicians_playing_guitar_on_stage_at_night_with_vibrant_lighting_effects.jpg'),
img('Games',['Steam recebe novos jogos','LEGO PlayStation'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/PSX-Console-wController.jpg','PlayStation original com controle','Evan-Amos / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:PSX-Console-wController.jpg'),
img('Tecnologia',['força-tarefa','riscos e oportunidades da IA'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Data_Center.jpg','Infraestrutura de data center associada a computação e IA','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Data_Center.jpg'),
img('Finanças',['Mercados fechados hoje','abertura de segunda-feira'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Stock-exchange-trading-floor.jpg','Pregão de bolsa com operadores e terminais de mercado','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Stock-exchange-trading-floor.jpg'),
img('Security Briefing',['Coreia do Sul','vazamentos de dados'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Server_Rack_(54126210834).jpg','Rack de servidores em ambiente de infraestrutura digital','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Server_Rack_(54126210834).jpg'),
img('Cyber Security',['Rejetto HFS','CVE-2026-61500'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/CSIRO_ScienceImage_2042_A_row_of_computer_servers_in_a_server_rack.jpg','Servidores em rack usados como contexto de segurança de sistemas','CSIRO / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_2042_A_row_of_computer_servers_in_a_server_rack.jpg'),
img('AppSec / SSDLC',['CVE-2026-105123','upload com caminho'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Programming_code.jpg','Código de software exibido em tela','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Programming_code.jpg'),
img('Carros até R$ 70 mil',['radar real de usados','R$64.890'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Used_Car_Lot_(6806377146).jpg','Pátio de automóveis usados à venda','John Fowler / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Used_Car_Lot_(6806377146).jpg'),
img('Motos',['domingo de chuva','checagem rápida de pneus'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/HONDA%20CBX%20250%20TWISTER.jpg','Motocicleta Honda CBX 250 Twister em imagem real','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:HONDA_CBX_250_TWISTER.jpg'),
img('Mecânica',['palhetas e pneus','domingo chuvoso'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rainy_Windshield_Wipers.jpg','Para-brisa com chuva e limpadores em funcionamento','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Rainy_Windshield_Wipers.jpg')
];
