import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl=url):RichMediaEntry=>({label,matches,tag:'MÍDIA · 03/10',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20261003:RichMediaEntry[]=[
img('Papo de hoje',['lembrança simples','criar antes do bebê'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pregnancy.jpg','Casal durante a gestação','Soul Flora / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pregnancy.jpg'),
img('Desafio do casal',['cápsula do tempo','20 minutos sem tela'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Family_photo_album.jpg','Álbum de fotografias usado para guardar memórias','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Family_photo_album.jpg'),
img('Curiosidades',['corvos reconhecem rostos','reconhecer rostos humanos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Corvus_brachyrhynchos_30196.JPG','Corvo-americano em fotografia real','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Corvus_brachyrhynchos_30196.JPG'),
img('Curiosidades',['piscar espalha a lágrima','superfície dos olhos'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Human_eye_with_blood_vessels.jpg','Olho humano em fotografia de referência','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Human_eye_with_blood_vessels.jpg'),
img('Curiosidades',['Lua se afastando','afastando lentamente da Terra'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/FullMoon2010.jpg','Lua cheia fotografada da Terra','Gregory H. Revera / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:FullMoon2010.jpg'),
img('Gravidez',['12 semanas + 6 dias','12S6D'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pregnancy.jpg','Gestação em imagem real de contexto','Soul Flora / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pregnancy.jpg'),
img('Ser Pai',['aliviar o domingo','antecipe uma tarefa'],'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg','Parceiro oferecendo apoio durante a gestação','CDC Hear Her','https://www.cdc.gov/hearher/about/support-family-friends.html'),
img('Brasil',['transporte coletivo será gratuito','primeiro turno'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bus_in_Sao_Paulo_Brazil.jpg','Ônibus urbano em São Paulo','Wikimedia Commons','https://commons.wikimedia.org/'),
img('Política',['véspera da eleição','bandeiras móveis'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg','Urnas eletrônicas brasileiras','Abdias Pinheiro / SECOM / TSE','https://commons.wikimedia.org/wiki/File:Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg'),
img('Zona Leste em Foco',['Shopping Penha','Outubro Rosa'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pink_ribbon.svg.png','Laço rosa, símbolo internacional de conscientização sobre câncer de mama','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pink_ribbon.svg'),
img('Corinthians',['São Paulo x Corinthians','final do Brasileirão Feminino'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Neo_Quimica_Arena_2022.jpg','Estádio do Corinthians em fotografia real de contexto','Wikimedia Commons','https://commons.wikimedia.org/'),
img('Carros',['R$70 mil','70 mil'],'https://editorial.pxcrush.net/carsales/general/editorial/ppsr-recalls-1-uebn.jpg?height=682&width=1024','Pátio de veículos usados','Carsales','https://www.carsales.com.au/editorial/details/safety-recalls-added-to-governments-ppsr-security-registry-140080/'),
img('Motos',['freios','manete'],'https://xprousa.com/cdn/shop/files/220-905003.jpg?v=1712557817','Sistema de freio dianteiro de motocicleta','XProUSA','https://xprousa.com/products/220-905003'),
img('Mecânica',['arrefecimento','líquido de arrefecimento'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Engine_coolant.jpg','Líquido de arrefecimento sendo adicionado a um veículo','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Engine_coolant.jpg')
];
