import type {RichMediaEntry} from './rich-media';

const zonaLesteSvg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><defs><linearGradient id="zlbg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fff4df"/><stop offset="1" stop-color="#f6d38d"/></linearGradient></defs><rect width="1080" height="1920" fill="url(#zlbg)"/><circle cx="540" cy="500" r="300" fill="#b84b2b" opacity=".10"/><path d="M325 760V520l215-180 215 180v240H325Z" fill="#fff" stroke="#8b3e28" stroke-width="16"/><rect x="505" y="570" width="70" height="190" rx="8" fill="#8b3e28" opacity=".85"/><circle cx="540" cy="480" r="34" fill="#f6d38d" stroke="#8b3e28" stroke-width="12"/><path d="M180 980h720" stroke="#8b3e28" stroke-width="12" opacity=".45"/><text x="540" y="1170" text-anchor="middle" font-size="88" font-weight="800" font-family="Arial,sans-serif" fill="#6b2d1e">466 ANOS</text><text x="540" y="1300" text-anchor="middle" font-size="58" font-weight="700" font-family="Arial,sans-serif" fill="#7f3925">SÃO MIGUEL PAULISTA</text><text x="540" y="1420" text-anchor="middle" font-size="39" font-family="Arial,sans-serif" fill="#7f5a44">CULTURA · FÉ · ESPORTE · TRADIÇÃO</text><text x="540" y="1580" text-anchor="middle" font-size="32" font-family="Arial,sans-serif" fill="#8e6a53">AGENDA · FESTEJOS DE SETEMBRO</text></svg>`;

const corinthiansSvg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#111"/><stop offset="1" stop-color="#353535"/></linearGradient></defs><rect width="1080" height="1920" fill="url(#bg)"/><circle cx="540" cy="590" r="300" fill="#fff" opacity=".07"/><circle cx="540" cy="590" r="235" fill="none" stroke="#fff" stroke-width="12" opacity=".28"/><text x="540" y="690" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">⚽</text><path d="M180 1030h720" stroke="#fff" stroke-width="12" opacity=".42"/><text x="540" y="1195" text-anchor="middle" font-size="72" font-weight="800" font-family="Arial,sans-serif" fill="#fff">MEMPHIS TITULAR</text><text x="540" y="1320" text-anchor="middle" font-size="48" font-weight="700" font-family="Arial,sans-serif" fill="#fff">CORINTHIANS × CHAPE</text><text x="540" y="1430" text-anchor="middle" font-size="38" font-family="Arial,sans-serif" fill="#d9d9d9">8 DESFALQUES · 19H30</text><text x="540" y="1580" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#aaa">FATO · ATUALIZAÇÃO · 06/09</text></svg>`;

export const dailyRichMedia202609061917:RichMediaEntry[]=[
{
 label:'Curiosidades',matches:['rã pode congelar parte do corpo','rã pode congelar'],tag:'FOTO REAL · ANIMAL',title:'Wood frog congelada',caption:'Foto real de wood frog congelada, diretamente relacionada à adaptação descrita no card.',images:[{url:'https://www.fws.gov/sites/default/files/styles/large_square/public/images/2025-03/frozen-wood-frog-janet-storey.jpg?h=4521fff0&itok=ySQW9GiZ',alt:'Wood frog parcialmente congelada sobre folhas e gelo',caption:'Wood frog durante congelamento sazonal.',credit:'U.S. Fish & Wildlife Service',sourceUrl:'https://www.fws.gov/species/wood-frog-rana-sylvatica',kind:'PHOTO'}],relatedLabel:'U.S. Fish & Wildlife Service · Wood Frog',relatedHref:'https://www.fws.gov/species/wood-frog-rana-sylvatica'
},
{
 label:'Curiosidades',matches:['poeira africana ajuda','poeira africana','amazônia'],tag:'IMAGEM SATELITAL · NASA',title:'Poeira do Saara atravessa o Atlântico',caption:'Visualização da pluma de poeira cruzando o Atlântico em direção à América do Sul, ligada diretamente à curiosidade sobre nutrientes da Amazônia.',images:[{url:'https://assets-jpcust.jwpsrv.com/thumbnails/y0tt3fk3-720.jpg',alt:'Imagem de satélite mostrando poeira do Saara atravessando o Atlântico em direção à Amazônia',caption:'Transporte transatlântico de poeira saariana observado por satélite.',credit:'NASA/CALIPSO · visualização publicada pela TIME',sourceUrl:'https://www.nasa.gov/centers-and-facilities/goddard/nasa-satellite-reveals-how-much-saharan-dust-feeds-amazons-plants/',kind:'REFERENCE'}],relatedLabel:'NASA · Saharan dust feeds Amazon',relatedHref:'https://www.nasa.gov/centers-and-facilities/goddard/nasa-satellite-reveals-how-much-saharan-dust-feeds-amazons-plants/'
},
{
 label:'Brasil',matches:['justiça suspende licenças','sigma lithium','grota do cirilo'],tag:'FOTO REAL · REUTERS',title:'Grota do Cirilo',caption:'Foto real da operação da Sigma Lithium na mina Grota do Cirilo, em Itinga (MG).',images:[{url:'https://www.reuters.com/resizer/v2/NITFZMVO3VLN5OHDOGQ73ZSCMY.jpg?auth=131f667a784bed0d3b09e72ceb917f481f519e25c246557de37abe49bc53fb80&quality=80&width=1920',alt:'Operação da Sigma Lithium na mina Grota do Cirilo em Itinga, Minas Gerais',caption:'Produção da Sigma Lithium em Grota do Cirilo.',credit:'Reuters · Washington Alves',sourceUrl:'https://www.reuters.com/world/americas/brazilian-court-suspends-licenses-sigma-lithium-mine-2026-09-06/',kind:'PHOTO'}],relatedLabel:'Reuters · decisão sobre Grota do Cirilo',relatedHref:'https://www.reuters.com/world/americas/brazilian-court-suspends-licenses-sigma-lithium-mine-2026-09-06/'
},
{
 label:'Mundo',matches:['primeira rodada em kyiv termina','conversas substantivas','cerca de três horas'],tag:'FOTO REAL · REUTERS',title:'Zelenskiy recebe enviados dos EUA em Kyiv',caption:'Foto real do encontro em Kyiv em 6 de setembro, diretamente ligada ao card.',images:[{url:'https://www.reuters.com/resizer/v2/CVYH7FAYWBMEZL2TFT7JJQPXZ4.jpg?auth=e3188229888dde6ad3738ebc4927687960d63dad9bc09fb5128818b1e49d6f61&quality=80&width=1080',alt:'Volodymyr Zelenskiy recebe Jared Kushner e Steve Witkoff em Kyiv em 6 de setembro de 2026',caption:'Zelenskiy recebe os enviados americanos em Kyiv.',credit:'Reuters · Valentyn Ogirenko',sourceUrl:'https://www.reuters.com/business/aerospace-defense/us-envoys-make-first-kyiv-visit-amid-ukraine-war-peace-push-2026-09-06/',kind:'PHOTO'}],relatedLabel:'Reuters · negociações em Kyiv',relatedHref:'https://www.reuters.com/business/aerospace-defense/us-envoys-make-first-kyiv-visit-amid-ukraine-war-peace-push-2026-09-06/'
},
{
 label:'Zona Leste em Foco',matches:['abertura oficial dos festejos','são miguel paulista','466 anos'],tag:'ARTE ESPECÍFICA · FALLBACK ESTÁVEL',title:'São Miguel Paulista · 466 anos',caption:'Arte 9:16 específica dos festejos de 466 anos, usada porque o cartaz externo da Prefeitura falhou de forma intermitente no hard gate.',images:[{url:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(zonaLesteSvg)}`,alt:'Arte 9:16 específica dos 466 anos de São Miguel Paulista e dos festejos de setembro',caption:'São Miguel Paulista · 466 anos · festejos de setembro',credit:'Father Giulian News · arte editorial específica 06/09',sourceUrl:'https://prefeitura.sp.gov.br/web/sao_miguel_paulista/w/s%C3%A3o-miguel-paulista-celebra-466-anos-com-programa%C3%A7%C3%A3o-que-re%C3%BAne-cultura-f%C3%A9-esporte-e-tradi%C3%A7%C3%A3o',kind:'REFERENCE'}],relatedLabel:'Prefeitura · programação oficial',relatedHref:'https://prefeitura.sp.gov.br/web/sao_miguel_paulista/w/s%C3%A3o-miguel-paulista-celebra-466-anos-com-programa%C3%A7%C3%A3o-que-re%C3%BAne-cultura-f%C3%A9-esporte-e-tradi%C3%A7%C3%A3o'
},
{
 label:'Corinthians',matches:['memphis começa como titular','oito desfalques','chapecoense'],tag:'ARTE ESPECÍFICA · FALLBACK ESTÁVEL',title:'Memphis titular · Corinthians x Chapecoense',caption:'Fallback editorial 9:16 específico para a escalação confirmada, usado porque a foto externa do personagem falhou de forma intermitente no hard gate.',images:[{url:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(corinthiansSvg)}`,alt:'Arte 9:16 específica: Memphis titular em Corinthians x Chapecoense, oito desfalques e jogo às 19h30',caption:'Memphis titular · Corinthians x Chapecoense · oito desfalques',credit:'Father Giulian News · fallback editorial específico 06/09',sourceUrl:'https://www.uol.com.br/esporte/futebol/ultimas-noticias/2026/09/06/escalacoes-corinthians-chapecoense-brasileirao-26.ghtm',kind:'REFERENCE'}],relatedLabel:'UOL · escalações de Corinthians x Chapecoense',relatedHref:'https://www.uol.com.br/esporte/futebol/ultimas-noticias/2026/09/06/escalacoes-corinthians-chapecoense-brasileirao-26.ghtm'
},
{
 label:'Finanças',matches:['opep+ mantém política de produção','inalterada para outubro','opep+'],tag:'FOTO REAL · OPEP',title:'Sede da OPEP em Viena',caption:'Foto da sede da OPEP em Viena, diretamente relacionada à decisão de produção do grupo.',images:[{url:'https://cloudfront-us-east-2.images.arcpublishing.com/reuters/SPCLQRDIPRNRDHRYMZJRRQRIWU.jpg',alt:'Sede da OPEP em Viena com o logotipo da organização na fachada',caption:'Sede da OPEP em Viena.',credit:'Reuters',sourceUrl:'https://www.opec.org/pr-detail/613-6-september-2026.html',kind:'PHOTO'}],relatedLabel:'OPEC · decisão oficial de 06/09',relatedHref:'https://www.opec.org/pr-detail/613-6-september-2026.html'
}
];
