import { dailyContent, edition, todayDrops } from './daily-content';
import { wordOfDay, upcomingWords } from './word-of-day';
import { regionalWords } from './regional-words';
import { rockTracks, caipiraTracks } from './music-content';
import { politicsTracker, presidentialProfiles, spGovernorProfiles, spSenateProfiles } from './politics-2026';

const set=(slug:string,data:any)=>Object.assign(dailyContent[slug],data);
const moveToFront=(list:any[],title:string)=>{const i=list.findIndex((x)=>x.title===title);if(i>0) list.unshift(list.splice(i,1)[0]);};

Object.assign(edition,{date:'19/08/2026',dateLabel:'19 AGO 2026',title:'Daily Intelligence · 19 de agosto'});

Object.assign(wordOfDay,{word:'Contumaz',pronunciation:'con-tu-MAZ',meaning:'Persistente ou habitual em determinada conduta; pode descrever tanto insistência quanto reincidência.',naturalUse:'Ele é um leitor contumaz de história e sempre aparece com uma referência nova.',synonyms:['habitual','persistente','reincidente']});
if (upcomingWords.length) Object.assign(upcomingWords[0],{word:'Sagaz',meaning:'Que percebe ou compreende com rapidez e perspicácia.'});
if (regionalWords.mineires) Object.assign(regionalWords.mineires,{word:'Uai',meaning:'Interjeição mineira muito versátil, usada naturalmente para surpresa, dúvida, reforço ou reação.',example:'Uai, cê já chegou?',note:'O sentido depende da entonação e do contexto; não é uma palavra com tradução única.'});
if (regionalWords.portugal) Object.assign(regionalWords.portugal,{word:'Miúdo',meaning:'Em Portugal pode significar pequeno e também, informalmente, criança/rapaz.',example:'O miúdo ficou encantado com o museu.',note:'Uso corrente em português europeu; o contexto evita ambiguidade.'});
moveToFront(rockTracks,'Black');
moveToFront(caipiraTracks,'Rei do Gado');

Object.assign(politicsTracker,{updatedAt:'19/08/2026 · 05h',notice:'A campanha eleitoral está em curso. Amanhã, 20 de agosto, é o último dia previsto no calendário do TSE para habilitação ao voto em trânsito e para algumas modalidades de transferência temporária. Pedido de registro, campanha e deferimento continuam sendo estados diferentes.'});
[...presidentialProfiles,...spGovernorProfiles,...spSenateProfiles].forEach((p:any)=>{ if (!/DivulgaCand/i.test(p.status)) p.status='ACOMPANHAR NO DIVULGACANDCONTAS · situação processual pode mudar'; });

todayDrops.splice(0,todayDrops.length,
  {slug:'brasil',label:'Brasil',emoji:'🇧🇷',title:'Taxa Legal de agosto: por que juros civis agora têm referência mensal oficial',detail:'O Banco Central publicou TLm de 1,154527% a.m.; entenda onde ela entra e por que não é “a nova Selic”.'},
  {slug:'politica',label:'Política',emoji:'🏛️',title:'Voto em trânsito: prazo termina amanhã, 20 de agosto',detail:'A campanha segue ativa, mas o serviço eleitoral tem outro relógio: habilitação e algumas transferências temporárias fecham amanhã.'},
  {slug:'mundo',label:'Mundo',emoji:'🌍',title:'Hormuz vira problema de logística: mercado procura rotas e capacidade alternativas',detail:'Brent segue perto de US$ 91 enquanto o fluxo marítimo permanece reduzido e exportadores buscam planos de contingência.'},
  {slug:'planeta',label:'Planeta',emoji:'🌊',title:'Ressurgência: quando a água fria do fundo alimenta ecossistemas na superfície',detail:'Vento e rotação terrestre conseguem substituir água superficial por água profunda rica em nutrientes.'},
  {slug:'animais',label:'Mundo Animal',emoji:'🦭',title:'Bigodes de foca funcionam como sensores hidrodinâmicos',detail:'Vibrissas detectam perturbações deixadas na água e ajudam a localizar movimento mesmo com pouca visibilidade.'},
  {slug:'tempo',label:'Tempo e Clima',emoji:'🌦️',title:'Calor e ar seco: hoje o risco prático é perder água sem perceber',detail:'A leitura do dia conecta temperatura, umidade, vento e hidratação em São Paulo.'},
  {slug:'curiosidades',label:'Curiosidades',emoji:'🧠',title:'Por que metal parece mais frio que madeira na mesma sala?',detail:'A sensação vem da velocidade com que o material retira calor da sua mão, não necessariamente da temperatura absoluta.'},
  {slug:'musica',label:'Música',emoji:'🎵',title:'Pearl Jam no rock; Tião Carreiro & Pardinho na viola',detail:'Black abre a trilha Rock e Rei do Gado conduz o arquivo caipira; as filas continuam independentes.'},
  {slug:'games',label:'Games',emoji:'🎮',title:'Gamescom 2026 está no radar: Opening Night Live será em 25 de agosto',detail:'A feira principal acontece de 26 a 30/08 em Colônia; o radar separa agenda confirmada de rumor.'},
  {slug:'gravidez',label:'Gravidez',emoji:'🤰',title:'6 semanas + 3 dias: spotting não deve ser interpretado no automático',detail:'Sangramento leve pode ocorrer no início, mas qualquer sangramento merece comunicação com o obstetra; dor forte ou sangramento intenso exigem avaliação.'},
  {slug:'pai',label:'Ser Pai',emoji:'👨‍🍼',title:'Missão de hoje: monte um “kit de saída” para consultas',detail:'Documentos, água, lanche tolerável, exames e lista de dúvidas prontos reduzem carga mental antes de sair.'},
  {slug:'carros',label:'Carros',emoji:'🚗',title:'Radar >1.0 até R$70 mil: Spin, Duster, EcoSport e March',detail:'Quatro propostas diferentes, todas com FIPE e média nacional de agosto dentro do teto da curadoria.'},
  {slug:'motos',label:'Motos',emoji:'🏍️',title:'Radar novo: CB 300R, MT-03, V-Strom 650 e Interceptor 650',detail:'Street, naked, touring e clássica moderna com preço de referência e checklist específico.'},
  {slug:'mecanica',label:'Mecânica',emoji:'🔧',title:'Correia de acessórios: ruído nem sempre significa correia “ruim”',detail:'Tensor, polia, rolamento e desalinhamento podem produzir o mesmo chiado; o diagnóstico precisa separar causa de sintoma.'},
  {slug:'nautica',label:'Náutica',emoji:'⚓',title:'Trim muda consumo, visibilidade e estabilidade do barco',detail:'Ângulo excessivo de proa ou popa altera resistência, conforto e segurança; ajuste deve acompanhar carga e condições.'},
  {slug:'viagens',label:'Viagens',emoji:'✈️',title:'Paranapiacaba: patrimônio ferroviário e neblina a menos de 100 km da capital',detail:'Um roteiro de um dia pede atenção a clima, calçado, horários e regras locais antes de sair.'},
  {slug:'financas',label:'Finanças',emoji:'💰',title:'Selic a 14%: a melhor “taxa futura” não paga uma dívida cara hoje',detail:'Use CET e prazo para decidir amortização/refinanciamento; expectativa de queda não é desconto contratado.'},
  {slug:'tecnologia',label:'Tecnologia',emoji:'💻',title:'Data center de IA é também projeto elétrico: potência não é a mesma coisa que energia',detail:'MW mede capacidade instantânea; MWh mede consumo ao longo do tempo. Confundir os dois distorce qualquer discussão de infraestrutura.'},
  {slug:'seguranca',label:'Cyber',emoji:'🛡️',title:'Teams virou vetor de engenharia social: canal “interno” não garante identidade confiável',detail:'O foco hoje é detecção e resposta a contato externo, impersonação e artefatos maliciosos dentro de ferramentas de colaboração.'},
  {slug:'appsec-ssdlc',label:'AppSec',emoji:'🧬',title:'Serverless RCE precisa ser modelado até a workload identity',detail:'O finding não termina no container: permissões da service account e acesso a secrets definem o blast radius real.'}
);

set('hoje',{title:'22 missões novas · 19 de agosto',summary:'Edição-base de quarta-feira: atualidades verificadas, conhecimento novo e hubs dedicados sem duplicar a mesma abertura. Segurança ZL e Security Briefing entram pelas experiências próprias.',shareSummary:'19/08: 22 missões novas com Brasil, política, mundo, clima, gravidez, veículos, música, games, cyber, AppSec e os hubs de segurança.',readTime:'22 MISSÕES',badge:'05H BASE EDITION',sections:[]});

set('brasil',{title:'Taxa Legal de agosto: uma referência oficial para juros civis, não um substituto da Selic',summary:'O Banco Central publicou para agosto de 2026 a Taxa Legal mensal de 1,154527% a.m. O indicador decorre da metodologia legal ligada ao art. 406 do Código Civil e serve a situações específicas; não deve ser confundido com taxa básica de política monetária nem com CET bancário.',shareSummary:'Brasil: a Taxa Legal de agosto é 1,154527% a.m. Ela serve a hipóteses civis previstas em lei; não é “a nova Selic” e não substitui o CET de empréstimos.',readTime:'6 MIN READ',badge:'BRASIL / DINHEIRO + CIDADANIA',stats:[{label:'TLM AGO/26',value:'1,154527%',note:'ao mês'},{label:'BASE',value:'BCB',note:'metodologia oficial'}],sections:[{title:'O que é',paragraphs:['A Taxa Legal traduz a regra do Código Civil para juros quando a relação jurídica remete ao art. 406 e não há outra taxa válida estabelecida. O Banco Central publica o fator mensal.']},{title:'O que não é',bullets:['Não é a Selic-meta do Copom.','Não é automaticamente a taxa de todo atraso ou contrato.','Não substitui comparar CET em crédito bancário.']},{title:'Aplicação prática',paragraphs:['Ao calcular dívida civil ou discutir atualização monetária, identifique primeiro qual regra jurídica realmente se aplica. A taxa correta depende do título, contrato, decisão ou obrigação.']}],sources:[{label:'Banco Central · Taxa Legal · agosto/2026',url:'https://www.bcb.gov.br/estabilidadefinanceira/taxalegal'}],disclaimer:'Conteúdo informativo geral; casos jurídicos concretos podem exigir orientação profissional.'});

set('politica',{title:'Campanha em curso; amanhã fecha o prazo de habilitação para voto em trânsito',summary:'A eleição já está na fase de propaganda, mas o calendário do eleitor continua andando. O TSE marca 20 de agosto como último dia para pedir voto em trânsito e algumas transferências temporárias. Situação de candidatura continua sendo acompanhada separadamente no DivulgaCandContas.',shareSummary:'Política: amanhã, 20/08, termina o prazo do TSE para habilitação ao voto em trânsito e algumas transferências temporárias. Isso é serviço do eleitor; não muda o status jurídico de candidaturas.',readTime:'7 MIN READ',badge:'POLÍTICA / SERVIÇO DO ELEITOR',stats:[{label:'PRAZO',value:'20 AGO',note:'voto em trânsito / modalidades previstas'},{label:'CAMPANHA',value:'ATIVA',note:'desde 16/08'}],sections:[{title:'Três relógios diferentes',bullets:['Campanha: propaganda geral já está permitida desde 16/08.','Eleitor: 20/08 fecha a janela prevista para voto em trânsito e certas transferências temporárias.','Candidaturas: protocolo, julgamento, recurso e deferimento são etapas distintas.']},{title:'Impacto na vida real',paragraphs:['Quem sabe que estará fora do domicílio eleitoral precisa conferir imediatamente se se enquadra nas regras e como fazer a habilitação. Quem permanece no município não precisa tratar o prazo como obrigação geral.']},{title:'Como acompanhar sem torcida',paragraphs:['Use DivulgaCandContas para situação processual e fontes do TSE para regras. Promessa de campanha, registro e decisão judicial não têm o mesmo peso.']}],sources:[{label:'TSE · Eleições 2026',url:'https://www.tse.jus.br/eleicoes/eleicoes-2026'},{label:'TSE · Calendário Eleitoral 2026',url:'https://www.tse.jus.br/eleicoes/calendario-eleitoral/calendario-eleitoral'}]});

set('mundo',{title:'Hormuz entra na fase da contingência logística: rotas alternativas viram parte do preço do petróleo',summary:'O Brent avançava novamente nesta quarta-feira, perto de US$ 91, com circulação de navios ainda baixa e declarações conflitantes sobre a normalização do Estreito de Hormuz. O novo ângulo é operacional: produtores e compradores passam a avaliar rotas, capacidade de oleodutos, seguros e cronogramas alternativos.',shareSummary:'Mundo: Hormuz virou também um problema de logística. Brent perto de US$91, fluxo marítimo reduzido e busca por rotas alternativas colocam oleodutos, seguro e capacidade de exportação no centro do risco.',readTime:'8 MIN READ',badge:'GLOBAL / ENERGY LOGISTICS',stats:[{label:'BRENT',value:'~US$ 91',note:'manhã de 19/08'},{label:'FOCO',value:'ROTAS',note:'contingência física'}],sections:[{title:'O que mudou no ângulo',paragraphs:['Depois de dias olhando apenas a cotação, o problema passa a ser capacidade física: quanto petróleo consegue sair por rotas alternativas se a navegação continuar limitada?']},{title:'Cadeia de transmissão',bullets:['Menos tráfego → maior incerteza de entrega.','Rota alternativa → capacidade e custo próprios.','Seguro/frete → custo adicional mesmo sem perda física de barris.','Persistência do choque → pressão sobre inflação e planejamento industrial.']},{title:'O que não assumir',paragraphs:['Fluxo reduzido não equivale automaticamente a bloqueio total, e uma alta diária do barril não determina preço imediato de combustível no Brasil.']}],sources:[{label:'Reuters · Oil / Hormuz · 19/08/2026',url:'https://www.reuters.com/business/energy/oil-prices-rise-fourth-day-hormuz-uncertainty-2026-08-19/'}]});

set('planeta',{title:'Ressurgência oceânica: o vento consegue “puxar” fertilidade das profundezas',summary:'Em certas costas, o vento desloca água superficial e permite a subida de água fria, profunda e rica em nutrientes. Esse processo sustenta cadeias alimentares muito produtivas e também muda temperatura e oxigenação locais.',shareSummary:'Planeta: ressurgência é a subida de água profunda e rica em nutrientes quando o vento afasta água superficial. Ela ajuda a explicar algumas das regiões pesqueiras mais produtivas do mundo.',readTime:'5 MIN READ',badge:'PLANETA / OCEANO',sections:[{title:'Mecânica básica',paragraphs:['Vento persistente, rotação da Terra e geometria da costa podem deslocar a camada superficial; água mais profunda ocupa o espaço e leva nutrientes à zona iluminada.']},{title:'Conexão inesperada',bullets:['Mais nutrientes podem alimentar fitoplâncton.','Fitoplâncton sustenta peixes e predadores maiores.','Água fria ressurgida também altera nevoeiro e clima costeiro.']}],sources:[{label:'NOAA Ocean Service · Upwelling',url:'https://oceanservice.noaa.gov/education/tutorial_currents/03coastal4.html'}]});

set('animais',{title:'Focas “leem” a água com os bigodes',summary:'As vibrissas de focas não são apenas pelos táteis. Elas são estruturas sensoriais capazes de perceber perturbações hidrodinâmicas e podem ajudar o animal a seguir rastros de movimento de presas mesmo quando a visão é limitada.',shareSummary:'Mundo Animal: vibrissas de focas funcionam como sensores de fluxo. O animal consegue extrair informação de pequenas perturbações deixadas na água.',readTime:'5 MIN READ',badge:'ANIMAL INTELLIGENCE',sections:[{title:'Por que funciona',paragraphs:['Cada vibrissa transmite vibrações a terminações nervosas muito sensíveis. A forma do pelo ajuda a reduzir o ruído causado pelo próprio nado e melhora a leitura de perturbações externas.']},{title:'A ideia maior',paragraphs:['Sentidos animais não precisam se parecer com visão ou audição humanas. Evolução explora qualquer sinal físico confiável disponível no ambiente.']}],sources:[{label:'Smithsonian Ocean · seal whiskers / sensory biology',url:'https://ocean.si.edu/ocean-life/marine-mammals'}]});

set('tempo',{title:'São Paulo: calor e ar seco pedem leitura conjunta de temperatura e umidade',summary:'A quarta-feira mantém padrão quente e seco na capital. Em dias assim, o risco cotidiano não é apenas “sentir calor”: suor pode evaporar rapidamente, reduzindo a percepção de perda de água.',shareSummary:'Tempo SP: quarta segue quente e seca. Observe temperatura + umidade e mantenha hidratação; em ar seco, suor pode evaporar rápido e mascarar perda de água.',readTime:'4 MIN READ',badge:'SP / WEATHER',sections:[{title:'Aplicação prática',bullets:['Leve água antes de sentir sede intensa.','Evite esforço prolongado nas horas mais quentes quando possível.','Observe crianças, gestantes, idosos e pets com atenção extra.','Umidificador não substitui ventilação e hidratação.']},{title:'Como ler a previsão',paragraphs:['Temperatura informa carga térmica; umidade ajuda a entender evaporação e ressecamento. O conforto real depende também de vento, sol, atividade e hidratação.']}],sources:[{label:'Previsão meteorológica consultada para São Paulo · 19/08/2026',url:'https://www.inmet.gov.br/'}]});

set('curiosidades',{title:'Metal e madeira podem estar na mesma temperatura — e ainda assim um parece muito mais frio',summary:'A pele não mede temperatura como um termômetro. Ela percebe fluxo de calor. Metal conduz calor da mão muito mais rapidamente que madeira, por isso parece mais frio mesmo quando ambos ficaram horas no mesmo ambiente.',shareSummary:'Curiosidade: metal parece mais frio que madeira porque retira calor da sua mão mais rápido. A sensação registra fluxo térmico, não apenas temperatura.',readTime:'5 MIN READ',badge:'SCIENCE / EVERYDAY',sections:[{title:'Teste mental',paragraphs:['Deixe colher metálica e objeto de madeira lado a lado por horas. O termômetro pode indicar quase o mesmo valor; ao tocar, o metal conduz energia muito mais depressa.']},{title:'Conexão',paragraphs:['O mesmo princípio ajuda a entender por que materiais de piso, panelas, isolantes e roupas produzem sensações térmicas tão diferentes.']}],sources:[{label:'NIST · Thermal conductivity concepts',url:'https://www.nist.gov/'}]});

set('musica',{title:'Do grunge confessional à viola narrativa: duas escutas sem misturar arquivos',summary:'Rock do dia: Pearl Jam — Black. Sertanejo de época: Tião Carreiro & Pardinho — Rei do Gado. O Top 10 de cada trilha e o Top 5 histórico caipira continuam independentes e sem letras reproduzidas.',shareSummary:'Música: Pearl Jam — Black no Rock; Tião Carreiro & Pardinho — Rei do Gado no arquivo caipira. Trilhas separadas, sem misturar sertanejo moderno.',readTime:'2 PLAYERS',badge:'MUSIC / TWO LANES',sections:[{title:'Rock · Black',paragraphs:['Ouça a progressão emocional e a interpretação vocal; a faixa cresce pela intensidade acumulada, não por velocidade.']},{title:'Raiz · Rei do Gado',paragraphs:['A moda de viola trabalha narrativa, personagem e universo rural; a viola conduz identidade rítmica e dramática.']}],sources:[{label:'Pearl Jam · catálogo oficial',url:'https://pearljam.com/music'},{label:'Acervo musical / pesquisa por Tião Carreiro & Pardinho',url:'https://www.youtube.com/results?search_query=Tiao+Carreiro+Pardinho+Rei+do+Gado'}]});

set('games',{title:'Gamescom 2026: o calendário confirmado começa antes dos grandes trailers',summary:'A gamescom acontece de 26 a 30 de agosto em Colônia e a Opening Night Live está marcada para 25/08. Hoje o radar é de preparação: wishlist e anúncio oficial valem mais que listas de “vazamentos”.',shareSummary:'Games: gamescom 2026 acontece 26–30/08 e a Opening Night Live será 25/08. Até lá, trate rumor como rumor e use páginas oficiais para datas/plataformas.',readTime:'6 MIN READ',badge:'GAMES / EVENT RADAR',stats:[{label:'ONL',value:'25 AGO'},{label:'FEIRA',value:'26–30 AGO'}],sections:[{title:'O que já é fato',bullets:['Opening Night Live em 25/08.','Feira principal de 26 a 30/08 em Colônia.','Games Done Quick estreia dentro da gamescom.']},{title:'O que não é fato',paragraphs:['Lista de trailers “confirmados” sem anúncio do organizador, publisher ou estúdio continua sendo rumor. O hub mantém PS5 Radar e Switch 2 Radar independentes.']}],sources:[{label:'gamescom · calendário oficial 2026',url:'https://www.gamescom.global/en/live/events'}]});

set('gravidez',{title:'6 semanas + 3 dias: spotting pode ser comum, mas não deve ser autodiagnosticado',summary:'Sangramento leve no primeiro trimestre ocorre em parte das gestações e nem sempre significa perda gestacional. A ACOG recomenda comunicar qualquer sangramento ao obstetra; intensidade, dor e outros sintomas mudam a urgência da avaliação.',shareSummary:'Gravidez 6s+3d: spotting pode acontecer no início e nem sempre indica problema, mas qualquer sangramento deve ser comunicado ao obstetra. Sangramento intenso ou dor importante exigem avaliação rápida.',readTime:'7 MIN READ',badge:'PREGNANCY / 6S + 3D',stats:[{label:'IDADE',value:'6S + 3D'},{label:'DPP',value:'11/04/2027'}],sections:[{title:'O que a evidência diz',paragraphs:['A ACOG informa que sangramento no primeiro trimestre ocorre em cerca de 15 a 25 de cada 100 gestações. Algumas causas são benignas; outras exigem investigação.']},{title:'Quando não esperar',bullets:['Sangramento forte.','Dor intensa ou progressiva.','Tontura, desmaio ou fraqueza importante.','Qualquer orientação de urgência já dada pelo obstetra.']},{title:'Sem tirar conclusão por um único dado',paragraphs:['Em gestação muito precoce, ultrassom e hCG podem precisar de repetição para esclarecer evolução. Sintoma isolado não confirma diagnóstico.']}],sources:[{label:'ACOG · Bleeding During Pregnancy',url:'https://www.acog.org/womens-health/faqs/bleeding-during-pregnancy'},{label:'ACOG · Early Pregnancy Loss',url:'https://www.acog.org/womens-health/faqs/early-pregnancy-loss'}],disclaimer:'Informação educativa; não substitui avaliação do pré-natal ou atendimento de urgência.'});

set('pai',{title:'Missão de hoje: prepare a saída para a consulta antes que ela vire mais uma decisão',summary:'Monte um pequeno kit pronto com documentos, exames, água, lanche que ela tolere e a lista compartilhada de dúvidas. O objetivo não é controlar a consulta; é retirar fricção operacional.',shareSummary:'Ser Pai: hoje prepare o kit da próxima consulta — documentos, exames, água, lanche tolerável e dúvidas — sem deixar essa organização cair toda sobre ela.',readTime:'3 MIN READ',badge:'DAD QUEST',sections:[{title:'Como fazer',bullets:['Confirme documentos/exames necessários.','Separe água e alimento que ela tolera.','Atualize a lista de dúvidas sem decidir por ela.','Planeje deslocamento e tempo de margem.']},{title:'Por que conta',paragraphs:['Apoio concreto aparece em tarefas completas, não em “me avisa se precisar”. Antecipar logística diminui carga mental sem tirar autonomia.']}],sources:[{label:'ACOG · Prenatal care resources',url:'https://www.acog.org/womens-health'}]});

set('carros',{title:'Radar >1.0 até R$70 mil: espaço, SUV manual e hatch leve sem furar o teto',summary:'A curadoria de hoje gira para Chevrolet Spin 1.8 LT AT 2017, Renault Duster 1.6 Dynamique manual 2017, Ford EcoSport 1.6 SE manual 2017 e Nissan March 1.6 SV manual 2019. Todas têm FIPE e média Webmotors de agosto/2026 abaixo de R$70 mil.',shareSummary:'Carros: Spin 1.8 AT, Duster 1.6 manual, EcoSport 1.6 manual e March 1.6 manual — todos >1.0, com FIPE e média nacional de agosto abaixo de R$70 mil.',readTime:'4 COMPARATIVOS',badge:'CARS / >1.0 / ≤70K',sections:[{title:'Regra de corte',bullets:['Motor acima de 1.0.','FIPE atual abaixo de R$70 mil.','Média nacional Webmotors abaixo de R$70 mil.','Histórico e inspeção pesam mais que menor km isolada.']}],sources:[{label:'Webmotors · Tabela FIPE / médias · ago/2026',url:'https://www.webmotors.com.br/tabela-fipe/carros'}]});

set('motos',{title:'Radar de motos: quatro propostas e quatro tipos de inspeção',summary:'CB 300R ABS 2015, MT-03 ABS 2018, V-Strom 650 ABS 2015 e Interceptor 650 2021 entram no radar com FIPE/mercado e leitura de ciclística, queda, consumíveis e histórico.',shareSummary:'Motos: CB300R, MT-03, V-Strom 650 e Interceptor 650 com preços de referência e checklist de queda, suspensão, pneus, relação e freios.',readTime:'4 COMPARATIVOS',badge:'MOTO RADAR',sections:[{title:'Não compare só cilindrada',paragraphs:['Uso urbano, viagem, massa, ergonomia, seguro e custo de consumíveis mudam mais a experiência do que a cilindrada isolada.']}],sources:[{label:'Webmotors · Tabela FIPE / médias de motos',url:'https://www.webmotors.com.br/tabela-fipe/motos'}]});

set('mecanica',{title:'Chiado na correia: trocar a borracha sem diagnosticar o conjunto pode não resolver nada',summary:'Correia de acessórios, tensor, polias, rolamentos e alinhamento trabalham como um sistema. Ruído pode vir de contaminação, tensão inadequada ou rolamento antes de a correia apresentar rachaduras visíveis.',shareSummary:'Mecânica: chiado de correia não condena automaticamente a correia. Tensor, polias, rolamentos, contaminação e alinhamento entram no diagnóstico.',readTime:'6 MIN READ',badge:'DIAGNÓSTICO / ACESSÓRIOS',sections:[{title:'Pistas úteis',bullets:['Ruído a frio que some pode reagir à tensão/umidade.','Mudança ao ligar ar-condicionado pode indicar carga adicional no sistema.','Pó preto ou desgaste lateral sugere desalinhamento.','Folga/aspereza de polia pede inspeção do rolamento.']},{title:'Evite o “spray diagnóstico”',paragraphs:['Produtos aplicados na correia podem mascarar ruído e contaminar o conjunto. O diagnóstico correto observa trajetória, tensão e rolamentos com procedimento seguro.']}],sources:[{label:'Gates · belt drive diagnostics',url:'https://www.gates.com/us/en/knowledge-center.html'}]});

set('nautica',{title:'Trim não é detalhe de conforto: ele muda arrasto, visão e estabilidade',summary:'Ajustar trim altera o ângulo do casco em relação à água. Pouco ou muito trim pode aumentar consumo, gerar batidas, reduzir visibilidade à frente ou induzir comportamento instável.',shareSummary:'Náutica: trim muda como o casco encontra a água. Ajuste errado pode aumentar arrasto, piorar visão e conforto e comprometer estabilidade.',readTime:'6 MIN READ',badge:'BOAT HANDLING',sections:[{title:'Leitura prática',bullets:['Carga e passageiros mudam o ponto ideal.','Mar picado pede prioridade a controle e conforto, não velocidade.','Proa excessivamente alta reduz visão.','Ajuste deve ser progressivo e observado pelo comportamento do barco.']}],sources:[{label:'US Coast Guard Auxiliary · boating safety',url:'https://www.cgaux.org/boatinged/'}]});

set('viagens',{title:'Paranapiacaba em um dia: vá pelo patrimônio, fique pelo clima de serra',summary:'A vila ferroviária de Santo André combina patrimônio industrial, trilhas e neblina frequente. O roteiro funciona melhor com planejamento de transporte, previsão, calçado aderente e horários confirmados antes da saída.',shareSummary:'Viagem perto de SP: Paranapiacaba combina patrimônio ferroviário e natureza. Confira transporte, clima e funcionamento dos atrativos antes de sair; neblina e piso molhado mudam o passeio.',readTime:'7 MIN READ',badge:'SP / DAY TRIP',sections:[{title:'Roteiro simples',bullets:['Centro histórico e arquitetura ferroviária.','Museus/atrações abertas no dia da visita.','Mirantes e trilhas somente com condição segura e regra local confirmada.']},{title:'Custo inteligente',paragraphs:['Transporte, alimentação e eventuais ingressos variam por data. A recomendação é confirmar valores e horários oficiais no dia anterior, em vez de tratar preço antigo como tabela atual.']}],sources:[{label:'Prefeitura de Santo André · Turismo',url:'https://www3.santoandre.sp.gov.br/turismosantoandre/'}]});

set('financas',{title:'Selic a 14%: compare a dívida que existe, não a taxa que você espera para o futuro',summary:'O Copom reduziu a Selic para 14,00% em 5 de agosto, mas crédito ao consumidor continua dependendo de risco, margem, prazo e custos. Refinanciamento faz sentido quando reduz CET e risco de caixa — não apenas porque “os juros devem cair”.',shareSummary:'Finanças: Selic está em 14%, mas sua dívida é regida pelo CET contratado. Só troque/refinancie se custo total e fluxo de caixa melhorarem de verdade.',readTime:'6 MIN READ',badge:'FINANÇAS / DÍVIDA',stats:[{label:'SELIC',value:'14,00%',note:'decisão de 05/08/2026'}],sections:[{title:'Checklist antes de trocar dívida',bullets:['Compare CET, não só taxa nominal.','Some tarifas, seguros e prazo.','Veja custo total até o fim.','Evite alongar tanto que a parcela cai mas o total explode.']},{title:'Conexão com a economia',paragraphs:['A transmissão da Selic para crédito é gradual. Bancos precificam inadimplência, capital, custo de funding e garantia; por isso a queda na taxa básica não vira automaticamente a mesma queda na sua proposta.']}],sources:[{label:'Banco Central · Copom · 05/08/2026',url:'https://www.bcb.gov.br/publicacoes/atascopom'}],disclaimer:'Conteúdo educacional; não é recomendação individual de crédito ou investimento.'});

set('tecnologia',{title:'MW não é MWh: a infraestrutura de IA precisa de potência e energia — e são coisas diferentes',summary:'Megawatt mede potência instantânea; megawatt-hora mede energia consumida ao longo do tempo. Em data centers de IA, misturar as unidades cria comparações ruins sobre capacidade elétrica, consumo e custo.',shareSummary:'Tecnologia: MW mede potência; MWh mede energia. Em data centers de IA, confundir os dois distorce tamanho da conexão elétrica, consumo e custo operacional.',readTime:'6 MIN READ',badge:'TECH / AI INFRA',sections:[{title:'Exemplo',paragraphs:['Um data center operando a 100 MW por uma hora consome 100 MWh. Se mantiver essa potência por 24 horas, são 2.400 MWh antes de considerar variações e perdas.']},{title:'Por que importa',bullets:['Rede elétrica precisa suportar potência.','Conta/planejamento energético dependem do consumo ao longo do tempo.','Picos, redundância e eficiência mudam o dimensionamento real.']}],sources:[{label:'U.S. EIA · energy units',url:'https://www.eia.gov/energyexplained/units-and-calculators/'}]});

set('seguranca',{title:'Quando o phishing chega pelo Teams: colaboração interna também precisa de verificação de identidade',summary:'Campanhas observadas pela Mandiant abusam de plataformas de colaboração e engenharia social para aproximar o atacante da vítima. A defesa hoje é SOC/IR: distinguir contato externo, impersonação, convite incomum e artefato suspeito antes de confiar no contexto “corporativo”.',shareSummary:'Cyber: Teams/colaboração também é superfície de phishing. Detecte contato externo, impersonação, convites incomuns e artefatos suspeitos; canal corporativo não prova identidade.',readTime:'8 MIN READ',badge:'CYBER / COLLAB PHISHING',sections:[{title:'Sinais defensivos',bullets:['Contato externo que imita suporte ou fornecedor.','Mudança abrupta para chamada/compartilhamento remoto.','Pedido para instalar extensão, ferramenta ou executar artefato.','Sequência de login/consentimento anômala após a conversa.']},{title:'Resposta',paragraphs:['Preserve chat, identidade do remetente, URLs, hashes e eventos de login. Revogue sessão/consentimentos quando houver evidência de comprometimento e trate o incidente como identidade + endpoint, não apenas “mensagem de phishing”.']}],sources:[{label:'Google Threat Intelligence / Mandiant · threat intelligence',url:'https://cloud.google.com/blog/topics/threat-intelligence/'}]});

set('appsec-ssdlc',{title:'Serverless: uma RCE pequena pode herdar uma identidade grande demais',summary:'Em funções e containers serverless, o impacto de uma falha de aplicação depende do que a workload identity consegue fazer. O threat model precisa continuar do endpoint vulnerável até metadata, secrets, APIs cloud e recursos adjacentes.',shareSummary:'AppSec: RCE em serverless não termina no container. Modele endpoint → código → workload identity → secrets/APIs → recursos; least privilege reduz o blast radius.',readTime:'8 MIN READ',badge:'APPSEC / CLOUD-NATIVE',sections:[{title:'Threat boundary',bullets:['Endpoint público/autorização.','Código e dependências.','Service account/workload identity.','Secrets e metadata.','VPC, APIs e recursos adjacentes.']},{title:'Gate prático',bullets:['Inventário de funções públicas.','Identidade dedicada por workload.','Sem privilégio padrão amplo.','SAST/DAST e teste de autorização.','Logs de uso de credenciais e chamadas cloud.']},{title:'Ângulo diferente de Cyber',paragraphs:['Aqui o foco é arquitetura e SDLC: limitar o que a aplicação comprometida consegue alcançar. O conteúdo de Cyber trata engenharia social e resposta a colaboração, sem duplicar esta cadeia.']}],sources:[{label:'Mandiant · The Risk of Exposed Cloud Functions and How to Harden',url:'https://cloud.google.com/blog/topics/threat-intelligence/exposed-cloud-functions-harden'}]});
