import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f4f1e8"/><rect x="70" y="110" width="940" height="1700" rx="84" fill="#e8ece7"/><circle cx="540" cy="610" r="285" fill="#314f47" opacity=".14"/><text x="540" y="705" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M210 1030h660" stroke="#314f47" stroke-width="14" opacity=".55"/><text x="540" y="1215" text-anchor="middle" font-size="53" font-weight="700" font-family="Arial,sans-serif" fill="#263b35">${headline}</text><text x="540" y="1340" text-anchor="middle" font-size="35" font-family="Arial,sans-serif" fill="#53655f">${sub}</text><text x="540" y="1530" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#6d7b76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 11/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 11/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260911:RichMediaEntry[]=[
img('Papo de hoje',['lugar perto de casa','ainda não exploraram'],'📍','PERTO DE CASA','O QUE FALTA EXPLORAR?','Arte 9:16 específica com mapa de bairro e ponto de descoberta para o papo do casal','https://www.gov.br/turismo/pt-br'),
img('Desafio do casal',['cada um escolhe uma música','música para o outro'],'🎧','UMA MÚSICA PRO OUTRO','OUÇAM INTEIRA','Arte 9:16 específica com dois fones e duas notas musicais para o desafio do casal','https://www.gov.br/cultura/pt-br'),
img('Curiosidades',['rãs conseguem passar parte do inverno','parcialmente congeladas'],'🐸','RÃ CONGELADA?','ELA PODE SOBREVIVER','Arte 9:16 específica com rã, gelo e moléculas de glicose representando adaptação ao congelamento','https://www.nps.gov/articles/000/wood-frog.htm'),
img('Curiosidades',['dia solar em mercúrio','176 dias terrestres'],'☿️','MERCÚRIO','DIA SOLAR = 176 DIAS','Arte 9:16 específica com Mercúrio, órbita e relógio comparando dia solar e ano','https://science.nasa.gov/mercury/facts/'),
img('Curiosidades',['raio pode vitrificar areia','fulguritos'],'⚡','RAIO + AREIA','FULGURITO','Arte 9:16 específica com descarga elétrica fundindo areia e formando tubo vítreo','https://www.nps.gov/articles/000/fulgurites.htm'),
img('Curiosidades',['córnea saudável','não possui vasos sanguíneos'],'👁️','CÓRNEA','TRANSPARENTE E AVASCULAR','Arte 9:16 específica com olho e córnea transparente sem vasos sanguíneos','https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/corneal-conditions'),
img('Curiosidades',['qr codes usam correção de erros','parte do símbolo está danificada'],'🔳','QR CODE','RECUPERA DADOS','Arte 9:16 específica com QR parcialmente danificado e blocos sendo reconstruídos','https://www.qrcode.com/en/about/error_correction.html'),
img('Gravidez',['9 semanas + 5 dias','9s5d'],'🤰','9 SEMANAS + 5 DIAS','CADA DIA CONTA','Arte 9:16 específica para 9 semanas e 5 dias de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/9-weeks/'),
img('Ser Pai',['saída de casa pronta','kit simples de saída'],'🎒','KIT DE SAÍDA','PRONTO ANTES DA CORRERIA','Arte 9:16 específica com bolsa, água, documentos e itens de apoio para uma saída na gestação','https://www.cdc.gov/hearher/support-family-friends/index.html'),
img('Mundo',['petróleo perto de us$110','pressão sobre títulos'],'🌍','ENERGIA + JUROS','MERCADOS SOB PRESSÃO','Arte 9:16 específica com globo, barril e curva de juros para pressão global de energia e inflação','https://www.reuters.com/world/china/global-markets-corrected-2026-09-11/'),
img('Tempo e Clima',['sexta mais quente','risco de tempestade'],'⛈️','SP · 11/09','VENTO + PANCADAS','Arte 9:16 específica com São Paulo, rajadas e nuvens de tempestade para previsão de 11 de setembro','https://cge.prefeitura.sp.gov.br/v3/noticias.jsp'),
img('Viagens',['códigos de reserva fora do e-mail','reservas offline'],'🎫','RESERVA OFFLINE','CÓDIGOS À MÃO','Arte 9:16 específica com bilhete, localizador e nota offline para viagem','https://www.gov.br/anac/pt-br/assuntos/passageiros'),
img('Música',['prestando atenção só na bateria','escuta em camadas'],'🥁','OUÇA EM CAMADAS','BATERIA → BAIXO','Arte 9:16 específica com bateria e baixo destacados em camadas de uma música','https://www.gov.br/cultura/pt-br'),
img('Games',['xbox fecha a semana','programação semanal da xbox wire'],'🎮','GAMES · 11/09','AGENDA DE SEXTA','Arte 9:16 específica com controle e calendário marcando sexta-feira 11 de setembro','https://news.xbox.com/en-us/2026/09/04/next-week-on-xbox-new-games-for-september-7-to-11/'),
img('Tecnologia',['enflame estreia em xangai','primeiro pregão'],'🧠','ENFLAME · IPO','CHIPS DE IA EM XANGAI','Arte 9:16 específica com chip de IA, bolsa de Xangai e gráfico de estreia','https://www.reuters.com/world/asia-pacific/tencent-backed-enflame-open-up-188-shanghai-debut-after-912-million-ipo-2026-09-11/'),
img('Finanças',['brent passa de us$108','primeira semana acima de us$100'],'🛢️','BRENT > US$108','ALTA SEMANAL FORTE','Arte 9:16 específica com barril, linha de US$100 e gráfico semanal de petróleo','https://www.reuters.com/business/energy/oil-prices-set-end-week-over-100-first-time-nearly-4-months-2026-09-11/'),
img('Carros até R$ 70 mil',['chassi e documentos','identificação do veículo'],'🚗','ATÉ R$70 MIL','CHASSI + DOCUMENTOS','Arte 9:16 específica com carro usado, documento e identificação veicular sendo conferidos','https://www.gov.br/pt-br/servicos/consultar-online-os-dados-de-placa-veicular'),
img('Motos',['folga na caixa de direção','degrau na direção'],'🏍️','CAIXA DE DIREÇÃO','SEM FOLGA OU DEGRAU','Arte 9:16 específica com guidão e rolamento de direção de motocicleta destacados','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['tampa do reservatório','sistema de arrefecimento'],'🌡️','ARREFECIMENTO','TAMPA TAMBÉM CONTROLA PRESSÃO','Arte 9:16 específica com reservatório, tampa pressurizada e circuito de arrefecimento','https://www.gov.br/senatran/pt-br')
];
