import type {RichMediaEntry} from './rich-media';
const img=(label:string,matches:string[],url:string,alt:string,credit:string,sourceUrl=url):RichMediaEntry=>({label,matches,tag:'MÍDIA · 04/10',title:alt,caption:credit,images:[{url,alt,caption:credit,credit,sourceUrl:sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20261004:RichMediaEntry[]=[
img('Papo de hoje',['que valor','aprenda vendo vocês'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pregnancy.jpg','Casal durante a gestação','Soul Flora / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pregnancy.jpg'),
img('Desafio do casal',['três músicas','microplaylist'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Headphones_1.jpg','Fones de ouvido para escuta musical','Wikimedia Commons','https://commons.wikimedia.org/'),
img('Curiosidades',['Golfinhos','assobios-assinatura'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Tursiops_truncatus_01.jpg','Golfinho-nariz-de-garrafa','Wikimedia Commons','https://commons.wikimedia.org/'),
img('Curiosidades',['ossos','remodelado'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Human_skeleton_front_en.svg.png','Esqueleto humano em referência anatômica','Wikimedia Commons','https://commons.wikimedia.org/'),
img('Curiosidades',['Saturno','densidade média'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Saturn_during_Equinox.jpg','Saturno fotografado pela missão Cassini','NASA / Wikimedia Commons','https://commons.wikimedia.org/'),
img('Gravidez',['13 semanas','13 SEMANAS'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pregnancy.jpg','Gestação em imagem real de contexto','Soul Flora / Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pregnancy.jpg'),
img('Ser Pai',['proteja o ritmo','presença prática'],'https://www.cdc.gov/hearher/media/images/support-family-friends-16x9-1.jpg','Parceiro oferecendo apoio durante a gestação','CDC Hear Her','https://www.cdc.gov/hearher/about/support-family-friends.html'),
img('Brasil',['Brasil vota hoje','primeiro turno'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg','Urnas eletrônicas brasileiras','Abdias Pinheiro / SECOM / TSE','https://commons.wikimedia.org/wiki/File:Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg'),
img('Política',['Primeiro turno','apuração oficial'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg','Urnas eletrônicas brasileiras','Abdias Pinheiro / SECOM / TSE','https://commons.wikimedia.org/wiki/File:Novas_urnas_eletr%C3%B4nicas_-_TSE.jpg'),
img('Tempo e Clima',['pancadas de chuva','domingo de eleição'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rain_on_window.jpg','Chuva observada através de uma janela','Wikimedia Commons','https://commons.wikimedia.org/'),
img('Corinthians',['Corinthians fica com o vice','final histórica'],'https://agemt.pucsp.br/sites/default/files/inline-images/539970296534d0f05c147o.jpg','São Paulo e Corinthians em confronto pelo futebol feminino','Agemt / PUC-SP','https://agemt.pucsp.br/noticias/corinthians-supera-sao-paulo-no-morumbis'),
img('Carros',['R$70 mil','70 mil'],'https://editorial.pxcrush.net/carsales/general/editorial/ppsr-recalls-1-uebn.jpg?height=682&width=1024','Pátio de veículos usados','Carsales','https://www.carsales.com.au/editorial/details/safety-recalls-added-to-governments-ppsr-security-registry-140080/'),
img('Motos',['freios','manete'],'https://xprousa.com/cdn/shop/files/220-905003.jpg?v=1712557817','Sistema de freio dianteiro de motocicleta','XProUSA','https://xprousa.com/products/220-905003'),
img('Mecânica',['arrefecimento','líquido de arrefecimento'],'https://commons.wikimedia.org/wiki/Special:Redirect/file/Engine_coolant.jpg','Líquido de arrefecimento sendo adicionado a um veículo','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Engine_coolant.jpg')
];