import type {RichMediaEntry} from './rich-media';
const art=(label:string,glyph:string,headline:string,sub:string)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920"><rect width="1080" height="1920" fill="#f4f0e7"/><rect x="70" y="110" width="940" height="1700" rx="84" fill="#e8eeea"/><circle cx="540" cy="610" r="285" fill="#31594d" opacity=".15"/><text x="540" y="705" text-anchor="middle" font-size="220" font-family="Arial,Apple Color Emoji,Segoe UI Emoji,sans-serif">${glyph}</text><path d="M210 1030h660" stroke="#31594d" stroke-width="14" opacity=".55"/><text x="540" y="1215" text-anchor="middle" font-size="56" font-weight="700" font-family="Arial,sans-serif" fill="#263f37">${headline}</text><text x="540" y="1340" text-anchor="middle" font-size="36" font-family="Arial,sans-serif" fill="#51675f">${sub}</text><text x="540" y="1530" text-anchor="middle" font-size="31" font-family="Arial,sans-serif" fill="#6b7d76">${label}</text></svg>`)}`;
const img=(label:string,matches:string[],glyph:string,headline:string,sub:string,alt:string,sourceUrl:string):RichMediaEntry=>({label,matches,tag:'ARTE ESPECÍFICA · 08/09',title:headline,caption:sub,images:[{url:art(label,glyph,headline,sub),alt,caption:sub,credit:'Father Giulian News · arte editorial específica 08/09',sourceUrl,kind:'REFERENCE'}]});
export const dailyRichMedia20260908:RichMediaEntry[]=[
img('Papo de hoje',['coisa mais inesperada que você aprendeu','inesperada que você aprendeu'],'💡','APRENDIZADO INESPERADO','O QUE TE SURPREENDEU?','Arte 9:16 específica com lâmpada e surpresa para conversa sobre algo inesperado aprendido na semana','https://www.gov.br/educacao/pt-br'),
img('Desafio do casal',['sobremesa ou lanche simples','poucos passos'],'🥪','FAÇAM JUNTOS','UM LANCHE SIMPLES','Arte 9:16 específica com lanche simples preparado em dupla para desafio do casal','https://www.gov.br/saude/pt-br'),
img('Curiosidades',['lontra-marinha tem uma das pelagens','pelagem extremamente densa'],'🦦','LONTRA-MARINHA','PELAGEM É ISOLAMENTO','Arte 9:16 específica com lontra-marinha e camada de ar representando isolamento da pelagem','https://www.montereybayaquarium.org/animals/animals-a-to-z/sea-otter'),
img('Curiosidades',['10 metros de profundidade','pressão no oceano'],'🌊','OCEANO · PRESSÃO','AUMENTA AO DESCER','Arte 9:16 específica com coluna de água e indicador de pressão por profundidade','https://oceanservice.noaa.gov/facts/pressure.html'),
img('Curiosidades',['lua se afasta da terra','3,8 centímetros por ano'],'🌙','LUA EM MOVIMENTO','~3,8 CM POR ANO','Arte 9:16 específica com Terra, Lua e seta de afastamento orbital','https://science.nasa.gov/moon/facts/'),
img('Curiosidades',['diamante e grafite','mesmo elemento: carbono'],'💎','CARBONO','DIAMANTE ≠ GRAFITE','Arte 9:16 específica com rede de diamante e camadas de grafite formadas por carbono','https://www.britannica.com/science/carbon-chemical-element'),
img('Curiosidades',['fungos que brilham no escuro','bioluminescência'],'🍄','FUNGOS QUE BRILHAM','BIOLUMINESCÊNCIA','Arte 9:16 específica com fungos emitindo brilho esverdeado em ambiente escuro estilizado','https://www.fs.usda.gov/wildflowers/beauty/bioluminescence/'),
img('Gravidez',['9 semanas + 2 dias','9s2d'],'🤰','9 SEMANAS + 2 DIAS','MUDANÇAS TODOS OS DIAS','Arte 9:16 específica para 9 semanas e 2 dias de gestação','https://www.nhs.uk/pregnancy/week-by-week/1-to-12/9-weeks/'),
img('Ser Pai',['opção neutra pronta','enjoo apertar'],'💧','DEIXE PRONTO','ÁGUA + OPÇÃO NEUTRA','Arte 9:16 específica com água e pequeno lanche neutro acessível para apoio durante enjoo','https://www.gov.br/saude/pt-br'),
img('Mundo',['ataques houthi atingem cidades','instalações de energia na arábia saudita','73 feridos'],'🔥','ARÁBIA SAUDITA','ATAQUES HOUTHI · ENERGIA','Arte 9:16 específica com instalação energética, alerta e referência visual ao sul da Arábia Saudita para os ataques confirmados em 08/09','https://www.reuters.com/world/middle-east/saudi-led-coalition-yemen-says-73-injured-houthi-attacks-kingdom-2026-09-08/'),
img('Mundo',['mísseis balísticos russos atingem kyiv','ataque balístico russo'],'🚀','KYIV SOB ATAQUE','MÍSSEIS BALÍSTICOS','Arte 9:16 específica com silhueta urbana de Kyiv e trajetória de míssil para o ataque confirmado em 08/09','https://www.reuters.com/world/europe/russian-ballistic-missiles-hit-kyiv-us-envoys-leave-2026-09-08/'),
img('Tempo e Clima',['são paulo amanhece encoberta','madrugada sem chuva','máxima prevista de 18°c'],'☁️','SÃO PAULO · MANHÃ','ENCOBERTO · 11–18°C','Arte 9:16 específica com nuvens e termômetro para a manhã encoberta e a faixa de 11°C a 18°C prevista pelo CGE em 08/09','https://www.cgesp.org/v3/'),
img('Corinthians',['único treino completo na argentina','antes de enfrentar o estudiantes'],'⚽','TIMÃO EM LA PLATA','TREINO ANTES DO JOGO','Arte 9:16 específica com bola, campo e referência a La Plata para agenda do Corinthians','https://www.gazetaesportiva.com/times/corinthians/corinthians-pressionado-semana-libertadores-brasileirao/'),
img('Viagens',['paradas que ele oferece','ponto seguro para parar'],'🛣️','ROTA + PARADAS','ESTRUTURA NO CAMINHO','Arte 9:16 específica com estrada e pontos de parada seguros ao longo do trajeto','https://www.der.sp.gov.br/'),
img('Música',['seguindo apenas a bateria','bateria e percussão'],'🥁','SIGA A BATERIA','PAUSAS · VIRADAS · DINÂMICA','Arte 9:16 específica com bateria e ondas rítmicas para escuta focada','https://www.gov.br/cultura/pt-br'),
img('Tecnologia',['mistral capta €3 bilhões','avaliação de cerca de us$ 24 bilhões'],'🧠','MISTRAL · €3 BI','~US$24 BI DE VALOR','Arte 9:16 específica com cérebro digital e referência à rodada de investimento da Mistral em 08/09','https://www.reuters.com/world/europe/french-ai-company-mistral-hits-24-billion-valuation-funding-round-2026-09-08/'),
img('Carros até R$ 70 mil',['primeira partida do dia','motor frio'],'🚗','ATÉ R$70 MIL','TESTE COM MOTOR FRIO','Arte 9:16 específica com carro, termômetro frio e chave de partida para avaliação de usado','https://www.gov.br/senatran/pt-br'),
img('Motos',['corrente muito seca','folga irregular'],'🏍️','CORRENTE E RELAÇÃO','FOLGA · ELOS · LUBRIFICAÇÃO','Arte 9:16 específica com corrente, coroa e pontos de inspeção de motocicleta','https://www.gov.br/prf/pt-br/assuntos/seguranca-viaria'),
img('Mecânica',['chiado de correia','sintoma, não diagnóstico'],'🔧','CHIADO DE CORREIA','PROCURE A CAUSA','Arte 9:16 específica com correia, tensionador e polias para diagnóstico de ruído','https://www.gov.br/senatran/pt-br')
];