import type { EditorialDossier } from './editorial-dossier-types';

const dossier=(title:string,deck:string,points:string[],sources:{label:string;url:string}[]=[]):EditorialDossier=>({
  readingTime:'8–12 MIN',
  title,
  deck,
  opening:[deck,'Esta atualização das 10h separa dado novo, mecanismo e consequência prática sem tratar cenário como certeza.'],
  sections:[
    {kicker:'O DADO NOVO',title:'O que mudou desde a edição-base',paragraphs:[points[0]??deck,points[1]??'A leitura depende de contexto e fonte.']},
    {kicker:'VIDA REAL',title:'Como isso chega ao cotidiano',paragraphs:[points[2]??'O efeito depende de transmissão, prazo e decisões intermediárias.'],bullets:points.slice(3,7)},
  ],
  callout:{label:'NÃO CONFUNDA',title:'Indicador não é resultado garantido',text:points[7]??'Um dado altera o cenário; raramente determina sozinho a próxima decisão.'},
  takeaways:[points[8]??'Separe indicador de resultado final.',points[9]??'Observe o mecanismo de transmissão.',points[10]??'Use a fonte mais próxima do dado original.'],
  sources,
});

export const editorialDaily20260817_10h:Record<string,EditorialDossier>={
  brasil:dossier('IBC-Br: a economia perdeu velocidade, mas o PIB oficial ainda vem depois','O dado do Banco Central mostra um segundo trimestre bem mais fraco que o primeiro e uma contração mensal em junho.',[
    'O IBC-Br avançou 0,2% no segundo trimestre e caiu 0,6% em junho, em ambos os casos na comparação dessazonalizada relevante para ritmo da atividade.','Serviços recuaram 0,1% no trimestre, enquanto indústria e agricultura ainda cresceram; isso ajuda a explicar por que a desaceleração não é uniforme.','Para famílias, o efeito tende a aparecer por emprego, renda, vendas e crédito antes de aparecer como uma manchete simples de “recessão” ou “recuperação”.','Não trate IBC-Br como PIB oficial.','Compare com mercado de trabalho e renda.','Crédito caro reduz consumo e investimento com defasagem.','PIB do IBGE em 1º de setembro será a referência oficial.','Desaceleração pode ajudar inflação, mas não obriga o BC a cortar juros imediatamente.','O ritmo caiu frente ao 1º trimestre.','Serviços foram o ponto mais fraco.','Decisão doméstica deve olhar renda e CET, não apenas o índice.'
  ],[{label:'Banco Central · Indicadores de atividade',url:'https://www.bcb.gov.br/estatisticas/indicadoratividade'},{label:'Reuters · IBC-Br · 17/08/2026',url:'https://www.reuters.com/world/americas/brazil-posts-modest-second-quarter-growth-central-bank-index-shows-2026-08-17/'}]),

  politica:dossier('Depois do registro, o melhor antídoto contra propaganda é documento oficial','A campanha começou, mas o eleitor agora dispõe de uma camada diária de dados oficiais para separar discurso, proposta, processo e financiamento.',[
    'O DivulgaCandContas reúne informações dos pedidos de registro e contas; o portal de Dados Abertos publica arquivos de candidatos de 2026 com frequência diária.','Para cargos do Executivo, o conjunto oficial inclui recursos de propostas de governo; isso permite confrontar anúncio de campanha com documento protocolado.','Para a população, o ganho prático é perguntar “isso muda meu salário, SUS, imposto, transporte ou segurança por qual mecanismo e em quanto tempo?”.','Presidente/governador: diferencie execução administrativa de lei, PEC e orçamento.','Senador: diferencie pauta legislativa de promessa de execução direta.','Pedido de registro não é sinônimo de deferimento.','Proposta publicada não é resultado garantido.','Mais documento oficial reduz dependência de corte de vídeo e corrente de mensagem.','Use duas fontes: processo/contas e proposta.','Cheque poder real do cargo.','Impacto na vida real deve ser descrito de forma condicional.'
  ],[{label:'TSE · DivulgaCandContas',url:'https://www.tse.jus.br/administracao/painel/divulgacao-de-candidaturas-e-contas-eleitorais'},{label:'TSE · Dados Abertos · Candidatos 2026',url:'https://dadosabertos.tse.jus.br/dataset/candidatos-2026'}]),

  financas:dossier('Juro alto funciona desacelerando a economia — e isso tem custo','O IBC-Br mais fraco é compatível com a transmissão da Selic restritiva, mas a próxima decisão do Copom continua dependendo de inflação, expectativas e riscos.',[
    'Com Selic em 14%, crédito caro reduz demanda e investimento; o IBC-Br de junho e do trimestre mostra que esse freio está aparecendo na atividade.','Ao mesmo tempo, inflação em 12 meses ainda exige cautela, então desaceleração não equivale automaticamente a um ciclo acelerado de cortes.','No orçamento da família, o mecanismo é concreto: parcela alta, refinanciamento caro e mais sensibilidade a perda ou oscilação de renda.','Compare CET e prazo, não só prestação.','Evite antecipar dívida com base em “juros vão cair”.','Reserva de emergência ganha valor quando atividade perde força.','Contratos pós-fixados podem reagir de maneira diferente dos prefixados.','Mercado antecipa decisões; o Banco Central decide com dados novos.','Atividade esfriou.','Crédito continua restritivo.','Planeje com a taxa disponível hoje.'
  ],[{label:'Banco Central · Taxa Selic',url:'https://www.bcb.gov.br/controleinflacao/taxaselic'},{label:'Reuters · atividade brasileira · 17/08/2026',url:'https://www.reuters.com/world/americas/brazil-posts-modest-second-quarter-growth-central-bank-index-shows-2026-08-17/'}]),

  tecnologia:dossier('IA virou também uma disputa por funding','A Alphabet avalia captar em dólar australiano, mostrando como a infraestrutura de IA está levando Big Tech a diversificar fontes e moedas de financiamento.',[
    'A empresa mandatou bancos para trabalhar em uma possível primeira emissão em AUD, com prazos considerados de 3 a 20 anos; valor e uso específico ainda não foram divulgados.','O movimento ocorre em um ciclo no qual hyperscalers aumentaram muito capex e passaram a recorrer mais a dívida e equity, não apenas ao caixa operacional.','Para tecnologia, isso importa porque custo do capital pode definir quais data centers, chips, redes e projetos são construídos primeiro.','Funding barato acelera expansão.','Funding caro aumenta exigência de retorno.','Diversificar moeda amplia investidores, mas adiciona gestão cambial.','Capex de IA concorre com outras demandas de capital.','“Planeja emitir” não significa “emissão concluída” nem define o destino exato dos recursos.','Infraestrutura de IA é intensiva em capital.','Mercado de dívida virou parte da cadeia tecnológica.','Observe capex, fluxo de caixa e custo de funding juntos.'
  ],[{label:'Reuters · Alphabet / bonds em AUD · 17/08/2026',url:'https://www.reuters.com/business/finance/alphabet-eyes-inaugural-australian-dollar-bond-bookrunners-message-says-2026-08-17/'},{label:'Google · infraestrutura de IA · Q1 2026',url:'https://blog.google/company-news/inside-google/message-ceo/alphabet-earnings-q1-2026/'}]),
};
