export type EditorialDeepRead = {
  slug: string;
  context: string[];
  practical: string[];
  limits: string[];
  watch: string[];
};

export const editorialDeepReads20260821: EditorialDeepRead[] = [
  { slug:'brasil', context:['Mudar a escala 6x1 mexe em jornada, descanso e organização de turnos; o efeito concreto depende do texto constitucional/legal que sobreviver à tramitação.','Setores contínuos podem precisar reorganizar cobertura, contratar, automatizar ou negociar escalas.'], practical:['Para trabalhador, a discussão envolve descanso, previsibilidade e renda. Para empresa, envolve produtividade, dimensionamento e custo por hora efetivamente coberta.','Compare o texto votado, eventuais transições e negociação coletiva antes de assumir que todos os setores terão a mesma regra.'], limits:['Avanço no Senado não significa regra já vigente.','Estimativas de emprego, produtividade ou custo dependem de hipóteses e não devem ser tratadas como resultado garantido.'], watch:['Próximas etapas e redação final.','Regras de transição/exceções.','Posições de governo, empregadores e centrais.'] },
  { slug:'mundo', context:['O ataque de grande escala a Kyiv combinou drones e diferentes tipos de mísseis, pressionando uma defesa aérea que precisa escolher o interceptor adequado para cada ameaça.','Mísseis balísticos são particularmente difíceis por velocidade e trajetória; Patriot é uma das capacidades usadas pela Ucrânia para esse tipo de defesa.'], practical:['A disponibilidade de interceptadores afeta não só risco militar, mas continuidade de energia, logística, hospitais e vida urbana.','Para ler notícias de guerra, separe dano confirmado, alegação de alvo militar e avaliação estratégica.'], limits:['Taxas de interceptação em guerra são difíceis de verificar de forma independente.','Uma fotografia de Patriot contextualiza defesa antimíssil, não mostra o ataque específico.'], watch:['Reposição de interceptadores.','Balanço consolidado de vítimas/danos.','Ataques a infraestrutura crítica e respostas diplomáticas.'] },
  { slug:'planeta', context:['A termoclina nasce quando aquecimento e mistura mantêm uma camada superficial relativamente quente, enquanto águas profundas permanecem frias.','A posição da termoclina muda com estação, latitude, vento e fenômenos como El Niño.'], practical:['Ela ajuda a entender por que temperatura da superfície não descreve todo o conteúdo de calor do oceano.','Também altera propagação de som, disponibilidade de nutrientes e comportamento de organismos.'], limits:['Não há uma profundidade única de termoclina para todo o oceano.','O esquema NOAA é conceitual; condições locais podem ser muito diferentes.'], watch:['Perfis de temperatura por profundidade.','Mudanças sazonais/El Niño.','Conteúdo de calor oceânico em áreas de ciclones.'] },
  { slug:'animais', context:['No canal SOFAR, a velocidade do som atinge um mínimo e os raios acústicos tendem a refratar de volta para essa zona.','Isso reduz perda de energia e permite que certos sons viajem muito mais longe do que perto da superfície.'], practical:['Mamíferos marinhos dependem fortemente de acústica para comunicação e orientação.','Hidrofones usam o mesmo ambiente físico para monitorar baleias, terremotos e outros sons oceânicos.'], limits:['Nem toda vocalização entra no canal ou percorre grandes distâncias.','Ruído, frequência, profundidade, relevo e temperatura alteram o alcance.'], watch:['Pesquisas de bioacústica.','Impacto do ruído de navios.','Mudanças de temperatura oceânica e propagação do som.'] },
  { slug:'tempo', context:['Uma frente fria reorganiza vento, temperatura e umidade; a queda de temperatura pode acontecer mesmo sem chuva forte em todos os bairros.','Rajadas são produzidas por gradientes de pressão e dinâmica de tempestades/frente, e podem variar muito localmente.'], practical:['Em vento forte, evite permanecer sob árvores, placas ou estruturas frágeis.','Planeje roupa e deslocamento para manhã/noite mais frias e acompanhe transporte se houver queda de galhos ou energia.'], limits:['Previsão é probabilística e condições de uma estação não representam toda a cidade.','Alerta para a Grande São Paulo não significa rajada de mesma intensidade em cada bairro.'], watch:['CGE/Defesa Civil.','Rajadas observadas.','Temperatura mínima e sensação térmica.'] },
  { slug:'curiosidades', context:['O espalhamento de Rayleigh é muito mais eficiente para comprimentos de onda curtos do que longos.','Ao pôr do sol, a luz atravessa uma coluna maior de atmosfera, então mais azul/verde sai do feixe direto antes de chegar aos olhos.'], practical:['O mesmo raciocínio explica o céu azul e ajuda a interpretar por que poeira, fumaça e aerossóis mudam a cor do horizonte.','Um experimento com lanterna e água levemente turva reproduz qualitativamente a mudança.'], limits:['“Vermelho = poluição” é simplificação; partículas e nuvens podem intensificar ou apagar cores.','A atmosfera não funciona como um filtro de cor uniforme.'], watch:['Diferenças entre dia limpo, úmido e com aerossóis.','Como a cor muda conforme o Sol se aproxima do horizonte.'] },
  { slug:'pai', context:['Carga mental é o trabalho invisível de perceber o que precisa acontecer, planejar, lembrar e delegar — mesmo quando outra pessoa executa.','Na gestação e no puerpério, sintomas, consultas e sono podem aumentar essa carga.'], practical:['Assuma ciclos completos de tarefas previsíveis: perceber, decidir, executar e avisar.','Pergunte quando a preferência dela importa, mas não transforme cada tarefa doméstica em uma solicitação de instruções.'], limits:['Apoiar não significa controlar alimentação, sintomas ou decisões médicas.','Preferências e capacidade variam de dia para dia.'], watch:['O que está gerando mais esforço naquele dia.','Consultas/exames próximos.','Sinais de que o cansaço ou sintomas precisam ser discutidos com o pré-natal.'] },
  { slug:'mecanica', context:['Fluidos DOT 3/4/5.1 à base de glicol absorvem umidade do ambiente ao longo do tempo.','Água reduz o ponto de ebulição; sob aquecimento severo, vapor no circuito pode aumentar a compressibilidade e o curso do pedal.'], practical:['Siga intervalo e especificação do fabricante.','Troca exige sangria correta e cuidado para não contaminar pintura ou introduzir ar.','Inspecione vazamentos, nível, mangueiras e estado geral junto com o fluido.'], limits:['Cor sozinha não mede ponto de ebulição.','DOT 5 à base de silicone tem comportamento diferente e não deve ser misturado indiscriminadamente.'], watch:['Histórico da última troca.','Especificação correta no manual.','Mudança de pedal em uso severo.'] },
  { slug:'nautica', context:['A milha náutica foi padronizada em 1.852 metros e conversa com a geometria angular da Terra e cartas marítimas.','Nó é velocidade: uma milha náutica por hora.'], practical:['A 10 nós, uma embarcação percorre cerca de 10 NM em uma hora sem considerar corrente/vento.','Tempo estimado de chegada combina distância, velocidade sobre o fundo e condições reais.'], limits:['Velocidade na água e sobre o fundo podem divergir por corrente e vento.','Carta ilustrativa não serve para navegação; use carta oficial atual e instrumentos adequados.'], watch:['SOG/STW no instrumento.','Corrente e vento.','Atualização e escala da carta usada.'] },
  { slug:'viagens', context:['Paranapiacaba fica no alto da Serra do Mar, ambiente de alta umidade onde neblina e chuva são características frequentes.','O patrimônio ferroviário nasceu da ligação entre planalto e porto, e o relevo explica boa parte da paisagem e da história.'], practical:['Calçado com aderência, capa/guarda-chuva e uma camada extra de roupa melhoram o passeio.','Confirme horários de visitação e retorno antes de sair, principalmente sem carro.'], limits:['Neblina não é garantida e pode reduzir visibilidade.','Horários e acesso a atrações mudam; a foto de referência não representa as condições do dia.'], watch:['Previsão meteorológica.','Agenda oficial de atrações/trilhas.','Opções de transporte para ida e retorno.'] },
  { slug:'financas', context:['Petróleo e câmbio podem afetar inflação por rotas diferentes: combustível/frete, insumos importados, expectativas e margens empresariais.','O real também reage a juros locais/globais, fluxo de capital, risco fiscal e apetite por emergentes.'], practical:['Para orçamento doméstico, observe tendência de combustível, alimentos/importados e crédito — não uma cotação isolada.','Para investimento, diferencie impacto em empresas importadoras, exportadoras e setores ligados a commodities.'], limits:['Brent alto não vira automaticamente preço de bomba na mesma proporção ou no mesmo dia.','Um fechamento do dólar não estabelece tendência de longo prazo.'], watch:['Brent e rotas de energia.','USD/BRL e juros futuros.','Inflação e comunicação de BC/Fed.'] },
  { slug:'tecnologia', context:['Inferência é a execução do modelo depois de treinado; aplicações agentic podem consumir muitos tokens e tool calls em sequência.','O CS-4 tenta aumentar velocidade por usuário e throughput por watt com três WSE-3 Turbo e arquitetura rack-scale modular.'], practical:['Para produto, latência menor pode permitir mais raciocínio/verificação no mesmo tempo de resposta.','Para infraestrutura, o cálculo precisa incluir energia, refrigeração, rede, utilização e custo por token — não só pico de FLOPS.'], limits:['Números de até 30x vêm do fabricante e variam por modelo/configuração; precisam de benchmark independente.','Mais velocidade não resolve qualidade, segurança ou retorno do produto.'], watch:['Benchmarks independentes.','Disponibilidade e preço.','Eficiência real por workload.','Comparação com GPUs/ASICs concorrentes.'] },
  { slug:'seguranca', context:['ClickFix explora uma mudança importante: o atacante tenta convencer o próprio usuário a abrir Run/Terminal e executar o comando, em vez de depender apenas de um exploit.','A técnica pode chegar por phishing, malvertising ou sites comprometidos e entregar infostealers, RATs e loaders.'], practical:['Treinamento precisa mencionar explicitamente CAPTCHAs ou “correções” que pedem Win+R/Terminal.','EDR pode procurar cadeias anômalas de explorer/terminal → PowerShell/curl → download/persistência.','Restringir Run/shell em perfis que não precisam reduz superfície.'], limits:['Nem todo uso de PowerShell/curl é malicioso; detecção precisa de contexto.','Bloquear um domínio isolado é frágil porque infraestrutura de campanha muda rápido.'], watch:['Novas variantes/lures.','Processos e comandos recorrentes no ambiente.','Atualizações de detecção da Microsoft/CTIR/CERT.'] },
];

export function deepReadForSlug(slug: string) { return editorialDeepReads20260821.find((item) => item.slug === slug); }
