import type { EditorialDossier } from './editorial-dossier-types';

const dossier=(title:string,deck:string,points:string[],sources:{label:string;url:string}[]=[]):EditorialDossier=>({
  readingTime:'8–12 MIN',
  title,
  deck,
  opening:[deck,'A leitura abaixo separa mecanismo, impacto prático e o que vale verificar antes de transformar informação em decisão.'],
  sections:[
    {kicker:'ENTENDA O MECANISMO',title:'O que está acontecendo por baixo da manchete',paragraphs:[points[0]??deck,points[1]??'O ponto central é observar causa, contexto e limites da informação.']},
    {kicker:'APLICAÇÃO PRÁTICA',title:'Como usar isso no mundo real',paragraphs:[points[2]??'A aplicação prática depende do contexto e da qualidade da evidência.'],bullets:points.slice(3,7)},
  ],
  callout:{label:'CONEXÃO',title:'O detalhe que muda a leitura',text:points[7]??'Dado isolado raramente é decisão; combine fonte, contexto, prazo e risco.'},
  takeaways:[points[8]??'Separe fato de cenário.',points[9]??'Procure a fonte primária.',points[10]??'Converta a informação em uma ação verificável.'],
  sources,
});

export const editorialDaily20260817:Record<string,EditorialDossier>={
  brasil:dossier('Abono salarial: calendário não é o mesmo que elegibilidade','A última faixa de nascimento do calendário 2026 começa em 17 de agosto, mas o cidadão ainda precisa conferir se cumpre os requisitos do benefício.',[
    'A CAIXA organiza o pagamento por mês de nascimento; novembro e dezembro entram nesta segunda-feira.','O calendário informa quando um benefício elegível pode ficar disponível, não cria o direito por si só.','Confira valor e situação nos canais oficiais antes de planejar o uso do dinheiro.','Evite links enviados por mensagem que peçam taxa ou senha.','Se o valor entrar, priorize dívida cara, reserva ou despesa já prevista.','Guarde comprovante e confira divergências pelos canais da CAIXA.','Não conte com valor estimado por terceiros.','Benefício trabalhista é um bom exemplo de por que “data de pagamento” e “direito ao benefício” são coisas diferentes.','17/08 é a data de início para novembro/dezembro.','Elegibilidade precisa ser verificada individualmente.','Use canal oficial e não pague intermediário.'
  ],[{label:'CAIXA · Abono Salarial',url:'https://www.caixa.gov.br/beneficios-trabalhador/abono-salarial/Paginas/default.aspx'}]),
  politica:dossier('Pós-registro: campanha, processo e contas são trilhas diferentes','Depois de 15 de agosto, o eleitor precisa acompanhar simultaneamente situação jurídica, propaganda e financiamento sem misturar uma coisa com a outra.',[
    'O DivulgaCandContas centraliza informações de pedidos de registro e contas eleitorais.','Pedido protocolado não significa deferimento; decisões e recursos podem alterar o status.','Compare discurso de campanha com documentos, proposta e capacidade institucional do cargo.','Cheque status jurídico antes de compartilhar “candidatura confirmada”.','Use prestação de contas para entender recursos e despesas.','No Executivo, compare proposta com orçamento e necessidade de Congresso/Alesp.','No Senado, trate promessa como pauta legislativa/fiscalizatória, não como execução direta.','A transparência pós-registro melhora porque há mais documentos oficiais para confrontar com propaganda.','Status jurídico e mérito da proposta são dimensões diferentes.','Impacto na vida real deve ser descrito de forma condicional.','Nenhum candidato recebe nota ou recomendação de voto.'
  ],[{label:'TSE · DivulgaCandContas',url:'https://www.tse.jus.br/administracao/painel/divulgacao-de-candidaturas-e-contas-eleitorais'},{label:'TSE · Calendário Eleitoral 2026',url:'https://www.tse.jus.br/legislacao/compilada/res/2026/resolucao-no-23-760-de-2-de-marco-de-2026'}]),
  mundo:dossier('Fed, dólar e bolsas: por que um dado americano atravessa fronteiras','Dados mais fracos nos EUA reduziram a expectativa de alta de juros e mexeram com moedas, yields e ações no início da semana.',[
    'Quando o mercado reduz a expectativa de juros, títulos americanos podem ficar relativamente menos atraentes e yields cair.','Isso pode enfraquecer o dólar e favorecer ativos de risco, mas o movimento não é automático nem permanente.','Para emergentes, a transmissão passa por fluxo de capital, câmbio e custo de financiamento.','Observe PMIs e inflação.','Compare probabilidade implícita com decisão oficial do Fed.','Não trate um pregão como tendência estrutural.','Energia e geopolítica podem virar a narrativa rapidamente.','Mercado precifica cenários antes de bancos centrais decidirem; preço não é comunicado oficial.','A aposta em alta de setembro caiu.','Dólar e yields reagiram.','A semana ainda depende de novos dados.'
  ],[{label:'Reuters · mercados globais · 17/08/2026',url:'https://www.reuters.com/world/china/global-markets-global-markets-2026-08-17/'}]),
  planeta:dossier('Aquíferos: água invisível, movimento lento','Água subterrânea ocupa poros e fraturas; sua recarga pode ser muito mais lenta que a percepção criada por uma chuva forte.',[
    'Chuva precisa infiltrar e atravessar camadas antes de chegar à zona saturada.','Permeabilidade, relevo, cobertura vegetal e uso do solo mudam a velocidade e o volume da recarga.','Planejamento hídrico precisa proteger áreas de recarga e controlar retirada.','Asfalto aumenta escoamento superficial.','Poços próximos podem competir pelo mesmo sistema.','Contaminação subterrânea pode persistir por anos.','Rios podem depender de descarga de aquíferos na estação seca.','Água subterrânea conecta uso urbano, agricultura e ecossistemas mesmo quando não é visível.','Aquífero não é um lago oco.','Recarga pode ser lenta.','Proteção de solo importa tanto quanto captação.'
  ],[{label:'USGS · Groundwater',url:'https://www.usgs.gov/special-topics/water-science-school/science/groundwater-what-groundwater'}]),
  animais:dossier('Urubus: saneamento ecológico em forma de ave','Necrófagos removem carcaças rapidamente e ocupam um nicho essencial na reciclagem de matéria orgânica.',[
    'A digestão altamente ácida ajuda essas aves a lidar com material que seria arriscado para muitas espécies.','Ao consumir carcaças, alteram a disponibilidade de alimento para outros necrófagos e decompositores.','Conservar essas aves é conservar uma função ecológica, não apenas uma espécie.','Não alimente animais silvestres.','Evite envenenamento secundário por iscas e pesticidas.','Colisões e perda de habitat também afetam populações.','A presença de urubus não é sinal de “ecossistema sujo”; é parte da ciclagem natural.','A estética humana costuma subestimar espécies que prestam serviços ecológicos importantes.','Necrófagos aceleram remoção de carcaças.','Digestão é altamente especializada.','Declínio populacional altera cadeias de decomposição.'
  ],[{label:'Smithsonian · vultures',url:'https://nationalzoo.si.edu/migratory-birds/news/why-vultures-matter'}]),
  tempo:dossier('Veranico em São Paulo: calor de dia e ar mais seco','A segunda-feira muda o padrão do fim de semana: tempo estável, máxima perto de 30°C e umidade mínima na faixa dos 30%.',[
    'A frente fria perde influência e o ar mais seco favorece aquecimento diurno.','Veranico é uma sequência curta de dias mais quentes e secos dentro de uma estação fria, não necessariamente uma onda de calor.','A rotina deve considerar hidratação, exposição solar e desconforto respiratório.','Evite exercício intenso no pico do calor se estiver desconfortável.','Água ao longo do dia é melhor que compensar tudo de uma vez.','Observe crianças, idosos e pessoas com doença respiratória.','A previsão pode mudar; atualizações de 10h e 17h devem substituir este quadro se necessário.','Umidade relativa depende da temperatura; o mesmo vapor pode produzir percentuais diferentes ao longo do dia.','Máxima perto de 30°C.','Umidade perto de 33%.','Sem chuva relevante na previsão-base.'
  ],[{label:'CGE/Defesa Civil · previsão para 17/08',url:'https://noticias.uol.com.br/cotidiano/ultimas-noticias/2026/08/15/alerta-chuva-sao-paulo.ghtm'}]),
  curiosidades:dossier('A anomalia da água que mantém o gelo na superfície','A água se expande ao congelar, fazendo o gelo ficar menos denso que a fase líquida.',[
    'Ligações de hidrogênio formam uma estrutura cristalina mais aberta no gelo.','A água líquida tem densidade máxima perto de 4°C, comportamento incomum entre substâncias comuns.','Esse detalhe físico muda ecossistemas inteiros em regiões frias.','Gelo superficial ajuda a isolar a água abaixo.','Lagos não precisam congelar de baixo para cima.','O ciclo sazonal mistura água e nutrientes.','No copo, gelo flutuante já desloca água equivalente ao próprio peso.','Uma propriedade molecular se transforma em regra de sobrevivência ecológica.','Gelo é menos denso que água líquida.','A estrutura cristalina ocupa mais volume.','Isso influencia lagos e clima local.'
  ],[{label:'USGS · Water density',url:'https://www.usgs.gov/special-topics/water-science-school/science/water-density'}]),
  musica:dossier('Do blues elétrico à tradição oral','Led Zeppelin e Pena Branca & Xavantinho mostram duas maneiras de construir emoção sem encher o arranjo de informação.',[
    'Since I’ve Been Loving You usa dinâmica, tensão e improvisação para fazer a música respirar.','Cuitelinho carrega uma tradição oral em interpretação contida, com forte sensação de deslocamento e saudade.','Escute primeiro a relação entre voz e espaço, depois os detalhes instrumentais.','No rock, perceba como o volume cresce e recua.','Na raiz, repare em timbre, fraseado e narrativa.','Evite ouvir só como fundo; são músicas que recompensam atenção.','O Top 5 caipira histórico permanece separado e não é substituído pelo drop diário.','Curadoria melhora quando repertórios não são misturados só por proximidade comercial.','Rock e caipira seguem separados.','O drop do dia muda sem duplicar catálogo.','Players continuam independentes.'
  ]),
  gravidez:dossier('6 semanas + 1 dia: enjoo, hidratação e limites do “normal”','Náusea pode aparecer em qualquer horário e varia muito; o foco prático é tolerância a líquidos, alimentação possível e sinais de desidratação.',[
    'A ACOG informa que náusea e vômitos da gravidez costumam começar antes de 9 semanas.','O termo morning sickness é enganoso porque sintomas podem ocorrer o dia inteiro.','Pequenas refeições e ajustes de rotina podem ajudar, mas medicação deve ser discutida com o pré-natal.','Observe quantidade e cor da urina.','Incapacidade de manter líquidos merece orientação.','Tontura/desmaio ao levantar é sinal de atenção.','Não compare intensidade de sintomas com outras gestantes como medida de evolução.','Na gestação inicial, segurança vem de acompanhamento e tendência clínica, não de um sintoma isolado.','6s+1d pela DPP 11/04/2027.','Enjoo pode ocorrer a qualquer hora.','Desidratação exige atenção.'
  ],[{label:'ACOG · Morning Sickness',url:'https://www.acog.org/womens-health/faqs/morning-sickness-nausea-and-vomiting-of-pregnancy'},{label:'Ministério da Saúde · Gravidez',url:'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/g/gravidez'}]),
  pai:dossier('Apoio concreto contra enjoo é retirar atrito da rotina','Cheiros, lixo, cozinha e tarefas pequenas podem pesar mais no primeiro trimestre; assumir essas fricções é uma forma objetiva de cuidado.',[
    'Aversões e náusea são comuns no primeiro trimestre e podem variar muito de um dia para outro.','O parceiro não precisa diagnosticar nem controlar comida: precisa facilitar o que ela tolera e respeitar limites.','Pergunte quais cheiros e tarefas estão piores hoje e assuma o que puder.','Ventile a cozinha.','Cuide do lixo e produtos fortes.','Deixe água e lanches simples disponíveis.','Anote dúvidas para o pré-natal em vez de improvisar medicação.','Presença útil é reduzir carga mental sem retirar autonomia.','Pergunte, não presuma.','Assuma tarefas-gatilho.','Escalone sintomas intensos ao pré-natal.'
  ],[{label:'ACOG · Partner’s Guide',url:'https://www.acog.org/womens-health/faqs/a-partners-guide-to-pregnancy'}]),
  carros:dossier('Quatro usados acima de 1.0 e abaixo de R$ 70 mil','O radar de hoje troca completamente o conjunto e mostra por que preço semelhante pode esconder complexidades mecânicas muito diferentes.',[
    'Punto, Sandero e Fox usam propostas mais simples e manuais; o Focus sobe muito em equipamento e risco de transmissão.','FIPE e média de mercado servem como referência, não como laudo do exemplar.','Separe dinheiro para cautelar, scanner, revisão inicial e eventuais consumíveis.','Não compre carro sem partida fria.','Teste arrefecimento e suspensão.','Histórico de transmissão é obrigatório no Focus.','Preço de anúncio acima de R$ 70 mil fica fora da curadoria.','Quanto mais “premium pelo preço de popular”, maior a necessidade de entender por que o mercado desconta aquele modelo.','Sem motores 1.0.','Teto rígido de R$ 70 mil.','Estado e histórico vencem aparência.'
  ],[{label:'Webmotors · FIPE agosto 2026',url:'https://www.webmotors.com.br/tabela-fipe/carros'}]),
  motos:dossier('Quatro motos, quatro custos totais','NMax, XRE 300, MT-07 e Versys parecem apenas uma escada de cilindrada, mas na prática mudam seguro, pneus, relação, posição e finalidade.',[
    'Scooter otimiza cidade; trail tolera piso ruim; naked privilegia desempenho; touring favorece estrada.','FIPE é só entrada: consumíveis e seguro crescem bastante nas maiores.','Defina uso antes de se apaixonar pelo motor.','Cheque marcas de queda.','Pneus e relação podem somar gasto relevante.','ABS e freios precisam de teste.','Na Versys, não invente média de mercado quando a plataforma informa amostra insuficiente.','Transparência sobre dado ausente é melhor que um preço falso com aparência precisa.','NMax é urbana.','XRE é uso misto.','MT-07 e Versys exigem orçamento maior de operação.'
  ],[{label:'Webmotors · FIPE Motos',url:'https://www.webmotors.com.br/tabela-fipe/motos'}]),
  mecanica:dossier('Fuel trim: diagnóstico antes da troca de peça','STFT e LTFT mostram quanto a ECU está adicionando ou retirando combustível para manter a mistura alvo.',[
    'STFT reage rápido; LTFT aprende uma tendência ao longo do tempo e condições.','Correção positiva aponta que a ECU está adicionando combustível; negativa indica retirada.','Compare lenta, carga parcial e temperatura de trabalho antes de concluir.','Ar falso tende a aparecer forte em lenta.','Pressão baixa de combustível pode persistir sob carga.','MAF/MAP e sonda precisam ser cruzados com outros dados.','Resetar adaptação sem corrigir a causa só apaga evidência temporariamente.','Scanner é instrumento de medição, não oráculo que nomeia a peça defeituosa.','Compare condições.','Cruze sensores.','Confirme com teste físico.'
  ]),
  nautica:dossier('Bomba de porão: redundância contra entrada de água','Uma bomba automática reduz risco, mas precisa de energia, caminho de descarga e manutenção para funcionar quando realmente necessária.',[
    'Água pode entrar por chuva, spray, vedação, mangueiras e pequenas falhas.','Boia travada, fusível queimado ou mangueira obstruída transformam uma bomba instalada em equipamento inútil.','Teste o sistema com água controlada antes de sair.','Confirme automático.','Cheque fusível e bateria.','Inspecione mangueira e saída.','Mantenha o porão sem detritos.','Equipamento de emergência deve ser testado em condição parecida com a função real, não apenas “ligado no botão”.','Bomba não corrige vazamento.','Automático precisa ser testado.','Alarme de nível adiciona uma camada importante.'
  ],[{label:'USCG · Boating Safety',url:'https://www.uscgboating.org/'}]),
  viagens:dossier('São Luiz do Paraitinga sem pressa','História, cultura caipira e Mata Atlântica fazem mais sentido em dois dias do que em uma corrida por “pontos turísticos”.',[
    'O centro histórico tombado preserva mais de 450 imóveis dentro da área protegida pelo Iphan.','A cidade fica a cerca de 176 km de São Paulo e serve de base para experiências urbanas e naturais.','Monte um dia de centro histórico e outro de natureza, verificando agendamentos.','Confirme funcionamento de atrações.','Não inicie trilha longa perto do fechamento.','Leve água e calçado adequado.','Não publique custo fechado sem data de hospedagem e transporte.','Uma boa viagem curta começa por reduzir improviso, não por encher o roteiro.','Centro histórico é a âncora.','Serra do Mar pede planejamento.','Custos devem ser cotados para a data real.'
  ],[{label:'IPHAN · São Luiz do Paraitinga',url:'https://portal.iphan.gov.br/pagina/detalhes/294'},{label:'Setur-SP',url:'https://www.turismo.sp.gov.br/sec_turismo/noticias/tradicao-folclore-festas-divino-atraem-turistas-todo-sp/'}]),
  financas:dossier('Fed menos agressivo não quita sua dívida cara','Mercado pode reduzir expectativa de juros, mas rotativo, cheque especial e parcelamento caro continuam cobrando CET hoje.',[
    'Yields e dólar reagiram à menor aposta de aperto do Fed.','A transmissão para o consumidor brasileiro passa por câmbio, política monetária local, risco de crédito e concorrência bancária.','Use a notícia para entender cenário, não para adiar renegociação de dívida cara.','Compare CET.','Simule portabilidade/renegociação.','Priorize liquidez de emergência.','Não confunda probabilidade implícita com decisão oficial.','Macro pode melhorar enquanto sua taxa individual continua alta por meses.','Mercado mudou expectativa.','Crédito doméstico reage com defasagem.','CET continua sendo a medida prática.'
  ],[{label:'Reuters · mercados globais · 17/08/2026',url:'https://www.reuters.com/world/china/global-markets-global-markets-2026-08-17/'}]),
  tecnologia:dossier('Custom silicon: a nuvem quer controlar mais da própria infraestrutura','Maia, TPU e Trainium mostram uma tendência: hyperscalers transformam hardware em parte da diferenciação do serviço.',[
    'Projetar chip próprio pode reduzir custo por workload e dependência de um único fornecedor.','Mas fabricar continua dependente de foundries, packaging, memória, energia e cadeia global.','Avalie desempenho por workload e custo total, não só TOPS/FLOPS.','Software e compiladores importam.','Disponibilidade de memória pode limitar uso.','Capacidade fabril vira ativo estratégico.','Clientes podem ficar mais presos ao ecossistema da nuvem.','Verticalização reduz algumas dependências e cria outras.','Chip próprio não elimina Nvidia.','Software define adoção.','Capacidade de fabricação é gargalo.'
  ],[{label:'Reuters · Maia 300',url:'https://www.reuters.com/business/microsoft-plans-unveil-its-new-maia-300-ai-chip-this-fall-information-reports-2026-08-10/'}]),
  seguranca:dossier('KEV: exploração real muda a prioridade','Um CVE em KEV carrega evidência de uso no mundo real; isso deve alterar SLA e hunting, especialmente em ativos expostos.',[
    'CVSS mede severidade técnica em um modelo; KEV adiciona evidência de exploração.','O melhor uso é cruzar KEV com inventário, exposição, reachability e criticidade.','Para edge e identidade, preserve evidência antes de simplesmente patchar.','Priorize ativos internet-facing.','Revise logs anteriores ao patch.','Confirme versão e feature afetada.','Documente mitigação temporária.','Patch reduz exposição futura, mas não prova ausência de comprometimento passado.','KEV é contexto operacional.','Scanner continua necessário.','Hunting entra quando a exploração já acontece.'
  ],[{label:'CISA · KEV',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog'}]),
  'appsec-ssdlc':dossier('Gate baseado em risco precisa de evidência','CVSS é só uma dimensão; um release gate defensável combina severidade com contexto da aplicação e exposição real.',[
    'Reachability separa componente presente de caminho explorável.','Exposição, privilégio e blast radius mudam urgência mesmo dentro da mesma severidade.','Registre por que bloqueou ou aceitou risco para que a decisão seja auditável.','Anexe SBOM/versão.','Registre endpoint ou caminho alcançável.','Cruze com KEV/advisory.','Exija owner e data de correção.','Um gate inteligente não significa gate frouxo; significa tornar a regra explicável e reproduzível.','Severidade não é urgência.','Contexto precisa ser evidenciado.','Exceção sem owner/prazo não é governança.'
  ],[{label:'CISA · KEV',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog'},{label:'FIRST · CVSS',url:'https://www.first.org/cvss/'}]),
};
