import type { EditorialDossier } from './editorial-dossier-types';

const dossier = (title:string, deck:string, opening:string[], sections:EditorialDossier['sections'], takeaways:string[], sources:EditorialDossier['sources']=[], disclaimer?:string):EditorialDossier => ({ readingTime:'10–14 MIN', title, deck, opening, sections, takeaways, sources, ...(disclaimer?{disclaimer}:{}) });

export const editorialDaily20260816: Record<string, EditorialDossier> = {
  brasil: dossier('CIN: identidade digital é também infraestrutura de confiança','A mudança do RG para a Carteira de Identidade Nacional não é apenas visual: ela reduz multiplicidade de números e amplia o papel da biometria na relação com o Estado.',['A transição é gradual, e o documento antigo não perde validade de forma instantânea. O ponto importante é entender quando a CIN passa de conveniência a requisito em fluxos específicos.'],[
    {kicker:'TRANSIÇÃO',title:'Por que não existe um “dia do fim do RG” agora',paragraphs:['A validade do documento antigo segue a transição oficial. Isso evita corrida artificial por atendimento e reduz o risco de golpes baseados em urgência falsa.'],bullets:['Primeira via em papel da CIN é gratuita.','A validade da CIN varia por faixa etária.','Regras de benefícios podem ter cronogramas próprios de biometria.']},
    {kicker:'PRIVACIDADE',title:'Biometria melhora identidade — e aumenta responsabilidade',paragraphs:['Quanto mais serviços dependem da mesma identidade biométrica, maior a necessidade de controles de acesso, rastreabilidade, minimização e resposta a incidentes.']},
    {kicker:'PRÁTICA',title:'O que fazer sem ansiedade',paragraphs:['Confirme exigências no canal oficial do seu estado ou do benefício; não entregue documentos e selfie a intermediários que criam falsa urgência.']}
  ],['O RG antigo não se torna inválido de uma hora para outra.','CIN e biometria estão virando infraestrutura de serviços públicos.','Transição digital precisa ser acompanhada de proteção contra fraude e abuso.'],[{label:'Governo Digital · CIN',url:'https://www.gov.br/governodigital/pt-br/identidade/identificacao-do-cidadao-e-carteira-de-identidade-nacional'}]),
  politica: dossier('Pós-registro: a campanha começa, mas o status jurídico continua mudando','A virada de 15 para 16 de agosto separa duas coisas que frequentemente são confundidas: estar em campanha e ter o registro definitivamente deferido.',['O prazo para apresentar pedidos terminou, mas a Justiça Eleitoral ainda analisa documentação, elegibilidade, impugnações e recursos. O comparador deve refletir essa incerteza sem transformar campanha em situação jurídica definitiva.'],[
    {kicker:'STATUS',title:'Pedido, análise e decisão são etapas diferentes',paragraphs:['O DivulgaCandContas passa a ser a referência operacional para acompanhar cada nome. Um pedido pode estar em análise, ser deferido, indeferido, sofrer recurso, renúncia ou substituição.']},
    {kicker:'PROPAGANDA',title:'Mais conteúdo político exige mais disciplina de fonte',paragraphs:['Com a propaganda geral permitida, aumenta o volume de anúncios, cortes, promessas e ataques. Separar material oficial, reportagem, decisão judicial e opinião evita que o comparador vire peça de campanha.']},
    {kicker:'NEUTRALIDADE',title:'Como comparar sem transformar o site em recomendação de voto',paragraphs:['Use a mesma estrutura para todos: trajetória verificável, propostas declaradas, argumentos favoráveis documentados, críticas e riscos documentados, status jurídico e fontes.']}
  ],['Propaganda autorizada não equivale a registro deferido.','Status eleitoral deve vir do TSE e pode mudar.','O comparador mantém estrutura simétrica e não dá nota nem recomendação.'],[{label:'TSE · Eleições 2026',url:'https://www.tse.jus.br/eleicoes/eleicoes-2026'},{label:'TSE · DivulgaCandContas',url:'https://divulgacandcontas.tse.jus.br/divulga/#/'}]),
  mundo: dossier('Quando a corrida da IA encontra o mercado de títulos','A infraestrutura de IA exige uma quantidade de capital que começa a disputar espaço com emissões soberanas e outros investimentos.',['A narrativa de IA normalmente começa em chips e modelos. A conexão macroeconômica menos óbvia aparece no financiamento: data centers, energia, rede e aquisições precisam de capital, e capital tem preço.'],[
    {kicker:'CAPITAL',title:'Juro real é o pedágio do investimento',paragraphs:['Quanto maior o retorno real disponível em títulos, maior tende a ser a taxa mínima exigida para financiar projetos de risco. Isso pode afetar valuations e decisões de expansão.']},
    {kicker:'IA',title:'Capex tecnológico não é abstrato',paragraphs:['Construir capacidade de IA envolve imóveis, conexão elétrica, refrigeração, óptica, storage e contratos de longo prazo. A conta passa muito além do preço da GPU.']},
    {kicker:'CENÁRIO',title:'Risco não é profecia',paragraphs:['Juros reais altos podem apertar condições financeiras sem necessariamente provocar recessão ou queda imediata das bolsas. O relevante é observar persistência e transmissão.']}
  ],['IA também é uma história de financiamento.','Juros reais altos elevam a régua de retorno de projetos.','Cenário de risco deve ser apresentado como possibilidade, não certeza.'],[{label:'Reuters · AI financing and real yields · 14/08/2026',url:'https://www.reuters.com/world/asia-pacific/ai-driven-surge-bond-yields-could-be-next-risk-markets-growth-2026-08-14/'}]),
  planeta: dossier('Termoclina: a fronteira invisível que organiza a água','Lagos e oceanos podem se comportar como sistemas em camadas, com consequências para oxigênio, nutrientes e vida aquática.',['Água quente e água fria têm densidades diferentes. Quando a energia disponível não é suficiente para misturar toda a coluna d’água, forma-se uma transição marcada de temperatura: a termoclina.'],[
    {kicker:'FÍSICA',title:'Temperatura muda densidade e circulação',paragraphs:['A superfície recebe energia solar e tende a aquecer primeiro. A água profunda permanece fria e mais densa, criando estabilidade vertical.']},
    {kicker:'ECOLOGIA',title:'Uma barreira física vira uma barreira ecológica',paragraphs:['Oxigênio dissolvido, nutrientes e organismos podem ficar distribuídos de forma muito diferente acima e abaixo da termoclina.']},
    {kicker:'SAZONALIDADE',title:'Vento e frio podem desmontar as camadas',paragraphs:['Mudanças sazonais resfriam a superfície e aumentam mistura, redistribuindo oxigênio e nutrientes.']}
  ],['A água não é necessariamente uma massa homogênea.','Estratificação altera ecologia e qualidade da água.','Mistura sazonal pode reorganizar todo o sistema.'],[{label:'NOAA Ocean Service',url:'https://oceanservice.noaa.gov/'}]),
  animais: dossier('Dormir sem desligar completamente','Sono uni-hemisférico mostra como evolução pode adaptar uma necessidade universal a riscos ambientais diferentes.',['Em algumas aves, um hemisfério cerebral entra em estado de sono mais profundo enquanto o outro mantém maior vigilância. Isso permite combinar recuperação com percepção do ambiente.'],[
    {kicker:'CÉREBRO',title:'Descanso assimétrico',paragraphs:['O padrão não significa ausência de sono. Significa que o sono pode ser distribuído no cérebro de modo diferente daquele observado em humanos.']},
    {kicker:'PRESSÃO',title:'Predador, migração e posição no grupo',paragraphs:['O benefício aumenta quando dormir profundamente por longos períodos eleva risco de predação ou perda de posição durante deslocamentos.']},
    {kicker:'LIÇÃO',title:'Inteligência não é a única medida de adaptação',paragraphs:['Fisiologia e comportamento resolvem problemas ecológicos específicos; comparar tudo com experiência humana esconde a especialização das espécies.']}
  ],['Sono animal tem soluções evolutivas diferentes.','Vigilância e descanso podem coexistir.','Contexto ecológico explica o comportamento melhor que analogias humanas.'],[{label:'Cornell Lab · Bird Academy',url:'https://academy.allaboutbirds.org/'}]),
  tempo: dossier('Do temporal ao ar seco: como o risco meteorológico muda em 24 horas','Depois da instabilidade de sábado, São Paulo entra em uma sequência de aquecimento e menor umidade.',['A mesma população que precisou acompanhar alagamentos e raios pode, no dia seguinte, precisar prestar atenção em hidratação, qualidade do ar e calor. Meteorologia prática é acompanhar a transição do risco.'],[
    {kicker:'DOMINGO',title:'A frente se afasta',paragraphs:['O sol ganha espaço e as máximas sobem. A umidade ainda não despenca imediatamente, mas a tendência dos dias seguintes é mais quente e seca.']},
    {kicker:'SEMANA',title:'Calor acumulado muda conforto e qualidade do ar',paragraphs:['Períodos secos reduzem dispersão de poluentes e aumentam risco de queimadas e irritação respiratória.']},
    {kicker:'ROTINA',title:'Troque o checklist junto com o tempo',paragraphs:['Guarda-chuva e alerta de alagamento dão lugar a água, protetor solar e acompanhamento da umidade relativa.']}
  ],['Risco meteorológico muda rapidamente.','A próxima tendência em SP é mais quente e seca.','Aplicação prática depende da fase do sistema, não do clima médio da estação.'],[{label:'CGE São Paulo',url:'https://www.cgesp.org/'}]),
  curiosidades: dossier('Cebola: uma reação química montada na hora do corte','O ardor nos olhos começa quando compartimentos celulares que estavam separados são rompidos.',['A cebola armazena precursores e enzimas em estruturas diferentes. Cortar ou esmagar mistura esses componentes e inicia uma cadeia química que produz moléculas voláteis irritantes.'],[
    {kicker:'QUÍMICA',title:'O irritante não está esperando pronto',paragraphs:['A ruptura celular é parte do mecanismo. Por isso uma faca mais afiada, que esmaga menos tecido, pode reduzir a quantidade liberada.']},
    {kicker:'OLHOS',title:'Lacrimejar é defesa',paragraphs:['O composto atinge a superfície úmida dos olhos e ativa terminações sensoriais; as lágrimas ajudam a diluir e remover o irritante.']},
    {kicker:'COZINHA',title:'Ventilação e temperatura mudam exposição',paragraphs:['Reduzir volatilidade ou afastar o composto do rosto tende a ajudar mais que truques sem mecanismo plausível.']}
  ],['O corte inicia a química.','Lágrima é resposta protetora.','Faca afiada e ventilação têm mecanismo plausível para reduzir irritação.'],[{label:'American Chemical Society',url:'https://www.acs.org/'}]),
  musica: dossier('Duas construções de tensão: dinâmica e narrativa','Dream On e Chico Mineiro mostram que uma música pode prender atenção por mecanismos completamente diferentes.',['No Aerosmith, a tensão cresce pela dinâmica e pelo alcance vocal. Em Tonico & Tinoco, a tensão nasce da narrativa e da expectativa sobre o destino dos personagens.'],[
    {kicker:'ROCK',title:'Escute a arquitetura de Dream On',paragraphs:['Observe como a música guarda energia para o final e usa repetição para tornar o clímax maior.']},
    {kicker:'CAIPIRA',title:'Chico Mineiro como conto oral',paragraphs:['A melodia serve à história; o impacto depende de acompanhar os acontecimentos, não apenas o refrão.']},
    {kicker:'EXERCÍCIO',title:'Repita a escuta mudando o foco',paragraphs:['Primeiro siga voz e letra; depois preste atenção apenas ao acompanhamento e ao modo como ele sustenta a tensão.']}
  ],['Rock e moda de viola podem construir clímax por caminhos diferentes.','O Top 5 histórico continua fixo.','Player embutido permite transformar contexto em escuta ativa.']),
  gravidez: dossier('Semana 6: o que muda rápido e o que ainda não deve virar conclusão','No início da semana 6, estruturas embrionárias avançam rapidamente e poucos dias podem mudar bastante a aparência de um ultrassom.',['A atividade cardíaca embrionária pode começar a ser detectável nesta fase, mas o momento varia com datação, equipamento e características do exame. Um resultado precoce precisa ser interpretado no contexto clínico.'],[
    {kicker:'DESENVOLVIMENTO',title:'Sistema nervoso e órgãos em organização intensa',paragraphs:['O tubo neural e estruturas cerebrais seguem desenvolvimento acelerado; brotos dos membros começam a se tornar mais reconhecíveis.']},
    {kicker:'ULTRASSOM',title:'“Ainda não apareceu” não é diagnóstico isolado',paragraphs:['Diretrizes obstétricas usam critérios e, quando necessário, exames seriados para evitar conclusões precipitadas.']},
    {kicker:'SEGURANÇA',title:'Sintomas que merecem avaliação',paragraphs:['Dor forte ou unilateral, sangramento importante, desmaio, febre ou piora importante justificam contato com equipe de saúde ou atendimento.']}
  ],['Seis semanas é uma fase de mudanças rápidas.','Ultrassom precoce depende fortemente da datação.','Sinais de alerta têm mais importância que comparação com relatos de outras gestantes.'],[{label:'NHS · Week 6',url:'https://www.nhs.uk/best-start-in-life/pregnancy/week-by-week-guide-to-pregnancy/1st-trimester/week-6/'},{label:'ACOG · Early Pregnancy Loss',url:'https://www.acog.org/womens-health/faqs/early-pregnancy-loss'}],'Conteúdo educativo; não substitui pré-natal ou avaliação médica.'),
  pai: dossier('Apoio prático é reduzir decisões pequenas','Preparar o básico da semana pode ter mais impacto do que procurar uma grande ação simbólica.',['Náusea, cansaço e mudanças de rotina aumentam o custo de pequenas decisões. Antecipar refeições simples, água, agenda e compras reduz atrito sem retirar autonomia.'],[
    {kicker:'20 MINUTOS',title:'Organize sem transformar cuidado em controle',paragraphs:['Combine o que ajuda e o que incomoda. Prepare opções, não ordens.']},
    {kicker:'ROTINA',title:'Faça o invisível aparecer',paragraphs:['Lista de compras, horários, documentos e transporte são tarefas pequenas isoladamente, mas acumulam carga mental.']},
    {kicker:'VÍNCULO',title:'Disponibilidade previsível vale mais que heroísmo pontual',paragraphs:['Constância cria confiança e permite que apoio seja percebido antes de virar emergência.']}
  ],['Reduzir carga mental é apoio concreto.','Planejamento deve respeitar preferências da gestante.','Constância pesa mais que ações grandiosas e raras.']),
  carros: dossier('Quatro usados: o preço da tabela é só a primeira camada','HB20, Onix Turbo, Kicks e Corolla mostram quatro combinações diferentes de idade, tecnologia, transmissão e custo total.',['FIPE e média de anúncios ajudam a calibrar negociação, mas não substituem cautelar, inspeção mecânica, histórico e orçamento para o primeiro ano.'],[
    {kicker:'HATCH',title:'HB20 versus Onix Turbo',paragraphs:['HB20 1.6 entrega conjunto conhecido; Onix mais novo oferece turbo e segurança, cobrando mais disciplina de manutenção.']},
    {kicker:'MAIORES',title:'Kicks versus Corolla',paragraphs:['Kicks prioriza posição alta e eficiência; Corolla oferece sedã médio, potência e conforto por preço maior.']},
    {kicker:'COMPRA',title:'Histórico > quilometragem isolada',paragraphs:['Cruze hodômetro com desgaste, notas de serviço, pneus, fluidos, estrutura e comportamento no teste.']}
  ],['Tabela não é diagnóstico.','Transmissão e histórico mudam o risco de cada opção.','Reserve orçamento para inspeção e manutenção pós-compra.'],[{label:'Webmotors · Tabela FIPE',url:'https://www.webmotors.com.br/tabela-fipe/'}]),
  motos: dossier('Quatro motos, quatro contextos de uso','PCX, Ténéré, Ninja 300 e CB 500X não deveriam ser julgadas pela mesma régua.',['A pergunta útil não é qual “é melhor”, mas qual proposta combina com o uso: cidade, piso ruim, pilotagem esportiva ou estrada.'],[
    {kicker:'URBANO',title:'PCX minimiza atrito cotidiano',paragraphs:['Automática e compacta, troca desempenho e versatilidade rodoviária por praticidade.']},
    {kicker:'MISTO',title:'Ténéré e CB 500X resolvem viagens em escalas diferentes',paragraphs:['A 250 prioriza simplicidade e piso ruim; a 500 adiciona reserva de motor e eleva custo de pneus, seguro e consumíveis.']},
    {kicker:'ESPORTIVA',title:'Ninja 300 pede leitura de quedas e modificações',paragraphs:['Carenagens, batentes, mesa, pedaleiras e pneus contam parte do histórico de uso.']}
  ],['Uso real vem antes da cilindrada.','Consumíveis podem alterar muito o custo de entrada.','Ciclística e histórico são essenciais em moto usada.'],[{label:'Webmotors · Tabela FIPE Motos',url:'https://www.webmotors.com.br/tabela-fipe/motos'}]),
  mecanica: dossier('Vela de ignição: pista útil, diagnóstico incompleto','A aparência da vela pode orientar hipóteses, mas interpretar uma peça isolada sem contexto cria falsos diagnósticos.',['Folga, eletrodo, depósitos e diferenças entre cilindros oferecem sinais sobre combustão, óleo e temperatura. A confirmação exige cruzar sintomas, scanner e medições.'],[
    {kicker:'LEITURA',title:'Compare cilindros, não apenas uma foto de referência',paragraphs:['Diferenças entre velas do mesmo motor podem ser mais informativas que tentar encaixar uma cor em uma tabela genérica.']},
    {kicker:'MEDIÇÃO',title:'Scanner e compressão tiram a hipótese do campo visual',paragraphs:['Misfire counters, fuel trims e testes mecânicos ajudam a separar ignição, mistura e vedação.']},
    {kicker:'MANUTENÇÃO',title:'Especificação e torque importam',paragraphs:['Vela errada ou instalada incorretamente pode criar novos problemas em vez de corrigir o antigo.']}
  ],['Vela é evidência, não sentença.','Compare cilindros e sintomas.','Confirme hipótese com dados antes de trocar peças.'],[{label:'Bosch Aftermarket',url:'https://www.boschaftermarket.com/'}]),
  nautica: dossier('Habilitação amadora define onde navegar — não substitui preparo','Arrais, Mestre e Capitão-Amador representam alcances diferentes, mas a categoria no documento é apenas parte da segurança.',['Conhecimento de meteorologia, carta, comunicação, combustível e salvatagem continua necessário mesmo dentro do limite formal de habilitação.'],[
    {kicker:'CATEGORIAS',title:'O alcance cresce com a habilitação',paragraphs:['A regulamentação diferencia navegação interior, costeira e oceânica. Mestre-Amador alcança navegação costeira dentro do limite regulamentar; Capitão-Amador amplia esse alcance.']},
    {kicker:'LIMITES',title:'Amador não é profissional',paragraphs:['A CHA de esporte e recreio não autoriza automaticamente transporte remunerado ou atuação profissional.']},
    {kicker:'SEGURANÇA',title:'Carteira não substitui planejamento',paragraphs:['A travessia deve considerar autonomia, abrigo, previsão, comunicações e condição da tripulação.']}
  ],['Categoria define alcance formal.','Atividade amadora e profissional têm regimes diferentes.','Planejamento continua essencial em qualquer categoria.'],[{label:'GOV.BR · Carteira de Habilitação de Amador',url:'https://www.gov.br/pt-br/servicos/solicitar-carteira-de-habilitacao-para-se-tornar-um-navegador-amador-ou-ascender-de-categoria'}]),
  viagens: dossier('Serra da Cantareira: perto não significa sem planejamento','Um destino natural próximo da capital ainda exige leitura de horário, acesso, clima, água e dificuldade da trilha.',['A vantagem de um passeio curto é reduzir deslocamento, não eliminar logística. Chegar tarde, sem água ou sem saber a condição da trilha transforma proximidade em risco desnecessário.'],[
    {kicker:'ANTES',title:'Confirme o funcionamento no canal oficial',paragraphs:['Unidades de conservação podem ter limites de acesso, mudanças por manutenção ou regras específicas de ingresso.']},
    {kicker:'TRILHA',title:'Calçado, água e tempo de retorno são parte do roteiro',paragraphs:['Planeje para terminar com margem antes do fechamento e ajuste distância à condição física do grupo.']},
    {kicker:'IMPACTO',title:'Natureza perto da cidade merece a mesma etiqueta ambiental',paragraphs:['Leve seu lixo, não alimente animais e permaneça nas trilhas autorizadas.']}
  ],['Perto de SP ainda exige planejamento.','Horário de retorno é tão importante quanto horário de chegada.','Regras da unidade devem ser checadas antes da saída.'],[{label:'Fundação Florestal SP',url:'https://fflorestal.sp.gov.br/'}]),
  financas: dossier('Juros reais: a régua invisível por trás de muitas decisões','O retorno descontado da inflação muda a atratividade relativa de títulos, ações, imóveis e projetos empresariais.',['Quando o mercado consegue obter retorno real maior em ativos de menor risco, investimentos mais incertos precisam prometer mais retorno para competir.'],[
    {kicker:'VALOR PRESENTE',title:'Fluxo futuro vale menos quando a taxa sobe',paragraphs:['A matemática do desconto reduz o valor presente de receitas distantes, afetando especialmente ativos de crescimento.']},
    {kicker:'CRÉDITO',title:'Custo de capital chega à empresa e à família',paragraphs:['Condições financeiras mais apertadas podem aparecer em empréstimos, financiamento e exigência maior de retorno.']},
    {kicker:'PRÁTICA',title:'Compare CET, prazo e liquidez antes de assumir dívida',paragraphs:['A menor parcela pode esconder um custo total maior quando o prazo é estendido.']}
  ],['Juro real é uma régua de oportunidade.','Taxas longas afetam valuation e crédito.','CET e custo total importam mais que parcela isolada.'],[{label:'Reuters · real yields · 14/08/2026',url:'https://www.reuters.com/world/asia-pacific/ai-driven-surge-bond-yields-could-be-next-risk-markets-growth-2026-08-14/'}],'Conteúdo educacional; não é recomendação individual de investimento.'),
  tecnologia: dossier('IA além da GPU: o sistema inteiro precisa escalar','Aceleradores recebem destaque, mas capacidade útil depende de energia, rede, memória, storage, refrigeração e software funcionando como um conjunto.',['Um cluster com chips disponíveis mas sem energia, interconexão ou memória suficiente não entrega a capacidade esperada. O gargalo se move para a peça mais lenta do sistema.'],[
    {kicker:'ENERGIA',title:'Megawatts viram parte da arquitetura',paragraphs:['Conexão elétrica, subestação e refrigeração podem ter cronogramas maiores que a compra dos servidores.']},
    {kicker:'REDE',title:'Treino distribuído depende de interconexão',paragraphs:['Baixa latência e grande largura de banda reduzem o tempo em que aceleradores ficam esperando dados ou sincronização.']},
    {kicker:'MEMÓRIA',title:'HBM e storage moldam throughput',paragraphs:['Capacidade e velocidade de memória determinam quanto do modelo e dos dados pode permanecer próximo do compute.']}
  ],['Capacidade de IA é um sistema, não um chip.','Energia e rede podem limitar expansão.','O gargalo se desloca conforme a cadeia evolui.'],[{label:'Reuters · AI infrastructure financing · 14/08/2026',url:'https://www.reuters.com/world/asia-pacific/ai-driven-surge-bond-yields-could-be-next-risk-markets-growth-2026-08-14/'}]),
  seguranca: dossier('KEV operacional: do catálogo para a fila de remediação','Exploração conhecida deve alterar prioridade, mas o melhor programa ainda cruza exposição, privilégio, criticidade e evidência de comprometimento.',['A lista KEV é um sinal forte de realidade ofensiva. O erro é tratá-la como substituta de contexto: uma falha explorada em um ativo crítico e exposto tem urgência diferente da mesma classe em ambiente isolado.'],[
    {kicker:'TRIAGEM',title:'Exploração real fura a fila',paragraphs:['KEV, internet-facing, privilégio pós-exploração e blast radius formam uma priorização mais útil que CVSS sozinho.']},
    {kicker:'IR',title:'Patch e hunting são trabalhos diferentes',paragraphs:['Se a exploração pode ter ocorrido antes da correção, atualizar software não responde se o atacante já persistiu.']},
    {kicker:'MÉTRICA',title:'Meça tempo até reduzir exposição',paragraphs:['SLA de ticket é menos útil que tempo até patch, mitigação, isolamento ou remoção do ativo exposto.']}
  ],['KEV é sinal de exploração real.','Contexto do ativo continua necessário.','Correção e investigação de comprometimento não são a mesma coisa.'],[{label:'CISA · KEV Catalog',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog'}]),
  'appsec-ssdlc': dossier('Exploit chain: por que findings não vivem isolados','Falhas no mesmo produto ou trust boundary podem combinar pré-condições e ampliar impacto.',['SSRF, injeção, bypass de autenticação e credenciais comprometidas são frequentemente analisados em tickets separados. O atacante, ao contrário, procura a sequência que elimina cada barreira.'],[
    {kicker:'MODELAGEM',title:'Pergunte qual obstáculo cada falha remove',paragraphs:['Uma falha que parece limitada pode fornecer acesso de rede, identidade ou execução necessário para a seguinte.']},
    {kicker:'GATE',title:'Reachability e exposição enriquecem severidade',paragraphs:['O gate pode preservar CVSS original e adicionar sinais: KEV, internet-facing, auth, privilégio, criticidade, blast radius e mitigação.']},
    {kicker:'EVIDÊNCIA',title:'Explique por que bloqueou',paragraphs:['Um blocker confiável deve registrar a cadeia de raciocínio e as evidências técnicas, permitindo revisão sem esconder risco atrás de uma nota agregada.']}
  ],['Atacantes encadeiam falhas; scanners listam linhas.','Contexto deve enriquecer, não substituir, severidade.','Gate bom produz decisão reproduzível com evidência.'],[{label:'CISA · KEV Catalog',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog'},{label:'NVD · CVE-2026-15410',url:'https://nvd.nist.gov/vuln/detail/CVE-2026-15410'}])
};
