import type { EditorialDossier } from './editorial-dossier-types';

export const editorialDaily20260814: Record<string, EditorialDossier> = {
  brasil: {
    readingTime: '9 MIN DE LEITURA',
    title: 'Portabilidade não é renegociação: é competição pelo seu contrato',
    deck: 'O ganho real do Open Finance aparece quando uma dívida deixa de ser informação presa em um banco e vira um contrato comparável por outras instituições.',
    opening: ['Imagine um empréstimo que parece inevitável porque trocar de banco dá trabalho. A portabilidade muda justamente esse custo de saída.', 'Quando os dados do contrato circulam de forma padronizada e consentida, a discussão deixa de ser “qual parcela cabe?” e passa a ser “qual instituição aceita carregar este risco por um custo menor?”.'],
    sections: [
      { kicker: 'MECANISMO', title: 'O banco novo precisa enxergar a dívida antiga', paragraphs: ['Saldo devedor, prazo, taxa e dados do contrato permitem construir uma proposta comparável. O Open Finance reduz fricção documental, mas não elimina análise de crédito.'] },
      { kicker: 'ARMADILHA', title: 'Parcela menor pode esconder prazo maior', paragraphs: ['Uma proposta aparentemente melhor pode alongar a dívida. Compare CET, total a pagar e prazo restante antes de aceitar a troca.'], bullets: ['Taxa menor + mesmo prazo costuma ser um sinal mais limpo.', 'Prazo maior precisa justificar o custo total adicional.', 'Seguro e tarifas entram no CET.'] },
      { kicker: 'SEGURANÇA', title: 'Portabilidade legítima começa no app oficial', paragraphs: ['Golpistas podem usar o assunto como isca. Não entregue senha, token ou código recebido por SMS a quem ligar oferecendo “migração instantânea”.'] },
    ],
    callout: { label: 'IDEIA CENTRAL', title: 'Compare contrato, não prestação', text: 'A portabilidade é poderosa quando aumenta concorrência sem transformar alongamento de dívida em falsa economia.' },
    takeaways: ['Open Finance reduz fricção na troca de dados.', 'CET + prazo + total pago são o trio de comparação.', 'Consentimento deve ser iniciado em ambiente oficial.'],
    sources: [{ label: 'Banco Central · Portabilidade de crédito', url: 'https://www.bcb.gov.br/detalhenoticia/20991/noticia' }],
  },
  politica: {
    readingTime: '8 MIN DE LEITURA',
    title: 'Amanhã fecha o protocolo; não fecha a análise jurídica',
    deck: 'O calendário eleitoral tem marcos diferentes e cada um responde a uma pergunta: quem foi escolhido, quem pediu registro e quem teve o registro aceito.',
    opening: ['A reta final antes de 15 de agosto costuma produzir manchetes com verbos diferentes: “lançou”, “registrou”, “confirmou”, “deferiu”. Eles não são sinônimos.', 'Entender o processo é uma defesa simples contra desinformação eleitoral, porque impede transformar um ato partidário em decisão da Justiça Eleitoral.'],
    sections: [
      { kicker: 'ETAPAS', title: 'Convenção, protocolo e julgamento', paragraphs: ['Convenções escolhem nomes. O pedido formal é transmitido à Justiça Eleitoral. Depois, documentação e condições de elegibilidade são analisadas.'] },
      { kicker: 'FONTES', title: 'Use cada fonte para a pergunta certa', paragraphs: ['TSE/TRE e DivulgaCandContas servem para status processual e dados declarados. Programas e entrevistas servem para propostas. Pesquisas medem intenção de voto dentro de metodologia própria.'] },
      { kicker: 'LEITURA CRÍTICA', title: 'Promessa precisa caber na competência do cargo', paragraphs: ['Uma boa triagem é perguntar se presidente, governador, senador ou deputado possui competência constitucional e orçamentária para executar o que está sendo prometido.'] },
    ],
    callout: { label: 'AMANHÃ', title: '15 de agosto, 19h', text: 'É o prazo final para apresentação dos pedidos de registro, não o momento em que todos os processos estarão julgados.' },
    takeaways: ['Registro protocolado não é registro deferido.', 'Status jurídico deve vir da Justiça Eleitoral.', 'Competência do cargo é parte da avaliação de qualquer proposta.'],
    sources: [{ label: 'TSE · Calendário Eleitoral', url: 'https://www.tse.jus.br/eleicoes/calendario-eleitoral/calendario-eleitoral' }],
  },
  mundo: {
    readingTime: '9 MIN DE LEITURA',
    title: 'O barril está negociando duas histórias ao mesmo tempo',
    deck: 'Estoques e demanda apontam para baixo; ameaça de bloqueio e risco físico de oferta apontam para cima. O preço é o resultado temporário dessa disputa.',
    opening: ['Petróleo parece simples até duas notícias opostas chegarem no mesmo dia. Um estoque enorme nos EUA deveria derrubar o preço. Uma ameaça de bloqueio a um produtor relevante deveria elevá-lo.', 'Quando os dois eventos coexistem, o mercado vira uma balança entre “há barris suficientes?” e “eles conseguirão chegar onde são necessários?”.'],
    sections: [
      { kicker: 'FUNDAMENTOS', title: 'Estoque é amortecedor, não seguro contra geopolítica', paragraphs: ['Inventários elevados dão conforto de curto prazo. Mas uma interrupção persistente em produção ou transporte pode consumir esse amortecedor e elevar custos de seguro e frete antes mesmo de faltar produto.'] },
      { kicker: 'TRANSMISSÃO', title: 'Do Estreito ao supermercado há várias pontes', paragraphs: ['Petróleo afeta diesel, logística, petroquímica, aviação e expectativas de inflação. Câmbio e política doméstica de preços podem ampliar ou reduzir o efeito no Brasil.'] },
      { kicker: 'O QUE OBSERVAR', title: 'Persistência vale mais que um pico de um dia', paragraphs: ['Um choque curto pode desaparecer dos preços finais. Uma alta que dura semanas tem mais chance de contaminar custos e expectativas.'] },
    ],
    callout: { label: 'PARA GUARDAR', title: 'Oferta física e demanda não votam separadamente', text: 'O preço incorpora simultaneamente disponibilidade, consumo, estoques, frete, seguro e risco de interrupção.' },
    takeaways: ['Estoque alto reduz, mas não elimina, risco de oferta.', 'Geopolítica pode atuar antes de existir escassez.', 'Persistência do choque é crucial para inflação.'],
    sources: [{ label: 'Reuters · Oil · 14/08/2026', url: 'https://www.reuters.com/business/energy/oil-steadies-after-us-threatens-blockade-iran-indefinitely-2026-08-14/' }],
  },
  planeta: {
    readingTime: '9 MIN DE LEITURA',
    title: 'Por que a maré de amanhã não chega na mesma hora de hoje',
    deck: 'A resposta começa no fato de que a Lua também está se movendo enquanto a Terra gira — e termina na geometria irregular de continentes, baías e fundos oceânicos.',
    opening: ['O relógio civil é solar. O relógio dominante das marés é lunar. Essa diferença de referência produz um deslocamento diário que qualquer navegador costeiro aprende a respeitar.', 'Mas 50 minutos extras não são uma regra de bolso para prever uma praia específica: o oceano real é uma coleção de bacias que ressoam, refletem e deformam a onda de maré.'],
    sections: [
      { kicker: 'ASTRONOMIA', title: 'A Terra precisa alcançar a Lua', paragraphs: ['Depois de 24 horas a Lua avançou na órbita. A rotação terrestre precisa de cerca de 50 minutos adicionais para recuperar a mesma orientação aproximada.'] },
      { kicker: 'OCEANOGRAFIA', title: 'Continentes quebram o modelo simples', paragraphs: ['Se a Terra fosse lisa e coberta de água, o padrão seria muito mais regular. Costas, profundidades e bacias criam marés diurnas, semidiurnas e mistas.'] },
      { kicker: 'NAVEGAÇÃO', title: 'Tabela local ganha de memória', paragraphs: ['Entrada de barra, rampa, banco de areia e fundeio dependem da estação e da previsão local. “Ontem funcionou” é um critério fraco.'] },
    ],
    callout: { label: 'NÚMERO BONITO', title: '24h50', text: 'É a duração aproximada do dia lunar, uma conexão direta entre astronomia e rotina costeira.' },
    takeaways: ['A Lua se move enquanto a Terra gira.', 'O padrão local depende da geografia oceânica.', 'Maré deve ser consultada localmente.'],
    sources: [{ label: 'NOAA · Lunar Day', url: 'https://oceanservice.noaa.gov/education/tutorial_tides/tides05_lunarday.html' }],
  },
  animais: {
    readingTime: '8 MIN DE LEITURA',
    title: 'O beija-flor vive acelerado de dia e quase “desliga” à noite',
    deck: 'Torpor é a solução fisiológica para um paradoxo: uma ave minúscula com metabolismo enorme precisa atravessar muitas horas sem reabastecer.',
    opening: ['Pairar no ar parece leve. Fisiologicamente, é caríssimo. O beija-flor sustenta uma atividade muscular intensa em um corpo que perde calor muito rápido.', 'À noite, continuar gastando como durante o dia seria uma estratégia ruim. O torpor reduz drasticamente a despesa energética até a próxima janela de alimentação.'],
    sections: [
      { kicker: 'ENERGIA', title: 'Tamanho pequeno é uma vantagem e um problema', paragraphs: ['Pequenos animais dissipam calor rapidamente. Para manter temperatura, precisam gastar energia; para voar estacionados, gastam ainda mais.'] },
      { kicker: 'TORPOR', title: 'A economia vem da desaceleração', paragraphs: ['Temperatura corporal e metabolismo caem muito mais do que no sono comum. O animal aceita funcionar em regime mínimo para preservar reservas.'] },
      { kicker: 'EVOLUÇÃO', title: 'Toda capacidade extrema cobra um trade-off', paragraphs: ['A natureza raramente oferece desempenho gratuito. O voo extraordinário é sustentado por alimentação frequente e uma estratégia noturna de economia agressiva.'] },
    ],
    callout: { label: 'CONEXÃO', title: 'Performance + economia', text: 'O mesmo organismo que gasta energia de forma espetacular também possui uma das estratégias mais radicais de conservação.' },
    takeaways: ['Torpor não é sono comum.', 'Corpos pequenos perdem calor depressa.', 'Adaptações vêm em pacotes de custos e compensações.'],
    sources: [{ label: 'Smithsonian · Hummingbirds', url: 'https://nationalzoo.si.edu/migratory-birds/hummingbirds' }],
  },
  tempo: {
    readingTime: '8 MIN DE LEITURA',
    title: 'Por que 50% de umidade não significa a mesma coisa em todo dia',
    deck: 'Umidade relativa é uma razão que muda quando a temperatura muda. Ponto de orvalho ajuda a separar “porcentagem” de quantidade real de vapor.',
    opening: ['Às 7h uma cidade pode ter 90% de umidade e ainda parecer fresca. Às 15h pode marcar 40% sem que todo o vapor tenha desaparecido.', 'Parte da mudança vem do próprio aquecimento do ar: a capacidade de conter vapor cresce e a porcentagem relativa cai.'],
    sections: [
      { kicker: 'MÉTRICA', title: 'Relativa significa relativa à temperatura', paragraphs: ['A porcentagem compara o vapor atual com o máximo possível naquela temperatura. Não é um tanque de água medido diretamente.'] },
      { kicker: 'PONTO DE ORVALHO', title: 'A temperatura em que o ar saturaria', paragraphs: ['Ele se relaciona melhor com conteúdo de vapor e conforto. Quando temperatura e ponto de orvalho se aproximam, condensação, nevoeiro ou orvalho tornam-se mais prováveis.'] },
      { kicker: 'ROTINA', title: 'No inverno, acompanhe a mínima de umidade da tarde', paragraphs: ['A manhã pode começar úmida e a tarde secar rapidamente. Hidratação, atividade física e qualidade do ar devem considerar o período mais seco.'] },
    ],
    callout: { label: 'ATALHO MENTAL', title: 'Temperatura + ponto de orvalho', text: 'Essa dupla costuma dizer mais sobre conforto do que a umidade relativa isolada.' },
    takeaways: ['Umidade relativa muda com temperatura.', 'Ponto de orvalho representa melhor o vapor presente.', 'O período mais seco pode ocorrer horas depois da manhã úmida.'],
    sources: [{ label: 'INMET · Inverno 2026', url: 'https://portal.inmet.gov.br/noticias/inverno-2026-confira-a-previs%C3%A3o-para-a-esta%C3%A7%C3%A3o' }],
  },
  curiosidades: {
    readingTime: '7 MIN DE LEITURA',
    title: 'A voz que você conhece não é exatamente a voz que sai no ar',
    deck: 'O estranhamento de uma gravação é um experimento involuntário sobre condução óssea, memória perceptiva e acústica.',
    opening: ['Você ouviu sua própria voz milhares de vezes antes de ouvir uma boa gravação dela. O problema é que essas experiências não usam o mesmo caminho físico.', 'Ao falar, vibrações alcançam o ouvido por dentro do crânio e pelo ar. O microfone recebe outra mistura — e o cérebro reclama da diferença.'],
    sections: [
      { kicker: 'FÍSICA', title: 'Dois caminhos chegam ao ouvido', paragraphs: ['Condução aérea leva som pelo canal auditivo. Condução óssea transmite vibração através de estruturas do crânio e altera a percepção do timbre.'] },
      { kicker: 'PSICOLOGIA', title: 'Familiaridade cria uma referência interna', paragraphs: ['O cérebro espera a versão que ouviu a vida inteira. Uma gravação quebra essa previsão, mesmo quando tecnicamente está boa.'] },
      { kicker: 'TECNOLOGIA', title: 'Microfone também não é neutro', paragraphs: ['Resposta de frequência, distância, sala e compressão mudam a gravação. Portanto, não existe uma única “voz verdadeira” independente do sistema de captação.'] },
    ],
    callout: { label: 'CURIOSIDADE', title: 'Você se escuta por dentro', text: 'É uma das poucas situações cotidianas em que a própria anatomia participa diretamente da mixagem do áudio.' },
    takeaways: ['Condução óssea muda o timbre percebido.', 'A gravação remove parte dessa via.', 'Microfone e ambiente também alteram a voz.'],
    sources: [{ label: 'NIDCD · How Do We Hear?', url: 'https://www.nidcd.nih.gov/health/how-do-we-hear' }],
  },
  gravidez: {
    readingTime: '9 MIN DE LEITURA',
    title: 'No começo da gestação, quatro dias podem mudar uma imagem inteira',
    deck: 'Ultrassom precoce é poderoso, mas deve ser lido como parte de uma sequência clínica — não como uma fotografia isolada comparada com a internet.',
    opening: ['Hoje a idade gestacional estimada é 5 semanas e 5 dias. Nesta escala, dias representam uma fração grande de toda a vida embrionária até aqui.', 'Por isso, datas imprecisas, ovulação mais tardia e diferenças técnicas podem alterar o que é visualizado. O obstetra interpreta exame, sintomas e cronologia juntos.'],
    sections: [
      { kicker: 'DESENVOLVIMENTO', title: 'A sexta semana está chegando', paragraphs: ['Guias do NHS descrevem nesta transição crescimento rápido de cérebro, sistema musculoesquelético e início dos brotos de membros.'] },
      { kicker: 'ULTRASSOM', title: 'Muito cedo não significa “ruim”', paragraphs: ['O Ministério da Saúde reconhece a utilidade do ultrassom precoce para datação e avaliação quando indicado. Ausência de determinada estrutura em um exame extremamente inicial precisa ser contextualizada e, quando necessário, reavaliada pelo profissional.'] },
      { kicker: 'CONSULTA', title: 'Chegue com dados organizados', paragraphs: ['DUM, medicamentos, histórico clínico, sintomas e exames anteriores melhoram a qualidade da consulta e reduzem dependência da memória no momento.'] },
    ],
    callout: { label: 'CUIDADO', title: 'Não faça diagnóstico por comparação de imagens', text: 'Exames de outras pessoas, feitos em dias e condições diferentes, não são uma régua confiável para uma gestação individual.' },
    takeaways: ['Hoje: 5s5d pela DPP informada.', 'Poucos dias fazem diferença no início.', 'Ultrassom precisa de contexto clínico.'],
    sources: [{ label: 'Ministério da Saúde · Pré-natal', url: 'https://linhasdecuidado.saude.gov.br/portal/pre-natal-baixo-risco/unidade-de-atencao-primaria/planejamento-terapeutico/' }, { label: 'NHS · Week 6', url: 'https://www.nhs.uk/best-start-in-life/pregnancy/week-by-week-guide-to-pregnancy/1st-trimester/week-6/' }],
    disclaimer: 'Conteúdo educativo; não substitui avaliação obstétrica.'
  },
  pai: {
    readingTime: '7 MIN DE LEITURA',
    title: 'Um bom plano de emergência é curto o suficiente para ser usado sob estresse',
    deck: 'A paternidade prática também é engenharia de contingência: organizar informações simples agora evita decisões desnecessárias no pior momento.',
    opening: ['Em uma situação de urgência, memória de trabalho piora e detalhes banais viram obstáculos: endereço, documento, telefone, hospital, carteira do plano.', 'A solução não é um manual de 20 páginas. É uma nota curta, compartilhada e revisada.'],
    sections: [
      { kicker: 'DESIGN', title: 'Uma tela, informações críticas', paragraphs: ['Coloque hospital, rota, contatos, documentos, alergias/medicações relevantes e instruções dadas pelo pré-natal.'] },
      { kicker: 'OWNERSHIP', title: 'Você precisa saber usar o plano sem pedir instruções', paragraphs: ['Assumir responsabilidade significa conhecer as informações, manter a nota atualizada e saber onde estão documentos e itens necessários.'] },
      { kicker: 'LIMITE', title: 'Plano de emergência não é protocolo médico caseiro', paragraphs: ['Ele organiza acesso a cuidado. Não serve para adiar atendimento tentando classificar sintomas sozinho.'] },
    ],
    callout: { label: 'MISSÃO', title: '15 minutos hoje', text: 'Criar a nota compartilhada é uma ação pequena que reduz carga mental dos dois.' },
    takeaways: ['Informação crítica deve estar duplicada.', 'Plano curto funciona melhor sob pressão.', 'A função é chegar ao cuidado, não diagnosticar.'],
    sources: [{ label: 'Ministério da Saúde · Caderneta da Gestante', url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-mulher/publicacoes/caderneta-brasileira-da-gestante.pdf/view' }],
  },
  carros: {
    readingTime: '10 MIN DE LEITURA',
    title: 'O Ford Ka de R$ 48 mil deve ser comprado como exemplar, não como tabela',
    deck: 'FIPE cria referência; histórico, estrutura, manutenção represada e pneus decidem se aquele carro específico vale o dinheiro.',
    opening: ['O Ka 1.5 SE manual 2019 cabe confortavelmente no teto de R$ 60 mil na referência atual. Isso não significa que todo anúncio nessa faixa é um bom negócio.', 'Carro usado é um produto único. Dois exemplares de mesma versão podem carregar milhares de reais de diferença escondida em manutenção e reparos.'],
    sections: [
      { kicker: 'PREÇO', title: 'FIPE de R$ 48.618 é ponto de partida', paragraphs: ['A média Webmotors aparece alguns milhares acima. Diferença pode refletir estado, região, loja e oferta — não uma regra de que o carro “vale mais”.'] },
      { kicker: 'INSPEÇÃO', title: 'Arrefecimento e estrutura merecem atenção', paragraphs: ['Procure vazamentos, sinais de reparo estrutural, histórico de colisão, desgaste desigual de pneus, ruídos de suspensão e condição da embreagem.'] },
      { kicker: 'CUSTO REAL', title: 'Reserve caixa para o primeiro ano', paragraphs: ['Mesmo um bom usado pode pedir fluidos, filtros, pneus ou suspensão. Comprar no limite do orçamento reduz margem para colocar manutenção em dia.'] },
    ],
    callout: { label: 'DECISÃO', title: 'Prefira um Ka mais caro e documentado a um “barato” misterioso', text: 'Desconto sem causa conhecida é risco, não vantagem.' },
    takeaways: ['FIPE não substitui inspeção.', 'Histórico pesa mais que km isolado.', 'Tenha reserva pós-compra.'],
    sources: [{ label: 'Webmotors · Ka 2019', url: 'https://www.webmotors.com.br/tabela-fipe/carros/ford/ka/2019/15-ti-vct-flex-se-manual' }],
  },
  motos: {
    readingTime: '9 MIN DE LEITURA',
    title: 'Trail usada guarda sua história na ciclística',
    deck: 'Quilometragem informa distância; bengalas, rodas, rolamentos, balança e quadro contam quanto esforço essa distância exigiu.',
    opening: ['A Lander é feita para tolerar piso ruim. Justamente por isso, é comum encontrar exemplares que trabalharam mais do que o painel sugere.', 'Uma inspeção inteligente lê marcas de uso: vazamento de bengala, roda desalinhada, pedaleira marcada, protetor amassado, folga em caixa de direção.'],
    sections: [
      { kicker: 'PREÇO', title: 'R$ 19.209 de FIPE em julho', paragraphs: ['A média Webmotors está acima de R$ 20 mil, e anúncios individuais variam bastante. Use preço para filtrar; use condição para decidir.'] },
      { kicker: 'CICLÍSTICA', title: 'Teste devagar também', paragraphs: ['Em baixa velocidade surgem desalinhamento, rolamento de direção marcado e comportamento estranho de guidão que podem passar despercebidos em aceleração.'] },
      { kicker: 'TERRA', title: 'Acessório pode denunciar uso', paragraphs: ['Protetor de motor, guidão, manetes e bagageiros são úteis, mas marcas e montagens improvisadas também contam a história da moto.'] },
    ],
    callout: { label: 'REGRA', title: 'Km é contexto, não veredito', text: '30 mil km em asfalto e 30 mil km com trilha, carga e quedas não produzem o mesmo desgaste.' },
    takeaways: ['Inspecione suspensão e quadro.', 'Teste em baixa e alta velocidade.', 'Preço baixo precisa de explicação.'],
    sources: [{ label: 'Webmotors · Lander 2019', url: 'https://www.webmotors.com.br/tabela-fipe/motos/yamaha/xtz-250-lander/2019' }],
  },
  mecanica: {
    readingTime: '9 MIN DE LEITURA',
    title: 'Uma bateria pode “passar” no multímetro e reprovar na partida',
    deck: 'Diagnóstico elétrico ganha precisão quando você mede o sistema sob esforço, não apenas em repouso.',
    opening: ['O multímetro mostra 12,6 V e a tentação é declarar a bateria saudável. Então você gira a chave e tudo apaga.', 'A contradição desaparece quando entendemos que tensão em aberto e capacidade de entregar corrente são propriedades relacionadas, mas não idênticas.'],
    sections: [
      { kicker: 'CARGA', title: 'Motor de partida exige muito em poucos segundos', paragraphs: ['Bateria envelhecida pode manter tensão sem carga e sofrer queda abrupta quando centenas de amperes são solicitados.'] },
      { kicker: 'CABOS', title: 'Resistência pequena vira queda grande com corrente alta', paragraphs: ['Terminal oxidado ou cabo danificado pode roubar tensão justamente na partida. Medir queda de tensão entre bateria e motor de partida ajuda a localizar o gargalo.'] },
      { kicker: 'SISTEMA', title: 'Depois da partida, investigue a recarga', paragraphs: ['Alternador fraco ou consumo parasita pode destruir uma bateria nova. Diagnóstico completo inclui carga e descarga do sistema.'] },
    ],
    callout: { label: 'FRASE', title: 'Meça o defeito na condição em que ele acontece', text: 'Falha de partida deve ser medida durante a partida.' },
    takeaways: ['12,6 V não encerra o diagnóstico.', 'Queda de tensão localiza resistência.', 'Bateria, cabos e alternador formam um sistema.'],
  },
  nautica: {
    readingTime: '9 MIN DE LEITURA',
    title: 'A âncora segura o barco; o planejamento segura a âncora no lugar certo',
    deck: 'Fundeio é uma decisão geométrica e meteorológica antes de ser uma manobra de convés.',
    opening: ['Uma enseada bonita pode ser um fundeadouro ruim. Profundidade demais, fundo inadequado, cabo submarino, giro limitado ou vento mudando de direção transformam conforto em risco.', 'A preparação correta começa lendo o espaço e as forças que atuarão no barco durante horas.'],
    sections: [
      { kicker: 'ÁREA', title: 'Pense em um círculo, não em um ponto', paragraphs: ['Depois de fundeado, o barco pode girar conforme vento e corrente. Outras embarcações também giram, nem sempre com o mesmo raio.'] },
      { kicker: 'FUNDO', title: 'A âncora precisa trabalhar no substrato disponível', paragraphs: ['Tipo de âncora, natureza do fundo e quantidade de cabo influenciam capacidade de unhar e permanecer segura.'] },
      { kicker: 'VIGILÂNCIA', title: 'Fundear não encerra a navegação', paragraphs: ['Confirme posição, monitore arrasto e acompanhe mudanças de vento, corrente e maré.'] },
    ],
    callout: { label: 'ANTES DE LARGAR', title: 'Saiba como vai sair', text: 'Uma rota de escape pensada antes da piora do tempo vale mais do que improviso à noite.' },
    takeaways: ['Espaço de giro importa.', 'Fundo e cabo determinam desempenho.', 'Monitore a posição depois de fundear.'],
    sources: [{ label: 'Marinha · NORMAM 511', url: 'https://www.marinha.mil.br/sites/default/files/atos-normativos/dhn/Port-N%C2%BA%2030-DHN-DGN-MB-21MAI2026-NORMAM-511-REV1.html' }],
  },
  viagens: {
    readingTime: '9 MIN DE LEITURA',
    title: 'Itu fica mais interessante quando você esquece por uma hora que “tudo é grande”',
    deck: 'O centro histórico conecta Convenção Republicana, igrejas coloniais, industrialização e arquitetura paulista em distâncias caminháveis.',
    opening: ['A fama turística de Itu criou um atalho mental: objetos gigantes. A cidade histórica oferece uma experiência bem mais rica.', 'Caminhar entre Museu Republicano, Matriz, Fábrica São Luiz e Museu da Energia transforma conceitos abstratos da história brasileira em edifícios, ruas e objetos.'],
    sections: [
      { kicker: 'MANHÃ', title: 'Comece pelo Museu Republicano', paragraphs: ['O sobrado preserva memória da Convenção de 1873 e objetos ligados à formação do movimento republicano paulista.'] },
      { kicker: 'A PÉ', title: 'Use o Eixo Histórico como espinha dorsal', paragraphs: ['A prefeitura sugere rota com duração aproximada de 4h30. Ela conecta igrejas, antigas fábricas, museus e praças sem depender de deslocamentos longos de carro.'] },
      { kicker: 'EXTRA', title: 'Só depois vá para os exageros', paragraphs: ['Orelhão e Praça dos Exageros funcionam bem como complemento leve, sem roubar o tempo da parte histórica.'] },
    ],
    callout: { label: 'ROTEIRO', title: 'História primeiro, foto divertida depois', text: 'Essa ordem muda completamente a impressão da cidade.' },
    takeaways: ['O centro é caminhável.', 'Museu Republicano dá contexto nacional.', 'Confira horários no dia da visita.'],
    sources: [{ label: 'Turismo Itu · Rotas', url: 'https://turismo.itu.sp.gov.br/rotas/' }],
  },
  financas: {
    readingTime: '9 MIN DE LEITURA',
    title: 'O mercado está comemorando inflação mais calma enquanto olha de canto para o petróleo',
    deck: 'Juros futuros são uma máquina de probabilidades: cada novo dado altera o cenário antes de qualquer decisão oficial.',
    opening: ['Bolsas asiáticas fecharam a semana com forte desempenho porque a probabilidade de nova alta do Fed diminuiu. Ao mesmo tempo, petróleo voltou a subir.', 'Esses dois movimentos contam histórias opostas para inflação futura — e é por isso que expectativas de juros nunca são estáticas.'],
    sections: [
      { kicker: 'EXPECTATIVA', title: 'Probabilidade implícita não é previsão garantida', paragraphs: ['Preços de derivativos condensam apostas coletivas que mudam com dados. Um novo choque de energia ou emprego pode reverter a leitura rapidamente.'] },
      { kicker: 'JUROS', title: 'Inflação corrente e risco futuro entram juntos', paragraphs: ['Banco central observa o que aconteceu, mas precisa decidir para o que pode acontecer meses à frente. Energia persistente pode contaminar expectativas mesmo após bons índices mensais.'] },
      { kicker: 'PESSOAL', title: 'Não transforme macro em trade diário', paragraphs: ['Para finanças domésticas, cenário ajuda a entender crédito e retornos; a estrutura da carteira deve continuar baseada em objetivos e liquidez.'] },
    ],
    callout: { label: 'HOJE', title: '~35% de chance implícita de alta do Fed em setembro', text: 'É fotografia de mercado citada pela Reuters, não uma decisão anunciada.' },
    takeaways: ['Mercado antecipa decisões.', 'Petróleo pode reabrir pressão inflacionária.', 'Probabilidade muda; plano financeiro não deve mudar a cada manchete.'],
    sources: [{ label: 'Reuters · Global Markets · 14/08/2026', url: 'https://www.reuters.com/world/china/global-markets-wrapup-1-2026-08-14/' }],
    disclaimer: 'Conteúdo educacional; não é recomendação de investimento.'
  },
  tecnologia: {
    readingTime: '10 MIN DE LEITURA',
    title: 'O qubit que interessa é o que sobrevive ao cálculo',
    deck: 'A corrida quântica começa a ficar compreensível quando trocamos a pergunta “quantos qubits?” por “quantas operações confiáveis consigo executar?”.',
    opening: ['Contar qubits é sedutor porque produz um número simples. Só que um computador quântico cheio de qubits ruidosos pode ser menos útil do que uma máquina menor e melhor controlada.', 'O desafio central é preservar informação quântica por tempo suficiente para que um algoritmo faça trabalho útil.'],
    sections: [
      { kicker: 'RUÍDO', title: 'O ambiente tenta medir o qubit o tempo inteiro', paragraphs: ['Interações não controladas destroem coerência e introduzem erros. Portas quânticas também têm fidelidade finita.'] },
      { kicker: 'LÓGICO', title: 'Correção de erros cria um qubit mais confiável a partir de muitos físicos', paragraphs: ['O overhead pode ser grande, mas é o caminho para cálculos tolerantes a falhas.'] },
      { kicker: 'LEITURA DE NOTÍCIA', title: 'Peça benchmark e taxa de erro', paragraphs: ['Número de qubits sem qualidade, conectividade e tarefa executada é marketing incompleto.'] },
    ],
    callout: { label: 'MÉTRICA', title: 'Qubits lógicos > contagem bruta', text: 'O objetivo é computação confiável, não apenas um chip numericamente maior.' },
    takeaways: ['Qubit físico é ruidoso.', 'Correção de erros exige redundância.', 'Benchmark vale mais que contagem isolada.'],
    sources: [{ label: 'IBM Quantum · Error correction', url: 'https://www.ibm.com/quantum/blog/quantum-error-correction' }],
  },
  seguranca: {
    readingTime: '11 MIN DE LEITURA',
    title: 'STOCKSTAY foi desenhado para uma espionagem que conhece o ambiente antes de agir',
    deck: 'Environmental keying, C2 por WebSocket e múltiplos componentes mostram uma arquitetura que tenta reduzir exposição fora do alvo certo.',
    opening: ['A Turla é um ator antigo, e isso aparece na forma como novas ferramentas são integradas a um ecossistema já maduro.', 'STOCKSTAY não é só “mais um backdoor”. Ele traz decisões de engenharia que diferenciam estágio inicial de operações já orientadas por reconhecimento.'],
    sections: [
      { kicker: 'ENTRADA', title: 'Arquivos RDP podem ser o convite', paragraphs: ['GTIG observou iscas que levam a vítima a iniciar conexão RDP com infraestrutura do ator. Isso muda a superfície de defesa: o arquivo não precisa conter o payload final para ser perigoso.'] },
      { kicker: 'KEYING', title: 'Configuração pode depender do hostname ou domínio da vítima', paragraphs: ['Essa técnica dificulta decriptar configurações fora do alvo e esconde detalhes do C2 durante análise genérica.'] },
      { kicker: 'HUNTING', title: 'Procure comportamento, não apenas hash', paragraphs: ['RDP outbound inesperado, persistência .NET, WebSocket de processos incomuns e staging em diretórios atípicos sobrevivem melhor à troca de amostras do que IOC estático.'] },
    ],
    callout: { label: 'LIÇÃO', title: 'Um arquivo de configuração também pode ser um controle operacional do atacante', text: 'Environmental keying revela que o malware conhece algo sobre a vítima antes de liberar seus segredos.' },
    takeaways: ['RDP file pode ser vetor de phishing.', 'WebSocket C2 merece contexto de processo.', 'Detecção comportamental complementa IOCs.'],
    sources: [{ label: 'GTIG · STOCKSTAY', url: 'https://cloud.google.com/blog/topics/threat-intelligence/stockstay-turla-intelligence-gathering/' }],
  },
  'appsec-ssdlc': {
    readingTime: '11 MIN DE LEITURA',
    title: 'Seu SBOM pode estar correto e o binário ainda assim ter vindo do lugar errado',
    deck: 'Software supply chain madura precisa provar conteúdo e origem: SBOM, provenance, assinatura e identidade do builder são peças complementares.',
    opening: ['Imagine que um atacante compromete uma etapa de build e injeta código depois da análise de dependências. O SBOM pode continuar perfeitamente válido para os pacotes declarados.', 'O problema agora não é inventário. É proveniência: esse artefato foi produzido pelo workflow autorizado a partir do commit esperado?'],
    sections: [
      { kicker: 'ATTESTATION', title: 'Vincule artefato a builder e origem', paragraphs: ['Uma attestation registra digest do artefato e metadados sobre quem construiu, a partir de qual fonte e em qual processo.'] },
      { kicker: 'IDENTIDADE', title: 'Prefira workload identity a chave estática', paragraphs: ['Chaves permanentes no CI são difíceis de rotacionar e fáceis de reutilizar após vazamento. Identidade efêmera reduz o valor de um segredo roubado.'] },
      { kicker: 'GATE', title: 'Verifique antes de promover', paragraphs: ['O deploy deve recusar imagem sem provenance válido, assinatura esperada ou digest vinculado à evidência. Isso leva supply chain para o enforcement, não apenas para auditoria.'] },
    ],
    callout: { label: 'MODELO', title: 'SBOM = o quê; provenance = como/onde; assinatura = quem afirma', text: 'As três respostas juntas são muito mais fortes do que qualquer uma isolada.' },
    takeaways: ['Inventário não prova origem.', 'Assinatura precisa de identidade protegida.', 'Validação deve ocorrer no ponto de promoção/deploy.'],
    sources: [{ label: 'SLSA · Provenance v1', url: 'https://slsa.dev/provenance/v1' }],
  },
};
