export type BriefingPriority = 'P0' | 'P1' | 'P2' | 'WATCH';
export type BriefingStatus = 'ACT NOW' | 'ASSESS' | 'TRACK' | 'STRATEGY';
export type BriefingSignalType = 'INCIDENT' | 'VULNERABILITY' | 'THREAT TREND' | 'GUIDANCE' | 'STRATEGY';
export type BriefingConfidence = 'HIGH' | 'MEDIUM';

export type SecurityBriefingStory = {
  id: string;
  pillar: string;
  priority: BriefingPriority;
  status: BriefingStatus;
  signalType: BriefingSignalType;
  confidence: BriefingConfidence;
  publishedAt: string;
  freshness: string;
  title: string;
  deck: string;
  whyNow: string;
  decision: string;
  technicalImpact: string;
  businessImpact: string;
  evidence: { label: string; value: string }[];
  exposureQuestions: string[];
  actionNow: string[];
  audience: string[];
  frameworks: string[];
  source: { label: string; url: string };
  executiveShare: string;
  technicalShare: string;
};

export const securityBriefingUpdatedAt = '18 AGO 2026 · 15H';

export const securityBriefingStories: SecurityBriefingStory[] = [
  {
    id: 'storm-2949-cloud-identity',
    pillar: 'IAM / CLOUD',
    priority: 'P0',
    status: 'ACT NOW',
    signalType: 'INCIDENT',
    confidence: 'HIGH',
    publishedAt: '18 MAI 2026',
    freshness: 'OBSERVED ATTACK CHAIN',
    title: 'Uma identidade comprometida virou acesso a Microsoft 365, Key Vault e produção',
    deck: 'A Microsoft descreveu uma intrusão do Storm-2949 que começou em identidade e avançou por SaaS, PaaS e IaaS usando recursos legítimos de administração em vez de malware tradicional.',
    whyNow: 'O caso demonstra que identidade privilegiada e control plane de cloud são um caminho único de ataque. Separar IAM, Cloud Security e AppSec em filas independentes pode esconder o blast radius real.',
    decision: 'Tratar identidade privilegiada de cloud como superfície crítica de produção e revisar SSPR, MFA, RBAC, Key Vault e correlação de sinais entre identidade e recursos cloud.',
    technicalImpact: 'O ator abusou de credenciais e SSPR, fez discovery e exfiltração no Microsoft 365, manipulou acesso a Key Vault e usou segredos obtidos para ampliar o comprometimento de aplicações e recursos Azure.',
    businessImpact: 'Uma conta comprometida pode abrir caminho para dados corporativos, segredos de aplicações e ambientes produtivos sem um exploit clássico. Isso amplia risco de indisponibilidade, exposição de dados e fraude operacional.',
    evidence: [
      { label: 'ATTACK SURFACE', value: 'SaaS · PaaS · IaaS' },
      { label: 'KEY VAULT', value: 'DEZENAS DE SEGREDOS' },
      { label: 'INITIAL LENS', value: 'IDENTITY / SSPR' },
    ],
    exposureQuestions: ['Quem possui Owner/Contributor sobre Key Vaults e produção?', 'SSPR e recuperação de conta têm controles equivalentes ao login normal?', 'SOC correlaciona alteração de RBAC, acesso a segredos e sign-in anômalo?'],
    actionNow: ['Revisar contas com privilégio persistente em cloud e cofres de segredo.', 'Endurecer recuperação/SSPR e exigir MFA resistente a phishing nos acessos críticos.', 'Criar detecção para leitura massiva de segredos e mudança incomum de RBAC.', 'Testar resposta a incidente partindo de identidade, não apenas endpoint.'],
    audience: ['IAM', 'Cloud Security', 'SOC', 'AppSec', 'Platform', 'Risk'],
    frameworks: ['Zero Trust', 'NIST CSF', 'CIS Controls', 'MITRE ATT&CK'],
    source: { label: 'Microsoft Security · Storm-2949 cloud-wide breach', url: 'https://www.microsoft.com/en-us/security/blog/2026/05/18/storm-2949-turned-compromised-identity-into-cloud-wide-breach/' },
    executiveShare: 'Identity + Cloud: a Microsoft mostrou uma intrusão em que uma identidade comprometida evoluiu para Microsoft 365, Azure, Key Vault e dados de produção. A pergunta para o negócio é simples: uma conta privilegiada hoje consegue alcançar quantos ativos críticos sem uma nova aprovação?',
    technicalShare: 'Storm-2949: revisar SSPR/MFA, RBAC persistente, Key Vault, logs de secret access e correlação Entra→Azure→M365. Priorizar contas que combinam identidade humana com acesso a control plane e segredos de produção.',
  },
  {
    id: 'cisco-sdwan-cve-2026-20245',
    pillar: 'VULNERABILITY MGMT',
    priority: 'P0',
    status: 'ACT NOW',
    signalType: 'VULNERABILITY',
    confidence: 'HIGH',
    publishedAt: '24 JUN 2026',
    freshness: 'ZERO-DAY OBSERVED',
    title: 'CVE-2026-20245: comprometimento administrativo virou root em Cisco Catalyst SD-WAN Manager',
    deck: 'A Mandiant observou exploração zero-day da falha em um provedor de serviços. O atacante já possuía uma conta administrativa comprometida e usou a vulnerabilidade para escalar até root.',
    whyNow: 'O caso mostra por que CVSS sozinho não descreve risco: um ativo de rede central, uma conta administrativa comprometida e uma escalada local podem formar uma cadeia de impacto muito maior que cada peça isolada.',
    decision: 'Validar exposição e versões de Catalyst SD-WAN Manager, aplicar correções do fabricante e tratar comprometimento de conta administrativa como cenário de escalada para controle total do appliance.',
    technicalImpact: 'A vulnerabilidade está relacionada ao upload de arquivos sem filtragem adequada. A Mandiant observou o ator usando técnicas antiforenses e modificando/restaurando arquivos de configuração para reduzir rastros.',
    businessImpact: 'Comprometimento de SD-WAN pode afetar conectividade, segmentação e confiança em uma camada central de rede, com potencial de interrupção operacional e acesso ampliado a ambientes conectados.',
    evidence: [
      { label: 'CVE', value: 'CVE-2026-20245' },
      { label: 'OBSERVED', value: 'ZERO-DAY' },
      { label: 'IMPACT', value: 'ADMIN → ROOT' },
    ],
    exposureQuestions: ['Existe Catalyst SD-WAN Manager no inventário?', 'A interface administrativa é acessível de redes amplas ou internet?', 'Há contas administrativas compartilhadas ou sem MFA forte?'],
    actionNow: ['Confirmar versões e advisory do fabricante.', 'Restringir acesso administrativo por rede e identidade.', 'Revisar logs/configurações por alterações suspeitas e gaps de auditoria.', 'Tratar credencial administrativa comprometida como incidente crítico.'],
    audience: ['Network Security', 'Vulnerability Mgmt', 'SOC', 'Infra', 'Risk'],
    frameworks: ['CVE', 'CVSS', 'SSVC', 'MITRE ATT&CK'],
    source: { label: 'Mandiant · CVE-2026-20245 Cisco Catalyst SD-WAN Manager', url: 'https://cloud.google.com/blog/topics/threat-intelligence/zero-day-exploitation-cisco-catalyst-sd-wan-manager' },
    executiveShare: 'Vulnerability Management: a CVE-2026-20245 foi explorada como zero-day em Cisco Catalyst SD-WAN Manager para transformar uma conta administrativa comprometida em root. A prioridade deve considerar função do ativo e cadeia de ataque, não apenas score.',
    technicalShare: 'CVE-2026-20245: identificar Catalyst SD-WAN Manager, confirmar versão/advisory, restringir management plane, revisar admins/MFA e buscar alterações antiforenses em configuração e logs.',
  },
  {
    id: 'mastra-npm-supply-chain',
    pillar: 'APPSEC / SUPPLY CHAIN',
    priority: 'P0',
    status: 'ACT NOW',
    signalType: 'INCIDENT',
    confidence: 'HIGH',
    publishedAt: '17 JUN 2026',
    freshness: 'SUPPLY CHAIN INCIDENT',
    title: 'Mastra npm: um pacote envenenado atingiu mais de 140 projetos e levou payload ao postinstall',
    deck: 'A Microsoft documentou um comprometimento de supply chain atribuído ao Sapphire Sleet em que um pacote npm adulterado distribuiu um payload escondido durante o fluxo de instalação.',
    whyNow: 'Dependências e scripts de lifecycle continuam sendo execução de código dentro do ambiente de desenvolvimento/CI. Quando o package manager executa código automaticamente, o boundary de confiança começa antes do build.',
    decision: 'Revisar política de scripts npm, quarentena de releases recentes, origem de pacotes e segredos disponíveis em runners e estações de desenvolvimento.',
    technicalImpact: 'O ponto crítico não é apenas detectar malware no pacote: é limitar o que uma dependência recém-publicada pode executar e quais credenciais o processo de instalação consegue alcançar.',
    businessImpact: 'Uma dependência comprometida pode distribuir risco simultaneamente para vários produtos, pipelines e clientes, elevando custo de resposta, rotação de credenciais e investigação de artefatos derivados.',
    evidence: [
      { label: 'AFFECTED', value: '140+ PROJETOS' },
      { label: 'ECOSYSTEM', value: 'NPM' },
      { label: 'EXECUTION', value: 'POSTINSTALL' },
    ],
    exposureQuestions: ['Quais pipelines permitem lifecycle scripts sem allowlist?', 'Runners de build recebem secrets antes de dependências serem validadas?', 'Existe cooldown/release age para dependências recém-publicadas?'],
    actionNow: ['Inventariar scripts preinstall/install/postinstall nas dependências críticas.', 'Separar estágio de resolução/validação do estágio que recebe credenciais.', 'Usar lockfile imutável e proxy/registry interno quando aplicável.', 'Criar processo de resposta para pacote comprometido: localizar builds, rotacionar segredos e reconstruir artefatos.'],
    audience: ['AppSec', 'DevSecOps', 'Platform', 'Developers', 'SOC', 'Supply Chain'],
    frameworks: ['SLSA', 'NIST SSDF', 'OWASP SAMM', 'SBOM'],
    source: { label: 'Microsoft Security · Mastra npm supply chain compromise', url: 'https://www.microsoft.com/en-us/security/blog/tag/npm/' },
    executiveShare: 'Software Supply Chain: um pacote npm comprometido ligado ao ecossistema Mastra atingiu mais de 140 projetos. O risco de dependência não termina no CVE: scripts de instalação podem executar código com o contexto do desenvolvedor ou do CI.',
    technicalShare: 'Mastra/npm: revisar lifecycle scripts, runners com secrets, lockfile, registry/proxy, release-age/cooldown e capacidade de localizar todos os artefatos construídos com uma versão comprometida.',
  },
  {
    id: 'exposed-serverless-functions',
    pillar: 'CLOUD / APPSEC',
    priority: 'P1',
    status: 'ASSESS',
    signalType: 'GUIDANCE',
    confidence: 'HIGH',
    publishedAt: '15 JUL 2026',
    freshness: 'MANDIANT FIELD GUIDANCE',
    title: 'Função serverless pública pode virar foothold para comprometer a cloud inteira',
    deck: 'A Mandiant relata que avaliações de segurança encontram com frequência aplicações serverless expostas sem autenticação. Vulnerabilidades de aplicação podem levar a token de service account, secrets e pivot para outros recursos cloud.',
    whyNow: 'Serverless está crescendo junto com automações, APIs e agentes de IA. O problema não é “serverless” em si; é combinar endpoint público, código customizado, dependências e uma identidade de workload poderosa.',
    decision: 'Inventariar funções públicas e revisar autenticação, service account, acesso ao metadata service, egress, WAF e limites de privilégio.',
    technicalImpact: 'LFI/RFI, command injection ou RCE podem expor código, env vars e tokens. Se a identidade do workload tiver permissões amplas, o comprometimento do container vira caminho para recursos adjacentes.',
    businessImpact: 'Uma função criada para acelerar uma feature pode se tornar entrada para dados, secrets e serviços internos. O custo do incidente cresce muito quando a identidade do workload possui privilégios maiores que a função exige.',
    evidence: [
      { label: 'SURFACE', value: 'PUBLIC SERVERLESS' },
      { label: 'PIVOT', value: 'SERVICE ACCOUNT' },
      { label: 'RISK', value: 'APP → CLOUD' },
    ],
    exposureQuestions: ['Quais Cloud Run/functions são públicas por requisito ou por acidente?', 'A service account padrão ainda tem privilégios amplos?', 'RCE em uma função alcança metadata, secrets ou VPC interna?'],
    actionNow: ['Inventariar endpoints serverless públicos.', 'Aplicar least privilege por workload identity.', 'Bloquear secrets em código/env quando houver alternativa de secret manager.', 'Adicionar SAST/DAST, WAF e testes de autorização antes da publicação.'],
    audience: ['Cloud Security', 'AppSec', 'Platform', 'Developers', 'Architecture'],
    frameworks: ['NIST SSDF', 'OWASP ASVS', 'CIS Cloud', 'Zero Trust'],
    source: { label: 'Mandiant · The Risk of Exposed Cloud Functions and How to Harden', url: 'https://cloud.google.com/blog/topics/threat-intelligence/exposed-cloud-functions-harden' },
    executiveShare: 'Cloud + AppSec: uma função serverless pública vulnerável pode expor a identidade do workload e virar ponte para outros recursos cloud. O controle decisivo é limitar o que essa função consegue fazer depois de comprometida.',
    technicalShare: 'Serverless: inventário de endpoints públicos, auth, service account least privilege, metadata/secrets, VPC e egress. Tratar RCE de aplicação como possível caminho de cloud takeover.',
  },
  {
    id: 'ai-assisted-vulnerability-management',
    pillar: 'AI / VULNERABILITY MGMT',
    priority: 'P1',
    status: 'ASSESS',
    signalType: 'GUIDANCE',
    confidence: 'HIGH',
    publishedAt: '16 JUL 2026',
    freshness: 'MANDIANT BLUEPRINT',
    title: 'IA em Vulnerability Management: velocidade ajuda, mas agentes privilegiados criam outro risco',
    deck: 'A Mandiant publicou um blueprint para integrar LLMs à descoberta, priorização e remediação de vulnerabilidades sem entregar privilégios excessivos a agentes dentro do código ou CI/CD.',
    whyNow: 'A mesma IA que ajuda a encontrar e contextualizar falhas pode receber acesso a repos, scanners, tickets e pipelines. O ganho de velocidade precisa vir acompanhado de boundaries claros para leitura, escrita e execução.',
    decision: 'Usar IA primeiro para enriquecimento, priorização e recomendação; exigir aprovação e políticas determinísticas antes de permitir alterações ou execução privilegiada.',
    technicalImpact: 'LLMs podem sintetizar threat intel, EPSS, exploração e contexto do ativo, mas agentes com tool access precisam de identidade própria, escopo mínimo, trilha de auditoria e guardrails de mudança.',
    businessImpact: 'Automação pode reduzir tempo de análise e backlog, mas erro em escala também cresce. Uma remediação automática mal governada pode introduzir regressão, indisponibilidade ou mudança não autorizada.',
    evidence: [
      { label: 'TTE CITADO', value: '-7 DIAS' },
      { label: 'MODEL', value: 'AI-ASSISTED RBVM' },
      { label: 'CONTROL', value: 'HUMAN + POLICY' },
    ],
    exposureQuestions: ['Algum agente já consegue alterar código, PR ou pipeline?', 'O contexto de risco usado pela IA é rastreável e reproduzível?', 'Existe limite entre recomendação automática e mudança automática?'],
    actionNow: ['Começar com enrichment e triagem assistida.', 'Versionar prompts/modelos relevantes para evidência.', 'Separar identidade do agente da identidade do desenvolvedor.', 'Exigir policy checks e revisão humana para mudanças de alto impacto.'],
    audience: ['Vulnerability Mgmt', 'AppSec', 'AI/ML', 'DevSecOps', 'Risk'],
    frameworks: ['SSVC', 'EPSS', 'NIST AI RMF', 'NIST SSDF'],
    source: { label: 'Mandiant · Blueprint for AI-Assisted Vulnerability Management', url: 'https://cloud.google.com/blog/topics/threat-intelligence/ai-assisted-vulnerability-management/' },
    executiveShare: 'AI + Vulnerability Management: IA pode acelerar priorização e remediação, mas um agente com acesso privilegiado ao CI/CD vira uma nova identidade de risco. Automatize análise antes de automatizar mudança.',
    technicalShare: 'AI-assisted VM: enrichment com threat intel/EPSS/exposição primeiro; identidade própria, least privilege, audit trail, policy checks e human approval antes de merge/deploy automatizado.',
  },
  {
    id: 'gtig-ai-threat-tracker-2026',
    pillar: 'AI SECURITY',
    priority: 'P1',
    status: 'TRACK',
    signalType: 'THREAT TREND',
    confidence: 'HIGH',
    publishedAt: '11 MAI 2026',
    freshness: 'GTIG THREAT TRACKER',
    title: 'GTIG observou ator usando um zero-day que acredita ter sido desenvolvido com ajuda de IA',
    deck: 'O Google Threat Intelligence Group descreve uma transição de uso experimental para aplicação industrial de IA em operações adversárias, incluindo descoberta/exploração de vulnerabilidades e initial access.',
    whyNow: 'O impacto prático não é “IA vai hackear tudo”, e sim redução do custo e do tempo para pesquisa, adaptação e escala de operações. Isso encurta a janela entre disclosure, exploração e resposta.',
    decision: 'Aumentar velocidade de exposure management e garantir que external attack surface, patching e compensating controls funcionem mesmo quando a janela de exploração diminui.',
    technicalImpact: 'Defensores precisam combinar inventário, exposição, exploração, telemetria e controle compensatório. A automação do adversário torna filas estáticas de CVEs menos úteis.',
    businessImpact: 'A organização pode ter menos tempo para corrigir vulnerabilidades de borda antes de exploração. Isso pressiona processos de mudança, owners e capacidade de aplicar mitigação emergencial.',
    evidence: [
      { label: 'TREND', value: 'AI-AUGMENTED OPS' },
      { label: 'OBSERVED', value: 'AI-LIKELY ZERO-DAY' },
      { label: 'FOCUS', value: 'INITIAL ACCESS' },
    ],
    exposureQuestions: ['Qual é o tempo real entre advisory e mitigação em ativos internet-facing?', 'O inventário identifica owner sem intervenção manual?', 'Existe caminho emergencial para WAF, isolation ou disable quando patch demora?'],
    actionNow: ['Medir MTTR por exposição e criticidade.', 'Automatizar correlação de asset inventory com advisories.', 'Definir compensating controls pré-aprovados para ativos de borda.', 'Reduzir dependência de triagem manual para vulnerabilidades com exploração real.'],
    audience: ['CISO', 'Vulnerability Mgmt', 'SOC', 'AppSec', 'Infra', 'Risk'],
    frameworks: ['CISA KEV', 'SSVC', 'EPSS', 'NIST CSF'],
    source: { label: 'Google Threat Intelligence · AI Threat Tracker 2026', url: 'https://cloud.google.com/blog/topics/threat-intelligence/ai-vulnerability-exploitation-initial-access/' },
    executiveShare: 'Threat Intel: o GTIG relata uso cada vez mais operacional de IA por adversários e observou um zero-day que acredita ter sido desenvolvido com ajuda de IA. A resposta não é comprar “AI security”; é reduzir o tempo entre saber da exposição e conseguir agir.',
    technicalShare: 'AI threat trend: fortalecer attack surface inventory, owner mapping, exposure-aware SLAs, compensating controls e automação de correlação advisory→asset→action.',
  },
  {
    id: 'open-source-supply-chain-2026',
    pillar: 'SUPPLY CHAIN',
    priority: 'P1',
    status: 'ACT NOW',
    signalType: 'THREAT TREND',
    confidence: 'HIGH',
    publishedAt: '30 JUL 2026',
    freshness: 'RECENT GTIG GUIDANCE',
    title: 'Open source supply chain ganhou escala: GTIG recomenda inventário de ações, cooldown e identidade curta',
    deck: 'GTIG/Mandiant avaliam que grandes campanhas contra repositórios, dependências e ferramentas de desenvolvimento cresceram em 2025 e no primeiro semestre de 2026 e devem continuar aumentando.',
    whyNow: 'A superfície não é apenas package.json. Actions, builders, registries, tokens e ferramentas terceiras também participam do caminho que cria o artefato de produção.',
    decision: 'Evoluir de SBOM isolado para inventário de dependências + ações de pipeline + identidades de automação + provenance do artefato.',
    technicalImpact: 'A orientação inclui SBOM, Action Bill of Materials, release-age/cooldown, registry control, tokens curtos/OIDC e análise de cadeias em vez de findings isolados.',
    businessImpact: 'Comprometimento upstream pode afetar diversos produtos simultaneamente e forçar reconstrução, rotação de credenciais e investigação em larga escala. Saber exatamente onde o componente entrou reduz tempo de resposta.',
    evidence: [
      { label: 'TREND', value: 'GROWTH 2025–H1 2026' },
      { label: 'SURFACE', value: 'REPO · PKG · CI/CD' },
      { label: 'CONTROL', value: 'COOLDOWN + OIDC' },
    ],
    exposureQuestions: ['Quais terceiros executam código dentro do pipeline?', 'É possível listar actions/plugins/builders por produto?', 'Tokens de automação são curtos e vinculados ao job?'],
    actionNow: ['Inventariar actions/plugins/builders além de bibliotecas.', 'Adotar cooldown/release-age para pacotes novos.', 'Migrar automações de tokens long-lived para OIDC/identidades curtas.', 'Vincular SBOM e provenance ao artefato final.'],
    audience: ['AppSec', 'DevSecOps', 'Platform', 'Supply Chain', 'Engineering'],
    frameworks: ['SLSA', 'SBOM', 'NIST SSDF', 'MITRE ATT&CK T1195'],
    source: { label: 'GTIG/Mandiant · Mitigation Guidance for Supply Chain Compromise', url: 'https://cloud.google.com/blog/topics/threat-intelligence/mitigation-guidance-for-supply-chain-compromise' },
    executiveShare: 'Supply Chain: GTIG/Mandiant apontam crescimento de compromissos em open source e recomendam ampliar a visão além de bibliotecas: actions, builders, registries e identidades de CI/CD também precisam de inventário e controle.',
    technicalShare: 'Supply chain: SBOM + ABOM/actions inventory + cooldown/release age + internal registry + OIDC short-lived tokens + provenance. Priorizar attack chains, não findings isolados.',
  },
  {
    id: 'agentic-cicd-claude-code',
    pillar: 'APPSEC / AI',
    priority: 'P1',
    status: 'ASSESS',
    signalType: 'VULNERABILITY',
    confidence: 'HIGH',
    publishedAt: '05 JUN 2026',
    freshness: 'RESPONSIBLY FIXED',
    title: 'AI agent dentro do CI/CD muda a trust boundary: issue e comentário viram entrada não confiável',
    deck: 'A Microsoft encontrou um caminho de prompt injection no Claude Code GitHub Action em que conteúdo GitHub controlado por usuários podia influenciar um agente com acesso a ferramentas e segredos. A Anthropic corrigiu o problema na versão 2.1.128.',
    whyNow: 'O caso é maior que uma vulnerabilidade específica: pipelines determinísticos estão recebendo agentes que interpretam linguagem natural. Issue body, PR description e comentário passam a fazer parte da superfície de entrada do CI.',
    decision: 'Separar workflows que processam conteúdo não confiável de contextos que possuem secrets, write access ou tools capazes de modificar repositório e ambiente.',
    technicalImpact: 'Prompt injection e diferença de sandbox entre ferramentas podem quebrar a suposição de que o agente só “analisa texto”. Tool permissions, file access, egress e secrets agora são controles de AppSec do workflow.',
    businessImpact: 'Uma automação criada para acelerar review pode se tornar caminho para vazamento de credenciais ou mudança de código. O risco está na combinação de autonomia e privilégio, não no modelo isoladamente.',
    evidence: [
      { label: 'FIXED', value: 'CLAUDE CODE 2.1.128' },
      { label: 'INPUT', value: 'ISSUE / PR / COMMENT' },
      { label: 'BOUNDARY', value: 'AGENT + CI SECRETS' },
    ],
    exposureQuestions: ['Quais workflows de IA processam conteúdo de usuários externos?', 'Eles recebem secrets, write permission ou network egress?', 'Bash, Read, MCP e outras tools compartilham a mesma sandbox/policy?'],
    actionNow: ['Inventariar agentes em CI/CD e eventos que os disparam.', 'Remover secrets de jobs que processam conteúdo não confiável.', 'Aplicar least privilege por tool e por evento.', 'Fixar versões e acompanhar advisories dos agentes/actions utilizados.'],
    audience: ['AppSec', 'DevSecOps', 'Developers', 'Platform', 'AI Security'],
    frameworks: ['OWASP Agentic Security', 'NIST SSDF', 'SLSA', 'Zero Trust'],
    source: { label: 'Microsoft Security · Claude Code GitHub Action case', url: 'https://www.microsoft.com/en-us/security/blog/2026/06/05/securing-ci-cd-in-agentic-world-claude-code-github-action-case/' },
    executiveShare: 'AI + CI/CD: quando um agente lê issues e PRs e também possui secrets ou permissão de escrita, texto externo vira parte do perímetro de segurança. Produtividade com IA precisa vir com separação de privilégio.',
    technicalShare: 'Agentic CI/CD: mapear untrusted GitHub content → prompt → tool access → secrets/egress/write. Separar jobs, remover secrets, least privilege por tool/evento e fixar versões das actions/agentes.',
  },
  {
    id: 'gentlemen-ransomware',
    pillar: 'THREAT INTEL',
    priority: 'P1',
    status: 'TRACK',
    signalType: 'INCIDENT',
    confidence: 'HIGH',
    publishedAt: '28 MAI 2026',
    freshness: 'ACTIVE RaaS ECOSYSTEM',
    title: 'The Gentlemen combina ransomware, dupla extorsão e propagação lateral em paralelo',
    deck: 'A Microsoft analisou um encryptor em Go operado como RaaS por Storm-2697, com múltiplos métodos de movimento lateral e capacidade de propagação ampla depois do acesso inicial.',
    whyNow: 'O risco relevante não é a linguagem Go; é o desenho operacional: uma vez dentro, o malware tenta aumentar cobertura rapidamente. Contenção de identidade e lateral movement precisam funcionar antes da fase de criptografia.',
    decision: 'Validar controles de lateral movement, privilégios administrativos, proteção contra tampering e capacidade de isolamento rápido de endpoints e identidades.',
    technicalImpact: 'O ransomware combina criptografia por arquivo, evasão, deleção de artefatos e propagação usando múltiplas técnicas por alvo, aumentando a chance de impacto amplo.',
    businessImpact: 'Propagação rápida reduz a janela de resposta e pode transformar um incidente localizado em indisponibilidade de múltiplas áreas, além de exfiltração e pressão de dupla extorsão.',
    evidence: [
      { label: 'MODEL', value: 'RaaS' },
      { label: 'LANG', value: 'GO' },
      { label: 'SPREAD', value: 'MULTI-METHOD' },
    ],
    exposureQuestions: ['Admin local reutilizado permite movimento lateral amplo?', 'PSExec/WMI e execução remota têm monitoramento e restrição?', 'SOC consegue isolar host e identidade em minutos?'],
    actionNow: ['Revisar privilégios locais e credenciais reutilizadas.', 'Validar proteção contra tampering e EDR block mode equivalente.', 'Monitorar execução remota e ferramentas de administração lateral.', 'Testar playbook de isolamento rápido e recuperação.'],
    audience: ['SOC', 'Endpoint', 'IAM', 'Infra', 'IR', 'Risk'],
    frameworks: ['MITRE ATT&CK', 'NIST CSF', 'CISA StopRansomware'],
    source: { label: 'Microsoft Security · The Gentlemen ransomware', url: 'https://www.microsoft.com/en-us/security/blog/2026/05/28/the-gentlemen-ransomware-dissecting-a-self-propagating-go-encryptor/' },
    executiveShare: 'Ransomware: The Gentlemen foi desenhado para combinar extorsão e propagação lateral agressiva. A decisão mais importante é reduzir a capacidade de uma identidade/host comprometido alcançar o restante do ambiente antes da criptografia.',
    technicalShare: 'The Gentlemen: validar admin reuse, PSExec/WMI, tamper protection, EDR containment, segmentation e playbook de isolamento de identidade+endpoint.',
  },
  {
    id: 'secure-by-design-business',
    pillar: 'TECH + BUSINESS',
    priority: 'P2',
    status: 'STRATEGY',
    signalType: 'STRATEGY',
    confidence: 'HIGH',
    publishedAt: 'FOUNDATION',
    freshness: 'STRATEGIC BASELINE',
    title: 'Secure by Design: segurança que depende do cliente configurar tudo continua sendo dívida de produto',
    deck: 'A abordagem Secure by Design da CISA coloca defaults seguros e redução de classes recorrentes de falhas como responsabilidade de produto e fabricante, não como uma lista de tarefas transferida ao cliente.',
    whyNow: 'Times de segurança frequentemente gastam capacidade compensando defaults inseguros, configuração complexa e controles opcionais. Isso é custo operacional e de suporte, não apenas risco técnico.',
    decision: 'Levar defaults, MFA, logging, atualização e classes recorrentes de falha para product review e roadmap com ownership de engenharia e negócio.',
    technicalImpact: 'Controles essenciais devem nascer habilitados ou ser fáceis de adotar, e classes recorrentes de vulnerabilidade precisam gerar mudança sistêmica de design, framework ou plataforma.',
    businessImpact: 'Menos configuração manual reduz erro operacional e suporte, enquanto segurança previsível melhora confiança do cliente e reduz custo de incidente e exceções.',
    evidence: [
      { label: 'LENS', value: 'PRODUCT DEFAULTS' },
      { label: 'OWNER', value: 'VENDOR / PRODUCT' },
      { label: 'OUTCOME', value: 'LESS CUSTOMER BURDEN' },
    ],
    exposureQuestions: ['Quais controles críticos ainda dependem de configuração manual?', 'Quais vulnerabilidades reaparecem em vários produtos?', 'Existe métrica de secure default e redução de classes de falha?'],
    actionNow: ['Mapear controles críticos opt-in.', 'Transformar classes repetidas de finding em mudança de plataforma.', 'Adicionar security outcomes ao product review.', 'Medir redução de configuração insegura e reincidência.'],
    audience: ['Product', 'Engineering', 'Security', 'Architecture', 'Business'],
    frameworks: ['CISA Secure by Design', 'NIST SSDF', 'OWASP SAMM'],
    source: { label: 'CISA · Secure by Design', url: 'https://www.cisa.gov/securebydesign' },
    executiveShare: 'Secure by Design: quando o produto depende de o cliente descobrir e habilitar cada controle crítico, segurança vira custo operacional transferido. Defaults seguros e redução de falhas recorrentes devem entrar no roadmap.',
    technicalShare: 'Secure by Design: mapear opt-ins críticos, secure defaults, logging/MFA/update, classes repetidas de falha e transformar findings recorrentes em mudanças de framework/plataforma.',
  },
];

export const securityBriefingPillars = ['TODOS', ...Array.from(new Set(securityBriefingStories.map((story) => story.pillar)))];
