export type VehicleOption = {
  id: string;
  name: string;
  year: string;
  version: string;
  category: string;
  priceFipe: string;
  priceMarket: string;
  priceRange?: string;
  reference: string;
  profile: string;
  kmContext: string;
  strengths: string[];
  attention: string[];
  inspection: string[];
  verdict: string;
  sourceLabel: string;
  sourceUrl: string;
};

export const carOptions: VehicleOption[] = [
  { id:'punto-attractive-2016', name:'Fiat Punto', year:'2016', version:'1.4 Attractive 8V manual', category:'HATCH / 1.4 / MANUAL', priceFipe:'R$ 41.513', priceMarket:'R$ 45.026,67', priceRange:'R$ 38,76 mil–60 mil', reference:'AGO/2026', profile:'Para quem quer um hatch acima de 1.0, confortável e com preço de entrada baixo, aceitando projeto mais antigo e seleção cuidadosa do exemplar.', kmContext:'Em carro 2016, manutenção comprovada pesa mais que perseguir baixa quilometragem. Compare volante, pedais, bancos, pneus e histórico com o hodômetro.', strengths:['FIPE perto de R$ 41,5 mil e média nacional perto de R$ 45 mil.','Motor 1.4 simples e câmbio manual reduzem complexidade frente a automáticos antigos.','Boa margem para reservar dinheiro para revisão inicial.'], attention:['Verifique suspensão dianteira, coxins, arrefecimento e vazamentos.','Evite elétrica improvisada ou acessórios mal instalados.','Acabamentos e peças específicas de carroceria podem exigir mais procura que itens mecânicos comuns.'], inspection:['Partida fria e marcha lenta.','Embreagem e engates.','Arrefecimento e ventoinha.','Suspensão em piso irregular.','Pneus e alinhamento.','Cautelar + scanner + inspeção independente.'], verdict:'É o carro de entrada do radar. Faz sentido se estiver íntegro e deixar margem para manutenção preventiva; não compre só porque é barato.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/carros/fiat/punto/2016/14-attractive-8v-flex-4p-manual/' },
  { id:'sandero-expression-2016', name:'Renault Sandero', year:'2016', version:'1.6 Expression 8V manual', category:'HATCH / 1.6 / MANUAL', priceFipe:'R$ 39.134', priceMarket:'R$ 41.497,56', priceRange:'R$ 28 mil–48,9 mil', reference:'AGO/2026', profile:'Para uso diário, família pequena e quem valoriza espaço interno, mecânica relativamente simples e custo de entrada baixo.', kmContext:'Rodagem alta com revisões e uso rodoviário pode ser melhor que baixa km de uso urbano severo. Leia suspensão, embreagem, arrefecimento e histórico como conjunto.', strengths:['FIPE abaixo de R$ 40 mil.','Espaço interno bom para a categoria.','Motor 1.6 atende melhor estrada e carga que versões 1.0, que estão fora desta curadoria.'], attention:['Suspensão e buchas sofrem em piso ruim.','Cheque arrefecimento, vazamentos e itens de manutenção da versão.','Acabamento simples não deve esconder estrutura mal reparada.'], inspection:['Partida fria.','Embreagem e câmbio.','Suspensão/buchas.','Arrefecimento.','Direção e alinhamento.','Cautelar + scanner.'], verdict:'A escolha mais racional do grupo para espaço e baixo custo, desde que não tenha sido negligenciado em manutenção.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/carros/renault/sandero/2016/16-expression-8v-flex-4p-manual' },
  { id:'fox-pepper-2016', name:'Volkswagen Fox', year:'2016', version:'1.6 MSI Pepper 16V manual', category:'HATCH / 1.6 MSI', priceFipe:'R$ 51.342', priceMarket:'R$ 55.319,80', priceRange:'R$ 45,5 mil–64,99 mil', reference:'AGO/2026', profile:'Para quem quer hatch compacto, posição de dirigir alta, motor 1.6 e boa disponibilidade de peças, sem chegar ao teto de R$ 70 mil.', kmContext:'Versão de apelo visual pode ter sido usada de forma mais intensa; desgaste de pneus, embreagem, freios e estrutura importa mais que a estética externa.', strengths:['Motor 1.6 acima do mínimo definido para a curadoria.','FIPE e média nacional bem abaixo de R$ 70 mil.','Rede de peças e oficinas ampla.'], attention:['Confira sistema de arrefecimento e histórico de manutenção.','Inspecione suspensão, coxins e ruídos internos.','Rodas maiores podem trazer pneus mais caros e sinais de impacto em buracos.'], inspection:['Partida fria/marcha lenta.','Embreagem e engates.','Suspensão, rodas e pneus.','Arrefecimento.','Freios.','Cautelar + scanner.'], verdict:'Equilibra desempenho, tamanho e facilidade de manutenção. Pague pelo estado do exemplar, não pela aparência Pepper.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/carros/volkswagen/fox/2016/16-msi-pepper-16v-flex-4p-manual' },
  { id:'focus-titanium-sedan-2015', name:'Ford Focus Sedan', year:'2015', version:'2.0 Titanium automático', category:'SEDÃ / 2.0 / AUTOMÁTICO', priceFipe:'R$ 52.853', priceMarket:'R$ 47.626,67', priceRange:'R$ 42,9 mil–57,9 mil', reference:'AGO/2026', profile:'Para quem quer acabamento, dinâmica e equipamentos de sedã médio pelo preço de compacto usado — e aceita fazer uma inspeção de transmissão muito mais rigorosa.', kmContext:'Aqui o histórico da transmissão vale mais que a km isolada. Um carro com quilometragem maior e documentação correta pode ser menos arriscado que um “baixo km” sem evidência.', strengths:['Muito equipamento e dinâmica por cerca de R$ 50 mil.','Motor 2.0 entrega desempenho bem acima dos demais do grupo.','Faixa de mercado observada permanece abaixo do teto de R$ 70 mil.'], attention:['Muitas versões dessa geração usam transmissão Powershift de dupla embreagem, que exige histórico excepcional e inspeção especializada.','Evite unidade com trepidação, mensagens de falha, demora em engates ou histórico nebuloso.','Peças e manutenção de sedã médio podem custar mais que em hatches simples.'], inspection:['Identificar exatamente transmissão/versão pelo VIN.','Teste frio e quente em trânsito lento e manobras.','Scanner de módulos, inclusive transmissão.','Suspensão e pneus.','Arrefecimento.','Cautelar + especialista Ford/Powershift antes de pagar.'], verdict:'É o “muito carro pelo dinheiro” com maior risco mecânico do radar. Só compre com diagnóstico especializado e documentação convincente da transmissão.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/carros/ford/focus/2015/20-titanium-sedan-16v-flex-4p-automatico' }
];

export const motorcycleOptions: VehicleOption[] = [
  { id:'nmax-160-2020', name:'Yamaha NMax 160 ABS', year:'2020', version:'NMax 160 ABS', category:'SCOOTER / URBANA', priceFipe:'R$ 15.115', priceMarket:'R$ 15.727,50', priceRange:'R$ 12,5 mil–17,9 mil', reference:'AGO/2026', profile:'Para mobilidade urbana, deslocamento diário e praticidade com CVT e ABS.', kmContext:'Em scooter, olhe manutenção da transmissão CVT, pneus, freios, rolamentos e carenagens além do hodômetro.', strengths:['Baixo custo de entrada.','ABS e praticidade urbana.','FIPE e média nacional próximas.'], attention:['Correia, roletes e embreagem centrífuga precisam de histórico.','Carenagem pode esconder quedas.','Rodas e suspensão sofrem bastante em piso ruim.'], inspection:['Partida fria.','CVT sem ruído anormal.','Freios/ABS.','Pneus e rodas.','Carenagens/alinhamento.','Histórico de revisões.'], verdict:'A escolha urbana do radar. Excelente para cidade; não é a ferramenta para estrada longa ou desempenho.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/motos/yamaha/nmax-160-abs/2020' },
  { id:'xre300-abs-2019', name:'Honda XRE 300 ABS', year:'2019', version:'XRE 300 ABS', category:'TRAIL / 300', priceFipe:'R$ 24.825', priceMarket:'R$ 27.346,67', priceRange:'R$ 22,9 mil–31 mil', reference:'AGO/2026', profile:'Para cidade ruim, deslocamentos mistos e pequenas viagens com ergonomia trail.', kmContext:'Leia sinais de terra, quedas e viagem: aros, bengalas, mesa, pedaleiras, relação e pneus contam a história melhor que km isolada.', strengths:['ABS.','Ergonomia e suspensão adequadas a piso irregular.','Mercado amplo e boa liquidez.'], attention:['Cheque alinhamento de rodas/mesa e retentores de bengala.','Relação, pneus e freios podem virar gasto imediato.','Procure reparos em carenagens, manetes e pedaleiras.'], inspection:['Aros/raios.','Bengalas e retentores.','Mesa/batentes.','Relação e pneus.','ABS/discos.','Motor frio + histórico.'], verdict:'Boa trail versátil, mas exemplar que caiu ou rodou muito em piso ruim precisa ser precificado como tal.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/motos/honda/xre-300-abs/2019' },
  { id:'mt07-abs-2020', name:'Yamaha MT-07 ABS', year:'2020', version:'MT-07 ABS', category:'NAKED / 689', priceFipe:'R$ 39.896', priceMarket:'R$ 42.942,14', priceRange:'R$ 38,9 mil–45,5 mil', reference:'AGO/2026', profile:'Para quem quer naked leve, forte em torque e divertida em cidade/estrada, aceitando custo maior de pneus, seguro e consumíveis.', kmContext:'Quilometragem menor não compensa sinais de abuso. Verifique pneus, relação, embreagem, mesa, batentes, manetes e eventuais modificações.', strengths:['Motor bicilíndrico de forte torque.','ABS.','Boa relação peso/desempenho.'], attention:['Seguro pode ser relevante conforme perfil/região.','Pneus e relação de maior desempenho custam mais.','Evite unidades muito modificadas ou com sinais de stunt/queda.'], inspection:['Mesa e batentes.','Bengalas e rodas.','Relação/pneus.','Freios/ABS.','Embreagem e motor frio.','Histórico + sinais de queda.'], verdict:'É a opção diversão/desempenho. O custo total sobe bastante em relação a 160–300 cc, mesmo que o preço de compra pareça acessível.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/motos/yamaha/mt-07-abs/2020' },
  { id:'versys650-2018', name:'Kawasaki Versys 650', year:'2018', version:'Versys 650', category:'TOURING / 650', priceFipe:'R$ 36.680', priceMarket:'Indisponível', reference:'AGO/2026', profile:'Para estrada e viagens com posição confortável e proteção aerodinâmica maior que uma naked.', kmContext:'Moto de viagem pode ter km alta e excelente histórico. Procure revisões por tempo/km, pneus, relação, rolamentos, sistema de carga e marcas de tombos com bagagem.', strengths:['Ergonomia de viagem.','Bicilíndrica adequada a rodovia.','FIPE abaixo de R$ 40 mil.'], attention:['Webmotors não tinha amostra suficiente para média nacional nesta referência; não invente “preço de mercado”.','Consumíveis e seguro custam mais que nas pequenas.','Acessórios de viagem podem indicar uso intenso; isso não é ruim se a manutenção acompanhar.'], inspection:['Sistema de carga/bateria.','Suspensão e rolamentos.','Pneus/relação.','Freios.','Marcas de queda e alinhamento.','Histórico de revisões e fluidos.'], verdict:'A escolha de viagem do grupo. Negocie pelo estado real porque a média Webmotors está indisponível nesta referência.', sourceLabel:'Webmotors · FIPE · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/motos/kawasaki/versys/2018' }
];
