export type VehicleOption = {
  id: string;
  name: string;
  year: string;
  version: string;
  category: string;
  priceFipe: string;
  priceMarket: string;
  priceRange?: string;
  reference: string;
  profile: string;
  kmContext: string;
  strengths: string[];
  attention: string[];
  inspection: string[];
  verdict: string;
  sourceLabel: string;
  sourceUrl: string;
};

export const carOptions: VehicleOption[] = [
  { id:'hb20-rspec-2019', name:'Hyundai HB20', year:'2019', version:'1.6 R-Spec automático', category:'HATCH / AUTOMÁTICO', priceFipe:'R$ 68.562', priceMarket:'R$ 68.918', priceRange:'R$ 66,4 mil–74,8 mil', reference:'AGO/2026', profile:'Para uso urbano diário com câmbio automático de seis marchas, bom desempenho do 1.6 e dimensões compactas.', kmContext:'Compare hodômetro com desgaste e histórico. Rodagem maior com manutenção documentada pode ser menos arriscada que baixa km sem evidência.', strengths:['Motor 1.6 de 128 cv e câmbio automático de seis marchas.','Boa oferta de peças e manutenção conhecida.','FIPE e média Webmotors ficam abaixo do teto de R$ 70 mil desta curadoria.'], attention:['Anúncios acima de R$ 70 mil ficam fora do nosso recorte, mesmo que existam no mercado.','Cheque histórico de fluido do câmbio e funcionamento frio/quente.','Suspensão, coxins, pneus e cautelar estrutural revelam muito do uso urbano e de eventuais impactos.'], inspection:['Partida fria e marcha lenta.','Engates D/R e trocas.','Suspensão em piso irregular.','Pneus e alinhamento.','Arrefecimento e vazamentos.','Cautelar + scanner + inspeção independente.'], verdict:'Boa opção de hatch automático perto do teto. Só faz sentido se o exemplar estiver realmente bom; acima de R$ 70 mil, o radar manda procurar outra unidade.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/carros/hyundai/hb20/2019/16-r-spec-16v-flex-4p-automatico' },
  { id:'onix-lt-turbo-2020', name:'Chevrolet Onix', year:'2020', version:'LT 1.0 Turbo automático', category:'HATCH / TURBO', priceFipe:'R$ 64.268', priceMarket:'R$ 66.381', priceRange:'R$ 57 mil–79 mil', reference:'AGO/2026', profile:'Hatch mais novo, econômico e bem equipado para cidade e estrada leve.', kmContext:'Em turbo moderno, manutenção correta de óleo e arrefecimento pesa mais que alguns milhares de quilômetros a menos.', strengths:['116 cv e câmbio automático de seis marchas.','Seis airbags na ficha desta versão.','FIPE e média nacional ficam dentro do teto de R$ 70 mil.'], attention:['Há anúncios acima de R$ 70 mil, mas eles não entram na recomendação desta curadoria.','Exija histórico de óleo conforme especificação e observe arrefecimento.','Turbo, mangueiras e admissão pedem inspeção sem improvisos.'], inspection:['Partida fria sem fumaça.','Scanner por falhas.','Óleo correto e revisões.','Turbo/admissão.','Arrefecimento.','Cautelar estrutural.'], verdict:'Entrega modernidade e segurança por preço competitivo. O exemplar precisa ter histórico muito bem documentado e o preço final deve permanecer dentro do teto.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/carros/chevrolet/onix/2020/10-turbo-flex-lt-automatico' },
  { id:'duster-dynamique-auto-2016', name:'Renault Duster', year:'2016', version:'2.0 Dynamique 4x2 automático', category:'SUV / AUTOMÁTICO', priceFipe:'R$ 59.080', priceMarket:'R$ 60.744', priceRange:'R$ 49,9 mil–69,9 mil', reference:'AGO/2026', profile:'Para quem quer espaço, posição de dirigir alta e robustez de uso em piso ruim sem ultrapassar o teto de R$ 70 mil.', kmContext:'Em SUV dessa idade, histórico, suspensão, arrefecimento, transmissão e sinais de uso severo dizem mais que a km isolada. Rodovia bem mantida pode ser menos desgastante que cidade curta e buracada.', strengths:['FIPE e média nacional ficam perto de R$ 60 mil.','Espaço interno e altura do solo favorecem família e piso ruim.','A faixa observada de anúncios ainda cabe integralmente no teto de R$ 70 mil.'], attention:['O automático de quatro marchas privilegia simplicidade e conforto, não economia ou desempenho de câmbios modernos.','Cheque arrefecimento, coxins, suspensão e vazamentos com atenção.','Altura de SUV não significa 4x4: esta versão é 4x2.'], inspection:['Partida fria e temperatura de trabalho.','Engates e trocas do câmbio frio e quente.','Suspensão, buchas e coxins.','Arrefecimento e vazamentos.','Pneus, alinhamento e desgaste irregular.','Cautelar estrutural + scanner + inspeção independente.'], verdict:'É a alternativa SUV do radar sem estourar o orçamento. Vale mais pelo espaço e robustez do que por refinamento; entre duas unidades, escolha histórico e estado antes de acessórios.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/carros/renault/duster/2016/20-dynamique-4x2-16v-flex-4p-automatico' },
  { id:'fluence-dynamique-auto-2016', name:'Renault Fluence', year:'2016', version:'2.0 Dynamique automático', category:'SEDÃ MÉDIO / CVT', priceFipe:'R$ 51.440', priceMarket:'R$ 54.945', priceRange:'R$ 40,9 mil–61,9 mil', reference:'AGO/2026', profile:'Para quem quer muito espaço, conforto e sedã médio por preço de compacto, aceitando liquidez menor e seleção mais cuidadosa do exemplar.', kmContext:'Nesse tipo de sedã, km alta não condena automaticamente. Histórico do câmbio, fluidos, arrefecimento, suspensão e uso rodoviário ou urbano são mais informativos.', strengths:['FIPE pouco acima de R$ 51 mil e média perto de R$ 55 mil.','Muito espaço e conforto pelo valor de compra.','A faixa observada de anúncios permanece abaixo de R$ 70 mil.'], attention:['Liquidez costuma ser menor que a de hatches compactos populares.','Histórico do CVT e troca de fluidos deve ser comprovado, não presumido.','Pneus, suspensão e peças de acabamento podem custar mais que em um compacto básico.'], inspection:['CVT frio e quente, sem trancos ou ruídos anormais.','Histórico de fluidos e revisões.','Suspensão e direção.','Ar-condicionado e eletrônica.','Arrefecimento e vazamentos.','Cautelar + scanner + inspeção independente.'], verdict:'É o “muito carro pelo dinheiro” do grupo. Faz sentido para conforto e estrada, desde que você aceite revenda menos rápida e compre um exemplar com manutenção realmente comprovada.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/carros/renault/fluence/2016/20-dynamique-16v-flex-4p-automatico' }
];

export const motorcycleOptions: VehicleOption[] = [
  { id:'pcx-2019', name:'Honda PCX', year:'2019', version:'150 / DLX', category:'SCOOTER / URBANA', priceFipe:'R$ 14.810', priceMarket:'R$ 16.194', priceRange:'R$ 14,5 mil–18 mil', reference:'AGO/2026', profile:'Para cidade, deslocamento diário e praticidade.', kmContext:'Observe manutenção da transmissão CVT, pneus, freios e carenagens além do hodômetro.', strengths:['Praticidade urbana.','Baixo custo de entrada.','Boa liquidez e rede de serviço.'], attention:['Correia, roletes e embreagem centrífuga precisam de histórico.','Carenagens podem esconder tombos.','Suspensão e rodas sofrem em piso ruim.'], inspection:['Partida fria.','CVT sem ruído anormal.','Freios e pneus.','Carenagens e alinhamento.','Rolamentos e suspensão.','Histórico de revisões.'], verdict:'Melhor para cidade pura; não compre pensando em desempenho ou viagem longa.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/motos/honda/pcx/2019' },
  { id:'tenere-250-2018', name:'Yamaha Ténéré 250', year:'2018', version:'XTZ 250', category:'TRAIL / 250', priceFipe:'R$ 20.996', priceMarket:'R$ 22.311', priceRange:'R$ 19,9 mil–24 mil', reference:'AGO/2026', profile:'Trail para cidade ruim, estrada e viagens leves.', kmContext:'Trail deve ser lida pelo tipo de uso: terra, viagens, carga e quedas leves; rodas, suspensão, mesa e relação contam a história.', strengths:['Ergonomia confortável.','Suspensão e rodas adequadas a piso ruim.','Mecânica 250 conhecida.'], attention:['Inspecione raios, aros, bengalas e mesa.','Relação e pneus podem ser gasto imediato.','Procure sinais de queda.'], inspection:['Raios e aros.','Retentores de bengala.','Mesa e batentes.','Relação e pneus.','Freios/rolamentos.','Histórico de óleo e válvulas.'], verdict:'Ótima para uso misto e viagem leve; estado de ciclística vale mais que acessórios.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/motos/yamaha/xtz-250-tenere/2018' },
  { id:'ninja300-abs-2017', name:'Kawasaki Ninja 300 ABS', year:'2017', version:'Ninja 300 ABS', category:'ESPORTIVA / 300', priceFipe:'R$ 20.466', priceMarket:'R$ 21.990', priceRange:'R$ 21,99 mil–22,99 mil', reference:'AGO/2026', profile:'Para quem quer carenada leve e experiência esportiva sem pular para cilindradas maiores.', kmContext:'Avalie pista, arrancadas, quedas e modificações; manetes, pedaleiras, carenagens e pneus contam a história.', strengths:['Bicilíndrica com entrega esportiva.','ABS nesta configuração.','Preço próximo de trails 250 usadas.'], attention:['Carenagem pode esconder reparos.','Relação, pneus e freios podem custar caro juntos.','Evite exemplares muito modificados.'], inspection:['Batentes e mesa.','Carenagens e fixações.','Bengalas e rodas.','Relação/pneus.','ABS e discos.','Motor frio e histórico.'], verdict:'Boa porta de entrada para esportiva, mas exige inspeção rigorosa de quedas e modificações.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/motos/kawasaki/ninja-300-abs/2017' },
  { id:'cb500x-2018', name:'Honda CB 500X ABS', year:'2018', version:'CB 500X ABS', category:'TOURING / 500', priceFipe:'R$ 34.400', priceMarket:'R$ 35.659', priceRange:'R$ 28 mil–39 mil', reference:'AGO/2026', profile:'Para estrada, viagens e uso misto com mais reserva de motor.', kmContext:'Motos de viagem podem ter km alta e ótimo histórico; procure manutenção por tempo e km, pneus, relação, rolamentos e sinais de tombos.', strengths:['Motor bicilíndrico adequado a rodovia.','ABS e ergonomia de viagem.','Preço de mercado próximo da FIPE.'], attention:['Consumíveis e seguro custam mais que nas 250.','Verifique suspensão, rolamentos e sistema de carga.','Acessórios podem indicar uso intenso, não necessariamente ruim.'], inspection:['Sistema de carga/bateria.','Suspensão e rolamentos.','Pneus e relação.','Freios/ABS.','Marcas de queda e alinhamento.','Histórico de revisões e fluidos.'], verdict:'A melhor do grupo para rodovia e viagem; não é a mais racional se o uso for só urbano.', sourceLabel:'Webmotors · FIPE / média nacional · ago/2026', sourceUrl:'https://www.webmotors.com.br/tabela-fipe/motos/honda/cb-500-x-abs/2018' }
];
